import os

replacements = {
    'lib/features/dashboard/web/web_patient_shell.dart': [
        ("'الخطة العلاجية الحالية'", "context.tr('current_treatment_plan')"),
        ("'تاريخ آخر صرف:'", "context.tr('last_dispense_date') + ':'"),
        ("'تاريخ الاستحقاق القادم:'", "context.tr('next_eligible_date') + ':'"),
        ("'معدل الالتزام:'", "context.tr('compliance_rate') + ':'"),
        ("'المقاييس الحيوية'", "context.tr('vital_metrics')"),
        ("'الوزن'", "context.tr('weight')"),
        ("'الطول'", "context.tr('height')"),
        ("'مؤشر الكتلة'", "context.tr('bmi')"),
        ("'تاريخ الجرعات'", "context.tr('dosing_history')"),
        ("'البيانات الشخصية'", "context.tr('personal_data')"),
        ("'الجنسية:'", "context.tr('nationality') + ':'"),
        ("'الإقامة:'", "context.tr('residency_status') + ':'"),
        ("'الإمارة:'", "context.tr('emirate') + ':'"),
        ("'الحالة الصحية المسبقة'", "context.tr('pre_existing_conditions')"),
        ("'لا يوجد أمراض مزمنة'", "context.tr('no_chronic_diseases')"),
        ("'تفاصيل التنبيه (Alert Details)'", "context.tr('alert_details')"),
        ("'البيانات المرتبطة:'", "context.tr('associated_data') + ':'"),
        ("'إغلاق'", "context.tr('close')"),
        ("Text('تم تنفيذ الإجراء بنجاح')", "Text(context.tr('action_executed_successfully'))"),
        ("const Text('تنفيذ الإجراء')", "Text(context.tr('execute_action'))"),
        ("context.tr('full_name') ?? 'الاسم الكامل للمستفيد'", "context.tr('full_name')"),
        ("context.tr('nationality') ?? 'الجنسية'", "context.tr('nationality')"),
        ("'تغطية الدعم المالي الحكومي'", "context.tr('gov_subsidy_details')"),
        ("'السعر الأساسي للدورة العلاجية'", "context.tr('base_medication_price')"),
        ("'نسبة التغطية المعتمدة'", "context.tr('coverage_rate')"),
        ("'المساهمة المغطاة من الوزارة'", "context.tr('govt_contribution')"),
        ("'المبلغ الصافي المستحق والدفع المشترك'", "context.tr('your_copay_per_checkin')"),
        ("'يُدفع مباشرة عند الحضور والمطابقة'", "context.tr('payable_at_checkin')"),
        ("'ملف الصحة والمؤشرات الحيوية للمستفيد'", "context.tr('my_health_profile')"),
        ("'بيانات الحالة الديموغرافية والمالية الشاملة والمسجلة ضمن الأنظمة الوطنية بوزارة الصحة'", "context.tr('health_profile_desc')"),
        ("'المؤشرات والبيانات السريرية المرتبطة بالحساب'", "context.tr('clinical_data_desc')"),
        ("'الجرعة الدوائية النشطة'", "context.tr('active_dose')"),
        ("'آخر فحص حيوي معملي'", "context.tr('last_vital_scan')"),
        ("'رقم الهوية الإماراتية'", "context.tr('emirates_id')"),
        ("'موثق عبر الرقم الرقمي'", "context.tr('verified_digital')"),
        ("'الملف الديموغرافي المعتمد'", "context.tr('demographics')"),
        ("'لا توجد تمارين مجدولة اليوم'", "context.tr('no_exercises_scheduled_today')"),
        ("'لا تنسى تسجيل حقنتك الأسبوعية لمتابعة التزامك'", "context.tr('dont_forget_weekly_injection')"),
        ("label: 'فقدان الوزن'", "label: context.tr('weight_loss')"),
        ("label: 'الجلسات المكتملة'", "label: context.tr('completed_sessions')"),
        ("'تحقق من الأهلية السريرية واطلب الدواء مباشرة للتوصيل أو الاستلام من أقرب صيدلية.'", "context.tr('check_eligibility_and_request')"),
        ("context.tr('my_health_profile') ??\n                      'ملف الصحة والمؤشرات الحيوية للمريض'", "context.tr('my_health_profile')"),
        ("'الملف الديموغرافي المعتمد'", "context.tr('demographics')"),
    ],
    'lib/features/dashboard/admin_views/activity_feed_ticker.dart': [
        ("context.tr('live_activity_feed') ?? 'سجل الأنشطة المباشر'", "context.tr('live_activity_feed')"),
        ("context.tr('live_badge') ?? 'مباشر'", "context.tr('live_badge')"),
    ],
    'lib/features/dashboard/admin_views/system_audit_log_view.dart': [
        ("t.translate('system_audit_log') ?? 'سجل النظام (Audit Log)'", "t.translate('system_audit_log')"),
        ("t.translate('system_audit_log_desc') ?? 'مراقبة حية لجميع الحركات والعمليات التي تمت في النظام.'", "t.translate('system_audit_log_desc')"),
        ("const Center(child: Text('لا توجد سجلات'))", "Center(child: Text(t.translate('no_records_found')))"),
    ],
    'lib/features/dashboard/mobile/mobile_admin_shell.dart': [
        ("context.tr('system_audit_log') == 'system_audit_log' ? 'سجل النظام' : context.tr('system_audit_log')", "context.tr('system_audit_log')"),
    ],
    'lib/features/dispensing/payment_screen.dart': [
        ("'جاري معالجة الدفع...'", "context.tr('processing_payment')"),
        ("'يرجى الانتظار، لا تقم بإغلاق هذه الشاشة.'", "context.tr('please_wait_dont_close')"),
        ("context.tr('payment_successful') == 'payment_successful' ? 'مغطى بالكامل - لا يوجد مبلغ مستحق' : 'Fully Covered - No Payment Required'", "context.tr('payment_successful')"),
        ("widget.amountToPay == 0.0 ? (context.tr('confirm_payment') == 'confirm_payment' ? 'تأكيد الصرف' : 'Confirm Dispense') : context.tr('confirm_payment')", "context.tr('confirm_payment')"),
        ("'ملخص الدفع'", "context.tr('payment_summary')"),
        ("Text('فاتورة مساهمة'", "Text(context.tr('copayment_invoice')"),
        ("Text('وزارة الصحة ووقاية المجتمع'", "Text(context.tr('ministry_health')"),
        ("_buildInvoiceRow('اسم المريض'", "_buildInvoiceRow(context.tr('patient_name')"),
        ("_buildInvoiceRow('اسم المستفيد'", "_buildInvoiceRow(context.tr('patient_name')"),
        ("_buildInvoiceRow('رقم الملف'", "_buildInvoiceRow(context.tr('file_number')"),
        ("_buildInvoiceRow('التاريخ'", "_buildInvoiceRow(context.tr('date')"),
        ("Text('مونجارو (تيرزيباتيد)'", "Text(context.tr('mounjaro_terzepatide')"),
        ("Text('جرعة ${widget.patient.currentDose}'", "Text('${context.tr('dose')} ${widget.patient.currentDose}'"),
        ("context.tr('payment_govt_discount') == 'payment_govt_discount' ? 'دعم حكومي' : context.tr('payment_govt_discount')", "context.tr('payment_govt_discount')"),
        ("Text('الإجمالي المستحق'", "Text(context.tr('total_due')"),
        ("Text('بيانات البطاقة'", "Text(context.tr('card_details')"),
        ("label: 'رقم البطاقة'", "label: context.tr('card_number')"),
        ("label: 'تاريخ الانتهاء'", "label: context.tr('expiry_date')"),
        ("label: 'رمز التحقق (CVV)'", "label: context.tr('cvv')"),
        ("label: 'الاسم على البطاقة'", "label: context.tr('name_on_card')"),
        ("hint: 'الاسم الكامل'", "hint: context.tr('full_name')"),
        ("_buildReceiptRow('رقم المرجع'", "_buildReceiptRow(context.tr('reference_number')"),
        ("_buildReceiptRow('التاريخ والوقت'", "_buildReceiptRow(context.tr('date_and_time')"),
        ("_buildReceiptRow('المريض'", "_buildReceiptRow(context.tr('patient')"),
        ("_buildReceiptRow('المستفيد'", "_buildReceiptRow(context.tr('patient')"),
        ("_buildReceiptRow('الوصف'", "_buildReceiptRow(context.tr('description')"),
        ("label: const Text('طباعة الإيصال')", "label: Text(context.tr('print_receipt'))"),
    ],
    'lib/core/localization/healthcare_terminology.dart': [
        ("'غرفة عمليات التنبيهات الذكية (AI Command Center)'", "tr('ai_command_center')"),
        ("'نظام مراقبة ذكي يعتمد على الذكاء الاصطناعي لاكتشاف التجاوزات، التنبؤ بنقص المخزون، وتحليل استجابة المرضى.'", "tr('ai_command_center_desc')"),
        ("'أمن واحتيال'", "tr('security_fraud')"),
        ("'متابعة سريرية'", "tr('clinical_followup')"),
        ("'أزمات الإمداد'", "tr('supply_crises')"),
        ("'تجميد الحساب'", "tr('freeze_account')"),
        ("'مراجعة الخطة'", "tr('review_plan')"),
        ("'إرسال إمداد طارئ'", "tr('send_emergency_supply')"),
        ("'التواصل مع المريض'", "tr('contact_patient')"),
    ]
}

translations_en_additions = {
    'current_treatment_plan': 'Current Treatment Plan',
    'last_dispense_date': 'Last Dispense Date',
    'next_eligible_date': 'Next Eligible Date',
    'compliance_rate': 'Compliance Rate',
    'vital_metrics': 'Vital Metrics',
    'weight': 'Weight',
    'height': 'Height',
    'bmi': 'BMI',
    'dosing_history': 'Dosing History',
    'personal_data': 'Personal Data',
    'nationality': 'Nationality',
    'residency_status': 'Residency Status',
    'emirate': 'Emirate',
    'pre_existing_conditions': 'Pre-existing Conditions',
    'no_chronic_diseases': 'No chronic diseases',
    'alert_details': 'Alert Details',
    'associated_data': 'Associated Data',
    'close': 'Close',
    'action_executed_successfully': 'Action Executed Successfully',
    'execute_action': 'Execute Action',
    'gov_subsidy_details': 'Government Subsidy Details',
    'base_medication_price': 'Base Medication Price',
    'coverage_rate': 'Coverage Rate',
    'govt_contribution': 'Government Contribution',
    'your_copay_per_checkin': 'Net Amount Due & Co-payment',
    'payable_at_checkin': 'Payable directly at check-in',
    'my_health_profile': 'My Health Profile',
    'health_profile_desc': 'Comprehensive demographic and financial data registered in MoHAP national systems',
    'clinical_data_desc': 'Clinical indicators and data associated with the account',
    'active_dose': 'Active Dose',
    'last_vital_scan': 'Last Vital Scan',
    'emirates_id': 'Emirates ID',
    'verified_digital': 'Verified via UAE Pass',
    'demographics': 'Verified Demographics',
    'no_exercises_scheduled_today': 'No exercises scheduled today',
    'dont_forget_weekly_injection': "Don't forget your weekly injection",
    'weight_loss': 'Weight Loss',
    'completed_sessions': 'Completed Sessions',
    'check_eligibility_and_request': 'Check clinical eligibility and request medication directly for delivery or pickup from the nearest pharmacy.',
    'live_activity_feed': 'Live Activity Feed',
    'live_badge': 'Live',
    'system_audit_log': 'System Audit Log',
    'system_audit_log_desc': 'Live monitoring of all movements and operations in the system.',
    'no_records_found': 'No records found',
    'processing_payment': 'Processing Payment...',
    'please_wait_dont_close': 'Please wait, do not close this screen.',
    'payment_successful': 'Fully Covered - No Payment Required',
    'confirm_payment': 'Confirm Dispense',
    'payment_summary': 'Payment Summary',
    'copayment_invoice': 'Co-payment Invoice',
    'ministry_health': 'Ministry of Health and Prevention',
    'patient_name': 'Patient Name',
    'file_number': 'File Number',
    'date': 'Date',
    'mounjaro_terzepatide': 'Mounjaro (Tirzepatide)',
    'dose': 'Dose',
    'payment_govt_discount': 'Government Subsidy',
    'total_due': 'Total Due',
    'card_details': 'Card Details',
    'card_number': 'Card Number',
    'expiry_date': 'Expiry Date',
    'cvv': 'CVV',
    'name_on_card': 'Name on Card',
    'full_name': 'Full Name',
    'reference_number': 'Reference Number',
    'date_and_time': 'Date & Time',
    'patient': 'Patient',
    'description': 'Description',
    'print_receipt': 'Print Receipt',
    'ai_command_center': 'AI Smart Alerts Center',
    'ai_command_center_desc': 'AI monitoring system to detect anomalies, predict inventory shortage, and analyze patient response.',
    'security_fraud': 'Security & Fraud',
    'clinical_followup': 'Clinical Follow-up',
    'supply_crises': 'Supply Crises',
    'freeze_account': 'Freeze Account',
    'review_plan': 'Review Plan',
    'send_emergency_supply': 'Emergency Supply',
    'contact_patient': 'Contact Patient',
}

translations_ar_additions = {
    'current_treatment_plan': 'الخطة العلاجية الحالية',
    'last_dispense_date': 'تاريخ آخر صرف',
    'next_eligible_date': 'تاريخ الاستحقاق القادم',
    'compliance_rate': 'معدل الالتزام',
    'vital_metrics': 'المقاييس الحيوية',
    'weight': 'الوزن',
    'height': 'الطول',
    'bmi': 'مؤشر الكتلة',
    'dosing_history': 'تاريخ الجرعات',
    'personal_data': 'البيانات الشخصية',
    'nationality': 'الجنسية',
    'residency_status': 'الإقامة',
    'emirate': 'الإمارة',
    'pre_existing_conditions': 'الحالة الصحية المسبقة',
    'no_chronic_diseases': 'لا يوجد أمراض مزمنة',
    'alert_details': 'تفاصيل التنبيه (Alert Details)',
    'associated_data': 'البيانات المرتبطة',
    'close': 'إغلاق',
    'action_executed_successfully': 'تم تنفيذ الإجراء بنجاح',
    'execute_action': 'تنفيذ الإجراء',
    'gov_subsidy_details': 'تغطية الدعم المالي الحكومي',
    'base_medication_price': 'السعر الأساسي للدورة العلاجية',
    'coverage_rate': 'نسبة التغطية المعتمدة',
    'govt_contribution': 'المساهمة المغطاة من الوزارة',
    'your_copay_per_checkin': 'المبلغ الصافي المستحق والدفع المشترك',
    'payable_at_checkin': 'يُدفع مباشرة عند الحضور والمطابقة',
    'my_health_profile': 'ملف الصحة والمؤشرات الحيوية',
    'health_profile_desc': 'بيانات الحالة الديموغرافية والمالية الشاملة والمسجلة ضمن الأنظمة الوطنية بوزارة الصحة',
    'clinical_data_desc': 'المؤشرات والبيانات السريرية المرتبطة بالحساب',
    'active_dose': 'الجرعة الدوائية النشطة',
    'last_vital_scan': 'آخر فحص حيوي معملي',
    'emirates_id': 'رقم الهوية الإماراتية',
    'verified_digital': 'موثق عبر الرقم الرقمي',
    'demographics': 'الملف الديموغرافي المعتمد',
    'no_exercises_scheduled_today': 'لا توجد تمارين مجدولة اليوم',
    'dont_forget_weekly_injection': 'لا تنسى تسجيل حقنتك الأسبوعية لمتابعة التزامك',
    'weight_loss': 'فقدان الوزن',
    'completed_sessions': 'الجلسات المكتملة',
    'check_eligibility_and_request': 'تحقق من الأهلية السريرية واطلب الدواء مباشرة للتوصيل أو الاستلام من أقرب صيدلية.',
    'live_activity_feed': 'سجل الأنشطة المباشر',
    'live_badge': 'مباشر',
    'system_audit_log': 'سجل النظام',
    'system_audit_log_desc': 'مراقبة حية لجميع الحركات والعمليات التي تمت في النظام.',
    'no_records_found': 'لا توجد سجلات',
    'processing_payment': 'جاري معالجة الدفع...',
    'please_wait_dont_close': 'يرجى الانتظار، لا تقم بإغلاق هذه الشاشة.',
    'payment_successful': 'مغطى بالكامل - لا يوجد مبلغ مستحق',
    'confirm_payment': 'تأكيد الصرف',
    'payment_summary': 'ملخص الدفع',
    'copayment_invoice': 'فاتورة مساهمة',
    'ministry_health': 'وزارة الصحة ووقاية المجتمع',
    'patient_name': 'اسم المريض',
    'file_number': 'رقم الملف',
    'date': 'التاريخ',
    'mounjaro_terzepatide': 'مونجارو (تيرزيباتيد)',
    'dose': 'جرعة',
    'payment_govt_discount': 'دعم حكومي',
    'total_due': 'الإجمالي المستحق',
    'card_details': 'بيانات البطاقة',
    'card_number': 'رقم البطاقة',
    'expiry_date': 'تاريخ الانتهاء',
    'cvv': 'رمز التحقق (CVV)',
    'name_on_card': 'الاسم على البطاقة',
    'full_name': 'الاسم الكامل',
    'reference_number': 'رقم المرجع',
    'date_and_time': 'التاريخ والوقت',
    'patient': 'المريض',
    'description': 'الوصف',
    'print_receipt': 'طباعة الإيصال',
    'ai_command_center': 'غرفة عمليات التنبيهات الذكية (AI Command Center)',
    'ai_command_center_desc': 'نظام مراقبة ذكي يعتمد على الذكاء الاصطناعي لاكتشاف التجاوزات، التنبؤ بنقص المخزون، وتحليل استجابة المرضى.',
    'security_fraud': 'أمن واحتيال',
    'clinical_followup': 'متابعة سريرية',
    'supply_crises': 'أزمات الإمداد',
    'freeze_account': 'تجميد الحساب',
    'review_plan': 'مراجعة الخطة',
    'send_emergency_supply': 'إرسال إمداد طارئ',
    'contact_patient': 'التواصل مع المريض',
}

for file, items in replacements.items():
    if not os.path.exists(file):
        continue
    with open(file, 'r', encoding='utf-8') as f:
        content = f.read()
    for o, n in items:
        content = content.replace(o, n)
    with open(file, 'w', encoding='utf-8') as f:
        f.write(content)

def append_to_translations(filepath, additions):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    idx = content.rfind('};')
    if idx != -1:
        addition_str = ''
        for k, v in additions.items():
            v_escaped = v.replace("'", "\\'")
            addition_str += f"  '{k}': '{v_escaped}',\n"
        
        new_content = content[:idx] + addition_str + content[idx:]
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)

append_to_translations('lib/core/localization/translations_ar.dart', translations_ar_additions)
append_to_translations('lib/core/localization/translations_en.dart', translations_en_additions)

print('Done applying mass replacements and updating dictionaries.')
