import { useState } from 'react'
import { CareIcon } from './CareIcon'
import { useDialogFocus } from './useDialogFocus'
import type { AppData, Role } from './domain'
import type { AdminPage } from './adminAnalytics'
import { activityLogRows, updateActivityState, type ActivityRow, type ActivityStatus } from './activityLogData'
import { downloadCsv } from './csvExport'
import { localizeArabic } from './ArabicText'
import * as catalogue from './ArabicCatalogue'
import './ActivityLog.css'

const translations:Record<string,string>={Unread:'غير مقروء',Action:'تتطلب إجراء',Information:'معلومات إضافية',Handled:'تم التعامل معها',Read:'مقروء',High:'عالية',Medium:'متوسطة',Low:'منخفضة',Inventory:'المخزون',Treatment:'العلاج',Adherence:'الالتزام',Clinical:'الرعاية',Safety:'السلامة',Appointments:'المواعيد',Admin:'المسؤول',Doctor:'الطبيب',Reviewer:'المراجع',Pharmacist:'الصيدلي',Patient:'المريض'}
const icons:Record<string,string>={Inventory:'box',Treatment:'file',Adherence:'chart',Clinical:'activity',Safety:'decision',Appointments:'calendar'}
export function ActivityLog({data,arabic,role,onUpdate,onNavigate,mode='live'}:{mode?:'live'|'audit';data:AppData;arabic:boolean;role:Role;onUpdate:(data:AppData)=>void;onNavigate:(page:AdminPage,id?:string)=>void}) {
 const t=(en:string,ar:string)=>arabic?ar:en
 const label=(v:string)=>arabic?translations[v]??v:v
 const local=(v:string)=>arabic?localizeArabic(v,catalogue):v
 const rows=activityLogRows(data)
 const [query,setQuery]=useState(''),[period,setPeriod]=useState('All'),[actor,setActor]=useState('All'),[category,setCategory]=useState('All'),[state,setState]=useState('All'),[priority,setPriority]=useState('All'),[sort,setSort]=useState('Newest')
 const [page,setPage]=useState(1),[size,setSize]=useState(10),[detailId,setDetailId]=useState<string|null>(null),[error,setError]=useState('')
 const [mountedAt]=useState(()=>Date.now())
 const clock=Math.max(mountedAt,...rows.map(row=>row.timestamp))
 const editable=role==='Admin'
 const selected=rows.find(r=>r.id===detailId)
 const close=()=>setDetailId(null)
 const dialogRef=useDialogFocus(Boolean(selected),close)
 const filtered=rows.filter(row=>(!query.trim()||`${local(row.action)} ${local(row.detail)} ${local(row.reason??'')} ${row.action} ${row.detail} ${row.entityId} ${row.id} ${row.patientId??''} ${row.patientName} ${row.patientNameAr} ${local(row.centre)}`.toLowerCase().includes(query.trim().toLowerCase()))&&(actor==='All'||actor===row.actor)&&(category==='All'||category===row.category)&&(state==='All'||(state==='Read'?row.read:row.status===state))&&(priority==='All'||priority===row.severity)&&(period==='All'||(row.timestamp>0&&row.timestamp>=clock-Number(period)*86400000&&row.timestamp<=clock))).sort((a,b)=>sort==='Oldest'?a.timestamp-b.timestamp:sort==='Priority'?({High:0,Medium:1,Low:2}[a.severity]-{High:0,Medium:1,Low:2}[b.severity])||b.timestamp-a.timestamp:b.timestamp-a.timestamp)
 const pages=Math.max(1,Math.ceil(filtered.length/size)),current=Math.min(page,pages),shown=filtered.slice((current-1)*size,current*size)
 const reset=()=>{setQuery('');setPeriod('All');setActor('All');setCategory('All');setState('All');setPriority('All');setSort('Newest');setPage(1)}
 const update=(ids:string[],action:'read'|'unread'|'handled')=>{try{onUpdate(updateActivityState(data,role,ids,action));setError('')}catch{setError(t('Unable to save the activity status. Please try again.','تعذر حفظ حالة النشاط. حاول مرة أخرى.'))}}
 const open=(row:ActivityRow)=>{setDetailId(row.id);if(editable&&!row.read)update([row.id],'read')}
 const exportRows=()=>downloadCsv(mode==='audit'?'system-audit.csv':'live-activity-log.csv',filtered.map(r=>({id:r.id,event:r.action,details:r.detail,type:r.category,severity:r.severity,actor:r.actor,patientId:r.patientId,patient:r.patientName,record:r.entityId,centre:r.centre,occurredAt:r.occurredAt??'',status:r.status,read:r.read,previousState:r.previousState,newState:r.newState,reason:r.reason})))
 const lastEvent=Math.max(0,...rows.map(r=>r.timestamp))
 const date=(stamp:number)=>new Date(stamp).toLocaleDateString('en-GB',{timeZone:'Asia/Dubai'}).replaceAll('/','-')
 const time=(stamp:number)=>new Date(stamp).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Dubai'})
 const filter=(name:string,value:string,set:(v:string)=>void,options:{value:string;name:string}[],icon:string)=><label className="la-filter"><CareIcon name={icon}/><select aria-label={name} value={value} onChange={e=>{set(e.target.value);setPage(1)}}><option value="All">{name}</option>{options.map(o=><option key={o.value} value={o.value}>{o.name}</option>)}</select></label>
 const values=(list:string[])=>list.map(value=>({value,name:label(value)}))
 const statusBadge=(row:ActivityRow)=><span className={`la-badge la-${row.status.toLowerCase()}`}><i/>{label(row.status)}</span>
 const stats:{status:ActivityStatus;icon:string;title:string}[]=[{status:'Handled',icon:'check',title:t('Handled','تم التعامل معها')},{status:'Information',icon:'info',title:t('Information needed','معلومات إضافية')},{status:'Action',icon:'clock',title:t('Requires action','تتطلب إجراء')},{status:'Unread',icon:'alert',title:t('Unread events','أحداث غير مقروءة')}]
 return <div className="activity-log" dir={arabic?'rtl':'ltr'} data-no-localize>
  <header className="la-hero"><div className="la-heading"><span className="la-heading-icon"><CareIcon name="activity"/></span><div><small>{t('Good morning, Laila','صباح الخير ليلى')}</small><h1>{mode==='audit'?t('System audit','سجل النظام'):t('Live activity log','سجل الأنشطة المباشر')}</h1><p>{mode==='audit'?t('Trace every recorded action, actor and change across the programme.','تتبّع الإجراءات المسجلة ومنفذيها والتغييرات على مستوى البرنامج.'):t('Operational events across care teams, inventory and treatment.','سجل مباشر للأحداث التشغيلية لفرق الرعاية والمخزون والعلاج.')}</p></div></div><div className="la-live"><CareIcon name="reset"/><div><b><i/>{t('Updates with programme records','يتحدث مع بيانات البرنامج')}</b><small>{lastEvent?t(`Latest event: ${date(lastEvent)} · ${time(lastEvent)}`,`آخر حدث: ${date(lastEvent)} · ${time(lastEvent)}`):t('No recorded events yet','لا توجد أحداث مسجلة بعد')}</small></div></div></header>
  <section className="la-stats" aria-label={t('Activity summary','ملخص الأنشطة')}>{stats.map(s=><button key={s.status} className={`la-stat la-${s.status.toLowerCase()}`} aria-pressed={state===s.status} onClick={()=>{setState(state===s.status?'All':s.status);setPage(1)}}><span><strong>{rows.filter(r=>r.status===s.status).length}</strong><small>{s.title}</small></span><i><CareIcon name={s.icon}/></i></button>)}</section>
  <section className="la-panel"><div className="la-toolbar"><label className="la-search"><CareIcon name="search"/><input aria-label={t('Search activity','البحث في الأنشطة')} placeholder={t('Search action, record, patient or details…','ابحث في الإجراء أو السجل أو المريض أو التفاصيل ...')} value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label><div className="la-tools"><details className="la-menu"><summary aria-label={t('Log actions','إجراءات السجل')}><CareIcon name="more"/></summary><div><button disabled={!editable||!filtered.some(r=>!r.read)} onClick={()=>update(filtered.map(r=>r.id),'read')}>{t('Mark filtered events read','تحديد الأحداث المفلترة كمقروءة')}</button><button onClick={reset}>{t('Reset filters','إعادة ضبط الفلاتر')}</button></div></details><button className="la-primary" onClick={exportRows} disabled={!filtered.length}><CareIcon name="download"/>{t('Export log','تصدير السجل')}</button></div></div>
  <div className="la-filters">{filter(t('Time period','الفترة الزمنية'),period,setPeriod,[{value:'1',name:t('Last 24 hours','آخر ٢٤ ساعة')},{value:'7',name:t('Last 7 days','آخر ٧ أيام')},{value:'30',name:t('Last 30 days','آخر ٣٠ يومًا')}],'calendar')}{filter(t('All roles','كل الأدوار'),actor,setActor,values([...new Set(rows.map(r=>r.actor))]),'user')}{filter(t('All types','كل الأنواع'),category,setCategory,values([...new Set(rows.map(r=>r.category))]),'box')}{filter(t('Read status','حالة القراءة'),state,setState,values(['Unread','Read','Action','Information','Handled']),'decision')}{filter(t('Priority','الأولوية'),priority,setPriority,values(['High','Medium','Low']),'filter')}<button onClick={reset}><CareIcon name="reset"/>{t('Reset','إعادة الضبط')}</button></div>
  {error&&<p className="la-error" role="alert">{error}</p>}<div className="la-results"><b>{t(`${filtered.length} events found`,`تم العثور على ${filtered.length} حدث`)}</b><label><CareIcon name="filter"/><select aria-label={t('Sort events','ترتيب الأحداث')} value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="Newest">{t('Sort: newest first','ترتيب: الأحدث أولًا')}</option><option value="Oldest">{t('Oldest first','الأقدم أولًا')}</option><option value="Priority">{t('Highest priority','الأولوية الأعلى')}</option></select></label></div>
  <div className="la-table-scroll"><table><thead><tr>{[['Event','الحدث'],['Type','النوع'],['Severity','الخطورة'],['Patient / record','المريض / السجل'],['Location / centre','الموقع / المركز'],['Date and time','التاريخ والوقت'],['Status','الحالة'],['Actions','إجراءات']].map(([en,ar])=><th key={en}>{t(en,ar)}</th>)}</tr></thead><tbody>{shown.map(row=><tr key={row.id}><td><div className="la-event"><span className="la-event-icon"><CareIcon name={icons[row.category]}/></span><div><b>{local(row.action)}</b><small title={local(row.detail)}>{label(row.actor)} · {local(row.detail)}</small></div></div></td><td><span className="la-type"><CareIcon name={icons[row.category]}/>{label(row.category)}</span></td><td><span className={`la-badge la-${row.severity.toLowerCase()}`}><CareIcon name={row.severity==='High'?'alert':'info'}/>{label(row.severity)}</span></td><td><span className="la-record">{arabic?row.patientNameAr||local(row.patientName):row.patientName}<small dir="ltr">{row.entityId}</small></span></td><td>{local(row.centre)||t('Programme-wide','على مستوى البرنامج')}</td><td className="la-date">{row.timestamp?<><span>{time(row.timestamp)}</span><span>{date(row.timestamp)}</span></>:<span>{row.time||'—'}</span>}</td><td>{statusBadge(row)}</td><td><div className="la-row-actions"><button onClick={()=>open(row)} aria-label={`${t('Open event','فتح الحدث')} ${row.id}`}>{t('Open','فتح')}</button><details className="la-menu"><summary aria-label={`${t('Event actions','إجراءات الحدث')} ${row.id}`}><CareIcon name="more"/></summary><div><button onClick={()=>open(row)}>{t('View details','عرض التفاصيل')}</button>{editable&&<><button onClick={()=>update([row.id],row.read?'unread':'read')}>{row.read?t('Mark unread','تحديد كغير مقروء'):t('Mark read','تحديد كمقروء')}</button><button disabled={row.status==='Handled'} onClick={()=>update([row.id],'handled')}>{t('Mark handled','تم التعامل معه')}</button></>}</div></details></div></td></tr>)}</tbody></table></div>
  {!filtered.length&&<div className="la-empty"><CareIcon name="history"/><h2>{t('No matching events','لا توجد أحداث مطابقة')}</h2><p>{t('Try another search or reset the filters.','جرّب بحثًا آخر أو أعد ضبط الفلاتر.')}</p><button onClick={reset}>{t('Reset filters','إعادة ضبط الفلاتر')}</button></div>}
  <footer className="la-pagination"><div><button aria-label={t('First page','الصفحة الأولى')} disabled={current===1} onClick={()=>setPage(1)}>«</button><button aria-label={t('Previous page','الصفحة السابقة')} disabled={current===1} onClick={()=>setPage(current-1)}>‹</button>{Array.from({length:Math.min(pages,5)},(_,i)=>Math.max(1,Math.min(current-2,pages-4))+i).map(n=><button key={n} aria-current={current===n?'page':undefined} onClick={()=>setPage(n)}>{n}</button>)}<button aria-label={t('Next page','الصفحة التالية')} disabled={current===pages} onClick={()=>setPage(current+1)}>›</button><button aria-label={t('Last page','الصفحة الأخيرة')} disabled={current===pages} onClick={()=>setPage(pages)}>»</button></div><span>{filtered.length?(current-1)*size+1:0} – {Math.min(current*size,filtered.length)} {t('of','من')} {filtered.length} {t('events','حدث')}</span><label>{t('Show','عرض')}<select aria-label={t('Rows per page','عدد الصفوف في الصفحة')} value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[10,20,50].map(n=><option key={n}>{n}</option>)}</select>{t('per page','لكل صفحة')}</label></footer></section>
  {selected&&<div className="la-overlay"><section className="la-dialog" ref={dialogRef} role="dialog" aria-modal="true" aria-label={t('Event details','تفاصيل الحدث')}><header><h2>{local(selected.action)}</h2><button aria-label={t('Close','إغلاق')} onClick={close}><CareIcon name="close"/></button></header><p>{local(selected.detail)}</p><dl><dt>{t('Record','السجل')}</dt><dd dir="ltr">{selected.entityId}</dd><dt>{t('Actor','منفذ الإجراء')}</dt><dd>{label(selected.actor)} {selected.actorId??''}</dd><dt>{t('Event ID','رقم الحدث')}</dt><dd>{selected.id}</dd><dt>{t('Date and time','التاريخ والوقت')}</dt><dd>{selected.timestamp?`${date(selected.timestamp)} · ${time(selected.timestamp)}`:selected.time}</dd><dt>{t('Patient','المريض')}</dt><dd>{(arabic?selected.patientNameAr||local(selected.patientName):selected.patientName)||'—'}</dd><dt>{t('Previous state','الحالة السابقة')}</dt><dd>{local(selected.previousState??'—')}</dd><dt>{t('New state','الحالة الجديدة')}</dt><dd>{local(selected.newState??'—')}</dd><dt>{t('Reason','السبب')}</dt><dd>{local(selected.reason??'—')}</dd><dt>{t('Status','الحالة')}</dt><dd>{statusBadge(selected)}</dd></dl>{selected.metadata&&<dl>{Object.entries(selected.metadata).map(([key,value])=><div className="la-metadata" key={key}><dt>{local(key)}</dt><dd>{local(value)}</dd></div>)}</dl>}<p className="la-note">{t('Read and follow-up status apply to this log entry. Clinical records are unchanged.','حالة القراءة والمتابعة تخص هذا الحدث في السجل، ولا تغيّر حالة السجل العلاجي.')}</p>{error&&<p role="alert" className="la-error">{error}</p>}<footer>{selected.target&&<button onClick={()=>{close();onNavigate(selected.target!,selected.targetId)}}>{t('Open related record','فتح السجل المرتبط')}</button>}{editable&&selected.status!=='Handled'&&<button className="la-primary" onClick={()=>update([selected.id],'handled')}>{t('Mark handled','تم التعامل معه')}</button>}</footer></section></div>}
 </div>
}
