import { useMemo, useState } from 'react'
import type { AppData } from './domain'
import type { AdminPage } from './adminAnalytics'
import { adminDashboardData } from './adminDashboardData'
import { CareIcon } from './EcosystemViews'
import assistantImage from './assets/login-ai-assistant.png'
import './AdminDashboard.css'

type Navigate = (page: AdminPage, id?: string) => void
type Dashboard = ReturnType<typeof adminDashboardData>
function Heading({ title, subtitle, children }: { title: string; subtitle: string; children?: React.ReactNode }) {
  return <div className="ad-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{children}</div>
}
function Journey({ rows }: { rows: Dashboard['journey'] }) {
  const [selected, setSelected] = useState<string | null>(null)
  const max = Math.max(4, ...rows.flatMap(row => [row.registered, row.started, row.completed]))
  const ceiling = Math.ceil(max / 4) * 4
  const x = (index: number) => 42 + index * 430 / Math.max(1, rows.length - 1)
  const y = (value: number) => 190 - value / ceiling * 156
  const series = [{ key: 'registered', label: 'New patients', color: '#00a58c' }, { key: 'started', label: 'Treatment starts', color: '#3caed0' }, { key: 'completed', label: 'Completed plans', color: '#ffab30' }] as const
  const focused = rows.find(row => row.key === selected)
  return <><svg className="ad-journey" viewBox="0 0 500 230" role="img" aria-label="Monthly new patients, treatment starts and completed plans from shared records">
    <defs>{series.map(series => <linearGradient id={`ad-${series.key}`} key={series.key} x1="0" y1="0" x2="0" y2="1"><stop stopColor={series.color} stopOpacity=".28"/><stop offset="1" stopColor={series.color} stopOpacity=".02"/></linearGradient>)}</defs>
    {[0, 1, 2, 3, 4].map(tick => <g key={tick}><line x1="42" x2="472" y1={y(tick * ceiling / 4)} y2={y(tick * ceiling / 4)} stroke="#e7eef3" strokeDasharray="3 3"/><text x="30" y={y(tick * ceiling / 4) + 4} textAnchor="end">{tick * ceiling / 4}</text></g>)}
    {series.map(series => { const path = rows.map((row, index) => `${index ? 'L' : 'M'} ${x(index)} ${y(row[series.key])}`).join(' '); return <g key={series.key}><path d={`${path} L 472 190 L 42 190 Z`} fill={`url(#ad-${series.key})`}/><path d={path} fill="none" stroke={series.color} strokeWidth="2.5"/>{rows.map((row, index) => <circle key={row.key} cx={x(index)} cy={y(row[series.key])} r="3" fill={series.color}/>)}</g> })}
    {rows.map((row, index) => <g key={row.key}><text x={x(index)} y="216" textAnchor="middle">{row.label}</text><rect x={x(index) - 15} y="25" width="30" height="172" fill="transparent"/></g>)}
  </svg><div className="ad-chart-months" aria-label="Inspect a month">{rows.map(row => <button key={row.key} aria-pressed={selected === row.key} onClick={() => setSelected(selected === row.key ? null : row.key)}>{row.label}</button>)}</div>
  <div className="ad-legend">{series.map(series => <span key={series.key}><i style={{ background: series.color }}/>{series.label}</span>)}</div>
  <p className="ad-chart-detail" aria-live="polite">{focused ? `${focused.label}: ${focused.registered} new patients · ${focused.started} treatment starts · ${focused.completed} completed plans` : 'Select a month to inspect the recorded activity.'}</p></>
}
function OutcomePredictions({ stats, horizon, onHorizon }: { stats: Dashboard; horizon: number; onHorizon: (value: number) => void }) {
  const outcomes = stats.outcomes
  const cards = [
    {label:'New obesity cases', value:outcomes.newObesity, note:'Projected to cross BMI 30', tone:'rose', icon:'Patients', scope:outcomes.obesityEligible},
    {label:'Weight improvement', value:outcomes.improving, note:'On treatment · weight trending down', tone:'teal', icon:'Clinical care', scope:outcomes.improvementEligible},
    {label:'Below obesity threshold', value:outcomes.belowObesity, note:'Projected BMI below 30 on treatment', tone:'blue', icon:'Clinical care', scope:outcomes.improvementEligible},
    {label:'Treatment completion', value:outcomes.expectedCompletions, note:'Patients reaching a planned end date', tone:'violet', icon:'Treatment requests', scope:null},
  ]
  return <section className="ad-panel ad-outcomes" aria-label="Patient outcome predictions">
    <Heading title="Patient outcome predictions" subtitle="A forward view of patient health."><span className="ad-badge">Demo estimates</span></Heading>
    <div className="ad-outcome-window"><span>Forecast window</span><div className="ad-tabs" aria-label="Forecast window">{[30,60,90].map(days => <button key={days} aria-pressed={horizon === days} onClick={() => onHorizon(days)}>{days} days</button>)}</div></div>
    <div className="ad-outcome-cards">{cards.map(card => <article className={`ad-outcome-card ${card.tone}`} key={card.label}><div><span className={`ad-icon ${card.tone}`}><CareIcon name={card.icon}/></span><strong>{card.value ?? '—'}</strong></div><h3>{card.label}</h3><p>{card.value === null ? 'More measurement history needed' : card.note}</p><small>{card.scope === null ? 'Schedule-based expectation' : `${card.scope} ${card.scope === 1 ? 'patient' : 'patients'} with usable trends`}</small></article>)}</div>
    <div className="ad-outcome-coverage"><span>Trend coverage</span><b>{outcomes.assessable} / {outcomes.adults} adults</b><progress aria-label="Patients with usable measurement history" value={outcomes.assessable} max={Math.max(1,outcomes.adults)}/></div>
    <details className="ad-forecast-method"><summary>How these estimates work</summary><p>Extends each adult’s recorded weight and BMI trend to the end of the selected window. Requires two measurements 14–180 days apart, with the latest no more than 90 days old and a stable recorded height. Counts only patients with usable history; groups may overlap.</p><p><b>{outcomes.missingHistory} patients</b> need more usable history. A dash means insufficient evidence, not zero risk. Planned completion counts each patient once and does not mean recovery.</p><p>Illustrative trends only; not a validated clinical forecast. <a href="https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight" target="_blank" rel="noreferrer">Adult BMI category reference</a>.</p></details>
  </section>
}
export function AdminDashboard({ data, now, onNavigate }: { data: AppData; now: Date; onNavigate: Navigate }) {
  const [months, setMonths] = useState(6)
  const [horizon, setHorizon] = useState(90)
  const stats = useMemo(() => adminDashboardData(data, now, months, horizon), [data, now, months, horizon])
  const metrics: {label:string;value:number|string;note:string;icon:string;tone:string;page:AdminPage}[] = [
    {label:'Patients in programme',value:stats.patients,note:'Registered patients',icon:'Patients',tone:'blue',page:'Patients'},
    {label:'Active on treatment',value:stats.active,note:'Current treatment status',icon:'Clinical care',tone:'teal',page:'Patients'},
    {label:'Pending review',value:stats.pending,note:'Review & information needed',icon:'Treatment requests',tone:'amber',page:'Treatment requests'},
    {label:'Medicine availability',value:`${stats.availability}%`,note:`${stats.available} of ${stats.strengths.length} strengths in stock`,icon:'Inventory',tone:'teal',page:'Inventory'},
    {label:'Safety & supply alerts',value:stats.alerts.length,note:'Open programme alerts',icon:'Alerts',tone:'rose',page:'Alerts'},
    {label:'Upcoming appointments',value:stats.upcoming,note:'Scheduled & confirmed',icon:'Appointments',tone:'blue',page:'Appointments'},
  ]
  const insights: {icon:string;tone:string;title:string;text:string;value:number;action:string;page:AdminPage}[] = [
    {icon:'Treatment requests',tone:'amber',title:'Review queue',value:stats.pending,text:'Requests awaiting review or information.',action:'Review requests',page:'Treatment requests'},
    {icon:'Inventory',tone:stats.lowStock + stats.outOfStock ? 'rose':'teal',title:'Supply watch',value:stats.lowStock+stats.outOfStock,text:`${stats.lowStock} low-stock strengths · ${stats.outOfStock} unavailable.`,action:'Check inventory',page:'Inventory'},
    {icon:'Appointments',tone:'blue',title:'Upcoming care',value:stats.visits,text:`Scheduled visits in the next ${horizon} days.`,action:'View appointments',page:'Appointments'},
  ]
  return <div className="admin-dashboard">
    <section className="ad-hero"><div className="ad-hero-copy"><p className="ad-greeting"><i className="ad-flag" role="img" aria-label="United Arab Emirates flag"/><span>UAE Treatment Programme</span></p><h1><span className="ad-hero-headline"><span>Smarter Care</span><span aria-hidden="true"> · </span><span>Healthier Lives</span></span><span>Across the UAE</span></h1><p>Connected insights across patients, care delivery, inventory, safety and outcomes.</p><div className="ad-hero-actions"><button className="button primary" onClick={() => onNavigate('Reports')}>View national overview</button><button className="button secondary" onClick={() => onNavigate('Data assistant')}><CareIcon name="Data assistant"/> Explore insights</button></div></div></section>
    <div className="ad-body"><section className="ad-metrics" aria-label="Programme metrics">{metrics.map(item => <button className="ad-metric" key={item.label} onClick={() => onNavigate(item.page)}><span className={`ad-icon ${item.tone}`}><CareIcon name={item.icon}/></span><span className="ad-metric-arrow" aria-hidden="true">↗</span><strong>{typeof item.value === 'number' ? item.value.toLocaleString() : item.value}</strong><b>{item.label}</b><small>{item.note}</small></button>)}</section>
    <div className="ad-main-grid"><section className="ad-panel ad-patient-journey"><Heading title="Patient journey overview" subtitle="Monthly activity across all centres."><select aria-label="Patient journey date range" value={months} onChange={event => setMonths(Number(event.target.value))}><option value="6">Last 6 months</option><option value="3">Last 3 months</option><option value="12">Last 12 months</option></select></Heading><Journey rows={stats.journey}/></section><OutcomePredictions stats={stats} horizon={horizon} onHorizon={setHorizon}/><section className="ad-panel ad-insights"><div className="ad-insights-intro"><div><span className="ad-badge">Programme intelligence</span><h2>Program Insights</h2><p>What needs your attention today.</p></div><img src={assistantImage} alt=""/></div><div className="ad-insight-list">{insights.map(item => <button key={item.page} onClick={() => onNavigate(item.page)}><span className={`ad-icon ${item.tone}`}><CareIcon name={item.icon}/></span><span className="ad-insight-copy"><b>{item.title}</b><small>{item.text}</small><em>{item.action} <span aria-hidden="true">↗</span></em></span><strong>{item.value}</strong></button>)}</div><div className="ad-insight-source"><i/> From your shared programme records</div><button className="ad-solid-button" onClick={() => onNavigate('Data assistant')}>Explore with AI assistant <span aria-hidden="true">→</span></button></section></div>
    <div className="ad-operations-grid"><section className="ad-panel"><Heading title="Treatment requests" subtitle="Current status of the shared request queue."><button className="ad-link" onClick={() => onNavigate('Treatment requests')}>View all</button></Heading><div className="ad-request-tiles">{stats.requests.map(item => <button className={item.tone} key={item.label} onClick={() => onNavigate('Treatment requests')}><span className={`ad-icon ${item.tone}`}><CareIcon name="Treatment requests"/></span><b>{item.count}</b><small>{item.label}</small></button>)}</div><p className="ad-footnote">{data.requests.length} total requests, including completed and dispensed.</p></section>
    <section className="ad-panel"><Heading title="Inventory status" subtitle="Available stock after expiry and reservations."><button className="ad-link" onClick={() => onNavigate('Inventory')}>View inventory</button></Heading><div className="ad-inventory"><div className="ad-ring" style={{background:`conic-gradient(#00a28b ${stats.availability}%, #e8f3f2 0)`}}><div><strong>{stats.availability}%</strong><small>Strength availability</small></div></div><div className="ad-inventory-details">{[[stats.units,'Available units','teal'],[stats.lowStock,'Low stock strengths','amber'],[stats.outOfStock,'Out of stock strengths','rose']].map(([value,label,tone]) => <div key={label}><span className={`ad-icon ${tone}`}><CareIcon name={tone === 'amber' ? 'Alerts':'Inventory'}/></span><span><b>{value}</b><small>{label}</small></span></div>)}</div></div></section>
    <section className="ad-panel"><Heading title="Recent activity" subtitle="Latest recorded events across the programme."><button className="ad-link" onClick={() => onNavigate('Activity log')}>View all</button></Heading><div className="ad-activity">{stats.activity.map(item => <button key={item.id} onClick={() => onNavigate('Activity log')}><span className="ad-icon teal"><CareIcon name="Activity log"/></span><span><b>{item.action}</b><small>{item.entityId} · {item.detail}</small></span><time>{item.occurredAt ? new Date(item.occurredAt).toLocaleDateString('en-AE',{month:'short',day:'numeric'}) : item.time}</time></button>)}{!stats.activity.length && <p>No programme activity recorded yet.</p>}</div></section></div>
    <div className="ad-outlook-heading"><div><h2>Looking ahead</h2><p>Enrollment, dispensing and planned care delivery.</p></div><label>Planning window<select value={horizon} onChange={event => setHorizon(Number(event.target.value))}><option value="30">Next 30 days</option><option value="60">Next 60 days</option><option value="90">Next 90 days</option></select></label></div>
    <div className="ad-outlook-grid"><section className="ad-panel ad-predictions"><Heading title="Operational outlook" subtitle="Simple pace-based estimates, recalculated as records change."><span className="ad-badge">Estimated</span></Heading><div className="ad-prediction-values"><div><span className="ad-icon blue"><CareIcon name="Patients"/></span><strong>{stats.expectedEnrollment}</strong><b>Expected new patients</b><small>{stats.enrollment} registered in the last 90 days ÷ 90 × {horizon}.</small></div><div><span className="ad-icon teal"><CareIcon name="Dispensing"/></span><strong>{stats.expectedDispenses}</strong><b>Expected dispensing events</b><small>{stats.recentDispenses} recorded in the last 30 days ÷ 30 × {horizon}.</small></div></div><div className="ad-stock-outlook"><CareIcon name="Alerts"/><span><b>{stats.stockRisks.length ? `${stats.stockRisks.length} strengths may run short` : 'No projected stock shortfall at the recorded pace'}</b><small>{stats.stockRisks.length ? stats.stockRisks.map(item => `${item.dose}: ${item.demand} expected / ${item.quantity} available`).join(' · ') : 'Compares available units with dispensing demand for this window.'}</small></span><button className="ad-link" onClick={() => onNavigate('Inventory')}>Review stock</button></div><p className="ad-footnote">Assumes the recorded pace continues. Demo estimates, not a clinical prediction model.</p></section>
    <section className="ad-panel ad-expectations"><Heading title="Care delivery expectations" subtitle={`Scheduled commitments over the next ${horizon} days.`}/>{[{value:stats.visits,title:'Scheduled care visits',description:'Confirmed and scheduled appointments within the planning window.',page:'Appointments' as const,icon:'Appointments'},{value:stats.planMilestones,title:'Treatment milestones',description:'Current approved, pharmacy-ready or dispensed plans reaching their end date.',page:'Integrated care plans' as const,icon:'Clinical care'},{value:stats.pending,title:'Requests awaiting a decision',description:'Current review and information queue; timing depends on care team review.',page:'Treatment requests' as const,icon:'Treatment requests'}].map(item => <button className="ad-expectation" key={item.title} onClick={() => onNavigate(item.page)}><span className="ad-icon blue"><CareIcon name={item.icon}/></span><span><b>{item.title}</b><small>{item.description}</small></span><strong>{item.value}</strong><span aria-hidden="true">›</span></button>)}</section></div>
    <footer className="ad-footer"><CareIcon name="Clinical care"/><div><b>Better insights. Better decisions. Healthier communities.</b><span>One connected view of the UAE treatment programme.</span></div><span className="ad-demo"><i/> Demonstration data</span></footer>
    </div></div>
}
