import { PharmacyPatientDocuments } from './PharmacyDocumentViews'
import { navigationBadges } from './navigationBadges'
import { CareIcon } from './CareIcon'
import { WorkspaceLoading, Skeleton } from './WorkspaceLoading'
import { skeletonFor } from './workspacePresentation'
import { PatientAvatar } from './PatientAvatar'
import { lazy, Suspense, useEffect, useMemo, useState } from 'react'
import { verifyPharmacyRequest, dispenseMedication, canonicalize, releaseToPharmacy, completeTreatment, adherenceFor, calculateEligibility, treatmentEligibility, can, canReadPatient, decide, inventoryByDose, markNotificationRead, markNotificationsRead as markAllRead, onHandByDose, recordDose, reservedByDose, resubmitRequest, restock, setAbuseReviewStatus, supportedDoses, type AbuseReviewRecord, type AppData,  type RequestStatus, type Role } from './domain'
const ClinicalWorkspace = lazy(() => import('./WorkflowViews').then(module => ({ default: module.ClinicalWorkspace })))
const PatientActivity = lazy(() => import('./WorkflowViews').then(module => ({ default: module.PatientActivity })))
const OrganizationManagement = lazy(() => import('./OrganizationManagement').then(module => ({ default: module.OrganizationManagement })))
import { GeographicCareNetwork } from './CareMap'
const MisusePrevention = lazy(() => import('./AdminViews').then(module => ({ default: module.MisusePrevention })))
const SmartAssistant = lazy(() => import('./AdminViews').then(module => ({ default: module.SmartAssistant })))
const SafetyAlerts = lazy(() => import('./SafetyAlerts').then(module=>({default:module.SafetyAlerts})))
const DataAssistant = lazy(() => import('./DataAssistant').then(module => ({ default: module.DataAssistant })))
const ReviewerDashboard = lazy(() => import('./ReviewerDashboard').then(module => ({ default: module.ReviewerDashboard })))
const DoctorDashboard = lazy(() => import('./DoctorDashboard').then(module => ({ default: module.DoctorDashboard })))
const DoctorRequests = lazy(() => import('./DoctorRequests').then(module => ({ default: module.DoctorRequests })))
const DoctorAppointments = lazy(() => import('./DoctorAppointments').then(module => ({ default: module.DoctorAppointments })))
const PharmacyDispensing = lazy(() => import('./PharmacyDispensing').then(module => ({ default: module.PharmacyDispensing })))
const PharmacyInventory = lazy(() => import('./PharmacyInventory').then(module => ({ default: module.PharmacyInventory })))
const PharmacistDashboard = lazy(() => import('./PharmacistDashboard').then(module => ({ default: module.PharmacistDashboard })))

import { operationalAlerts, type AdminPage, type MisuseSignal } from './adminAnalytics'
import { useArabicDom } from './ArabicLayer'
import { loadMockData, saveMockData, subscribeMockData } from './mockRepository'
import { DraftPlanEditor, CareJourney, OperationsHome, RiskPanel } from './EcosystemViews'
import './App.css'
import { CarePlanDialog, IntegratedCareWorkspace, IntegratedPlanCards, MedicationCoverage, PatientContext } from './CarePlanViews'
import { PatientCareWorkspace } from './PatientCareWorkspace'
import { LoginGate } from './LoginGate'
import logo from './assets/healthcare-logo.png'
import { brandName } from './brand'
import assistantImage from './assets/login-ai-assistant.png'
const ActivityLog = lazy(() => import('./ActivityLog').then(module => ({ default: module.ActivityLog })))
const Reports = lazy(() => import('./Reports').then(module => ({ default: module.Reports })))
const AdminDashboard = lazy(() => import('./AdminDashboard').then(module => ({ default: module.AdminDashboard })))
import { DoctorTreatmentRequest } from './DoctorTreatmentRequest'
import { RegistrationForm } from './PatientRegistration'
import { Patient360, type Section as PatientSection } from './Patient360'
import './CareSystem.css'
import './IntegratedCare.css'
import './DoctorFlow.css'
import './PatientRegistry.css'
import './BrandTheme.css'
import './Drawer.css'
import './ProductPolish.css'

type Page = AdminPage | 'My care'
type PatientTab = 'Home' | 'Treatment' | 'Medication' | 'Progress' | 'Appointments' | 'Activity' | 'Notifications' | 'Profile'
type DrawerLink = { label: string; page: Page; icon: string; tab?: PatientTab }
type DrawerGroup = { label: string; icon: string; links: DrawerLink[] }
const patientTabs: PatientTab[] = ['Home', 'Treatment', 'Medication', 'Progress', 'Appointments', 'Activity', 'Notifications', 'Profile']
const drawerNavigation: Record<Role, DrawerGroup[]> = {
  Admin: [
    { label: 'MAIN', icon: 'dashboard', links: [
      { label: 'Dashboard', page: 'Overview', icon: 'dashboard' }, { label: 'Patients', page: 'Patients', icon: 'patients' }, { label: 'Treatment requests', page: 'Treatment requests', icon: 'clipboard' }, { label: 'Patient care', page: 'Integrated care plans', icon: 'care-plan' }, { label: 'Appointments', page: 'Appointments', icon: 'calendar' },
    ] },
    { label: 'OPERATIONS', icon: 'activity', links: [
      { label: 'Geographic analytics', page: 'Geographic analytics', icon: 'pin' }, { label: 'National inventory', page: 'Inventory', icon: 'box' }, { label: 'Safety & supply alerts', page: 'Alerts', icon: 'alert' }, { label: 'Live activity log', page: 'Activity log', icon: 'history' }, { label: 'Doctor management', page: 'Doctor management', icon: 'stethoscope' }, { label: 'Treatment centers', page: 'Treatment center management', icon: 'building' },
    ] },
    { label: 'INSIGHTS & GOVERNANCE', icon: 'chart', links: [
      { label: 'Misuse prevention', page: 'Misuse prevention', icon: 'decision' }, { label: 'Reports', page: 'Reports', icon: 'file' }, { label: 'System audit', page: 'System audit', icon: 'history' },
    ] },
  ],
  Doctor: [
    { label: 'MAIN', icon: 'dashboard', links: [
      { label: 'Dashboard', page: 'Overview', icon: 'dashboard' }, { label: 'Patients', page: 'Patients', icon: 'patients' }, { label: 'Treatment requests', page: 'Treatment requests', icon: 'clipboard' }, { label: 'Patient care', page: 'Integrated care plans', icon: 'care-plan' }, { label: 'Appointments', page: 'Appointments', icon: 'calendar' },
    ] },
    { label: '', icon: 'stethoscope', links: [
      { label: 'Geographic analytics', page: 'Geographic analytics', icon: 'pin' },
    ] },
  ],
  Reviewer: [
    { label: 'MAIN', icon: 'dashboard', links: [
      { label: 'Overview', page: 'Overview', icon: 'dashboard' }, { label: 'Review queue', page: 'Treatment requests', icon: 'clipboard' }, { label: 'Patients', page: 'Patients', icon: 'patients' }, { label: 'Integrated care plans', page: 'Integrated care plans', icon: 'care-plan' },
    ] },
    { label: 'REVIEW & EVIDENCE', icon: 'decision', links: [{ label: 'Decision support', page: 'Smart assistant', icon: 'decision' }] },
  ],
  Pharmacist: [
    { label: 'MAIN', icon: 'dashboard', links: [
      { label: 'Overview', page: 'Overview', icon: 'dashboard' }, { label: 'Dispensing', page: 'Dispensing', icon: 'pill' }, { label: 'Patients', page: 'Patients', icon: 'patients' }, { label: 'Integrated care plans', page: 'Integrated care plans', icon: 'care-plan' },
    ] },
    { label: 'OPERATIONS', icon: 'activity', links: [
      { label: 'National inventory', page: 'Inventory', icon: 'box' }, { label: 'Safety & supply alerts', page: 'Alerts', icon: 'alert' },
    ] },
  ],
  Patient: [
    { label: 'MY CARE', icon: 'home', links: patientTabs.slice(0, 3).map(tab => ({ label: tab, page: 'My care', tab, icon: tab === 'Home' ? 'home' : tab === 'Treatment' ? 'pill' : 'injection' })) },
    { label: 'CARE & PROGRESS', icon: 'activity', links: patientTabs.slice(3).map(tab => ({ label: tab, page: 'My care', tab, icon: tab === 'Progress' ? 'chart' : tab === 'Appointments' ? 'calendar' : tab === 'Activity' ? 'activity' : tab === 'Notifications' ? 'bell' : 'user' })) },
  ],
}
const patientCarePages: string[] = ['Integrated care plans', 'Continuous care', 'Clinical care', 'Smart assistant']
const statusClass = (status: RequestStatus) => status.toLowerCase().replaceAll(' ', '-')
function App() {
  const [displayDate] = useState(() => new Date())
  const [data, setData] = useState<AppData>(loadMockData)
  useEffect(() => subscribeMockData(setData), [])
  const [careContext,setCareContext]=useState<{patientId:string;planId:string|null}>({patientId:'',planId:null})
  const [carePlanPatient,setCarePlanPatient]=useState<string|null>(null)
  const [role, setRole] = useState<Role>('Admin')
  const [loggedIn,setLoggedIn]=useState(false)
  const [page, setPage] = useState<Page>('Overview')
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState<string | null>(null)
  const [patientSection,setPatientSection]=useState<PatientSection>('Overview')
  const [reason, setReason] = useState('')
  const [message, setMessage] = useState('')
  const [messageIsError,setMessageIsError] = useState(false)
  const [rtl, setRtl] = useState(() => localStorage.getItem('healthcare-language') === 'ar')
  const localizationRoot = useArabicDom(loggedIn && rtl, data.patients)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  const [showRegistration, setShowRegistration] = useState(false)
  const [showNewRequest, setShowNewRequest] = useState(false)
  const [showNotifications, setShowNotifications] = useState(false)
  const [notificationFilter, setNotificationFilter] = useState<'All' | 'Unread' | 'Read'>('All')
  const [draftPatient, setDraftPatient] = useState('P999')
  const [requestOrigin,setRequestOrigin]=useState<string|null>(null)
  const [patientTab, setPatientTab] = useState<PatientTab>('Home')
  useEffect(() => { localStorage.setItem('healthcare-language', rtl ? 'ar' : 'en'); document.documentElement.lang = rtl ? 'ar' : 'en'; document.documentElement.dir = rtl ? 'rtl' : 'ltr' }, [rtl])
  useEffect(() => {
    const dialog = document.querySelector<HTMLElement>('[role=dialog]')
    if (!dialog) return
    const previous = document.activeElement as HTMLElement | null
    const controls = () => Array.from(dialog.querySelectorAll<HTMLElement>('button:not([disabled]), input, select, textarea, [tabindex="0"]'))
    controls()[0]?.focus()
    const handler = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { if (showNewRequest) setShowNewRequest(false); else { setSelected(null); setShowNotifications(false); setShowRegistration(false) } }
      if (event.key === 'Tab') { const list = controls(); const first = list[0]; const last = list.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() } }
    }
    document.addEventListener('keydown',handler)
    return () => { document.removeEventListener('keydown',handler); previous?.focus() }
  }, [selected,showNewRequest,showNotifications,showRegistration])
  const patientIdentity=data.patients.find(p=>p.id===(data.activePatientId??'P999'))
  function openCarePlan(patientId:string){setCarePlanPatient(patientId)}
  function openMedicationRequest(patientId:string){setDraftPatient(patientId);setRequestOrigin(patientId);setShowNewRequest(true)}
  const persist = (next: AppData) => { setMessageIsError(false); const normalized = canonicalize(next); try { saveMockData(normalized); setData(normalized) } catch { throw new Error('Browser storage is unavailable. Your changes could not be saved. Export or free browser storage and retry.') } }
  const requests = useMemo(() => data.requests.filter(request => { const patient = data.patients.find(item => item.id === request.patientId); return `${request.id} ${patient?.name} ${patient?.id} ${request.status} ${request.dose} ${request.medication ?? 'Mounjaro'} ${patient?.emirate ?? ''}`.toLowerCase().includes(search.toLowerCase()) }), [data, search])
  function changeRole(next: Role) { setCareContext({patientId:'',planId:null}); setCarePlanPatient(null); setSearch(''); setShowNotifications(false); setShowNewRequest(false); setReason(''); setRole(next); setPage(drawerNavigation[next][0].links[0].page); setPatientTab('Home'); setSelected(null); setMessage('') }
  function runAction(action: 'approve' | 'information' | 'reject' | 'dispense', id: string) { try { persist(action === 'dispense' ? dispenseMedication(data,role,id,true) : decide(data, role, id, action, reason)); setMessage(action === 'approve' ? 'Request approved and sent to pharmacy.' : action === 'dispense' ? 'Dispensing completed. Stock, patient history and audit were updated.' : action === 'information' ? 'The doctor has been asked to provide more information.' : 'Request rejected with a recorded reason.'); setReason(''); setSelected(null) } catch (error) { setMessageIsError(true); setMessage(error instanceof Error ? error.message : 'The action could not be completed.') } }
  function runResubmit(id: string) { try { persist(resubmitRequest(data, role, id, reason)); setMessage('Updated request returned to the reviewer queue.'); setReason(''); setSelected(null) } catch (error) { setMessageIsError(true); setMessage(error instanceof Error ? error.message : 'Request could not be resubmitted.') } }
  function recordPatientDose() { try { const next = recordDose(data, role, data.activePatientId??'P999'); persist(next); setMessage('Dose recorded. Your progress and care team activity are up to date.') } catch (error) { setMessageIsError(true); setMessage(error instanceof Error ? error.message : 'Dose could not be recorded.') } }
  function receiveStock(dose: string, quantity: number, batch: string, expiry: string, centre: string, source: string, receivedAt: string) { try { persist(restock(data, role, dose, quantity, batch, expiry, centre, source, receivedAt)); setMessage(`${quantity} units of ${dose} received from ${source} and recorded against the batch.`); return true } catch (error) { setMessageIsError(true); setMessage(error instanceof Error ? error.message : 'Stock could not be received.'); return false } }
  const visibleNotifications = data.notifications.filter(item => canReadPatient(data,role,item.patientId))
  const unreadNotifications = visibleNotifications.filter(item => !item.read).length
  function markOneRead(id: string) { try { persist(markNotificationRead(data, role, id)) } catch (error) { setMessageIsError(true); setMessage(error instanceof Error ? error.message : 'Notification could not be updated.') } }
  function markNotificationsRead() { try { persist(markAllRead(data, role)) } catch(error) { setMessageIsError(true); setMessage((error as Error).message) } }
  function navigateFromAlert(target: Page, id?: string) { setPage(target); setSelected(target === 'Treatment requests' ? id ?? null : target === 'Patients' && id ? `patient:${id}` : null) }
  function navigateAdmin(target: AdminPage, selection?: string) {
    const canonical: Record<string, AdminPage> = {'Doctor portal':'Patients','Distribution portal':'Treatment requests','Patient portal':'Patients','System audit':'System audit','Doctor management':'Doctor management','Treatment center management':'Treatment center management'}
    setPage(canonical[target]??target)
    setSelected(selection ?? null)
  }
  function reviewSafetySignal(signal: MisuseSignal, status: AbuseReviewRecord['status']) { try { persist(setAbuseReviewStatus(data, role, signal, status)); setMessage(`Safety signal marked ${status.toLowerCase()}.`) } catch (error) { setMessageIsError(true); setMessage(error instanceof Error ? error.message : 'Safety signal could not be updated.') } }
  const filteredNotifications = visibleNotifications.filter(item => notificationFilter === 'All' || (notificationFilter === 'Unread' ? !item.read : item.read))

  const workspaceDescription: Record<Role, string> = { Admin: 'Administrator access', Doctor: 'Clinical workspace', Reviewer: 'Medical review access', Pharmacist: 'Pharmacy operations', Patient: 'Patient care access' }
  const drawerPromo: Record<Role, { title: string; description: string; page: Page; tab?: PatientTab }> = {
    Admin: { title: 'AI Assistant', description: 'Get insights, analyze data and take action across the programme.', page: 'Data assistant' },
    Doctor: { title: 'AI Assistant', description: 'Get insights, analyze data and take action across the programme.', page: 'Data assistant' },
    Reviewer: { title: 'Decision support', description: 'Review clinical evidence alongside the shared patient record.', page: 'Smart assistant' },
    Pharmacist: { title: 'Safe dispensing', description: 'Verify treatment requests, stock and dispensing records.', page: 'Dispensing' },
    Patient: { title: 'Care companion', description: 'See your care plan, progress and upcoming appointments.', page: 'My care', tab: 'Home' },
  }
  const badges=useMemo(()=>navigationBadges(data,role),[data,role])
  const navBadge = (link: DrawerLink) => {
    if (link.tab === 'Notifications' && role === 'Patient') return data.notifications.filter(item => item.patientId === (data.activePatientId ?? 'P999') && !item.read).length
    return badges[link.page]??0
  }
  function navigateDrawer(link: Pick<DrawerLink, 'page' | 'tab'>) { setPage(link.page); if (link.tab) setPatientTab(link.tab); setSelected(null); setMobileOpen(false) }
  if(!loggedIn)return <LoginGate data={data} arabic={rtl} onLanguage={()=>setRtl(value=>!value)} onEnter={selectedRole=>{changeRole(selectedRole);setLoggedIn(true)}}/>
  const profileName = role === 'Patient' ? patientIdentity?.name ?? 'Patient' : role === 'Reviewer' ? 'Dr. Mariam Nasser' : role === 'Pharmacist' ? (rtl ? data.pharmacists?.[0]?.nameAr ?? data.pharmacists?.[0]?.name : data.pharmacists?.[0]?.name) ?? 'Pharmacist' : role === 'Doctor' ? data.doctors.find(d => d.id === (data.activeDoctorId ?? data.doctors[0]?.id))?.name ?? 'Doctor' : (rtl ? 'د. ليلى حسن' : 'Dr. Laila Hassan')
  const profileInitials = profileName.split(' ').filter(Boolean).slice(-2).map(part => part[0]).join('').toUpperCase()
  const activeWorkspace = drawerPromo[role]
  const unifiedCare = ['Admin','Doctor','Reviewer'].includes(role) && patientCarePages.includes(page)
  return <div ref={localizationRoot} className={`app role-${role.toLowerCase()} ${rtl ? 'rtl' : ''} ${sidebarCollapsed ? 'drawer-collapsed' : ''}`} dir={rtl ? 'rtl' : 'ltr'} lang={rtl ? 'ar' : 'en'}>
    <a className="skip-link" href="#main-content">Skip to content</a><aside className={`sidebar drawer-shell ${mobileOpen ? 'open' : ''}`}>
      <div className="brand drawer-brand"><div className="brand-mark"><img src={logo} alt=""/></div><div className="drawer-brand-copy"><strong data-no-localize>{brandName(rtl)}</strong><small>{rtl ? 'برنامج العلاج في الإمارات' : 'UAE treatment programme'}</small></div><button className="drawer-collapse" aria-label={sidebarCollapsed ? 'Expand navigation' : 'Collapse navigation'} title={sidebarCollapsed ? 'Expand navigation' : 'Collapse navigation'} onClick={() => { if (window.matchMedia('(max-width: 760px)').matches) setMobileOpen(false); else setSidebarCollapsed(value => !value) }}><span aria-hidden="true">«</span></button></div>
      <div className="workspace-label">Care workspace</div>
      <div className="role-switch drawer-role-switch"><span className="drawer-role-icon"><CareIcon name="patients"/></span><span className="role-dot"/><span className="drawer-role-copy"><b>{role}</b>{role !== 'Doctor' && <small>{workspaceDescription[role]}</small>}</span><select aria-label="Choose workspace role" value={role} onChange={event => changeRole(event.target.value as Role)}>{(['Admin', 'Doctor', 'Reviewer', 'Pharmacist', 'Patient'] as Role[]).map(item => <option key={item}>{item}</option>)}</select><span className="chevron">⌄</span></div>
      <nav className="primary-nav drawer-navigation" aria-label="Main navigation">{drawerNavigation[role].map(group => <section className="drawer-group" key={group.label}>{group.label && <div className="drawer-group-heading"><span><CareIcon name={group.icon}/></span><b>{group.label}</b><i/></div>}{group.links.map(link => { const active = link.label === 'Patient care' ? unifiedCare : link.page === 'My care' ? page === 'My care' && patientTab === link.tab : page === link.page; const badge = navBadge(link); return <button key={`${link.page}-${link.tab ?? link.label}`} aria-current={active ? 'page' : undefined} title={sidebarCollapsed ? link.label : undefined} className={`nav-item ${active ? 'active' : ''}`} onClick={() => navigateDrawer(link)}><span className="nav-icon"><CareIcon name={link.icon}/></span><span className="drawer-link-label">{link.label}</span>{badge > 0 && <span className={`nav-count ${link.page === 'Alerts' ? 'alert-badge' : ''}`}>{badge}</span>}<span className="drawer-link-chevron" aria-hidden="true">›</span></button> })}</section>)}</nav>
      {role === 'Patient' && <label className="patient-profile-select drawer-patient-select">Demo patient profile<select aria-label="Demo patient profile" value={data.activePatientId ?? 'P999'} onChange={event => { persist({ ...data, activePatientId: event.target.value }); setPatientTab('Home') }}>{data.patients.map(patient => <option key={patient.id} value={patient.id}>{patient.id} · {patient.name} · {patient.residency}</option>)}</select></label>}
      <div className="sidebar-spacer"/>
      {<button className="drawer-promo" title={activeWorkspace.description} aria-label={activeWorkspace.title} onClick={() => navigateDrawer(activeWorkspace)}><span className="drawer-assistant-icon">{['Admin','Doctor'].includes(role) ? <img className="drawer-assistant-robot" src={assistantImage} alt=""/> : <CareIcon name={role === 'Pharmacist' ? 'pill' : role === 'Patient' ? 'care-plan' : 'decision'}/>}</span><b>{activeWorkspace.title}</b><span className="drawer-promo-arrow" aria-hidden="true">›</span></button>}{!['Admin','Doctor'].includes(role)&&<button className="drawer-promo assistant-entry" onClick={()=>{setPage('Data assistant');setSelected(null);setMobileOpen(false)}}><CareIcon name="bot"/><span>{rtl?'المساعد الذكي':'AI assistant'}</span><CareIcon name="open"/></button>}
      <div className="profile drawer-profile" title={`${profileName} · ${role}`}><div className="avatar" aria-hidden="true">{profileInitials}</div><div className="profile-info"><b>{profileName}</b></div></div>
    </aside>
    {mobileOpen && <button className="scrim" aria-label="Close navigation" onClick={() => setMobileOpen(false)}/>}
    <main className="main-area"><header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><CareIcon name="menu"/></button>{role==='Admin'&&['Overview','Reports'].includes(page)&&<form className="admin-top-search" onSubmit={event=>{event.preventDefault();setPage('Patients');setSelected(null)}}><CareIcon name="search"/><input aria-label="Search patients" placeholder={rtl?'ابحث عن مريض بالاسم أو الرقم...':'Search patients by name, ID or emirate...'} value={search} onChange={event=>setSearch(event.target.value)}/><button type="submit" aria-label="Search patient registry"><CareIcon name="search"/></button></form>}<div className="crumb">Programme <span>/</span> {unifiedCare ? (rtl ? 'رعاية المريض' : 'Patient care') : page}</div>{role==='Doctor'&&['Overview','Appointments'].includes(page)&&<form className="doctor-top-search" onSubmit={event=>{event.preventDefault();if(page==='Overview'){setPage('Patients');setSelected(null)}}}><CareIcon name="search"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={page==='Appointments'?(rtl?'ابحث عن مريض أو رقم طلب أو موعد...':'Search patient or appointment...'):(rtl?'ابحث عن مريض...':'Search patients...')} aria-label={rtl?'ابحث عن مريض':'Search patients'}/></form>}<div className="top-actions"><div className="today"><span className="calendar-icon"><CareIcon name="calendar"/></span> {displayDate.toLocaleDateString(rtl ? 'ar-AE' : 'en-AE', {day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Dubai'})}</div><button className="icon-button language" onClick={() => setRtl(!rtl)} aria-label="Switch language">{rtl ? 'EN' : 'ع'}<span>Language</span></button><button className="icon-button bell" aria-label={`Notifications, ${unreadNotifications} unread`} onClick={() => setShowNotifications(!showNotifications)}><CareIcon name="Bell"/>{unreadNotifications > 0 && <span className="notification-count">{unreadNotifications}</span>}<i/></button><div className="top-avatar" title={profileName}>{profileInitials}</div><button className="icon-button top-signout" aria-label={rtl ? 'تسجيل الخروج' : 'Sign out'} title={rtl ? 'تسجيل الخروج' : 'Sign out'} onClick={() => { setLoggedIn(false); setSelected(null); setMobileOpen(false); setShowNotifications(false) }}><CareIcon name="logout"/></button></div></header>
      <div className={`page-content ${page==='Data assistant'?'assistant-workspace-page':''} ${['Doctor management','Treatment center management'].includes(page)?'organization-page':''} ${['Activity log','System audit'].includes(page)?'activity-log-page':''} ${page==='Alerts'?'safety-alerts-page':''} ${unifiedCare?'patient-care-page':''} ${role==='Admin'&&page==='Overview'?'admin-dashboard-page':''} ${page==='Reports'?'reports-workspace-page':''} ${role==='Reviewer'&&page==='Overview'?'reviewer-dashboard-page':''} ${role==='Doctor'&&page==='Overview'?'doctor-dashboard-page':''} ${['Admin','Doctor','Reviewer'].includes(role)&&page==='Treatment requests'?'doctor-requests-page':''} ${page==='Appointments'?'doctor-appointments-page':''} ${role==='Pharmacist'&&page==='Dispensing'?'pharmacy-dispensing-page':''} ${['Admin','Pharmacist'].includes(role)&&page==='Inventory'?'pharmacy-inventory-page':''} ${role==='Pharmacist'&&page==='Overview'?'pharmacist-dashboard-page':''} ${role==='Admin'&&page==='Integrated care plans'?'admin-care-plans-page':''} ${page==='Geographic analytics'?'geographic-care-page':''}`} id="main-content"><WorkspaceLoading workspace={`${role}:${unifiedCare?'Patient care':page}:${page==='My care'?patientTab:''}`} arabic={rtl}><Suspense fallback={<Skeleton kind={skeletonFor(page)} arabic={rtl}/>}>
        <div className={`page-heading ${['Admin','Doctor'].includes(role)&&page==='Patients'&&selected?.startsWith('patient:')?'patient-detail-heading-hidden':''}`}><div><div className="greeting">{role === 'Admin' ? 'Good morning, Laila' : role === 'Patient' ? 'Your care, in one place' : `Good morning, ${role.toLowerCase()}`}</div><h1>{page === 'Overview' ? role === 'Admin' ? 'Dashboard' : role === 'Doctor' ? 'Clinical dashboard' : role === 'Reviewer' ? 'Medical review' : 'Pharmacy operations' : role === 'Admin' && page === 'Inventory' ? 'National inventory' : role === 'Admin' && page === 'Alerts' ? 'Safety & supply alerts' : role === 'Admin' && page === 'Activity log' ? 'Live activity log' : page === 'Smart assistant' ? 'Decision support' : page === 'Data assistant' ? 'AI assistant' : page}</h1><p>{page === 'Overview' ? 'A clear view of programme operations, care activity and supply.' : page === 'Treatment requests' ? 'Review requests and follow each decision through dispensing.' : descriptions[page]}</p></div><div className="heading-actions">{['Admin','Doctor'].includes(role) && page === 'Patients' && !selected && <button className="button primary" onClick={() => setShowRegistration(true)}>{rtl?'إضافة مريض':'Add patient'}</button>}{role === 'Admin' && page === 'Overview' && <span className="period-select"><CareIcon name="calendar"/> Programme snapshot</span>}{role === 'Doctor' && !['Integrated care plans'].includes(page) && <button className="button primary" onClick={() => {setRequestOrigin(null);setShowNewRequest(true)}}><CareIcon name="plus"/> New treatment request</button>}</div></div>
        {message && <div className={`toast ${messageIsError ? 'toast-error' : ''}`} role="status"><span>{messageIsError ? '!' : '✓'}</span>{message}<button onClick={() => setMessage('')} aria-label="Dismiss">×</button></div>}
        {page === 'Overview' && role==='Doctor' && <DoctorDashboard data={data} arabic={rtl} onNavigate={navigateAdmin} onPatient={id=>{setPatientSection('Overview');setPage('Patients');setSelected(`patient:${id}`)}}/>}
        {page === 'Overview' && role==='Pharmacist' && <PharmacistDashboard data={data} arabic={rtl} onUpdate={persist} onNavigate={target=>{setPage(target);setSelected(null)}}/>}
        {page === 'Overview' && role==='Admin' && <AdminDashboard data={data} now={displayDate} onNavigate={navigateAdmin}/>}
        {page === 'Overview' && role==='Reviewer' && <ReviewerDashboard data={data} arabic={rtl} now={displayDate} onNavigate={navigateAdmin} onPatient={id=>{setPatientSection('Overview');setPage('Patients');setSelected(`patient:${id}`)}}/>}
        {page === 'Overview' && !['Admin','Doctor','Pharmacist','Reviewer'].includes(role) && <OperationsHome data={data} role={role} onPatient={id => setSelected(`patient:${id}`)} onNavigate={(target,id) => { setPage(target); setSelected(id ? target === 'Patients' ? `patient:${id}` : id : null) }}/>}
        {unifiedCare && <PatientCareWorkspace key={role} context={careContext} onContext={setCareContext} data={data} role={role} arabic={rtl} page={page as AdminPage} onNavigate={navigateAdmin} onUpdate={persist} onCreateRequest={openMedicationRequest} onPatient={(id,section)=>{setPatientSection(section??'Overview');setPage('Patients');setSelected(`patient:${id}`)}}/>}
        {(page === 'Continuous care'||page==='Integrated care plans') && !unifiedCare && <IntegratedCareWorkspace key={page} data={data} role={role} arabic={rtl} onUpdate={persist} onPatient={id=>{setPatientSection('Care Plan');setPage('Patients');setSelected(`patient:${id}`)}}/>}
        {carePlanPatient && <CarePlanDialog data={data} role={role} patientId={carePlanPatient} onClose={()=>setCarePlanPatient(null)} onSaved={next=>{persist(next);setPage('Patients');setPatientSection('Care Plan');setSelected(`patient:${carePlanPatient}`);setCarePlanPatient(null)}} onCreateRequest={id=>{setCarePlanPatient(null);openMedicationRequest(id)}}/>}
        {showRegistration && <RegistrationForm data={data} role={role} arabic={rtl} onUpdate={persist} onClose={() => setShowRegistration(false)} onCreated={(id)=>{setShowRegistration(false);setPatientSection('Overview');setSelected(`patient:${id}`)}}/>}
        {page === 'Geographic analytics' && ['Admin','Doctor'].includes(role) && <GeographicCareNetwork data={{...data,patients:data.patients.filter(p=>canReadPatient(data,role,p.id))}} arabic={rtl}/>}
        {page === 'Data assistant' && <DataAssistant onCreateRequest={['Admin','Doctor'].includes(role)?()=>{setRequestOrigin(null);setShowNewRequest(true)}:undefined} key={role} role={role} data={data} arabic={rtl} onNavigate={(target,id)=>{if(target==='Integrated care plans'&&id){const plan=data.integratedCarePlans?.find(p=>p.id===id);if(plan)setCareContext({patientId:plan.patientId,planId:plan.id})}if(role==='Patient'){setPage('My care');setPatientTab(target==='Appointments'?'Appointments':target==='Treatment requests'||target==='Integrated care plans'?'Treatment':target==='Activity log'?'Activity':'Home')}else if(role==='Pharmacist'&&target==='Treatment requests'){setPage('Dispensing');setSelected(null)}else navigateAdmin(target,id)}}/>}
        {page === 'Smart assistant' && !unifiedCare && <SmartAssistant arabic={rtl} canViewInventory={can(role,'inventory:read')} data={{...data, patients: data.patients.filter(p => canReadPatient(data,role,p.id))}} onNavigate={navigateAdmin}/>}
        {page === 'Misuse prevention' && role === 'Admin' && <MisusePrevention data={data} onReview={reviewSafetySignal}/>}
        {page === 'Doctor management' && role === 'Admin' && <OrganizationManagement key="doctors" mode="doctors" data={data} arabic={rtl} onUpdate={persist}/>}
        {page === 'Treatment center management' && role === 'Admin' && <OrganizationManagement key="centres" mode="centres" data={data} arabic={rtl} onUpdate={persist}/>}
        {page === 'System audit' && role === 'Admin' && <ActivityLog key="audit" mode="audit" data={data} arabic={rtl} role={role} onUpdate={persist} onNavigate={navigateFromAlert}/>}
        {page === 'Patients' && !(['Admin','Doctor'].includes(role)&&selected?.startsWith('patient:')) && <Patients role={role} data={data} arabic={rtl} search={search} setSearch={setSearch} onSelect={(id,section)=>{setPatientSection(section??'Overview');setSelected(id.startsWith('patient:') ? id : `patient:${id}`)}} onCreateRequest={openMedicationRequest} onCreateCarePlan={openCarePlan}/>}
        {page === 'Treatment requests' && ['Admin','Doctor','Reviewer'].includes(role) && <DoctorRequests data={data} role={role} arabic={rtl} requests={data.requests.filter(item=>canReadPatient(data,role,item.patientId))} selected={selected} onSelect={setSelected} onNew={()=>{setDraftPatient('');setRequestOrigin(null);setShowNewRequest(true)}} reason={reason} onReason={setReason} onAction={runAction} onResubmit={runResubmit}/>}
        {page === 'Treatment requests' && !['Admin','Doctor','Reviewer'].includes(role) && <Requests key={`${role}-${page}`} role={role} data={data} requests={requests.filter(item => canReadPatient(data, role, item.patientId))} search={search} setSearch={setSearch} selected={selected} setSelected={setSelected} reason={reason} setReason={setReason} onAction={runAction} onResubmit={runResubmit} onUpdate={persist}/>}
        {page === 'Dispensing' && role === 'Pharmacist' && <PharmacyDispensing data={data} arabic={rtl} onUpdate={persist}/>}
        {page === 'Inventory' && ['Admin','Pharmacist'].includes(role) && <><PharmacyInventory data={data} arabic={rtl}/>{role==='Admin'&&<details className="admin-stock-management"><summary>{rtl?'إدارة التوريد والمخزون':'Manage supply and inventory'}</summary><Inventory data={data} role={role} onRestock={receiveStock}/></details>}</>}
        {page === 'Inventory' && !['Admin','Pharmacist'].includes(role) && <Inventory data={data} role={role} onRestock={receiveStock}/>}{page === 'Reports' && <Reports data={data} now={displayDate} onUpdate={persist} arabic={rtl}/>}{page === 'Activity log' && <ActivityLog data={data} arabic={rtl} role={role} onUpdate={persist} onNavigate={(target,id)=>{setPage(target);setSelected(target==='Patients'&&id?`patient:${id}`:id??null)}}/>}{page === 'Alerts' && <SafetyAlerts data={data} arabic={rtl} onUpdate={persist} onNavigate={navigateFromAlert} role={role}/>}{page === 'My care' && <PatientHome arabic={rtl} key={data.activePatientId??'P999'} data={data} onRecordDose={recordPatientDose} activeTab={patientTab} setActiveTab={setPatientTab} onUpdate={persist} role={role}/>}{page === 'Clinical care' && !unifiedCare && <ClinicalWorkspace data={data} role={role} arabic={rtl} onUpdate={persist} onPatient={id=>{setPatientSection('Analysis');setPage('Patients');setSelected(`patient:${id}`)}}/>}{page === 'Appointments' && <DoctorAppointments key={`${role}:${selected??'list'}`} initialId={selected??undefined} role={role} data={data} arabic={rtl} query={search} onQuery={setSearch} onUpdate={persist}/>}
        {selected?.startsWith('patient:') && ['Admin','Doctor'].includes(role) && canReadPatient(data,role,selected.slice(8)) && <Patient360 key={`${selected}-${patientSection}`} initialTab={patientSection} arabic={rtl} role={role} onUpdate={persist} onCreateCarePlan={openCarePlan} onCreateRequest={openMedicationRequest} patientId={selected.slice(8)} data={data} onBack={() => setSelected(null)}/>}
        {selected?.startsWith('patient:') && !['Admin','Doctor'].includes(role) && canReadPatient(data,role,selected.slice(8)) && <PatientDetail key={`${selected}-${patientSection}`} initialTab={patientSection} role={role} onUpdate={persist} onCreateCarePlan={openCarePlan} onCreateRequest={openMedicationRequest} patientId={selected.slice(8)} data={data} close={() => setSelected(null)}/>}
        {showNewRequest && ['Admin','Doctor'].includes(role) && <DoctorTreatmentRequest data={data} role={role} initialPatientId={draftPatient} arabic={rtl} onClose={()=>{setShowNewRequest(false);if(requestOrigin){setPage('Patients');setSelected(`patient:${requestOrigin}`)}setRequestOrigin(null)}} onComplete={(next,draft)=>{persist(next);setShowNewRequest(false);setRequestOrigin(null);setPage(requestOrigin?'Patients':'Treatment requests');setSelected(requestOrigin?`patient:${requestOrigin}`:next.requests[0]?.id??null);setMessage(draft?'Treatment draft saved':next.requests[0]?.status==='Ready to dispense'?'System criteria met. Request sent to pharmacy.':'Doctor exception sent for approval review.')}}/>}
        {showNotifications && <div className="modal-backdrop" onClick={() => setShowNotifications(false)}><section className="patient-modal panel notifications-modal" role="dialog" aria-modal="true" aria-label="Notifications" onClick={event => event.stopPropagation()}><button className="close-button" aria-label="Close notifications" onClick={() => setShowNotifications(false)}>×</button><div className="panel-head"><div><h2>Notifications</h2><p>Updates generated by programme activity · {visibleNotifications.filter(item => !item.read).length} unread</p></div><button className="text-link" onClick={markNotificationsRead}>Mark all read</button></div>
          <div className="notification-filters" role="group" aria-label="Filter notifications">{(['All', 'Unread', 'Read'] as const).map(value => <button key={value} aria-pressed={notificationFilter === value} className={notificationFilter === value ? 'selected' : ''} onClick={() => setNotificationFilter(value)}>{value}</button>)}</div>
          {filteredNotifications.length ? filteredNotifications.map(item => <button className={`notification-row notification-open ${item.read ? '' : 'unread'}`} key={item.id} onClick={() => { markOneRead(item.id); setShowNotifications(false); if (role === 'Patient') { setPage('My care'); setPatientTab(['Dose record','Pharmacy documents'].includes(item.relatedEntity??'') ? 'Medication' : 'Notifications') } else if (item.relatedEntity === 'Treatment request') { setPage(role === 'Pharmacist' ? 'Dispensing' : 'Treatment requests'); setSelected(role === 'Pharmacist' ? null : item.relatedEntityId ?? null) } else { setPage('Patients'); setSelected(`patient:${item.patientId}`) } }}><span className="step-icon green">•</span><span><b>{item.title}</b><small>{item.detail}</small><time>{item.createdAt} · {data.patients.find(patient => patient.id === item.patientId)?.name ?? item.patientId}{item.relatedEntityId ? ` · ${item.relatedEntityId}` : ''}</time></span><span className="notification-unread-indicator">{item.read ? 'Read' : 'Unread'} ›</span></button>) : <div className="empty-state"><div><CareIcon name="walk"/></div><b>No {notificationFilter.toLowerCase()} notifications</b><span>Updates will appear here when a request or care activity changes.</span></div>}
        </section></div>}
      </Suspense></WorkspaceLoading></div>
      <footer className="footer"><span data-no-localize>{brandName(rtl)}</span><span>Frontend demonstration <i/> Local browser storage</span></footer>
    </main>
  </div>
}
export default App
const descriptions: Record<Page, string> = { 'Integrated care plans':'Coordinate medication, rehabilitation, home exercises and follow-up with one doctor-confirmed plan.', 'Continuous care': 'Medication, rehabilitation, activity and follow-up in one shared care record.', Overview: 'A clear view of programme operations, care activity and supply.', 'Geographic analytics': 'Find nearby rehabilitation, pharmacy outlets and treatment centres on the shared care map.', Patients: 'Search and open a patient record to review their care.', 'Treatment requests': 'A shared queue for clinical review, decisions and handoff.', Inventory: 'Available medication across participating treatment centres.', Alerts: 'Operational items derived from current programme activity.', 'Activity log': 'A live operational stream of care team and inventory events.', 'Smart assistant': 'Rule-based clinical evidence and safety context for authorized care teams.', 'Data assistant': 'Ask questions about the records currently stored in this application.', 'Misuse prevention': 'Review operational patterns flagged by transparent safety rules.', Reports: 'Programme activity calculated from shared treatment records.', 'Doctor portal': 'Complete clinician workspace for patient search, clinical review and treatment requests.', 'Distribution portal': 'Pharmacy workflow for verification, dispensing and inventory.', 'Patient portal': 'Patient view of care, medication, appointments and progress.', 'Doctor management': 'Manage programme doctor assignments and current workload.', 'Treatment center management': 'Review facility operations, care teams, inventory and activity.', 'System audit': 'Filterable security and governance history of programme state changes.', 'My care': 'Your current treatment, next steps and progress.', Dispensing: 'Verify approved requests and record medication dispensing.', 'Clinical care': 'Review and update structured assessments, vitals and laboratory evidence.', Appointments: 'Schedule care visits and track appointment outcomes across the programme.' }
function Requests({ role, data, requests, search, setSearch, selected, setSelected, reason, setReason, onAction, onResubmit, onUpdate }: { role: Role; data: AppData; requests: AppData['requests']; search: string; setSearch: (value: string) => void; selected: string | null; setSelected: (value: string | null) => void; reason: string; setReason: (value: string) => void; onAction: (action: 'approve' | 'information' | 'reject' | 'dispense', id: string) => void; onResubmit: (id: string) => void; onUpdate: (data: AppData) => void }) {
  const [operationError,setOperationError] = useState('')
  function advance(id: string, complete = false) { try { onUpdate(complete ? completeTreatment(data,role,id,reason) : releaseToPharmacy(data,role,id)); setOperationError('') } catch(error) { setOperationError((error as Error).message) } }
  const [statusFilter, setStatusFilter] = useState<RequestStatus | 'All'>(role === 'Reviewer' ? 'Under review' : 'All')
  const [sortOrder, setSortOrder] = useState<'Newest' | 'Oldest' | 'Priority'>('Newest')
  const [eligibilityFilter, setEligibilityFilter] = useState<'All' | 'Meets criteria' | 'Needs review'>('All')
  const item = requests.find(value => value.id === selected)
  const [now] = useState(() => Date.now())
  const visible = requests.filter(row => {
    const patient = data.patients.find(person => person.id === row.patientId)
    const eligibility = patient ? treatmentEligibility(data,patient.id).eligible : false
    return (statusFilter === 'All' || row.status === statusFilter) && (eligibilityFilter === 'All' || (eligibilityFilter === 'Meets criteria' ? eligibility : !eligibility))
  }).slice().sort((a,b) => {
    if (sortOrder === 'Priority') {
      const aged = (item: typeof a) => item.status === 'Under review' && item.createdAt && now - new Date(item.createdAt).getTime() > 48 * 3600000 ? 0 : item.status === 'Needs information' ? 1 : 2
      return aged(a) - aged(b) || (b.createdAt ?? '').localeCompare(a.createdAt ?? '')
    }
    return sortOrder === 'Newest' ? (b.createdAt ?? '').localeCompare(a.createdAt ?? '') : (a.createdAt ?? '').localeCompare(b.createdAt ?? '')
  })
  return <>
    <section className="queue-toolbar"><div className="searchbox"><span><CareIcon name="search"/></span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search patient, request, dose or emirate" aria-label="Search requests"/></div><label className="filter-field">Status<select className="filter-button" value={statusFilter} onChange={event => setStatusFilter(event.target.value as RequestStatus | 'All')}><option>All</option>{(['Draft','Under review','Approved','Ready to dispense','Dispensed','Completed','Needs information','Rejected'] as RequestStatus[]).map(value => <option key={value}>{value}</option>)}</select></label><label className="filter-field">Eligibility<select className="filter-button" value={eligibilityFilter} onChange={event => setEligibilityFilter(event.target.value as typeof eligibilityFilter)}><option>All</option><option>Meets criteria</option><option>Needs review</option></select></label><label className="filter-field sort-field">Sort<select className="filter-button" value={sortOrder} onChange={event => setSortOrder(event.target.value as typeof sortOrder)}><option>Newest</option><option>Oldest</option><option>Priority</option></select></label><span className="result-count">{visible.length} requests</span></section>
    {item && <section className="panel request-detail"><div className="detail-header"><div><button className="back-link" onClick={() => setSelected(null)}>← Back to queue</button><h2>{item.id} <span className={`status ${statusClass(item.status)}`}><i/>{item.status}</span></h2></div><button className="close-button" aria-label="Close details" onClick={() => setSelected(null)}>×</button></div>
      <div className="detail-grid"><div><small>Patient</small><b>{data.patients.find(p => p.id === item.patientId)?.name}</b></div><div><small>Patient ID</small><b>{item.patientId}</b></div><div><small>Medication</small><b>{item.medication ?? 'Mounjaro'} · {item.dose}</b></div><div><small>Treatment plan</small><b>{item.planId}</b></div><div><small>Duration / follow-up</small><b>{item.durationDays ? `${item.durationDays} days · ${item.followUpDate ?? '—'}` : data.treatmentPlans.find(plan => plan.id === item.planId)?.followUpDate ?? '—'}</b></div></div>
      <CareJourney data={data} patientId={item.patientId}/><RequestEvidence data={data} request={item} role={role}/>{operationError && <p role="alert" className="inline-warning">{operationError}</p>}{item.status === 'Draft' && can(role,'request:submit') && <DraftPlanEditor key={item.id} data={data} role={role} requestId={item.id} onUpdate={onUpdate}/>}{item.status === 'Approved' && can(role,'request:review') && <button className="button primary" onClick={() => advance(item.id)}>Release to pharmacy</button>}{item.status === 'Dispensed' && can(role,'clinical:write') && <div className="completion-form"><label className="reason-label">Follow-up summary<textarea value={reason} onChange={e => setReason(e.target.value)} rows={2}/></label><button className="button primary" onClick={() => advance(item.id,true)}>Complete treatment</button></div>}{item.note && <div className="inline-warning">Request note: {item.note}</div>}
      {item.status === 'Under review' && can(role, 'request:review') && <><label className="reason-label">Reason or note <span>{item.approvalRoute==='Exception review'?'Required for exception approval, rejection or information request':'Required for rejection or information request'}</span><textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Add clinical rationale or requested information" rows={3}/></label><div className="detail-actions"><button className="button quiet" onClick={() => onAction('information', item.id)}>Request information</button><button className="button danger" onClick={() => onAction('reject', item.id)}>Reject request</button><button className="button primary" onClick={() => onAction('approve', item.id)}>Approve request</button></div></>}
      {item.status === 'Needs information' && can(role, 'request:submit') && <><label className="reason-label">Updated evidence summary <span>Required to return this request to review</span><textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Summarize the updated clinical information" rows={3}/></label><div className="detail-actions"><button className="button primary" onClick={() => onResubmit(item.id)}>Resubmit for review</button></div></>}
      {item.status === 'Ready to dispense' && can(role, 'request:dispense') && <DispensingSafety key={item.id} data={data} request={item} onDispense={() => onAction('dispense', item.id)}/>}</section>}
    <section className="panel queue-panel"><div className="panel-head"><div><h2>{selected ? 'Other requests' : role === 'Reviewer' ? 'Review queue' : role === 'Pharmacist' ? 'Dispensing queue' : 'All treatment requests'}</h2><p>Patient, plan and request evidence stay linked to the shared programme record.</p></div></div><div className="table-wrap"><table><thead><tr><th>Patient</th><th>Request</th><th>Medication</th><th>Submitted</th><th>Eligibility</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map(row => { const patient = data.patients.find(p => p.id === row.patientId)!; const eligible = treatmentEligibility(data,patient.id).eligible; return <tr key={row.id}><td><button className="patient-link" onClick={() => setSelected(`patient:${patient.id}`)}><PatientAvatar patient={patient} className="mini-avatar"/><span><b>{patient.name}</b><small>{patient.id} · {patient.emirate}</small></span></button></td><td className="mono">{row.id}</td><td>{row.dose} · {row.medication ?? 'Mounjaro'}</td><td>{row.created}</td><td><span className={`eligibility-pill ${eligible ? 'met' : 'watch'}`}>{eligible ? 'Meets criteria' : 'Review required'}</span></td><td><span className={`status ${statusClass(row.status)}`}><i/>{row.status}</span></td><td><button className="button table-button" onClick={() => setSelected(row.id)}>{row.status === 'Ready to dispense' && role === 'Pharmacist' ? 'Verify' : 'Review'}</button></td></tr>})}</tbody></table>{visible.length === 0 && <div className="empty-state"><div><CareIcon name="search"/></div><b>No matching requests</b><span>Try another patient, ID, status or eligibility filter.</span></div>}</div><div className="table-mobile">{visible.map(row => { const patient = data.patients.find(p => p.id === row.patientId)!; const eligible = treatmentEligibility(data,patient.id).eligible; return <button className="mobile-record" key={row.id} onClick={() => setSelected(row.id)}><PatientAvatar patient={patient} className="mini-avatar"/><span className="mobile-record-info"><b>{patient.name} · {row.id}</b><small>{row.dose} · {row.medication ?? 'Mounjaro'} · {patient.emirate}</small><span className={`status ${statusClass(row.status)}`}><i/>{row.status}</span><small>{eligible ? 'Meets criteria' : 'Review required'}</small></span><span>›</span></button>})}{visible.length === 0 && <div className="empty-state"><b>No matching requests</b><span>Try another patient, ID, status or eligibility filter.</span></div>}</div></section>
  </>
}
function RequestEvidence({ data, request, role }: { data: AppData; request: AppData['requests'][number]; role:Role }) {
  const patient = data.patients.find(item => item.id === request.patientId)
  const plan = data.treatmentPlans.find(item => item.id === request.planId)
  const assessment = data.assessments.filter(item => item.patientId === request.patientId).sort((a,b) => b.createdAt.localeCompare(a.createdAt))[0]
  const vitals = data.vitals.filter(item => item.patientId === request.patientId).sort((a,b) => b.recordedAt.localeCompare(a.recordedAt))[0]
  const labs = data.labs.filter(item => item.patientId === request.patientId).sort((a,b) => b.date.localeCompare(a.date))
  const eligibility = patient ? calculateEligibility(patient, data.labs) : null
  const history = data.audit.filter(item => item.entityId === request.id).slice(0, 8)
  return <div className="request-evidence">{request.integratedCarePlanId&&<div className="evidence-box"><b>Integrated care plan</b><span>{request.integratedCarePlanId} · {data.integratedCarePlans?.find(p=>p.id===request.integratedCarePlanId)?.title}</span></div>}{role==='Pharmacist'&&<MedicationCoverage data={data} patientId={request.patientId} requestId={request.id}/ >}{request.approvalRoute==='Exception review'&&<section className="evidence-box exception-rationale"><b>Doctor-requested exception</b><span>System findings: {request.exceptionReasons?.join(' · ')||'See eligibility evidence below'}</span><span>Doctor rationale: {request.doctorRationale||'No rationale recorded'}</span><span>{request.exceptionApproved?'Reviewer approved this exception':'Awaiting independent reviewer decision'}</span></section>}<section className="evidence-box"><b>Transparent eligibility review</b><span>Based on current clinical evidence and monthly refill timing. Only documented exceptions require reviewer approval.</span>{eligibility?.criteria.map(item => <span key={item.label} className={item.passed ? 'evidence-pass' : 'evidence-fail'}><CareIcon name={item.passed?'check':'alert'}/> {item.label} · {item.evidence}</span>)}{eligibility?.warnings.map(item => <span className="evidence-fail" key={item}>Warning · {item}</span>)}</section>
    <div className="detail-grid"><div><small>Assessment</small><b>{assessment ? `${assessment.reason} · ${assessment.status}` : 'Missing clinical assessment'}</b></div><div><small>Latest findings / plan</small><b>{assessment ? `${assessment.findings} · ${assessment.notes}` : 'No note on record'}</b></div><div><small>Medical history / allergies</small><b>{assessment ? `${assessment.medicalHistory} · ${assessment.allergies}` : 'Not recorded'}</b></div><div><small>Latest vitals</small><b>{vitals ? `${vitals.weightKg} kg · ${vitals.heightCm} cm · BMI ${vitals.bmi} · BP ${vitals.systolic}/${vitals.diastolic} · HR ${vitals.heartRate}` : 'No vitals on record'}</b></div><div><small>Treatment plan</small><b>{plan ? `${plan.frequency} · ${plan.durationDays} days · ${plan.startDate} to ${plan.endDate} · follow-up ${plan.followUpDate}` : 'Plan not linked'}</b></div><div><small>Prescription</small><b>{request.prescriptionId ?? 'Created after approval'}</b></div></div>
    <div className="evidence-box"><b>Laboratory history</b>{labs.length ? labs.slice(0, 5).map(item => <span key={item.id}>{item.test}: {item.value} {item.unit} · {item.status} · {item.date} · {item.interpretation}</span>) : <span>Required clinical lab evidence is missing.</span>}</div>
    <div className="evidence-box"><b>Review and audit history</b>{history.length ? history.map(item => <span key={item.id}>{item.actor} · {item.action} · {item.time} · {item.previousState ?? '—'} → {item.newState ?? '—'}{item.reason ? ` · ${item.reason}` : ''}</span>) : <span>No prior review event is recorded for this request.</span>}</div></div>
}
function DispensingSafety({ data, request, onDispense }: { data: AppData; request: AppData['requests'][number]; onDispense: () => void }) {
  const [identityConfirmed, setIdentityConfirmed] = useState(false)
  const checks = verifyPharmacyRequest(data,request.id,identityConfirmed)
  const blocked = checks.some(item => !item.passed)
  return <section className="safety-panel"><div><h3>Dispensing verification</h3><p>Every check must pass. The earliest-expiry valid batch is assigned automatically.</p></div><div className="verification-grid">{checks.map(check => <div className={`safety-check ${check.passed ? 'passed' : 'blocked'}`} key={check.id}><span><CareIcon name={check.passed?'check':'alert'}/></span><b>{check.label}</b><small>{check.evidence}</small></div>)}</div><label className="identity-check"><input type="checkbox" checked={identityConfirmed} onChange={event => setIdentityConfirmed(event.target.checked)}/><span>I verified the patient identity at collection.</span></label>{blocked && <div className="inline-warning">Resolve the highlighted checks before dispensing. No stock is committed until verification passes.</div>}<div className="detail-actions"><button className="button primary" disabled={blocked} onClick={onDispense}>Confirm dispensing</button></div></section>
}

function RegistryIcon({name}:{name:'view'|'treatment'|'care'|'medication'|'appointment'|'more'}){
 const icons={view:'eye',treatment:'Treatment requests',care:'Care plan',medication:'Medication',appointment:'Appointments',more:'more'}
 return <CareIcon name={icons[name]}/>
}
function Patients({ role, data, arabic, search, setSearch, onSelect, onCreateRequest, onCreateCarePlan }: { role: Role; data: AppData; arabic:boolean; search: string; setSearch: (v: string) => void; onSelect: (id: string,section?:PatientSection) => void; onCreateRequest:(id:string)=>void; onCreateCarePlan:(id:string)=>void }) {
 const [residency,setResidency]=useState('All')
 const [emirate,setEmirate]=useState('All')
 const [centre,setCentre]=useState('All')
 const [treatment,setTreatment]=useState('All')
 const [eligibility,setEligibility]=useState('All')
 const [medication,setMedication]=useState('All')
 const [doctor,setDoctor]=useState('All')
 const [risk,setRisk]=useState('All')
 const [sort,setSort]=useState('Name A–Z')
 const [page,setPage]=useState(0)
 const accessible=data.patients.filter(p=>canReadPatient(data,role,p.id))
 const flagged=new Set(operationalAlerts(data).flatMap(item=>item.patientId?[item.patientId]:[]))
 const t=(en:string,ar:string)=>arabic?ar:en
 const name=(p:AppData['patients'][number])=>arabic&&p.nameAr&&p.nameAr!=='مستفيد البرنامج'?p.nameAr:p.name
 const type=(value:string|undefined)=>arabic?({'Citizen':'مواطن','Resident':'مقيم','Visitor':'زائر'} as Record<string,string>)[value??'']??'—':value??'—'
 const status=(value:string|undefined)=>arabic?({'Meets clinical criteria':'مستوفي المعايير','Refill timing':'توقف إعادة الصرف','Review required':'قيد المراجعة','Not eligible':'غير مؤهل','Active':'تحت العلاج','No active plan':'لا توجد خطة علاج'} as Record<string,string>)[value??'']??'—':value??'—'
 const eligibilityTone=(value:string|undefined)=>value==='Meets clinical criteria'?'good':value==='Not eligible'?'bad':'warn'
 const filtered=accessible.filter(p=>{const text=`${p.name} ${p.nameAr??''} ${p.id} ${p.emirate} ${p.treatmentCentre??''} ${p.assignedDoctor??''} ${p.currentDose??''}`.toLowerCase();const alert=flagged.has(p.id);return text.includes(search.toLowerCase())&&(residency==='All'||p.residency===residency)&&(emirate==='All'||p.emirate===emirate)&&(centre==='All'||p.treatmentCentre===centre)&&(treatment==='All'||p.treatmentStatus===treatment)&&(eligibility==='All'||p.eligibility===eligibility)&&(medication==='All'||p.currentDose===medication)&&(doctor==='All'||p.assignedDoctor===doctor)&&(risk==='All'||(risk==='Flagged'?alert:!alert))}).sort((a,b)=>sort==='BMI high–low'?b.bmi-a.bmi:sort==='Adherence low–high'?adherenceFor(data,a.id)-adherenceFor(data,b.id):sort==='Follow-up newest'?String(b.lastFollowup??'').localeCompare(String(a.lastFollowup??'')):a.name.localeCompare(b.name))
 const pageSize=10,pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)),currentPage=Math.min(page,pageCount-1),visible=filtered.slice(currentPage*pageSize,(currentPage+1)*pageSize)
 const resetPage=(action:()=>void)=>{action();setPage(0)}
 const lastDispense=(id:string)=>data.dispenses.filter(d=>d.patientId===id).sort((a,b)=>(b.dispensedAt??b.date).localeCompare(a.dispensedAt??a.date))[0]
 const formatDate=(value?:string)=>value?new Intl.DateTimeFormat(arabic?'ar-AE':'en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Dubai'}).format(new Date(`${value}T12:00:00Z`)):'—'
 const open=(id:string,section:PatientSection='Overview')=>onSelect(`patient:${id}`,section)
 const action=(id:string,section:PatientSection,label:string,icon:'view'|'treatment'|'care'|'medication'|'appointment',className='')=><button type="button" className={`registry-action ${className}`} title={label} aria-label={`${label} · ${id}`} onClick={()=>open(id,section)}><RegistryIcon name={icon}/></button>
 const menu=(p:AppData['patients'][number])=><details className="registry-more"><summary title={t('More actions','المزيد من الإجراءات')} aria-label={`${t('More actions','المزيد من الإجراءات')} · ${p.id}`}><RegistryIcon name="more"/></summary><div className="registry-more-menu"><button onClick={()=>open(p.id,'Clinical History')}>{t('Clinical history','التاريخ السريري')}</button><button onClick={()=>open(p.id,'Analysis')}>{t('Analysis / labs','التحاليل')}</button><button onClick={()=>open(p.id,'Documents')}>{t('Documents','المستندات')}</button><button onClick={()=>open(p.id,'Notifications')}>{t('Notifications','الإشعارات')}</button><button onClick={()=>open(p.id,'Activity')}>{t('Activity','النشاط')}</button><button onClick={()=>open(p.id,'Treatment')}>{t('Medication / dispensing','الدواء والصرف')}</button><button onClick={()=>open(p.id,'Appointments')}>{t('Appointments','المواعيد')}</button>{can(role,'clinical:write')&&<><button onClick={()=>onCreateRequest(p.id)}>{t('Create treatment request','إنشاء طلب علاج')}</button><button onClick={()=>onCreateCarePlan(p.id)}>{t('Create care plan','إنشاء خطة رعاية')}</button></>}</div></details>
 const actions=(p:AppData['patients'][number])=><div className="registry-actions">{action(p.id,'Overview',t('View Patient 360','عرض ملف المريض 360'),'view','primary')}{action(p.id,'Treatment',t('Treatment','العلاج'),'treatment')}{action(p.id,'Care Plan',t('Care plan','خطة الرعاية'),'care')}{menu(p)}</div>
 return <div className="registry-enterprise" dir={arabic?'rtl':'ltr'}>
  <div className="registry-kpis"><article><span>{t('Total patients','إجمالي المرضى')}</span><strong>{accessible.length}</strong><small>{t('Accessible records','ملفات متاحة')}</small></article><article><span>{t('Active','نشط')}</span><strong>{accessible.filter(p=>p.isActive).length}</strong><small>{t('Current programme status','حالة البرنامج الحالية')}</small></article><article><span>{t('Eligible','مؤهل')}</span><strong>{accessible.filter(p=>p.eligibility==='Meets clinical criteria').length}</strong><small>{t('Current system criteria','معايير النظام الحالية')}</small></article><article><span>{t('Under treatment','تحت العلاج')}</span><strong>{accessible.filter(p=>p.treatmentStatus==='Active').length}</strong><small>{t('Active treatment record','سجل علاج نشط')}</small></article></div>
  <section className="registry-workspace" aria-label={t('Patient registry','سجل المرضى')}><div className="registry-heading"><div><span>{t('CLINICAL DIRECTORY','الدليل السريري')}</span><h2>{t('Patient registry','سجل المرضى')}</h2><p>{t('Search and open the shared care record for each patient.','ابحث وافتح سجل الرعاية المشترك لكل مريض.')}</p></div><b>{filtered.length} {t('patients','مريض')}</b></div>
   <div className="registry-toolbar"><label className="registry-search"><span aria-hidden="true"><CareIcon name="search"/></span><input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder={t('Search name, ID, doctor or centre','ابحث بالاسم أو الرقم أو الطبيب أو المركز')} aria-label={t('Search patients','البحث عن المرضى')}/></label><label className="registry-sort">{t('Sort','الترتيب')}<select value={sort} onChange={e=>resetPage(()=>setSort(e.target.value))}><option>Name A–Z</option><option>BMI high–low</option><option>Adherence low–high</option><option>Follow-up newest</option></select></label></div>
   <div className="registry-types" role="group" aria-label={t('Patient type','فئة المريض')}>{(['All','Citizen','Resident','Visitor'] as const).map(value=><button key={value} aria-pressed={residency===value} className={residency===value?'selected':''} onClick={()=>resetPage(()=>setResidency(value))}>{value==='All'?t('All patient types','جميع فئات الإقامة'):value==='Citizen'?t('Citizen','مواطن'):value==='Resident'?t('Resident','مقيم'):t('Visitor','زائر')}</button>)}</div>
   {role==='Admin'&&<div className="admin-filter-bar patient-admin-filters"><label>{t('Emirate','الإمارة')}<select value={emirate} onChange={e=>resetPage(()=>setEmirate(e.target.value))}><option value="All">{t('All','الكل')}</option>{[...new Set(data.patients.map(p=>p.emirate))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>{t('Treatment centre','مركز العلاج')}<select value={centre} onChange={e=>resetPage(()=>setCentre(e.target.value))}><option value="All">{t('All','الكل')}</option>{data.centres.map(c=><option key={c.id}>{c.name}</option>)}</select></label><label>{t('Treatment status','حالة العلاج')}<select value={treatment} onChange={e=>resetPage(()=>setTreatment(e.target.value))}><option value="All">{t('All','الكل')}</option><option value="Active">{t('Active','نشط')}</option><option value="No active plan">{t('No active plan','لا توجد خطة نشطة')}</option></select></label><label>{t('Eligibility','الأهلية')}<select value={eligibility} onChange={e=>resetPage(()=>setEligibility(e.target.value))}><option value="All">{t('All','الكل')}</option>{[...new Set(data.patients.map(p=>p.eligibility).filter(Boolean))].map(x=><option key={x}>{x}</option>)}</select></label><label>{t('Medication','الدواء')}<select value={medication} onChange={e=>resetPage(()=>setMedication(e.target.value))}><option value="All">{t('All','الكل')}</option>{[...new Set(data.patients.map(p=>p.currentDose).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>{t('Doctor','الطبيب')}<select value={doctor} onChange={e=>resetPage(()=>setDoctor(e.target.value))}><option value="All">{t('All','الكل')}</option>{[...new Set(data.patients.map(p=>p.assignedDoctor).filter(Boolean))].sort().map(x=><option key={x}>{x}</option>)}</select></label><label>{t('Risk / alert','الخطورة / التنبيه')}<select value={risk} onChange={e=>resetPage(()=>setRisk(e.target.value))}><option value="All">{t('All','الكل')}</option><option value="Flagged">{t('Flagged','به تنبيه')}</option><option value="Clear">{t('Clear','بلا تنبيه')}</option></select></label></div>}
   <div className="registry-table-scroll"><table className="registry-enterprise-table"><thead><tr><th>{t('Patient','المريض')}</th><th>{t('Type','الفئة')}</th><th>{t('Emirate / centre','الإمارة / المركز')}</th><th>{t('Doctor','الطبيب')}</th><th>BMI</th><th>{t('Adherence','الالتزام')}</th><th>{t('Eligibility','الأهلية')}</th><th>{t('Last dispense','آخر صرف')}</th><th>{t('Actions','الإجراءات')}</th></tr></thead><tbody>{visible.map(p=>{const adherence=adherenceFor(data,p.id),dispense=lastDispense(p.id);return <tr key={p.id}><td><button className="registry-patient-link" onClick={()=>open(p.id)}><PatientAvatar patient={p} className="registry-avatar" arabic={arabic}/><span><b>{name(p)}</b><small>{p.id} · {p.age} {t('years','عامًا')} · {type(p.residency)} · {p.emirate}</small><em className={p.treatmentStatus==='Active'?'active':''}>{status(p.treatmentStatus)}</em></span></button></td><td>{type(p.residency)}</td><td><span className="registry-cell-stack"><b>{p.emirate}</b><small>{p.treatmentCentre??'—'}</small></span></td><td>{p.assignedDoctor??'—'}</td><td><span className="registry-bmi">{p.bmi.toFixed(1)}</span></td><td><div className="registry-adherence"><strong>{adherence}%</strong><progress value={adherence} max={100} aria-label={`${t('Adherence','الالتزام')} ${p.id}: ${adherence}%`}/></div></td><td><span className={`registry-badge ${eligibilityTone(p.eligibility)}`}>{status(p.eligibility)}</span></td><td className="registry-date">{formatDate(dispense?.date)}</td><td>{actions(p)}</td></tr>})}</tbody></table>{visible.length===0&&<div className="registry-empty"><b>{t('No patients match these filters','لا يوجد مرضى يطابقون البحث')}</b><p>{t('Change the search or filters to see other records.','غيّر البحث أو عوامل التصفية لعرض ملفات أخرى.')}</p></div>}</div>
   <div className="registry-mobile-list">{visible.map(p=>{const adherence=adherenceFor(data,p.id);return <article className="registry-mobile-card" key={p.id}><div className="registry-mobile-head"><PatientAvatar patient={p} className="registry-avatar" arabic={arabic}/><div><b>{name(p)}</b><small>{p.id} · {p.age} {t('years','عامًا')} · {type(p.residency)} · {p.emirate}</small></div><span className={`registry-badge ${eligibilityTone(p.eligibility)}`}>{status(p.eligibility)}</span></div><div className="registry-mobile-details"><span>{p.assignedDoctor??'—'}</span><span>{p.currentDose?`Mounjaro ${p.currentDose}`:'—'}</span><span>{t('Last dispense','آخر صرف')}: {formatDate(lastDispense(p.id)?.date)}</span><span>{t('Adherence','الالتزام')}: {adherence}%</span></div>{actions(p)}</article>})}{visible.length===0&&<div className="registry-empty">{t('No matching patients','لا يوجد مرضى مطابقون')}</div>}</div>
   <div className="registry-pagination"><span>{t('Showing','عرض')} {filtered.length?currentPage*pageSize+1:0}–{Math.min((currentPage+1)*pageSize,filtered.length)} {t('of','من')} {filtered.length}</span><div><button aria-label={t('Previous page','الصفحة السابقة')} disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>{arabic?'›':'‹'}</button>{Array.from({length:pageCount},(_,i)=>i).slice(Math.max(0,Math.min(currentPage,pageCount-3)),Math.max(3,Math.min(pageCount,currentPage+3))).map(i=><button key={i} className={currentPage===i?'selected':''} aria-current={currentPage===i?'page':undefined} onClick={()=>setPage(i)}>{i+1}</button>)}<button aria-label={t('Next page','الصفحة التالية')} disabled={currentPage>=pageCount-1} onClick={()=>setPage(currentPage+1)}>{arabic?'‹':'›'}</button></div><small>{t('Page','صفحة')} {currentPage+1} / {pageCount}</small></div>
  </section>
 </div>
}
function Inventory({ data, role, onRestock }: { data: AppData; role: Role; onRestock: (dose: string, quantity: number, batch: string, expiry: string, centre: string, source: string, receivedAt: string) => boolean }) {
  const stock = inventoryByDose(data)
  const onHand = onHandByDose(data)
  const reserved = reservedByDose(data)
  const [dose, setDose] = useState<typeof supportedDoses[number]>(supportedDoses[0])
  const [quantity, setQuantity] = useState(12)
  const [batchNumber, setBatchNumber] = useState('')
  const [expiry, setExpiry] = useState('2027-03-31')
  const [centre, setCentre] = useState('Dubai Central Pharmacy')
  const [source, setSource] = useState('Gulf Medical Supply LLC')
  const [receivedAt, setReceivedAt] = useState(() => todayIso())
  const [search, setSearch] = useState('')
  const [confirmedReceipt, setConfirmedReceipt] = useState(false)
  const [inventoryNow] = useState(() => Date.now())
  const today = new Date(inventoryNow).toISOString().slice(0, 10)
  const expiryCutoff = new Date(inventoryNow + 60 * 86400000).toISOString().slice(0, 10)
  const tomorrow = new Date(inventoryNow + 86400000).toISOString().slice(0, 10)
  const total = Object.values(stock).reduce((sum, item) => sum + item, 0)
  const lots = data.batches.filter(item => `${item.dose} ${item.batchNumber} ${item.centre}`.toLowerCase().includes(search.toLowerCase())).sort((a,b) => a.expiry.localeCompare(b.expiry))
  const nearExpiry = data.batches.filter(item => item.quantity > 0 && item.expiry <= expiryCutoff)
  return <div className="workflow-stack"><section className="workflow-summary panel"><div><small>Total available units</small><b>{total}</b></div><div><small>Medication strengths</small><b>{supportedDoses.length}</b></div><div><small>Low stock strengths</small><b>{Object.values(stock).filter(item => item < 12).length}</b></div><div><small>Batches near expiry</small><b>{nearExpiry.length}</b></div></section>
    <div className="workflow-columns inventory-columns"><section className="panel workflow-card"><div className="panel-head"><div><h2>National inventory</h2><p>Live totals are calculated from dispensing and receipt transactions.</p></div><span className="map-mark">All centres</span></div><div className="table-wrap"><table><thead><tr><th>Medication strength</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Reorder point</th><th>Stock status</th></tr></thead><tbody>{Object.entries(stock).map(([strength, amount]) => <tr key={strength}><td><b>Mounjaro · {strength}</b></td><td>{onHand[strength]} units</td><td>{reserved[strength]} units</td><td>{amount} units</td><td>12 units</td><td><span className={`status ${amount < 12 ? 'needs-information' : 'ready-to-dispense'}`}><i/>{amount < 12 ? 'Reorder needed' : 'Available'}</span></td></tr>)}</tbody></table></div></section>
    {can(role, 'inventory:manage') && <section className="panel workflow-card"><div className="panel-head"><div><h2>Receive stock</h2><p>Add a traceable medication batch to programme inventory.</p></div></div><form className="form-grid compact single-column" onSubmit={event => { event.preventDefault(); if (onRestock(dose, quantity, batchNumber, expiry, centre, source, receivedAt)) { setBatchNumber(''); setConfirmedReceipt(false) } }}><label>Medication strength<select value={dose} onChange={event => setDose(event.target.value as typeof supportedDoses[number])}>{supportedDoses.map(item => <option key={item}>{item}</option>)}</select></label><label>Quantity<input type="number" min="1" max="10000" step="1" value={quantity} onChange={event => setQuantity(Number(event.target.value))} required/></label><label>Batch number<input value={batchNumber} onChange={event => setBatchNumber(event.target.value)} required placeholder="e.g. UAE-2026-B01"/></label><label>Expiry date<input type="date" min={tomorrow} value={expiry} onChange={event => setExpiry(event.target.value)} required/></label><label>Treatment centre<select value={centre} onChange={event => setCentre(event.target.value)} required>{data.centres.filter(item => item.status === 'Active').map(item => <option key={item.id}>{item.name}</option>)}</select></label><label>Supplier / source<input value={source} onChange={event => setSource(event.target.value)} required/></label><label>Received date<input type="date" max={today} value={receivedAt} onChange={event => setReceivedAt(event.target.value)} required/></label><label className="confirm-receipt"><input type="checkbox" checked={confirmedReceipt} onChange={event => setConfirmedReceipt(event.target.checked)} required/><span>I confirm the batch details and receipt quantity.</span></label><button className="button primary" type="submit" disabled={!confirmedReceipt}>Receive batch</button></form></section>}</div>
    <section className="panel workflow-card"><div className="panel-head"><div><h2>Batch inventory</h2><p>Batch quantities reconcile to receipt and dispensing movements; ready requests reserve units at strength level.</p></div><span className="result-count">{data.batches.length} batches</span></div><div className="queue-toolbar"><div className="searchbox"><span><CareIcon name="search"/></span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search strength, batch or centre" aria-label="Search batches"/></div></div><div className="table-wrap"><table><thead><tr><th>Batch</th><th>Strength</th><th>Received</th><th>Dispensed</th><th>On hand</th><th>Centre</th><th>Supplier / source</th><th>Receipt date</th><th>Expiry</th><th>Status</th></tr></thead><tbody>{lots.map(item => { const expired = item.expiry <= today; const soon = !expired && item.expiry <= expiryCutoff; const batchMovements = data.movements.filter(movement => movement.batchId === item.id); const receivedQuantity = batchMovements.filter(movement => movement.quantity > 0).reduce((sum, movement) => sum + movement.quantity, 0) || item.quantity; const dispensedQuantity = -batchMovements.filter(movement => movement.quantity < 0).reduce((sum, movement) => sum + movement.quantity, 0); return <tr key={item.id}><td className="mono">{item.batchNumber}</td><td>{item.dose}</td><td>{receivedQuantity}</td><td>{dispensedQuantity}</td><td>{item.quantity}</td><td>{item.centre}</td><td>{item.source}</td><td>{item.receivedAt}</td><td>{item.expiry}</td><td><span className={`status ${expired || item.quantity === 0 ? 'rejected' : soon ? 'needs-information' : 'ready-to-dispense'}`}><i/>{expired ? 'Expired' : item.quantity === 0 ? 'Depleted' : soon ? 'Expiring soon' : 'Available'}</span></td></tr>})}</tbody></table>{lots.length === 0 && <div className="empty-state"><b>No matching batches</b><span>Change the search to find inventory.</span></div>}</div></section>
    <div className="workflow-columns"><section className="panel workflow-card"><div className="panel-head"><div><h2>Inventory movements</h2><p>Receipts and dispensing adjustments</p></div></div>{data.movements.map(item => <div className="workflow-history" key={item.id}><b>{item.type} · {item.quantity > 0 ? '+' : ''}{item.quantity} {item.dose}</b><span>{item.reference} · {item.centre} · {new Date(item.at).toLocaleString()}</span><small>{item.actor} · {item.note}</small></div>)}</section><section className="panel workflow-card"><div className="panel-head"><div><h2>Dispensing records</h2><p>Completed medication transactions</p></div></div>{data.dispenses.length ? <div className="dispense-list">{data.dispenses.map(item => <div key={item.id}><b>{data.patients.find(patient => patient.id === item.patientId)?.name} · {item.patientId}</b><span>{item.dose} · {item.centre}</span><small>{item.date} · {item.id} · Batch {data.batches.find(batch => batch.id === item.batchId)?.batchNumber ?? 'legacy record'}</small></div>)}</div> : <div className="empty-state"><b>No dispensing recorded</b><span>Completed requests will appear here with centre and dose details.</span></div>}</section></div></div>
}

function todayIso() { return new Date().toISOString().slice(0,10) }
function PatientHome({ arabic, data, role, onUpdate, onRecordDose, activeTab, setActiveTab }: { arabic:boolean;data: AppData; role: Role; onUpdate: (data: AppData) => void; onRecordDose: () => void; activeTab: PatientTab; setActiveTab: (tab: PatientTab) => void }) {
  const [appointmentQuery,setAppointmentQuery]=useState('')
  const patient = data.patients.find(item => item.id === (data.activePatientId??'P999'))!
  const requests = data.requests.filter(item => item.patientId === patient.id).sort((a,b)=>(b.createdAt??'').localeCompare(a.createdAt??''))
  const request = requests.find(item => item.status === 'Under review') ?? requests[0]
  const activeRequest = requests.find(item=>item.status==='Dispensed')
  const activePlan = data.treatmentPlans.find(item=>item.id===activeRequest?.planId)
  const intervalDays = activePlan?.frequency==='Daily'?1:activePlan?.frequency==='Every 2 weeks'?14:7
  const loggedToday = data.doses.some(item=>item.patientId===patient.id && item.recordedAt.slice(0,10)===todayIso())
  const doses = data.doses.filter(item => item.patientId === patient.id).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt))
  const notifications = data.notifications.filter(item => item.patientId === patient.id)
  const dispenses = data.dispenses.filter(item => item.patientId === patient.id)
  const nextAppointment = data.appointments.filter(item => item.patientId === patient.id && ['Scheduled','Confirmed'].includes(item.status) && item.date >= todayIso()).sort((a,b) => `${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`))[0]
  return <div className="patient-layout"><section className="patient-welcome"><span className="welcome-mark"><CareIcon name="injection"/></span><div><h2>Hello, {patient.name.split(' ')[0]}</h2><p>{patient.treatmentStatus === 'Active' ? 'Your care plan is active. Your care team is keeping an eye on your progress.' : 'Review your care history and arrange the next step with your care team.'}</p></div><span className="plan-status">{patient.treatmentStatus === 'Active' ? 'Treatment active' : 'Follow-up'}</span></section>
    {activeTab === 'Home' && <><CareJourney data={data} patientId={patient.id}/><section className="patient-cards"><article className="panel patient-dose"><div className="patient-card-label">NEXT DOSE</div><div className="dose-date">{activePlan && doses[0] ? new Date(new Date(doses[0].recordedAt).getTime() + intervalDays * 86400000).toLocaleDateString('en-AE',{day:'numeric',month:'short'}) : 'See care plan'} <span>· prescribed schedule</span></div><div className="medication-name"><span className="medicine-icon"><CareIcon name="injection"/></span><span><b>Mounjaro</b><small>{patient.currentDose ?? '—'} · injection pen</small></span></div><button className="button primary" onClick={onRecordDose} disabled={!activeRequest || loggedToday}>{loggedToday ? 'Dose recorded today' : 'Record today’s dose'}</button><button className="text-link patient-plan-link" onClick={() => setActiveTab('Medication')}>View medication history <span>→</span></button></article><article className="panel patient-progress"><div className="panel-head"><div><h2>Your progress</h2><p>Based on recorded doses in this care plan</p></div><span className="progress-icon">↗</span></div><div className="progress-number">{adherenceFor(data, patient.id)}<span>%</span></div><p>{doses.length} doses recorded</p><div className="progress-track"><i style={{ width: `${adherenceFor(data, patient.id)}%` }}/></div><button className="text-link" onClick={() => setActiveTab('Progress')}>View progress <span>→</span></button></article></section><section className="patient-cards"><article className="panel next-steps"><div className="panel-head"><div><h2>Your next steps</h2><p>Keep up with your upcoming care</p></div></div><div className="steps-list"><div className="step-item"><span className="step-icon blue"><CareIcon name="Clinical care"/></span><span><b>Care team review</b><small>{request?.status === 'Under review' ? 'Your request is being reviewed by a clinician.' : 'Your care team will review your next check-in.'}</small></span><span className="step-arrow">→</span></div><div className="step-item"><span className="step-icon green"><CareIcon name="calendar"/></span><span><b>Therapy session</b><small>{nextAppointment ? `${nextAppointment.date} · ${nextAppointment.time} · ${nextAppointment.centre}` : 'No visit scheduled'}</small></span><span className="step-arrow">→</span></div><div className="step-item"><span className="step-icon amber"><CareIcon name="Analysis"/></span><span><b>Latest lab result</b><small>{patient.latestLab} · {data.labs.filter(i=>i.patientId===patient.id).sort((a,b)=>b.date.localeCompare(a.date))[0]?.date ?? 'Not recorded'}</small></span><span className="step-arrow">→</span></div></div></article><PatientNotifications notifications={notifications}/></section></>}
    {activeTab === 'Treatment' && <><IntegratedPlanCards data={data} patientId={patient.id} role={role}/><section className="panel next-steps"><div className="panel-head"><div><h2>Your treatment</h2><p>Current plan and request history</p></div><span className="plan-status">{patient.treatmentStatus}</span></div><div className="detail-grid"><div><small>Medication</small><b>Mounjaro</b></div><div><small>Current dose</small><b>{patient.currentDose ?? '—'} · {activePlan?.frequency ?? 'See care plan'}</b></div><div><small>Plan</small><b>{activePlan?.id ?? request?.planId ?? 'No active plan'}</b></div><div><small>Care team</small><b>{patient.assignedDoctor ?? 'Not assigned'}</b></div></div>{requests.map(item => <div className="patient-notification" key={item.id}><span className="step-icon blue"><CareIcon name="clock"/></span><span><b>{item.id} · {item.status}</b><small>{item.dose} · {item.created}{item.note ? ` · ${item.note}` : ''}</small></span></div>)}</section></>}
    {activeTab === 'Medication' && <><PharmacyPatientDocuments data={data} patientId={patient.id} arabic={arabic}/><section className="panel next-steps"><div className="panel-head"><div><h2>Medication</h2><p>Recorded doses and dispensing history</p></div><button className="button primary" onClick={onRecordDose} disabled={!activeRequest || loggedToday}>{loggedToday ? 'Dose recorded today' : 'Record today’s dose'}</button></div><div className="medication-name medication-large"><span className="medicine-icon"><CareIcon name="injection"/></span><span><b>Mounjaro · {patient.currentDose ?? '—'}</b><small>{activePlan?.frequency ?? 'See care plan'} · injection pen</small></span></div>{doses.map(item => <div className="patient-notification" key={item.id}><span className="step-icon green"><CareIcon name="check"/></span><span><b>Dose recorded</b><small>{item.dose} · {new Date(item.recordedAt).toLocaleDateString('en-AE')}</small></span></div>)}{dispenses.map(item => <div className="patient-notification" key={item.id}><span className="step-icon blue"><CareIcon name="box"/></span><span><b>Medication dispensed</b><small>{item.dose} · {item.centre} · {item.date}</small></span></div>)}{!doses.length && !dispenses.length && <div className="empty-state"><b>No medication history yet</b><span>Recorded medication activity will appear here.</span></div>}</section></>}
    {activeTab === 'Progress' && <><section className="panel"><div className="panel-head"><div><h2>Weight history</h2><p>Clinical measurements recorded by your care team.</p></div></div><div className="weight-history">{data.vitals.filter(i=>i.patientId===patient.id).sort((a,b)=>a.recordedAt.localeCompare(b.recordedAt)).map(i=><div key={i.id}><span>{i.recordedAt.slice(0,10)}</span><div className="bar-track"><i style={{width:`${Math.min(100,i.weightKg / 150 * 100)}%`}}/></div><b>{i.weightKg} kg</b><small>BMI {i.bmi}</small></div>)}</div><RiskPanel data={data} patientId={patient.id}/></section><section className="panel patient-progress progress-view"><div className="panel-head"><div><h2>Your progress</h2><p>Dose days recorded in the last four weeks against the prescribed schedule</p></div></div><div className="progress-number">{adherenceFor(data, patient.id)}<span>%</span></div><p>{doses.length} dose records in this programme snapshot</p><div className="progress-track"><i style={{ width: `${adherenceFor(data, patient.id)}%` }}/></div>{doses.map(item => <div className="patient-notification" key={item.id}><span className="step-icon green"><CareIcon name="check"/></span><span><b>Completed dose</b><small>{item.dose} · {new Date(item.recordedAt).toLocaleDateString('en-AE')}</small></span></div>)}</section></>}
    {activeTab === 'Appointments' && <DoctorAppointments data={data} role="Patient" arabic={arabic} query={appointmentQuery} onQuery={setAppointmentQuery} onUpdate={onUpdate}/>}
    {activeTab === 'Activity' && <><IntegratedPlanCards data={data} patientId={patient.id} role={role}/><PatientActivity data={data} role={role} patientId={patient.id} onUpdate={onUpdate}/></>}
    {activeTab === 'Notifications' && <PatientNotifications notifications={notifications}/>}
    {activeTab === 'Profile' && <section className="panel next-steps"><div className="panel-head"><div><h2>Your profile</h2><p>Information linked to your care programme record</p></div></div><div className="detail-grid"><div><small>Name</small><b>{patient.name}</b></div><div><small>Patient ID</small><b>{patient.id}</b></div><div><small>Age</small><b>{patient.age} years</b></div><div><small>Emirate</small><b>{patient.emirate}</b></div><div><small>Residency</small><b>{patient.residency ?? '—'}</b></div><div><small>Current treatment</small><b>Mounjaro · {patient.currentDose ?? '—'}</b></div><div><small>Eligibility</small><b>{patient.eligibility ?? 'Review required'}</b></div></div></section>}
    <nav className="patient-bottom-nav" aria-label="Patient app navigation">{(['Home','Treatment','Medication','Progress','Appointments','Activity','Notifications','Profile'] as PatientTab[]).map((tab) => <button key={tab} className={activeTab === tab ? 'selected' : ''} onClick={() => setActiveTab(tab)}><span><CareIcon name={tab === 'Notifications' ? 'Bell' : tab}/></span>{tab}</button>)}</nav>
  </div>
}
function PatientNotifications({ notifications }: { notifications: AppData['notifications'] }) { return <article className="panel next-steps"><div className="panel-head"><div><h2>Notifications</h2><p>Updates from your care team</p></div><span className="attention-count">{notifications.filter(item => !item.read).length} new</span></div>{notifications.length ? notifications.map(item => <div className="patient-notification" key={item.id}><span className="step-icon green">•</span><span><b>{item.title}</b><small>{item.detail} · {item.createdAt}</small></span></div>) : <div className="empty-state"><b>No notifications yet</b><span>Care updates will appear here.</span></div>}</article>}
function PatientDetail({ patientId, data, close,role,onUpdate,onCreateCarePlan,onCreateRequest,initialTab='Overview' }: { patientId: string; data: AppData; close: () => void;role:Role;onUpdate:(data:AppData)=>void;onCreateCarePlan:(id:string)=>void;onCreateRequest:(id:string)=>void;initialTab?:PatientSection }) {
  const patient = data.patients.find(item => item.id === patientId)
  const [tab, setTab] = useState(initialTab==='Clinical History'?'Clinical history':initialTab==='Analysis'?'Labs':initialTab==='Care Plan'?'Care plan':initialTab)
  if (!patient) return null
  const patientRequests = data.requests.filter(item => item.patientId === patient.id)
  const patientPlans = data.treatmentPlans.filter(item => item.patientId === patient.id)
  const patientLabs = data.labs.filter(item => item.patientId === patient.id)
  const patientVitals = data.vitals.filter(item => item.patientId === patient.id)
  const patientAppointments = data.appointments.filter(item => item.patientId === patient.id)
  const activity = data.audit.filter(item => item.patientId === patient.id || patientRequests.some(request => request.id === item.entityId))
  const treatment = treatmentEligibility(data,patient.id)
  const tabs = ['Overview','Clinical history','Labs','Treatment','Care plan','Appointments','Continuous care','Documents','Notifications','Activity']
  return <div className={role==='Doctor'?'doctor-patient-page':'modal-backdrop'} onClick={role==='Doctor'?undefined:close}><section className={role==='Doctor'?'doctor-patient-content':'patient-modal patient-360 panel'} role={role==='Doctor'?undefined:'dialog'} aria-modal={role==='Doctor'?undefined:true} aria-label={role==='Doctor'?undefined:'Patient 360'} onClick={event => event.stopPropagation()}><button className={role==='Doctor'?'doctor-back':'close-button'} aria-label={role==='Doctor'?'Back to patients':'Close patient record'} onClick={close}>{role==='Doctor'?'← Back to patients':'×'}</button><div className="patient-modal-head"><PatientAvatar patient={patient} className="large-avatar"/><div><h2>{patient.name}</h2><span>{patient.id} · {patient.age} years · {patient.emirate}</span></div><span className="plan-status">{patient.treatmentStatus}</span></div>
    <PatientContext data={data} patientId={patientId}/><div className="patient-actions"><b>Actions</b><button className="button quiet" onClick={()=>setTab('Overview')}>View patient overview</button>{can(role,'clinical:write')&&<><button className="button quiet" onClick={()=>onCreateRequest(patientId)}>Create treatment request</button><button className="button primary" onClick={()=>onCreateCarePlan(patientId)}>Create Care Plan</button></>}</div>
    <div className="patient-360-tabs" role="tablist">{tabs.map(item => <button key={item} role="tab" aria-selected={tab === item} tabIndex={tab === item ? 0 : -1} className={tab === item ? 'selected' : ''} onKeyDown={event=>{ const rtl=document.documentElement.dir==='rtl'; const direction=event.key==='ArrowRight'?(rtl?-1:1):event.key==='ArrowLeft'?(rtl?1:-1):0; if(direction || ['Home','End'].includes(event.key)){event.preventDefault();const index=event.key==='Home'?0:event.key==='End'?tabs.length-1:(tabs.indexOf(tab)+direction+tabs.length)%tabs.length;setTab(tabs[index]);(event.currentTarget.parentElement?.children[index] as HTMLButtonElement)?.focus()} }} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === 'Overview' && <><CareJourney data={data} patientId={patientId}/><div className="patient-team"><span>{patient.assignedDoctor}</span><span>{patient.treatmentCentre}</span></div><section className="decision-support"><div className="decision-header"><div><b>Clinical decision support</b><small>Evidence summary calculated from this patient record</small></div><span>Clinician review</span></div><div className="decision-facts"><div><small>BMI</small><b>{patient.bmi.toFixed(1)} kg/m²</b></div><div><small>HbA1c</small><b>{patient.latestLab.replace('HbA1c · ', '')}</b></div><div><small>Fasting glucose</small><b>{patient.fastingGlucose ?? 'Not recorded'}</b></div><div><small>Previous dispensing</small><b>{data.dispenses.some(item => item.patientId === patient.id) ? 'Record available' : 'No record'}</b></div></div><p>{treatment.eligible ? 'System criteria and monthly dispensing interval are met. A new request can go directly to pharmacy verification.' : `Review needed: ${treatment.reasons.join(', ')}. The doctor can document an exception for independent approval.`}</p></section><div className="detail-grid patient-clinical-grid"><div><small>Emirates ID</small><b>{patient.emiratesId ?? 'Not recorded'}</b></div><div><small>Nationality / residency</small><b>{patient.nationality ?? '—'} · {patient.residency ?? '—'}</b></div><div><small>Sex</small><b>{patient.sex ?? '—'}</b></div><div><small>Weight / height</small><b>{patient.weightKg ?? '—'} kg / {patient.heightCm ?? '—'} cm</b></div><div><small>Diagnosis</small><b>{patient.diagnosis}</b></div><div><small>Current medication</small><b>Mounjaro · {patient.currentDose ?? '—'}</b></div><div><small>Last follow-up</small><b>{patient.lastFollowup ?? '—'}</b></div><div><small>Next eligibility date</small><b>{treatment.refill.nextEligibleDate ?? 'Eligible now'}</b></div></div></>}
    {(tab === 'Continuous care'||tab==='Care plan') && <><IntegratedPlanCards data={data} patientId={patientId} role={role} onUpdate={onUpdate}/><RiskPanel data={data} patientId={patientId}/></>}
    {tab === 'Documents' && <>{data.documents?.filter(i=>i.patientId===patientId).map(i=><article className="evidence-box" key={i.id}><b>{i.title}</b><small>{i.date} · {data.doctors.find(d=>d.id===i.authorId)?.name}</small><p>{i.content}</p>{i.dataUrl&&<a href={i.dataUrl} download={i.fileName??i.title}>Download file</a>}</article>)}{!data.documents?.some(i=>i.patientId===patientId)&&<div className="empty-state"><b>No documents recorded</b><span>Clinical evidence remains available in the Labs and Clinical history tabs.</span></div>}</>}
    {tab === 'Notifications' && <PatientNotifications notifications={data.notifications.filter(i=>i.patientId===patientId)}/>}
    {tab === 'Clinical history' && <><div className="evidence-box"><b>Previous illnesses</b><span>{patient.previousIllnesses?.join(' · ')??'Not recorded'}</span><b>Chronic conditions</b><span>{patient.chronicConditions?.join(' · ')??patient.diagnosis}</span><b>Medical procedures</b>{patient.procedures?.length?patient.procedures.map(p=><span key={`${p.name}-${p.date}`}>{p.date} · {p.name} · {p.note}</span>):<span>No procedures recorded</span>}<b>Previous medications</b>{patientPlans.filter(p=>p.status==='Completed').map(p=><span key={p.id}>{p.medication} · {p.dose} · {p.startDate} to {p.endDate}</span>)}</div><div className="detail-grid patient-clinical-grid"><div><small>Medical history</small><b>{data.assessments.find(item => item.patientId === patient.id)?.medicalHistory ?? 'Not recorded'}</b></div><div><small>Allergies</small><b>{data.assessments.find(item => item.patientId === patient.id)?.allergies ?? 'Not recorded'}</b></div><div><small>Symptoms</small><b>{data.assessments.find(item => item.patientId === patient.id)?.symptoms ?? 'Not recorded'}</b></div></div><div className="evidence-box"><b>Assessment history</b>{data.assessments.filter(item => item.patientId === patient.id).map(item => <span key={item.id}>{item.reason} · {item.diagnosis} · {item.status} · {new Date(item.createdAt).toLocaleDateString()} · {item.notes}</span>)}</div><div className="evidence-box"><b>Vitals history</b>{patientVitals.length ? patientVitals.map(item => <span key={item.id}>{new Date(item.recordedAt).toLocaleDateString()} · {item.weightKg} kg · BMI {item.bmi} · BP {item.systolic}/{item.diastolic} · HR {item.heartRate}</span>) : <span>No vitals recorded.</span>}</div></>}
    {tab === 'Labs' && <div className="table-wrap"><table><thead><tr><th>Test</th><th>Result</th><th>Reference</th><th>Status</th><th>Date</th><th>Interpretation</th></tr></thead><tbody>{patientLabs.map(item => <tr key={item.id}><td>{item.test}</td><td>{item.value} {item.unit}</td><td>{item.reference}</td><td><span className={`lab-status ${item.status.toLowerCase()}`}>{item.status}</span></td><td>{item.date}</td><td>{item.interpretation}</td></tr>)}</tbody></table>{patientLabs.length === 0 && <div className="empty-state"><b>No laboratory evidence</b><span>Add results in Clinical care.</span></div>}</div>}
    {tab === 'Treatment' && <><div className="evidence-box"><b>Treatment plans</b>{patientPlans.length ? patientPlans.map(item => <span key={item.id}>{item.id} · {item.medication} {item.dose} · {item.frequency} for {item.durationDays} days · {item.status} · follow-up {item.followUpDate}</span>) : <span>No treatment plans are linked.</span>}</div><div className="evidence-box"><b>Linked treatment requests</b>{patientRequests.length ? patientRequests.map(item => <span key={item.id}>{item.id} · Mounjaro {item.dose} · {item.status}{item.note ? ` · ${item.note}` : ''}</span>) : <span>No treatment requests linked to this patient.</span>}</div><div className="evidence-box"><b>Dispensing history</b>{data.dispenses.filter(item => item.patientId === patient.id).map(item => <span key={item.id}>{item.date} · {item.dose} · {item.centre} · {item.id}</span>)}</div></>}
    {tab === 'Appointments' && <div className="appointment-list">{patientAppointments.map(item => <article className="appointment-row" key={item.id}><div className="appointment-date"><b>{new Date(`${item.date}T12:00:00`).toLocaleDateString('en-AE',{day:'2-digit'})}</b><span>{new Date(`${item.date}T12:00:00`).toLocaleDateString('en-AE',{month:'short'})}</span></div><div className="appointment-info"><b>{item.purpose}</b><span>{item.status} · {item.date} at {item.time}</span><small>{item.doctor} · {item.centre}{item.notes ? ` · ${item.notes}` : ''}</small></div></article>)}{patientAppointments.length === 0 && <div className="empty-state"><b>No appointments</b><span>Appointments for this patient will appear here.</span></div>}</div>}
    {tab === 'Activity' && <>{[...data.doses.filter(item => item.patientId === patient.id).map(item => ({ id: item.id, title: 'Dose recorded', occurredAt: item.recordedAt, detail: `${item.dose} · ${new Date(item.recordedAt).toLocaleDateString()}` })), ...data.exercise.filter(item => item.patientId === patient.id).map(item => ({ id: item.id, title: `${item.activity} activity`, occurredAt: item.date, detail: `${item.durationMinutes} minutes · ${item.date}` })), ...activity.map(item => ({ id: item.id, title: item.action, occurredAt: item.occurredAt ?? '', detail: `${item.actor} · ${item.entity} · ${item.detail}` }))].sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)).slice(0, 20).map(item => <div className="workflow-history" key={item.id}><b>{item.title}</b><span>{item.detail}</span></div>)}{activity.length === 0 && data.doses.filter(item => item.patientId === patient.id).length === 0 && data.exercise.filter(item => item.patientId === patient.id).length === 0 && <div className="empty-state"><b>No activity recorded</b><span>Clinical and programme events will be shown here.</span></div>}</>}
    <p className="report-footnote">This patient 360 uses mock programme data. No live patient or Ministry source is connected.</p></section></div>
}
