import { reportTranslations } from './ReportTranslations'
import { careWorkflowTranslations } from './CareWorkflowTranslations'
import { careTranslations } from './CareTranslations'
import { adminTranslations, localizeAdminTemplate } from './AdminTranslations'
const phrases = new Map<string, string>([
  ["Patient care", "رعاية المريض"],
  ["Overview", "نظرة عامة"],
  ["Patients", "المرضى"],
  ["Treatment requests", "طلبات العلاج"],
  ["Inventory", "المخزون"],
  ["Reports", "التقارير"],
  ["Activity log", "سجل النشاط"],
  ["My care", "رعايتي"],
  ["Dispensing", "صرف الأدوية"],
  ["Alerts", "التنبيهات"],
  ["Clinical care", "الرعاية السريرية"],
  ["Appointments", "المواعيد"],
  ["Care workspace", "مساحة الرعاية"],
  ["Administrator access", "صلاحية المسؤول"],
  ["Clinical workspace", "مساحة العمل السريرية"],
  ["Medical review access", "صلاحية المراجعة الطبية"],
  ["Pharmacy operations", "عمليات الصيدلية"],
  ["Patient care access", "صلاحية رعاية المريض"],
  ["MAIN", "الرئيسية"],
  ["OPERATIONS", "العمليات"],
  ["INSIGHTS & GOVERNANCE", "الرؤى والحوكمة"],
  ["INTELLIGENCE", "الذكاء"],
  ["CLINICAL WORKSPACE", "مساحة العمل السريرية"],
  ["REVIEW & EVIDENCE", "المراجعة والأدلة"],
  ["MY CARE", "رعايتي"],
  ["CARE & PROGRESS", "الرعاية والتقدم"],
  ["National inventory", "المخزون الوطني"],
  ["Safety & supply alerts", "تنبيهات السلامة والإمداد"],
  ["Live activity log", "سجل الأنشطة المباشرة"],
  ["Treatment centers", "مراكز العلاج"],
  ["Executive dashboard", "لوحة المؤشرات التنفيذية"],
  ["Decision support", "دعم القرار"],
  ["Misuse prevention", "منع إساءة الاستخدام"],
  ["System audit", "سجل تدقيق النظام"],
  ["AI Assistant", "المساعد الذكي"],
  ["Safe dispensing", "الصرف الآمن"],
  ["Care companion", "مرشد الرعاية"],
  ["Get insights, analyze data and take action across the programme.", "استعرض المؤشرات وحلّل البيانات واتخذ الإجراءات المناسبة ضمن البرنامج."],
  ["Review shared evidence and coordinate the next step in care.", "راجع الأدلة المشتركة ونسّق الخطوة التالية في الرعاية."],
  ["Review clinical evidence alongside the shared patient record.", "راجع الأدلة السريرية ضمن سجل المريض المشترك."],
  ["Verify treatment requests, stock and dispensing records.", "تحقق من طلبات العلاج والمخزون وسجلات الصرف."],
  ["See your care plan, progress and upcoming appointments.", "اطّلع على خطة رعايتك وتقدمك ومواعيدك القادمة."],
  ["Demonstration data", "بيانات تجريبية"],
  ["Sign out", "تسجيل الخروج"],
  ["National programme overview", "نظرة عامة على البرنامج الوطني"],
  ["Good morning, Laila", "صباح الخير، ليلى"],
  ["Your care, in one place", "رعايتك في مكان واحد"],
  ["Programme", "البرنامج"],
  ["WORKSPACE", "مساحة العمل"],
  ["UAE treatment programme", "برنامج العلاج في الإمارات"],
  ["Patient registry", "سجل المرضى"],
  ["Registered patients", "المرضى المسجلون"],
  ["Active", "نشط"],
  ["Eligible", "مؤهل"],
  ["Under treatment", "تحت العلاج"],
  ["Search by patient name or ID", "ابحث باسم المريض أو رقمه"],
  ["Search patient or request", "ابحث عن مريض أو طلب"],
  ["Search appointments", "ابحث عن موعد"],
  ["Search batches", "ابحث عن دفعة"],
  ["All", "الكل"],
  ["Citizens", "مواطنون"],
  ["Residents", "مقيمون"],
  ["Resident", "مقيم"],
  ["Citizen", "مواطن"],
  ["Treatment request status", "حالة طلب العلاج"],
  ["Current distribution from programme records", "التوزيع الحالي استناداً إلى سجلات البرنامج"],
  ["View reports", "عرض التقارير"],
  ["Needs attention", "يتطلب المتابعة"],
  ["Items that may need follow-up", "عناصر قد تتطلب المتابعة"],
  ["Open request queue", "فتح قائمة الطلبات"],
  ["Recent treatment requests", "أحدث طلبات العلاج"],
  ["All requests", "كل الطلبات"],
  ["Programme by emirate", "البرنامج حسب الإمارة"],
  ["Active patients in the last 30 days", "المرضى النشطون خلال آخر 30 يوماً"],
  ["Inventory snapshot", "ملخص المخزون"],
  ["Available units by strength", "الوحدات المتاحة حسب الجرعة"],
  ["Manage", "إدارة"],
  ["Low stock", "مخزون منخفض"],
  ["Available", "متاح"],
  ["Clinical workspace", "مساحة الرعاية السريرية"],
  ["Patient assessment and evidence", "تقييم المريض والأدلة"],
  ["Selected patient", "المريض المحدد"],
  ["Current BMI", "مؤشر كتلة الجسم الحالي"],
  ["Latest lab", "أحدث تحليل"],
  ["Programme eligibility", "أهلية البرنامج"],
  ["Evidence criteria met", "معايير الأدلة مستوفاة"],
  ["Review evidence", "مراجعة الأدلة"],
  ["Clinical assessment", "التقييم السريري"],
  ["Save an in-progress assessment or submit a complete note.", "احفظ التقييم كمسودة أو أرسل ملاحظة مكتملة."],
  ["Reason for visit", "سبب الزيارة"],
  ["Diagnosis / context", "التشخيص / السياق"],
  ["Symptoms", "الأعراض"],
  ["Medical history", "التاريخ الطبي"],
  ["Current medications", "الأدوية الحالية"],
  ["Allergies", "الحساسية"],
  ["Clinical findings", "النتائج السريرية"],
  ["Clinician plan / notes", "خطة الطبيب / الملاحظات"],
  ["Save draft", "حفظ المسودة"],
  ["Submit assessment", "إرسال التقييم"],
  ["Record vitals", "تسجيل المؤشرات الحيوية"],
  ["BMI is calculated from weight and height.", "يُحسب مؤشر كتلة الجسم من الوزن والطول."],
  ["Weight (kg)", "الوزن (كغ)"],
  ["Height (cm)", "الطول (سم)"],
  ["Systolic BP", "ضغط الدم الانقباضي"],
  ["Diastolic BP", "ضغط الدم الانبساطي"],
  ["Heart rate", "معدل ضربات القلب"],
  ["Calculated BMI", "مؤشر كتلة الجسم المحسوب"],
  ["Save vitals", "حفظ المؤشرات الحيوية"],
  ["Laboratory result", "نتيجة المختبر"],
  ["Record evidence with an interpretation.", "سجّل النتيجة مع التفسير."],
  ["Test", "الفحص"],
  ["Value", "القيمة"],
  ["Unit", "الوحدة"],
  ["Reference range", "النطاق المرجعي"],
  ["Result status", "حالة النتيجة"],
  ["Collection date", "تاريخ أخذ العينة"],
  ["Interpretation", "التفسير"],
  ["Add lab result", "إضافة نتيجة مختبر"],
  ["Eligibility evidence", "أدلة الأهلية"],
  ["A clinician makes the final treatment decision.", "يتخذ الطبيب القرار النهائي بشأن العلاج."],
  ["Adult patient (18+)", "المريض بالغ (18 عاماً فأكثر)"],
  ["BMI at or above 30", "مؤشر كتلة الجسم 30 أو أكثر"],
  ["Relevant diagnosis recorded", "تم تسجيل تشخيص مناسب"],
  ["HbA1c result available", "نتيجة HbA1c متاحة"],
  ["Appointments", "المواعيد"],
  ["Schedule appointment", "جدولة موعد"],
  ["Schedule a future visit in the shared patient calendar.", "أضف زيارة مستقبلية إلى تقويم المريض المشترك."],
  ["Patient", "المريض"],
  ["Purpose", "الغرض"],
  ["Doctor", "الطبيب"],
  ["Centre", "المركز"],
  ["Date", "التاريخ"],
  ["Time", "الوقت"],
  ["Notes", "ملاحظات"],
  ["Schedule appointment", "جدولة الموعد"],
  ["Scheduled", "مجدول"],
  ["Confirmed", "مؤكد"],
  ["Completed", "مكتمل"],
  ["Cancelled", "ملغى"],
  ["No show", "لم يحضر"],
  ["Confirm", "تأكيد"],
  ["Complete", "إنهاء"],
  ["Cancel", "إلغاء"],
  ["No show", "لم يحضر"],
  ["Record an activity", "تسجيل نشاط"],
  ["Activity history", "سجل النشاط"],
  ["Activity this month", "النشاط هذا الشهر"],
  ["Recorded sessions", "الجلسات المسجلة"],
  ["Activity types", "أنواع النشاط"],
  ["Latest entry", "أحدث إدخال"],
  ["Log movement to follow your activity over time.", "سجّل نشاطك لمتابعة تقدمك."],
  ["Activity", "النشاط"],
  ["Duration (minutes)", "المدة (بالدقائق)"],
  ["Intensity", "الشدة"],
  ["Light", "خفيف"],
  ["Moderate", "متوسط"],
  ["Vigorous", "شديد"],
  ["Walking", "المشي"],
  ["Running", "الجري"],
  ["Cycling", "ركوب الدراجة"],
  ["Gym", "النادي الرياضي"],
  ["Swimming", "السباحة"],
  ["Other", "أخرى"],
  ["Save activity", "حفظ النشاط"],
  ["No activity recorded yet", "لم يتم تسجيل أي نشاط بعد"],
  ["Receive stock", "استلام مخزون"],
  ["Add a traceable medication batch to programme inventory.", "أضف دفعة دواء قابلة للتتبع إلى مخزون البرنامج."],
  ["Medication strength", "تركيز الدواء"],
  ["Quantity", "الكمية"],
  ["Batch number", "رقم الدفعة"],
  ["Expiry date", "تاريخ الانتهاء"],
  ["Treatment centre", "مركز العلاج"],
  ["Receive batch", "استلام الدفعة"],
  ["Batch inventory", "مخزون الدفعات"],
  ["Earliest-expiry eligible stock is selected automatically at dispensing.", "يتم اختيار الدفعة الصالحة الأقرب انتهاءً تلقائياً عند الصرف."],
  ["Available units", "الوحدات المتاحة"],
  ["Reorder point", "حد إعادة الطلب"],
  ["Stock status", "حالة المخزون"],
  ["Reorder needed", "تتطلب إعادة الطلب"],
  ["Inventory movements", "حركات المخزون"],
  ["Receipts and dispensing adjustments", "الاستلام وتسويات الصرف"],
  ["Dispensing records", "سجلات الصرف"],
  ["Completed medication transactions", "معاملات الدواء المكتملة"],
  ["Operational alerts", "التنبيهات التشغيلية"],
  ["Current programme records have no items requiring follow-up.", "لا تتطلب سجلات البرنامج الحالية أي متابعة."],
  ["System activity and audit", "نشاط النظام وسجل التدقيق"],
  ["Search action, record or detail", "ابحث عن إجراء أو سجل أو تفاصيل"],
  ["Role", "الدور"],
  ["No matching audit events", "لا توجد أحداث تدقيق مطابقة"],
  ["Treatment request outcomes", "نتائج طلبات العلاج"],
  ["Export CSV", "تصدير CSV"],
  ["Patient overview", "نظرة عامة على المرضى"],
  ["Pharmacy dispensing", "صرف الصيدلية"],
  ["Inventory batches", "دفعات المخزون"],
  ["Coverage estimates", "تقديرات التغطية"],
  ["Audit events", "أحداث التدقيق"],
  ["Dataset", "مجموعة البيانات"],
  ["Requests", "الطلبات"],
  ["Approved for dispensing", "موافق عليه للصرف"],
  ["Held or rejected", "معلق أو مرفوض"],
  ["Average adherence", "متوسط الالتزام"],
  ["Expiring batches", "دفعات قاربت على الانتهاء"],
  ["Mock cost estimates", "تقديرات التكلفة التجريبية"],
  ["Patients by emirate", "المرضى حسب الإمارة"],
  ["Appointment outcomes", "نتائج المواعيد"],
  ["Overview", "نظرة عامة"],
  ["Clinical history", "التاريخ السريري"],
  ["Labs", "التحاليل"],
  ["Treatment", "العلاج"],
  ["Appointments", "المواعيد"],
  ["Activity", "النشاط"],
  ["Profile", "الملف الشخصي"],
  ["Medication", "الدواء"],
  ["Progress", "التقدم"],
  ["Notifications", "الإشعارات"],
  ["Home", "الرئيسية"],
  ["New treatment plan and request", "خطة علاج وطلب جديد"],
  ["Proposed dose", "الجرعة المقترحة"],
  ["Frequency", "التكرار"],
  ["Duration (days)", "المدة (بالأيام)"],
  ["Start date", "تاريخ البدء"],
  ["End date", "تاريخ الانتهاء"],
  ["Follow-up date", "تاريخ المتابعة"],
  ["Indication", "دواعي العلاج"],
  ["Instructions", "التعليمات"],
  ["Monitoring plan", "خطة المراقبة"],
  ["Pre-submission evidence", "الأدلة قبل الإرسال"],
  ["Submit for review", "إرسال للمراجعة"],
  ["All treatment requests", "كل طلبات العلاج"],
  ["Review queue", "قائمة المراجعة"],
  ["Dispensing queue", "قائمة الصرف"],
  ["Request information", "طلب معلومات"],
  ["Reject request", "رفض الطلب"],
  ["Approve request", "الموافقة على الطلب"],
  ["Resubmit for review", "إعادة الإرسال للمراجعة"],
  ["Dispensing safety checks", "فحوصات سلامة الصرف"],
  ["Confirm dispensing", "تأكيد الصرف"],
  ["Patient identity confirmed", "تم التحقق من هوية المريض"],
  ["Stock available", "المخزون متاح"],
  ["Approval current", "الموافقة سارية"],
  ["Prescription linked", "الوصفة الطبية مرتبطة"],
  ["No previous dispensing", "لا يوجد صرف سابق"],
  ["Arabic", "العربية"],
  ["English", "الإنجليزية"],
  ["Language", "اللغة"],
  ["Search", "بحث"],
  ["Status", "الحالة"],
  ["Sort", "ترتيب"],
  ["Newest", "الأحدث"],
  ["Oldest", "الأقدم"],
  ["Today", "اليوم"],
  ["Tomorrow", "غداً"],
  ["Tomorrow", "غداً"],
  ["Hello", "مرحباً"],
  ["All times Gulf Standard Time (GST)", "جميع الأوقات بتوقيت الخليج القياسي"],
  ["Secure workspace", "مساحة عمل آمنة"],
  ["Health Care Programme", "برنامج الرعاية الصحية"],
  ["Cancel", "إلغاء"],
  ["Close", "إغلاق"],
  ["Dismiss", "إخفاء"]
])
const phraseAdditions: [string, string][] = [
  ['A clear view of treatment activity across the programme.', 'نظرة واضحة على نشاط العلاج في البرنامج.'],
  ['Programme workspace', 'مساحة عمل البرنامج'],
  ['In the shared patient registry', 'ضمن سجل المرضى المشترك'],
  ['Active programme records', 'سجلات البرنامج النشطة'],
  ['Meets clinical criteria in mock records', 'يستوفي المعايير السريرية وفق السجلات التجريبية'],
  ['Active treatment plans', 'خطط العلاج النشطة'],
  ['Patients registered', 'المرضى المسجلون'],
  ['Awaiting verification', 'بانتظار التحقق'],
  ['Linked dispensing records', 'سجلات الصرف المرتبطة'],
  ['Strengths below 12 units', 'تركيزات تقل عن 12 وحدة'],
  ['Across four strengths', 'عبر أربعة تركيزات'],
  ['Requests need a decision', 'طلبات تحتاج إلى قرار'],
  ['Approved requests', 'الطلبات المعتمدة'],
  ['Returned to care team', 'أُعيدت إلى فريق الرعاية'],
  ['Shared patient records', 'سجلات المرضى المشتركة'],
  ['Patient and request details share the same programme record.', 'تستخدم بيانات المريض والطلب سجل البرنامج نفسه.'],
  ['A traceable record of decisions and operational changes.', 'سجل قابل للتتبع للقرارات والتغييرات التشغيلية.'],
  ['Available medication across participating treatment centres.', 'الأدوية المتاحة في مراكز العلاج المشاركة.'],
  ['Review requests and follow each decision through dispensing.', 'راجع الطلبات وتابع القرارات حتى صرف الدواء.'],
  ['Search and open a patient record to review their care.', 'ابحث وافتح سجل المريض لمراجعة الرعاية المقدمة.'],
  ['Operational items derived from current programme activity.', 'عناصر تشغيلية مستمدة من نشاط البرنامج الحالي.'],
  ['Programme activity calculated from shared treatment records.', 'نشاط البرنامج محسوب من سجلات العلاج المشتركة.'],
  ['Current requests by status', 'الطلبات الحالية حسب الحالة'],
  ['linked records', 'سجلات مرتبطة'],
  ['Last 30 days', 'آخر 30 يوماً'],
  ['Recent activity across all care teams', 'أحدث الأنشطة عبر فرق الرعاية'],
  ['Latest activity across all care teams', 'أحدث الأنشطة عبر فرق الرعاية'],
  ['Latest lab result', 'أحدث نتيجة مختبر'],
  ['recorded', 'مسجل'],
  ['Your current treatment, next steps and progress.', 'علاجك الحالي وخطواتك التالية وتقدمك.'],
  ['Your care team is keeping an eye on your progress.', 'يتابع فريق الرعاية تقدمك.'],
  ['Your care plan is active.', 'خطة رعايتك نشطة.'],
  ['Your next steps', 'خطواتك التالية'],
  ['Keep up with your upcoming care', 'تابع مواعيد رعايتك القادمة'],
  ['Your appointments', 'مواعيدك'],
  ['Upcoming and completed visits with your care team', 'الزيارات القادمة والمكتملة مع فريق الرعاية'],
  ['No appointments scheduled', 'لا توجد مواعيد مجدولة'],
  ['Your care team will add appointments here.', 'سيضيف فريق الرعاية مواعيدك هنا.'],
  ['You have no activity recorded yet', 'لم تسجل أي نشاط بعد'],
  ['No activity recorded yet', 'لم يتم تسجيل أي نشاط بعد'],
  ['Your progress', 'تقدمك'],
  ['Based on recorded doses in this care plan', 'استناداً إلى الجرعات المسجلة في خطة الرعاية'],
  ['Based on doses logged in the last four weeks', 'استناداً إلى الجرعات المسجلة خلال الأسابيع الأربعة الماضية'],
  ['Treatment approved and pharmacy-ready', 'العلاج معتمد وجاهز للصرف'],
  ['Patient record found', 'تم العثور على سجل المريض'],
  ['Dose recognized', 'تم التحقق من الجرعة'],
  ['No previous dispensing', 'لا يوجد صرف سابق'],
  ['Refill timing valid', 'توقيت إعادة الصرف مناسب'],
  ['Unexpired batch available', 'تتوفر دفعة غير منتهية الصلاحية'],
  ['Required assessment and lab evidence', 'التقييم السريري ونتائج المختبر المطلوبة'],
  ['Stock available', 'المخزون متاح'],
  ['Search patient, purpose or centre', 'ابحث عن مريض أو غرض أو مركز'],
  ['Search strength, batch or centre', 'ابحث عن تركيز أو دفعة أو مركز'],
  ['Search action, record or detail', 'ابحث عن إجراء أو سجل أو تفاصيل'],
  ['Search by patient name or ID', 'ابحث باسم المريض أو رقمه'],
  ['No matching requests', 'لا توجد طلبات مطابقة'],
  ['Try another name, ID or status.', 'جرّب اسماً أو رقماً أو حالة أخرى.'],
  ['No patients match this search', 'لا يوجد مرضى يطابقون هذا البحث'],
  ['Try a different name, ID or residency.', 'جرّب اسماً أو رقماً أو حالة إقامة مختلفة.'],
  ['No appointments match', 'لا توجد مواعيد مطابقة'],
  ['Change the search or status filter.', 'غيّر البحث أو مرشح الحالة.'],
  ['No matching batches', 'لا توجد دفعات مطابقة'],
  ['Change the search to find inventory.', 'غيّر البحث للعثور على المخزون.'],
  ['No matching audit events', 'لا توجد أحداث تدقيق مطابقة'],
  ['Try another search term or role.', 'جرّب عبارة بحث أو دوراً آخر.'],
  ['This patient 360 uses mock programme data. No live patient or Ministry source is connected.', 'يعرض ملف المريض بيانات تجريبية. لا يتصل بمصدر حي للمرضى أو الوزارة.'],
  ['The earliest-expiry valid batch is assigned automatically at dispensing.', 'تُخصص تلقائياً عند الصرف الدفعة الصالحة الأقرب إلى انتهاء الصلاحية.'],
  ['Every check must pass before stock can be committed.', 'يجب اجتياز جميع الفحوصات قبل خصم المخزون.'],
  ['Medication and dose supported', 'الدواء والجرعة مدعومان'],
  ['Approval current', 'الموافقة سارية'],
  ['Prescription linked', 'الوصفة الطبية مرتبطة'],
  ['Patient identity confirmed', 'تم التحقق من هوية المريض'],
  ['I verified the patient identity at collection.', 'تحققت من هوية المريض عند استلام الدواء.'],
  ['Confirm dispensing', 'تأكيد صرف الدواء'],
  ['Dispensing completed. Stock, patient history and audit were updated.', 'اكتمل الصرف وتم تحديث المخزون وسجل المريض والتدقيق.'],
  ['Treatment request submitted for medical review.', 'أُرسل طلب العلاج للمراجعة الطبية.'],
  ['Updated request returned to the reviewer queue.', 'أُعيد الطلب المحدّث إلى قائمة المراجع.'],
  ['Dose recorded. Your progress and care team activity are up to date.', 'سُجلت الجرعة وتم تحديث تقدمك ونشاط فريق الرعاية.'],
  ['Mark all read', 'تحديد الكل كمقروء'],
  ['Updates generated by programme activity', 'تحديثات ناتجة عن نشاط البرنامج'],
  ['All times Gulf Standard Time (GST)', 'جميع الأوقات بتوقيت الخليج القياسي'],
  ['Secure workspace', 'مساحة عمل آمنة'],
  ['Under review', 'قيد المراجعة'],
  ['Ready to dispense', 'جاهز للصرف'],
  ['Needs information', 'يتطلب معلومات إضافية'],
  ['Approved', 'معتمد'],
  ['Rejected', 'مرفوض'],
  ['Dispensed', 'تم الصرف'],
  ['Meets criteria', 'يستوفي المعايير'],
  ['Review required', 'يتطلب المراجعة'],
  ['Review queue', 'قائمة المراجعة'],
  ['Dispensing queue', 'قائمة الصرف'],
  ['All treatment requests', 'جميع طلبات العلاج'],
  ['Request approved', 'تمت الموافقة على الطلب'],
  ['Information requested', 'تم طلب معلومات إضافية'],
  ['Treatment request rejected', 'تم رفض طلب العلاج'],
  ['Treatment approved', 'تمت الموافقة على العلاج'],
  ['Medication dispensed', 'تم صرف الدواء'],
  ['Clinical review pending', 'المراجعة السريرية معلقة'],
  ['Critical stock level', 'مستوى مخزون حرج'],
  ['Low stock level', 'مستوى المخزون منخفض'],
  ['Medication batch expiring', 'دفعة دواء قاربت على الانتهاء'],
  ['Expired medication batch', 'دفعة دواء منتهية الصلاحية'],
  ['Appointment coming up', 'موعد قريب'],
  ['Low recorded adherence', 'انخفاض الالتزام المسجل'],
  ['Review pending over 48 hours', 'المراجعة معلقة لأكثر من 48 ساعة'],
  ['Pharmacy verification issue', 'مشكلة في التحقق الصيدلي'],
  ['Treatment approval expired', 'انتهت صلاحية الموافقة على العلاج'],
  ['Search alert, patient or record', 'ابحث عن تنبيه أو مريض أو سجل'],
  ['Search patient, request, dose or emirate', 'ابحث عن مريض أو طلب أو جرعة أو إمارة'],
  ['Search action, record or detail', 'ابحث عن إجراء أو سجل أو تفاصيل'],
  ['Report', 'التقرير'],
  ['From', 'من'],
  ['To', 'إلى'],
  ['Emirate / centre', 'الإمارة / المركز'],
  ['Read state', 'حالة القراءة'],
  ['All', 'الكل'],
  ['Unread', 'غير مقروء'],
  ['Read', 'مقروء'],
  ['Critical', 'حرج'],
  ['Warning', 'تحذير'],
  ['Info', 'معلومات'],
  ['Mark read', 'تحديد كمقروء'],
  ['Dismiss', 'إخفاء'],
  ['Supplier / source', 'المورد / المصدر'],
  ['Received date', 'تاريخ الاستلام'],
  ['I confirm the batch details and receipt quantity.', 'أؤكد تفاصيل الدفعة وكمية الاستلام.'],
  ['Patient overview', 'نظرة عامة على المرضى'],
  ['Review performance', 'أداء المراجعة'],
  ['Treatment approvals', 'موافقات العلاج'],
  ['Missing information', 'المعلومات المطلوبة'],
  ['Expiring medication', 'الأدوية قاربت على الانتهاء'],
  ['Financial / coverage', 'المالية / التغطية'],
  ['Operational activity', 'النشاط التشغيلي'],
  ['Export filtered CSV', 'تصدير ملف CSV المصفى'],
  ['matching records', 'سجلات مطابقة'],
  ['No alerts match these filters', 'لا توجد تنبيهات تطابق عوامل التصفية'],
  ['Clear or adjust the date, location and status filters.', 'امسح عوامل تصفية التاريخ والموقع والحالة أو عدّلها.'],
  ['Treatment plan', 'خطة العلاج'],
  ['Prescription', 'الوصفة الطبية'],
  ['Medical history / allergies', 'التاريخ الطبي / الحساسية'],
  ['Latest vitals', 'أحدث المؤشرات الحيوية'],
  ['Laboratory history', 'سجل المختبر'],
  ['Review and audit history', 'سجل المراجعة والتدقيق'],
  ['Transparent eligibility review', 'مراجعة أهلية واضحة'],
  ['The reviewer makes the treatment decision.', 'يتخذ المراجع قرار العلاج النهائي.'],
  ['Good morning, reviewer', 'صباح الخير، أيها المراجع'],
  ['Good morning, doctor', 'صباح الخير، أيها الطبيب'],
  ['Good morning, pharmacist', 'صباح الخير، أيها الصيدلي'],
  ['Good morning, admin', 'صباح الخير، أيها المسؤول'],
  ['Switch language', 'تغيير اللغة'],
  ['Needs review', 'يتطلب المراجعة'],
  ['Priority', 'الأولوية'],
  ['Reason or note', 'السبب أو الملاحظة'],
  ['Required for rejection or information request', 'مطلوب لرفض الطلب أو طلب معلومات إضافية'],
  ['Latest findings / plan', 'أحدث النتائج / الخطة'],
  ['Clinical evidence reviewed; confirm against current visit.', 'تمت مراجعة الأدلة السريرية؛ يرجى تأكيدها في الزيارة الحالية.'],
  ['Continue monitoring and review at follow-up.', 'استمر في المراقبة والمراجعة في موعد المتابعة.'],
  ['History reviewed in patient record', 'تمت مراجعة التاريخ في سجل المريض'],
  ['No known allergies recorded', 'لا توجد حساسية معروفة مسجلة'],
  ['Within reference range.', 'ضمن النطاق المرجعي.'],
  ['Submitted', 'مُرسل'],
  ['Created after approval', 'يُنشأ بعد الموافقة'],
  ['Dr. Laila Hassan', 'د. ليلى حسن'],
  ['Dr. Omar Khalid', 'د. عمر خالد'],
  ['Dr. Sara Al Mansoori', 'د. سارة المنصوري'],
  ['Dr. Ahmed Al Ali', 'د. أحمد العلي'],
  ['Dr. Reem Al Dhaheri', 'د. ريم الظاهري'],
  ['Internal Medicine', 'الباطنة العامة'],
  ['Cardiology', 'أمراض القلب'],
  ['Created after approval', 'يُنشأ بعد الموافقة'],
  ['Required lab evidence is missing.', 'نتائج المختبر المطلوبة غير متوفرة.'],
  ['No prior review event is recorded for this request.', 'لا يوجد سجل مراجعة سابق لهذا الطلب.'],
  ['No matching requests', 'لا توجد طلبات مطابقة'],
  ['Try another patient, ID, status or eligibility filter.', 'جرّب مريضاً أو رقماً أو حالة أو مرشح أهلية آخر.'],
  ['Programme snapshot', 'ملخص البرنامج'],
  ['Abu', 'أبو'],
  ['Dhabi', 'ظبي'],
  ['Dubai', 'دبي'],
  ['Sharjah', 'الشارقة'],
  ['Ajman', 'عجمان'],
  ['Fujairah', 'الفجيرة'],
  ['Ras', 'رأس'],
  ['Khaimah', 'الخيمة'],
  ['Umm', 'أم'],
  ['Quwain', 'القيوين'],
  ['Emirati', 'إماراتي'],
  ['Jordanian', 'أردني'],
  ['Egyptian', 'مصري'],
  ['Lebanese', 'لبناني'],
  ['Visitor', 'زائر'],
  ['Citizen', 'مواطن'],
  ['Resident', 'مقيم'],
  ['Nationality', 'الجنسية'],
  ['Residency', 'الإقامة'],
  ['Age', 'العمر'],
  ['Emirate', 'الإمارة'],
  ['Thursday', 'الخميس'],
  ['January', 'يناير'],
  ['February', 'فبراير'],
  ['March', 'مارس'],
  ['April', 'أبريل'],
  ['May', 'مايو'],
  ['June', 'يونيو'],
  ['July', 'يوليو'],
  ['August', 'أغسطس'],
  ['September', 'سبتمبر'],
  ['October', 'أكتوبر'],
  ['November', 'نوفمبر'],
  ['December', 'ديسمبر'],
  ['Ahmed Al Mansoori', 'أحمد المنصوري'],
  ['Sara Yousef', 'سارة يوسف'],
  ['Mahmoud Ibrahim', 'محمود إبراهيم'],
  ['Fatima Al Qasimi', 'فاطمة القاسمي'],
  ['Rashid Al Nuaimi', 'راشد النعيمي'],
  ['Khalid Al Hashmi', 'خالد الهاشمي'],
  ['Mariam Al Kaabi', 'مريم الكعبي'],
  ['Omar Al Shamsi', 'عمر الشامسي'],
  ['Noor Al Mazrouei', 'نور المزروعي'],
  ['Yousef Al Ketbi', 'يوسف الكتبي'],
  ['Aisha Hassan', 'عائشة حسن'],
  ['Hamad Al Suwaidi', 'حمد السويدي'],
  ['Reem Al Shehhi', 'ريم الشحي'],
  ['Salem Al Dhaheri', 'سالم الظاهري'],
  ['Layla Nasser', 'ليلى ناصر'],
  ['Saeed Al Marri', 'سعيد المري'],
  ['Huda Abdulla', 'هدى عبدالله'],
  ['Majid Al Falasi', 'ماجد الفلاسي'],
  ['Good morning', 'صباح الخير'],
  ['Programme snapshot', 'ملخص البرنامج'],
  ['Clinical review due', 'موعد المراجعة السريرية'],
  ['UAE', 'الإمارات'],
  ['Abu Dhabi', 'أبوظبي'],
  ['Ras Al Khaimah', 'رأس الخيمة'],
  ['Umm Al Quwain', 'أم القيوين'],
  ['BMI', 'مؤشر كتلة الجسم'],
  ['HbA1c', 'السكر التراكمي'],
  ['mg/dL', 'ملغ/دل'],
  ['Meets clinical criteria', 'يستوفي المعايير السريرية'],
  ['Not eligible', 'غير مؤهل'],
  ['Fasting glucose', 'سكر صائم'],
  ['Not recorded', 'غير مسجل'],
  ['Previous dispensing', 'عمليات الصرف السابقة'],
  ['No record', 'لا يوجد سجل'],
  ['Clinical decision support', 'دعم القرار السريري'],
  ['Evidence summary calculated from this patient record', 'ملخص الأدلة مستمد من سجل هذا المريض'],
  ['Available criteria are met based on age, BMI, diagnosis and a recorded HbA1c. A physician remains responsible for the final treatment decision.', 'تستوفي البيانات المتاحة المعايير بحسب العمر ومؤشر كتلة الجسم والتشخيص ونتيجة السكر التراكمي المسجلة. يظل القرار النهائي بشأن العلاج من مسؤولية الطبيب.'],
  ['No active plan', 'لا توجد خطة نشطة'],
  ['Current medication', 'الدواء الحالي'],
  ['Emirates ID', 'رقم الهوية الإماراتية'],
  ['Nationality / residency', 'الجنسية / الإقامة'],
  ['Weight / height', 'الوزن / الطول'],
  ['Last follow-up', 'آخر متابعة'],
  ['Next eligibility date', 'تاريخ الأهلية التالي'],
  ['No active treatment plan', 'لا توجد خطة علاج نشطة'],
  ['Clinician review', 'مراجعة الطبيب'],
  ['Sex', 'الجنس'],
  ['Active patients', 'المرضى النشطون'],
  ['Search and open the patient record to review current treatment and eligibility.', 'ابحث وافتح سجل المريض لمراجعة العلاج الحالي والأهلية.'],
  ['Refill timing', 'موعد إعادة الصرف'],
  ['Previous page', 'الصفحة السابقة'],
  ['Next page', 'الصفحة التالية'],
  ['Page', 'الصفحة'],
  ['Severity', 'الخطورة'],
  ['Alphabetical', 'أبجدي'],
  ['Rule-based alerts from stock, treatment, safety, adherence and appointment records.', 'تنبيهات آلية مستندة إلى سجلات المخزون والعلاج والسلامة والالتزام والمواعيد.'],
  ['Updated renal panel required', 'يلزم تحديث فحص وظائف الكلى'],
  ['in the last 28 days', 'خلال آخر 28 يوماً'],
  ['units available', 'وحدة متاحة'],
  ['expires', 'تنتهي صلاحيته'],
  ['Administrative dashboard', 'لوحة تحكم الإدارة'],
  ['Dashboard', 'لوحة التحكم'],
  ['AI assistant', 'المساعد الذكي'],
  ['Data assistant', 'المساعد الذكي'],
  ['Ask questions about the records currently stored in this application.', 'اسأل عن السجلات المحفوظة حاليًا في التطبيق.'],
  ['Executive dashboard', 'لوحة القيادة التنفيذية'],
  ['Geographic analytics', 'التحليل الجغرافي'],
  ['National inventory', 'المخزون الوطني'],
  ['Safety & supply alerts', 'تنبيهات السلامة والإمداد'],
  ['Live activity log', 'سجل الأنشطة المباشر'],
  ['Smart assistant', 'المساعد الذكي'],
  ['Misuse prevention', 'سجل منع إساءة الاستخدام'],
  ['Doctor portal', 'بوابة الطبيب (كاملة)'],
  ['Distribution portal', 'منفذ التوزيع (كاملة)'],
  ['Patient portal', 'بوابة المريض'],
  ['Doctor management', 'إدارة الأطباء'],
  ['Treatment centers', 'إدارة مراكز العلاج'],
  ['System audit', 'سجل النظام'],
  ['Treatment pathway', 'مسار العلاج'],
  ['Request lifecycle', 'مراحل طلب العلاج'],
  ['Recent programme activity', 'أحدث أنشطة البرنامج'],
  ['Connected workspaces', 'مساحات العمل المرتبطة'],
  ['Treatment volume', 'حجم العلاج'],
  ['Approval rate', 'نسبة الموافقة'],
  ['Pending workload', 'المهام المعلقة'],
  ['Dispensing volume', 'حجم الصرف'],
  ['Adherence overview', 'ملخص الالتزام'],
  ['Geographic distribution', 'التوزيع الجغرافي'],
  ['Patients by emirate', 'المرضى حسب الإمارة'],
  ['Service activity', 'نشاط الخدمات'],
  ['Transparent rule-based decision support', 'دعم قرار شفاف قائم على القواعد'],
  ['Evidence for the care team', 'الأدلة لفريق الرعاية'],
  ['Clinician remains responsible', 'يبقى الطبيب مسؤولاً عن القرار'],
  ['Records flagged for review', 'سجلات تحتاج إلى المراجعة'],
  ['No review flags detected', 'لم تُكتشف إشارات تستدعي المراجعة'],
  ['Programme directory · mock credentials', 'دليل البرنامج · بيانات اعتماد تجريبية'],
  ['Care delivery network', 'شبكة تقديم الرعاية'],
  ['Governance and traceability', 'الحوكمة وإمكانية التتبع'],
  ['Emirate', 'الإمارة'],
  ['Treatment centre', 'مركز العلاج'],
  ['Active treatments', 'العلاجات النشطة'],
  ['Pending requests', 'الطلبات المعلقة'],
  ['Approved requests', 'الطلبات المعتمدة'],
  ['Available stock', 'المخزون المتاح'],
  ['Open operational signals', 'الإشارات التشغيلية المفتوحة'],
  ['Review status', 'حالة المراجعة'],
  ['Event type', 'نوع الحدث'],
  ['Flagged for review', 'محدد للمراجعة'],
  ['No external AI model is used.', 'لا يُستخدم نموذج ذكاء اصطناعي خارجي.'],
  ['This screen summarizes records and programme checks. It does not use an external AI model or make clinical decisions.', 'تلخص هذه الشاشة السجلات وفحوص البرنامج، ولا تستخدم نموذج ذكاء اصطناعي خارجي أو تتخذ قرارات سريرية.'],
  ['Monthly totals use event timestamps in the current dataset.', 'تعتمد الإجماليات الشهرية على أوقات الأحداث في مجموعة البيانات الحالية.'],
  ['Mock programme geography · not national health statistics', 'جغرافيا البرنامج التجريبية · ليست إحصاءات صحية وطنية'],
  ['Credential references are demo values; no licensing authority is connected.', 'مراجع بيانات الاعتماد تجريبية ولا يوجد اتصال بجهة ترخيص.'],
  ['Mock locations are not linked to a live map or facility registry.', 'المواقع تجريبية وغير مرتبطة بخريطة مباشرة أو سجل منشآت.'],
  ['Signals are recalculated from canonical requests, dispense records, dose logs and inventory.', 'تُعاد حسابات الإشارات من الطلبات وسجلات الصرف والجرعات والمخزون الموحد.'],
  ['A clear view of programme operations, care activity and supply.', 'عرض واضح لعمليات البرنامج ونشاط الرعاية والإمداد.'],
  ['Executive summary · mock programme records', 'ملخص تنفيذي · سجلات برنامج تجريبية'],
  ['Programme volume, outcomes, geography and operations from recorded mock data.', 'حجم البرنامج ونتائجه وتوزيعه الجغرافي وعملياته استناداً إلى بيانات تجريبية مسجلة.'],
  ['This view summarizes recorded demand, review workload, dispensing, adherence, appointments and stock. It does not infer national totals.', 'تلخص هذه الشاشة الطلب المسجل وأعمال المراجعة والصرف والالتزام والمواعيد والمخزون، ولا تستنتج إجماليات وطنية.'],
  ['Counts are calculated from current programme requests and records.', 'تُحسب الأعداد من طلبات البرنامج وسجلاته الحالية.'],
  ['State changes recorded across care teams.', 'تغييرات الحالة المسجلة عبر فرق الرعاية.'],
  ['Care teams work from the same patient and inventory records.', 'تعتمد فرق الرعاية على سجلات المرضى والمخزون المشتركة.'],
  ['Care team actions will appear here.', 'ستظهر إجراءات فريق الرعاية هنا.'],
  ['No activity recorded', 'لا توجد أنشطة مسجلة'],
  ['Open requests', 'فتح الطلبات'],
  ['Live log', 'السجل المباشر'],
  ['Requests in the shared register', 'الطلبات في السجل المشترك'],
  ['Total patients', 'إجمالي المرضى'],
  ['Shared patient registry', 'سجل المرضى المشترك'],
  ['Current active plans', 'خطط العلاج النشطة الحالية'],
  ['Pending requests', 'الطلبات المعلقة'],
  ['Review and evidence queue', 'قائمة المراجعة والأدلة'],
  ['Active treatments', 'العلاجات النشطة'],
  ['Under review', 'قيد المراجعة'],
  ['Needs information', 'يتطلب معلومات إضافية'],
  ['Pharmacy ready', 'جاهز للصيدلية'],
  ['Completed treatments', 'العلاجات المكتملة'],
  ['Active doctors', 'الأطباء النشطون'],
  ['Active reviewers', 'المراجعون النشطون'],
  ['Treatment centres', 'مراكز العلاج'],
  ['Inventory items', 'أصناف المخزون'],
  ['Low stock items', 'أصناف المخزون المنخفض'],
  ['Expiring batches', 'دفعات قاربت على الانتهاء'],
  ['Unresolved alerts', 'التنبيهات غير المحلولة'],
  ['Care delivery across the UAE programme', 'تقديم الرعاية ضمن برنامج الإمارات'],
  ['A live operational stream of care team and inventory events.', 'سجل مباشر للأحداث التشغيلية لفريق الرعاية والمخزون.'],
  ['State-changing actions include the actor, affected record and decision context.', 'تتضمن الإجراءات التي تغيّر الحالة المنفذ والسجل المتأثر وسياق القرار.'],
  ['Review operational patterns flagged by transparent safety rules.', 'راجع الأنماط التشغيلية التي ترصدها قواعد السلامة الواضحة.'],
  ['Operational safety monitoring', 'مراقبة السلامة التشغيلية'],
  ['Calculated from shared programme records', 'محسوبة من سجلات البرنامج المشتركة'],
  ['Calculated from current records', 'محسوبة من السجلات الحالية'],
  ['patients in scope', 'المرضى ضمن النطاق'],
  ['requests in scope', 'الطلبات ضمن النطاق'],
  ['Current patient profiles', 'ملفات المرضى الحالية'],
  ['Active patient plans', 'خطط العلاج النشطة'],
  ['Requests pending', 'الطلبات المعلقة'],
  ['Review or evidence needed', 'تتطلب مراجعة أو أدلة'],
  ['at listed centres', 'في المراكز المسجلة'],
  ['Assigned patients', 'المرضى المسندون'],
  ['Open doctor workload', 'عبء عمل الأطباء المفتوح'],
  ['Requests in shared queue', 'الطلبات في قائمة الانتظار المشتركة'],
  ['Treatment center management', 'إدارة مراكز العلاج'],
  ['Review facility operations, care teams, inventory and activity.', 'راجع عمليات المنشأة وفرق الرعاية والمخزون والنشاط.'],
  ['Open care locations', 'مواقع الرعاية المفتوحة'],
  ['Emirates covered', 'الإمارات المشمولة'],
  ['Based on centre directory', 'استناداً إلى دليل المراكز'],
  ['Filterable security and governance history of programme state changes.', 'سجل قابل للتصفية لتغييرات الحالة والحوكمة والأمن في البرنامج.'],
  ['Facility details', 'تفاصيل المنشأة'],
  ['Requests in the shared queue', 'الطلبات في قائمة الانتظار المشتركة'],
  ['decided requests', 'طلبات تم البت فيها'],
  ['Review or evidence still required', 'لا تزال المراجعة أو الأدلة مطلوبة'],
  ['Completed dispensing records', 'سجلات الصرف المكتملة'],
  ['Monthly totals use event timestamps in the current dataset.', 'تعتمد الإجماليات الشهرية على أوقات الأحداث في مجموعة البيانات الحالية.'],
  ['Adherence is calculated from dose logs recorded in the last 28 days.', 'يُحسب الالتزام من سجلات الجرعات خلال آخر 28 يوماً.'],
  ['Patients grouped by their current programme profile.', 'المرضى مصنفون حسب ملفهم الحالي في البرنامج.'],
  ['Available units', 'الوحدات المتاحة'],
  ['Upcoming appointments', 'المواعيد القادمة'],
  ['appointments recorded', 'موعداً مسجلاً'],
  ['Calculated from current rules', 'محسوبة وفق القواعد الحالية'],
  ['No period-over-period claim is shown: this mock dataset contains uneven historical coverage.', 'لا تُعرض مقارنة بين الفترات لأن تغطية البيانات التاريخية التجريبية غير منتظمة.'],
  ['UAE programme coverage', 'تغطية البرنامج في الإمارات'],
  ['Ranked from mock patient records, with active centre counts.', 'مرتبة حسب سجلات المرضى التجريبية، مع أعداد المراكز النشطة.'],
  ['Request and stock values follow patient and batch centre links.', 'تستند أعداد الطلبات والمخزون إلى ربط المرضى والدفعات بالمراكز.'],
  ['No centres in this filter', 'لا توجد مراكز ضمن هذا المرشح'],
  ['Choose another emirate.', 'اختر إمارة أخرى.'],
  ['Filtered centre activity', 'نشاط المراكز بعد التصفية'],
  ['dispenses', 'عملية صرف'],
  ['open signals', 'إشارة مفتوحة'],
  ['Rule-based clinical evidence and safety context for authorized care teams.', 'أدلة سريرية وسياق سلامة قائم على القواعد ومتاح لفرق الرعاية المخولة.'],
  ['This screen summarizes records and programme checks. It does not use an external AI model or make clinical decisions.', 'تلخص هذه الشاشة السجلات وفحوص البرنامج. ولا تستخدم نموذج ذكاء اصطناعي خارجياً أو تتخذ قرارات سريرية.'],
  ['Patient record', 'سجل المريض'],
  ['Open patient 360', 'فتح الملف الشامل للمريض'],
  ['Programme criteria', 'معايير البرنامج'],
  ['Criteria met', 'استوفى المعايير'],
  ['No lab on file', 'لا توجد نتيجة مختبر مسجلة'],
  ['No active request', 'لا يوجد طلب نشط'],
  ['No medication recorded', 'لا يوجد دواء مسجل'],
  ['No dispensing record', 'لا يوجد سجل صرف'],
  ['Safety context', 'سياق السلامة'],
  ['No rule-based warning for this record', 'لا يوجد تحذير قائم على القواعد لهذا السجل'],
  ['Continue to review the full clinical history and current programme rules.', 'تابع مراجعة التاريخ السريري الكامل وقواعد البرنامج الحالية.'],
  ['Review treatment requests', 'مراجعة طلبات العلاج'],
  ['Check inventory', 'التحقق من المخزون'],
  ['Rule-based signals show evidence and status; they do not imply intent or accuse a patient.', 'تعرض الإشارات القائمة على القواعد الأدلة والحالة، ولا تستنتج النوايا أو تتهم المريض.'],
  ['open flags', 'إشارات مفتوحة'],
  ['Patient, request or evidence', 'المريض أو الطلب أو الدليل'],
  ['No flagged records match these filters', 'لا توجد سجلات محددة تطابق هذه المرشحات'],
  ['Clear a filter to see current rule-based findings.', 'أزل أحد المرشحات لعرض النتائج الحالية القائمة على القواعد.'],
  ['No duplicate, refill-timing, prescription or inventory anomaly was found in the current mock records.', 'لم يُعثر في السجلات التجريبية الحالية على تكرار أو خلل في موعد إعادة الصرف أو الوصفة أو المخزون.'],
  ['Review decisions are saved to the audit history.', 'تُحفظ قرارات المراجعة في سجل التدقيق.'],
  ['Available in programme directory', 'متاح في دليل البرنامج'],
  ['Linked patient profiles', 'ملفات المرضى المرتبطة'],
  ['Credential references are demo values; no licensing authority is connected.', 'مراجع بيانات الاعتماد تجريبية ولا يوجد اتصال بجهة ترخيص.'],
  ['Doctor, specialty or centre', 'الطبيب أو التخصص أو المركز'],
  ['No doctors match these filters', 'لا يوجد أطباء يطابقون هذه المرشحات'],
  ['Change the search or status.', 'غيّر البحث أو الحالة.'],
  ['patients', 'مرضى'],
  ['active plans', 'خطط نشطة'],
  ['pending requests', 'طلبات معلقة'],
  ['activity events', 'أحداث نشاط'],
  ['Assigned centre', 'المركز المسند'],
  ['Deactivate doctor', 'إلغاء تفعيل الطبيب'],
  ['Reactivate doctor', 'إعادة تفعيل الطبيب'],
  ['Changes to a doctor’s centre update the linked patient centre assignments and create an audit event.', 'يؤدي تغيير مركز الطبيب إلى تحديث المراكز المرتبطة بمرضاه وإنشاء حدث في سجل التدقيق.'],
  ['Care delivery network', 'شبكة تقديم الرعاية'],
  ['Mock locations are not linked to a live map or facility registry.', 'المواقع التجريبية غير مرتبطة بخريطة مباشرة أو سجل منشآت.'],
  ['Centre or location', 'المركز أو الموقع'],
  ['No centres match these filters', 'لا توجد مراكز تطابق هذه المرشحات'],
  ['Change the search or emirate.', 'غيّر البحث أو الإمارة.'],
  ['Doctors', 'الأطباء'],
  ['No doctor assigned', 'لا يوجد طبيب مسند'],
  ['Patients / active treatments', 'المرضى / العلاجات النشطة'],
  ['Requests / dispenses', 'الطلبات / عمليات الصرف'],
  ['Stock on hand', 'المخزون المتوفر'],
  ['Set inactive', 'تعيين كمركز غير نشط'],
  ['Reactivate centre', 'إعادة تفعيل المركز'],
  ['View geography', 'عرض التوزيع الجغرافي'],
  ['Centre details', 'تفاصيل المركز'],
  ['Operational status', 'الحالة التشغيلية'],
  ['Assigned doctors', 'الأطباء المسندون'],
  ['Inventory batches', 'دفعات المخزون'],
  ['Dispensing records', 'سجلات الصرف'],
  ['Inspect national inventory', 'عرض المخزون الوطني'],
  ['Review recorded state changes, actors, entities, reasons and before/after values. Operational event browsing remains in Live activity log.', 'راجع تغييرات الحالة المسجلة والمنفذين والكيانات والأسباب والقيم قبل التغيير وبعده. يبقى استعراض الأحداث التشغيلية في سجل الأنشطة المباشر.'],
  ['matching events', 'أحداث مطابقة'],
  ['Actor, action, entity, patient or reason', 'المنفذ أو الإجراء أو الكيان أو المريض أو السبب'],
  ['Actor / role', 'المنفذ / الدور'],
  ['Patient / request', 'المريض / الطلب'],
  ['Previous state', 'الحالة السابقة'],
  ['New state', 'الحالة الجديدة'],
  ['Reason / details', 'السبب / التفاصيل'],
  ['No audit events match these filters', 'لا توجد أحداث تدقيق تطابق هذه المرشحات'],
  ['Clear a filter or choose another date range.', 'أزل أحد المرشحات أو اختر نطاقاً زمنياً آخر.'],
  ['Search action, record or detail', 'ابحث في الإجراء أو السجل أو التفاصيل'],
  ['Search alert, patient or record', 'ابحث في التنبيه أو المريض أو السجل'],
  ['Search audit activity', 'ابحث في نشاط التدقيق'],
  ['Read state', 'حالة القراءة'],
  ['No matching audit events', 'لا توجد أحداث تدقيق مطابقة'],
  ['All matching events', 'كل الأحداث المطابقة'],
  ['Treatment centre', 'مركز العلاج'],
  ['Centre', 'المركز'],
  ['Available stock', 'المخزون المتاح'],
  ['Safety alerts', 'تنبيهات السلامة'],
  ['Dispensing volume', 'حجم الصرف'],
  ['Approval rate', 'نسبة الموافقة'],
  ['Pending workload', 'عبء العمل المعلق'],
  ['Treatment volume', 'حجم العلاج'],
  ['Requests in the shared register', 'الطلبات في السجل المشترك'],
  ['Awaiting reviewer decision', 'بانتظار قرار المراجع'],
  ['Approved or handed to pharmacy', 'تمت الموافقة أو الإحالة إلى الصيدلية'],
  ['Current request status', 'حالة الطلب الحالية'],
  ['Awaiting safety verification', 'بانتظار التحقق من السلامة'],
  ['Recorded transactions', 'المعاملات المسجلة'],
  ['Plans marked complete', 'الخطط المحددة كمكتملة'],
  ['Programme directory', 'دليل البرنامج'],
  ['Clinical review team', 'فريق المراجعة السريرية'],
  ['Open participating sites', 'مواقع المشاركة المفتوحة'],
  ['Medication strengths held', 'تراكيز الأدوية المتوفرة'],
  ['Below reorder point', 'أقل من حد إعادة الطلب'],
  ['Within 60 days or expired', 'تنتهي خلال 60 يوماً أو منتهية الصلاحية'],
  ['Current rule-based signals', 'الإشارات الحالية القائمة على القواعد'],
]
for (const [en, ar] of phraseAdditions) phrases.set(en, ar)
const words = new Map<string, string>([
  ["patient", "المريض"],
  ["patients", "المرضى"],
  ["request", "الطلب"],
  ["requests", "الطلبات"],
  ["treatment", "العلاج"],
  ["clinical", "سريري"],
  ["review", "مراجعة"],
  ["reviewer", "المراجع"],
  ["pharmacist", "الصيدلي"],
  ["admin", "المسؤول"],
  ["doctor", "الطبيب"],
  ["inventory", "المخزون"],
  ["report", "التقرير"],
  ["reports", "التقارير"],
  ["activity", "النشاط"],
  ["appointment", "الموعد"],
  ["appointments", "المواعيد"],
  ["assessment", "التقييم"],
  ["eligibility", "الأهلية"],
  ["evidence", "الأدلة"],
  ["status", "الحالة"],
  ["search", "بحث"],
  ["filter", "تصفية"],
  ["all", "الكل"],
  ["active", "نشط"],
  ["eligible", "مؤهل"],
  ["approved", "معتمد"],
  ["rejected", "مرفوض"],
  ["pending", "قيد الانتظار"],
  ["dispensed", "مصروف"],
  ["ready", "جاهز"],
  ["information", "معلومات"],
  ["required", "مطلوب"],
  ["available", "متاح"],
  ["medication", "الدواء"],
  ["dose", "الجرعة"],
  ["strength", "التركيز"],
  ["quantity", "الكمية"],
  ["batch", "الدفعة"],
  ["expiry", "الانتهاء"],
  ["date", "التاريخ"],
  ["time", "الوقت"],
  ["notes", "ملاحظات"],
  ["name", "الاسم"],
  ["reason", "السبب"],
  ["diagnosis", "التشخيص"],
  ["symptoms", "الأعراض"],
  ["history", "التاريخ"],
  ["allergies", "الحساسية"],
  ["weight", "الوزن"],
  ["height", "الطول"],
  ["heart", "القلب"],
  ["rate", "المعدل"],
  ["save", "حفظ"],
  ["submit", "إرسال"],
  ["record", "تسجيل"],
  ["add", "إضافة"],
  ["complete", "إكمال"],
  ["cancel", "إلغاء"],
  ["confirm", "تأكيد"],
  ["open", "فتح"],
  ["close", "إغلاق"],
  ["home", "الرئيسية"],
  ["profile", "الملف الشخصي"],
  ["progress", "التقدم"],
  ["notifications", "الإشعارات"],
  ["medication", "الدواء"],
  ["patient", "المريض"],
  ["programme", "البرنامج"],
  ["national", "الوطني"],
  ["overview", "نظرة عامة"],
  ["emirate", "الإمارة"],
  ["citizens", "المواطنون"],
  ["residents", "المقيمون"],
  ["resident", "مقيم"],
  ["citizen", "مواطن"],
  ["centre", "المركز"],
  ["center", "المركز"],
  ["doctor", "الطبيب"],
  ["role", "الدور"],
  ["sort", "ترتيب"],
  ["newest", "الأحدث"],
  ["oldest", "الأقدم"],
  ["activity", "النشاط"],
  ["history", "التاريخ"],
  ["lab", "مختبر"],
  ["labs", "التحاليل"],
  ["value", "القيمة"],
  ["unit", "الوحدة"],
  ["interpretation", "التفسير"],
  ["reference", "المرجع"],
  ["range", "النطاق"],
  ["blood", "الدم"],
  ["pressure", "الضغط"],
  ["systolic", "انقباضي"],
  ["diastolic", "انبساطي"],
  ["duration", "المدة"],
  ["intensity", "الشدة"],
  ["light", "خفيف"],
  ["moderate", "متوسط"],
  ["vigorous", "شديد"],
  ["walking", "المشي"],
  ["running", "الجري"],
  ["cycling", "الدراجة"],
  ["swimming", "السباحة"],
  ["other", "أخرى"],
  ["appointments", "المواعيد"],
  ["upcoming", "القادمة"],
  ["completed", "مكتمل"],
  ["cancelled", "ملغى"],
  ["confirmed", "مؤكد"],
  ["scheduled", "مجدول"],
  ["no", "لا"],
  ["show", "حضور"],
  ["information", "معلومات"],
  ["requested", "مطلوب"],
  ["low", "منخفض"],
  ["stock", "مخزون"],
  ["critical", "حرج"],
  ["warning", "تحذير"],
  ["success", "نجاح"],
  ["patient", "المريض"],
  ["care", "الرعاية"],
  ["team", "الفريق"],
  ["queue", "القائمة"],
  ["requests", "الطلبات"],
  ["activity", "النشاط"],
  ["records", "السجلات"],
  ["recorded", "مسجل"],
  ["search", "بحث"],
  ["export", "تصدير"],
  ["all", "الكل"],
  ["today", "اليوم"],
  ["tomorrow", "غداً"],
  ["draft", "مسودة"],
  ["history", "التاريخ"],
  ["request", "الطلب"],
  ["clinician", "الطبيب"],
  ["medical", "طبي"],
  ["follow-up", "المتابعة"],
  ["follow", "متابعة"],
  ["up", "لاحقة"],
  ["vitals", "المؤشرات الحيوية"],
  ["emirates", "الإمارات"],
  ["id", "الرقم"],
  ["registered", "مسجل"],
  ["active", "نشط"],
  ["under", "تحت"],
  ["for", "لمدة"],
  ["days", "أيام"],
  ["weekly", "أسبوعياً"],
  ["daily", "يومياً"],
  ["patient", "المريض"],
  ["pharmacy", "الصيدلية"],
  ["programme", "البرنامج"],
  ["month", "الشهر"],
  ["minutes", "دقيقة"],
  ["estimated", "تقديري"],
  ["coverage", "التغطية"],
  ["financial", "مالي"],
  ["audit", "التدقيق"],
  ["emergency", "طارئ"],
  ["current", "حالي"],
  ["derived", "مستمد"],
  ["from", "من"],
  ["and", "و"],
  ["makes", "يتخذ"],
  ["decision", "القرار"],
  ["the", "ال"],
  ["years", "عاماً"],
  ["missing", "غير متوفر"],
  ["within", "ضمن"],
  ["normal", "طبيعي"],
  ["findings", "النتائج"],
  ["plan", "الخطة"],
  ["reviewed", "تمت مراجعته"],
  ["visit", "الزيارة"],
  ["or", "أو"],
  ["note", "ملاحظة"],
  ["details", "التفاصيل"],
  ["priority", "الأولوية"],
  ["submitted", "مُرسل"],
  ["management", "الإدارة"],
  ["weight", "الوزن"],
  ["kg", "كغ"],
  ["weekly", "أسبوعياً"],
  ["every", "كل"],
  ["two", "اثنين"],
  ["days", "أيام"],
  ["follow-up", "المتابعة"],
  ["meets", "يستوفي"],
  ["criteria", "المعايير"],
  ["eligible", "مؤهل"],
  ["not", "غير"],
  ["fasting", "صائم"],
  ["glucose", "الجلوكوز"],
  ["previous", "السابق"],
  ["dispensing", "الصرف"],
  ["record", "السجل"],
  ["type", "نوع"],
  ["diabetes", "السكري"],
  ["male", "ذكر"],
  ["female", "أنثى"],
  ["cm", "سم"],
  ["mounjaro", "مونجارو"],
  ["showing", "يعرض"],
  ["of", "من"],
  ["safety", "السلامة"],
  ["adherence", "الالتزام"],
  ["units", "وحدات"],
  ["severity", "الخطورة"],
  ["alphabetical", "أبجدي"],
  ["health", "الصحة"],
  ["operations", "العمليات"],
  ["supply", "الإمداد"],
  ["total", "إجمالي"],
  ["shared", "مشترك"],
  ["plans", "الخطط"],
  ["awaiting", "بانتظار"],
  ["handed", "أُحيل"],
  ["transactions", "المعاملات"],
  ["held", "المتوفرة"],
  ["reorder", "إعادة الطلب"],
  ["expired", "منتهي الصلاحية"],
  ["strengths", "التراكيز"],
  ["signals", "الإشارات"],
  ["unresolved", "غير محلولة"],
  ["matching", "مطابقة"],
  ["events", "الأحداث"],
  ["actor", "المنفذ"],
  ["entity", "الكيان"],
  ["previous", "السابقة"],
  ["new", "الجديدة"],
  ["timestamp", "الطابع الزمني"],
  ["network", "الشبكة"],
  ["centre", "المركز"],
  ["centres", "المراكز"],
  ["facility", "المنشأة"],
  ["facilities", "المنشآت"],
  ["geography", "التوزيع الجغرافي"],
  ["ranked", "مرتبة"],
  ["outcomes", "النتائج"],
  ["demand", "الطلب"],
  ["volume", "الحجم"],
  ["workload", "عبء العمل"],
  ["signals", "الإشارات"]
])
for (const [english,arabic] of [...careTranslations,...careWorkflowTranslations]) phrases.set(english,arabic)
for (const [english, arabic] of [...adminTranslations, ...reportTranslations]) phrases.set(english, arabic)
const orderedPhrases = [...phrases].sort(([left], [right]) => right.length - left.length)

export { phrases, words, orderedPhrases, localizeAdminTemplate }
