import {useState} from 'react'
import {CareIcon} from './CareIcon'
import {PatientAvatar} from './PatientAvatar'
import {useDialogFocus} from './useDialogFocus'
import {localizeArabic} from './ArabicText'
import * as catalogue from './ArabicCatalogue'
import {can,canReadPatient,saveAppointment,recordRehabilitationSession,updateIntegratedCarePlan,type AppData,type Role} from './domain'
import './CarePlanDetail.css'

type Props={data:AppData;role:Role;arabic:boolean;planId:string;onUpdate:(data:AppData)=>void;onBack:()=>void;onPatient:(id:string)=>void;onRequest:(id:string)=>void}
export function CarePlanDetail({data,role,arabic,planId,onUpdate,onBack,onPatient,onRequest}:Props){
 const t=(en:string,ar:string)=>arabic?ar:en
 const local=(value:string)=>arabic?localizeArabic(value.replace(/laboratory report/g,'تقرير التحليل المخبري').replace('Migrated from the existing prescribed rehabilitation programme.','تم اعتماد الخطة استنادًا إلى برنامج التأهيل الموصوف سابقًا.'),catalogue):value
 const plan=data.integratedCarePlans?.find(p=>p.id===planId&&canReadPatient(data,role,p.patientId))
 const patient=data.patients.find(p=>p.id===plan?.patientId)
 const [today]=useState(()=>new Date().toISOString().slice(0,10))
 const [modal,setModal]=useState<'edit'|'followup'|'session'|'exercises'|'evidence'|'history'|'documents'|'medication'|null>(null)
 const [title,setTitle]=useState(''),[notes,setNotes]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState('09:00'),[error,setError]=useState('')
 const close=()=>{setModal(null);setError('')},ref=useDialogFocus(!!modal,close)
 if(!plan||!patient)return <div className="cpd-empty"><h2>{t('Care plan not found','لم يتم العثور على خطة الرعاية')}</h2><button onClick={onBack}>{t('Back to care plans','العودة إلى خطط الرعاية')}</button></div>
 const request=data.requests.find(r=>r.id===plan.treatmentRequestId),rx=data.treatmentPlans.find(p=>p.id===request?.planId),med=data.medications?.find(m=>m.id===plan.medicationId)
 const doctor=data.doctors.find(d=>d.id===plan.doctorId),centre=data.rehabilitationCentres?.find(c=>c.id===plan.rehabilitation?.centreId)
 const exercises=(data.homeExercises??[]).filter(e=>plan.homeExerciseIds.includes(e.id)),appointment=data.appointments.find(a=>a.id===plan.appointmentId)
 const events=data.audit.filter(e=>e.entityId===plan.id||e.entityId===plan.treatmentRequestId||e.entityId===plan.appointmentId).sort((a,b)=>(b.occurredAt??'').localeCompare(a.occurredAt??''))
 const docs=(data.documents??[]).filter(d=>d.patientId===patient.id)
 const sessions=plan.rehabilitation?.sessions.length??0,total=plan.rehabilitation?.plannedSessions??0,progress=total?Math.round(sessions/total*100):0
 const writable=can(role,'clinical:write'),schedule=can(role,'appointment:manage')
 const open=(kind:typeof modal)=>{setError('');setTitle(plan.title);setNotes(kind==='edit'?plan.monitoring:'');setDate(kind==='session'?today:plan.followUpDate);setTime(appointment?.time??'09:00');setModal(kind)}
 const save=()=>{try{
  if(modal==='edit')onUpdate(updateIntegratedCarePlan(data,role,plan.id,{title,monitoring:notes}))
  if(modal==='session')onUpdate(recordRehabilitationSession(data,role,plan.id,date,notes))
  if(modal==='followup'){
   const next=saveAppointment(data,role,{...appointment,patientId:patient.id,doctor:doctor?.name??patient.assignedDoctor??'',centre:appointment?.centre??patient.treatmentCentre??'',purpose:appointment?.purpose??'Integrated care follow-up',date,time,status:'Scheduled',notes:notes||appointment?.notes||plan.monitoring})
   onUpdate({...next,integratedCarePlans:next.integratedCarePlans?.map(p=>p.id===plan.id?{...p,followUpDate:date,appointmentId:next.appointments[0].id}:p)})
  }
  close()
 }catch(e){setError(local((e as Error).message))}}
 const badge=(value:string)=><span className="cpd-badge">{local(value)}</span>
 const field=(label:string,value:string,icon:string)=><div className="cpd-field"><CareIcon name={icon}/><div><small>{label}</small><b>{value}</b></div></div>
 const action=(label:string,icon:string,handler:()=>void,primary=false)=><button className={primary?'cpd-primary':''} onClick={handler}><CareIcon name={icon}/>{label}</button>
 const steps=[{title:t('Medical assessment','التقييم الطبي'),state:t('Completed','مكتمل')},{title:t('Treatment eligibility','أهلية العلاج'),state:plan.review.eligibilityMet?t('Completed','مكتمل'):t('Review required','تتطلب مراجعة')},{title:t('Medication','العلاج الدوائي'),state:request?local(request.status):t('Not included','غير مشمول')},{title:t('Physiotherapy','العلاج الطبيعي'),state:plan.rehabilitation?local(plan.rehabilitation.status):t('Not included','غير مشمول')},{title:t('Home exercises','التمارين المنزلية'),state:exercises.length?t('Included in plan','ضمن الخطة'):t('Not included','غير مشمول')},{title:t('Follow-up & monitoring','المتابعة والمراقبة'),state:local(appointment?.status??'Scheduled')}]
 const latest=[plan.createdAt,plan.review.confirmedAt,...events.map(e=>e.occurredAt??''),...(plan.rehabilitation?.sessions.map(s=>s.date)??[])].sort().at(-1)!.slice(0,10)
 return <div className="care-plan-detail" dir={arabic?'rtl':'ltr'} data-no-localize>
  <section className="cpd-patient"><div className="cpd-identity"><PatientAvatar patient={patient} arabic={arabic}/><div><h2>{arabic?patient.nameAr??local(patient.name):patient.name}</h2><small>{patient.id} · {local(patient.residency??'Patient')}</small></div>{badge(plan.status)}</div>{field(t('Age','العمر'),`${patient.age} ${t('years','سنة')}`,'calendar')}{field(t('Sex','النوع'),local(patient.sex??'—'),'user')}{field(t('Primary diagnosis','التشخيص الرئيسي'),local(patient.diagnosis),'file')}{action(t('View patient file','عرض ملف المريض'),'user',()=>onPatient(patient.id))}</section>
  <section className="cpd-hero"><div className="cpd-plan-title"><span className="cpd-plan-icon"><CareIcon name="walk"/></span><div><small>{plan.id}</small><h1>{local(plan.title)}</h1><p>{t('One coordinated plan for treatment, rehabilitation and follow-up.','خطة متكاملة للعلاج والتأهيل والتمارين المنزلية والمتابعة.')}</p></div>{badge(plan.status)}</div><div className="cpd-hero-bottom"><div className="cpd-dates">{field(t('Start date','تاريخ البداية'),plan.createdAt.slice(0,10),'calendar')}{field(t('Planned duration','المدة المخططة'),rx?`${rx.durationDays} ${t('days','يوم')}`:'—','clock')}{field(t('Last update','آخر تحديث'),latest,'reset')}</div><div className="cpd-actions">{request&&action(t('Open treatment request','فتح طلب العلاج'),'file',()=>onRequest(request.id))}{schedule&&action(t('Schedule follow-up','جدولة متابعة'),'calendar',()=>open('followup'))}{writable&&action(t('Update plan','تحديث الخطة'),'edit',()=>open('edit'),true)}</div></div><span className="cpd-hero-art" aria-hidden="true"><CareIcon name="walk"/></span></section>
  <section className="cpd-journey"><h3>{t('Treatment plan journey','مسار خطة العلاج')}</h3><p>{t('Current milestones from the shared care record.','نظرة عامة على مراحل الخطة الحالية وحالتها.')}</p><ol>{steps.map((step,i)=><li key={step.title} className={i===2&&request?'current':''}><span>{i+1}</span><b>{step.title}</b><small>{step.state}</small></li>)}</ol></section>
  <div className="cpd-components">
   <section className="cpd-card"><h3><CareIcon name="pill"/>{t('Medication','العلاج الدوائي')}</h3>{request?<><div className="cpd-med"><CareIcon name="pill"/><div><small>{t('Medication','الدواء')}</small><b>{local(med?.name??request.medication??'Mounjaro')} {local(request.dose)}</b></div></div>{field(t('Treatment request','رقم طلب العلاج'),request.id,'file')}{field(t('Frequency','الجرعة'),local(rx?.frequency??'—'),'calendar')}{badge(request.status)}<footer>{action(t('Medication details','عرض تفاصيل الدواء'),'open',()=>open('medication'))}</footer></>:<p>{t('No medication included','لا يوجد علاج دوائي ضمن الخطة')}</p>}</section>
   <section className="cpd-card"><h3><CareIcon name="walk"/>{t('Physiotherapy','العلاج الطبيعي')}</h3>{plan.rehabilitation?<>{field(t('Treatment centre','مركز العلاج'),local(centre?.name??'—'),'building')}<div className="cpd-progress"><progress value={sessions} max={total}/><b>{sessions} / {total} {t('sessions','جلسات')}</b></div>{badge(plan.rehabilitation.status)}<p>{t('Completed sessions','الجلسات المسجلة')}: {progress}%</p><footer>{writable&&sessions<total&&action(t('Record rehabilitation session','تسجيل جلسة تأهيل'),'calendar',()=>open('session'))}</footer></>:<p>{t('No rehabilitation included','لا يوجد تأهيل ضمن الخطة')}</p>}</section>
   <section className="cpd-card"><h3><CareIcon name="home"/>{t('Home exercises','التمارين المنزلية')}</h3>{exercises.slice(0,2).map(e=><div className="cpd-exercise" key={e.id}><CareIcon name="walk"/><div><b>{local(e.name)}</b><small>{local(e.frequency)} · {e.durationMinutes} {t('minutes','دقيقة')}</small></div></div>)}{!exercises.length&&<p>{t('No home exercises included','لا توجد تمارين منزلية ضمن الخطة')}</p>}<footer>{action(t('View home exercises','عرض التمارين المنزلية'),'open',()=>open('exercises'))}</footer></section>
   <section className="cpd-card"><h3><CareIcon name="calendar"/>{t('Follow-up & monitoring','المتابعة والمراقبة')}</h3>{field(t('Next follow-up','تاريخ المتابعة القادمة'),plan.followUpDate,'calendar')}<small>{t('Monitoring tasks','المهام')}</small><p className="cpd-monitoring">{local(plan.monitoring)}</p>{field(t('Responsible clinician','المسؤول'),local(doctor?.name??patient.assignedDoctor??'—'),'stethoscope')}</section>
  </div>
  <div className="cpd-secondary">
   <section className="cpd-card"><h3><CareIcon name="file"/>{t('Linked documents and records','الوثائق والسجلات المرتبطة')}</h3>{docs.slice(0,3).map(d=><div className="cpd-document" key={d.id}><CareIcon name="file"/><div><b>{local(d.title)}</b><small>{d.date}{d.sizeBytes?` · ${Math.ceil(d.sizeBytes/1024)} KB`:''}</small></div></div>)}{!docs.length&&<p>{t('No documents attached to this patient','لا توجد وثائق مرفقة لهذا المريض')}</p>}<footer>{action(t('View all documents','عرض جميع الوثائق'),'open',()=>open('documents'))}</footer></section>
   <section className="cpd-card"><h3><CareIcon name="clock"/>{t('Decisions and reviews','القرارات والمراجعات')}</h3><div className="cpd-timeline"><div><b>{t('Care plan confirmed','تم اعتماد خطة العلاج')}</b><small>{local(doctor?.name??plan.review.doctorId)} · {plan.review.confirmedAt.slice(0,10)}</small><p>{local(plan.review.rationale)}</p></div>{events.slice(0,1).map(e=><div key={e.id}><b>{local(e.action)}</b><small>{e.occurredAt?.slice(0,10)??e.time}</small></div>)}</div><footer>{action(t('View full history','عرض التاريخ الكامل'),'open',()=>open('history'))}</footer></section>
   <section className="cpd-card cpd-assistant"><h3><CareIcon name="decision"/>{t('Clinical decision support','مساعد القرار السريري')}<small>{t('Decision support only','دعم القرار فقط')}</small></h3><p>{local(plan.monitoring)}</p><ul>{(plan.aiRecommendations??[]).slice(0,3).map(r=><li key={r}>{local(r)}</li>)}{!plan.aiRecommendations?.length&&<li>{t('Review the recorded clinical criteria with the treating clinician.','راجع المعايير السريرية المسجلة مع الطبيب المعالج.')}</li>}</ul><footer>{action(t('View evidence and recommendations','عرض الأدلة والتوصيات'),'open',()=>open('evidence'))}</footer></section>
  </div><div className="cpd-bottom">{action(t('Back to patient care','العودة إلى قائمة رعاية المريض'),'open',onBack)}<div className="cpd-actions">{request&&action(t('Open treatment request','فتح طلب العلاج'),'file',()=>onRequest(request.id))}{schedule&&action(t('Schedule follow-up','جدولة متابعة'),'calendar',()=>open('followup'))}{writable&&action(t('Update plan','تحديث الخطة'),'edit',()=>open('edit'),true)}</div></div>
  {modal&&<div className="cpd-overlay"><section ref={ref} className="cpd-dialog" role="dialog" aria-modal="true" aria-label={t('Care plan details','تفاصيل خطة الرعاية')}><header><h2>{local(plan.title)}</h2><button onClick={close} aria-label={t('Close','إغلاق')}><CareIcon name="close"/></button></header>
  {['edit','followup','session'].includes(modal)?<form onSubmit={e=>{e.preventDefault();save()}}>{modal==='edit'?<label>{t('Plan title','عنوان الخطة')}<input required value={title} onChange={e=>setTitle(e.target.value)}/></label>:<label>{t('Date','التاريخ')}<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label>}{modal==='followup'&&<label>{t('Time','الوقت')}<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label>}<label>{t('Monitoring / notes','المتابعة / الملاحظات')}<textarea required={modal!=='followup'} minLength={modal!=='followup'?5:undefined} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="cpd-primary" type="submit">{t('Save changes','حفظ التغييرات')}</button></form>:modal==='exercises'?exercises.map(e=><article key={e.id}><h3>{local(e.name)}</h3><p>{local(e.instructions)}</p><p>{local(e.frequency)} · {e.durationMinutes} {t('minutes','دقيقة')} · {local(e.repetitions)}</p><p>{local(e.notes)}</p></article>):modal==='history'?events.map(e=><article key={e.id}><h3>{local(e.action)}</h3><small>{local(e.actor)} · {e.occurredAt??e.time}</small><p>{local(e.detail)}</p></article>):modal==='documents'?docs.map(d=><article key={d.id}><h3>{local(d.title)}</h3><small>{d.date}</small><p>{local(d.content)}</p>{d.dataUrl&&<a href={d.dataUrl} download={d.fileName??d.id}>{t('Download attachment','تنزيل المرفق')}</a>}</article>):modal==='evidence'?<><ul>{plan.review.criteria.map(c=><li key={c.label}>{c.passed?'✓':'—'} {local(c.label)}: {local(c.evidence)}</li>)}</ul><p>{local(plan.review.rationale)}</p>{plan.aiRecommendations?.map(r=><p key={r}>{local(r)}</p>)}</>:<><h3>{local(med?.name??request?.medication??'—')} · {local(request?.dose??'—')}</h3><p>{local(rx?.instructions??'—')}</p><p>{local(rx?.frequency??'—')} · {rx?.startDate} – {rx?.endDate}</p><p>{local(rx?.monitoringPlan??'—')}</p></>}
  </section></div>}
 </div>
}
