import {useState,type FormEvent} from 'react'
import {CareIcon} from './CareIcon'
import {can,canReadPatient,recordVitals,saveAssessment,treatmentEligibility,type AppData,type Role} from './domain'
import {localizeArabic} from './ArabicText'
import * as catalogue from './ArabicCatalogue'
import './ClinicalAssessment.css'
type Props={data:AppData;role:Role;arabic?:boolean;selectedPatientId?:string;onUpdate:(data:AppData)=>void;onPatient?:(id:string)=>void}
export function ClinicalWorkspace(props:Props){
 const patients=props.data.patients.filter(p=>canReadPatient(props.data,props.role,p.id))
 const [selected,setSelected]=useState(patients[0]?.id??'')
 const id=props.selectedPatientId??selected
 if(!patients.some(p=>p.id===id))return <p>{props.arabic?'لا يوجد مريض متاح':'No accessible patient'}</p>
 return <>{!props.selectedPatientId&&<label>{props.arabic?'المريض':'Patient'}<select value={id} onChange={e=>setSelected(e.target.value)}>{patients.map(p=><option key={p.id} value={p.id}>{props.arabic?p.nameAr??p.name:p.name}</option>)}</select></label>}<Assessment key={id} {...props} patientId={id}/></>
}
function Assessment({data,role,arabic=false,onUpdate,onPatient,patientId}:Props&{patientId:string}){
 const t=(en:string,ar:string)=>arabic?ar:en,local=(v:string)=>arabic?localizeArabic(v.replace(/\bobesity\b/gi,'السمنة').replace('kg/m²','كجم/م²'),catalogue):v
 const patient=data.patients.find(p=>p.id===patientId)!
 const history=data.vitals.filter(v=>v.patientId===patientId).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt))
 const assessments=data.assessments.filter(a=>a.patientId===patientId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),latest=assessments[0]
 const [assessment,setAssessment]=useState(()=>({id:latest?.id,reason:latest?.reason??'',diagnosis:latest?.diagnosis??patient.diagnosis,symptoms:latest?.symptoms??'',medicalHistory:latest?.medicalHistory??patient.previousIllnesses?.join(', ')??'',medications:latest?.medications??'',allergies:latest?.allergies??'',findings:latest?.findings??'',notes:latest?.notes??''}))
 const [vitals,setVitals]=useState(()=>({weightKg:String(history[0]?.weightKg??patient.weightKg??''),heightCm:String(history[0]?.heightCm??patient.heightCm??''),systolic:String(history[0]?.systolic??''),diastolic:String(history[0]?.diastolic??''),heartRate:String(history[0]?.heartRate??'')}))
 const [feedback,setFeedback]=useState(''),[failed,setFailed]=useState(false),[allHistory,setAllHistory]=useState(false),[evidence,setEvidence]=useState(false)
 const editable=can(role,'clinical:write'),eligibility=treatmentEligibility(data,patientId)
 const plan=data.integratedCarePlans?.filter(p=>p.patientId===patientId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]
 const request=data.requests.find(r=>r.id===plan?.treatmentRequestId)
 const labs=data.labs.filter(l=>l.patientId===patientId&&l.status!=='Pending').sort((a,b)=>b.date.localeCompare(a.date))
 const bmi=Number(vitals.heightCm)>0&&Number(vitals.weightKg)>0?Number(vitals.weightKg)/((Number(vitals.heightCm)/100)**2):null
 const completeness=[{label:t('Vital signs','القياسات الحيوية'),done:history.length>0},{label:t('Medical history','التاريخ المرضي'),done:!!assessment.medicalHistory.trim()},{label:t('Symptoms','الأعراض'),done:!!assessment.symptoms.trim()},{label:t('Current medication','الأدوية الحالية'),done:!!assessment.medications.trim()},{label:t('Clinical findings','نتائج الفحص'),done:!!assessment.findings.trim()},{label:t('Doctor note','ملاحظة الطبيب'),done:!!assessment.notes.trim()}]
 const percent=Math.round(completeness.filter(c=>c.done).length/completeness.length*100)
 function save(status:'Draft'|'Submitted'){try{const next=saveAssessment(data,role,{...assessment,patientId,status});onUpdate(next);setAssessment({...assessment,id:next.assessments[0].id});setFailed(false);setFeedback(status==='Draft'?t('Draft saved.','تم حفظ المسودة.'):t('Assessment submitted.','تم اعتماد التقييم.'))}catch(e){setFailed(true);setFeedback(local((e as Error).message))}}
 function saveVital(e:FormEvent){e.preventDefault();try{onUpdate(recordVitals(data,role,patientId,{weightKg:Number(vitals.weightKg),heightCm:Number(vitals.heightCm),systolic:Number(vitals.systolic),diastolic:Number(vitals.diastolic),heartRate:Number(vitals.heartRate)}));setFailed(false);setFeedback(t('Measurements saved and eligibility updated.','تم حفظ القياسات وتحديث الأهلية.'))}catch(e){setFailed(true);setFeedback(local((e as Error).message))}}
 const stages=[{label:t('Medical assessment','التقييم الطبي'),icon:'stethoscope',state:eligibility.assessment?t('Completed','مكتمل'):t('In progress','قيد التقييم')},{label:t('Treatment eligibility','أهلية العلاج'),icon:'decision',state:eligibility.eligible?t('Criteria met','مستوفٍ'):t('Review required','تتطلب مراجعة')},{label:t('Medication','العلاج الدوائي'),icon:'pill',state:request?local(request.status):t('Not included','غير مشمول')},{label:t('Physiotherapy','العلاج الطبيعي'),icon:'walk',state:plan?.rehabilitation?local(plan.rehabilitation.status):t('Not included','غير مشمول')},{label:t('Home exercises','التمارين المنزلية'),icon:'activity',state:plan?.homeExerciseIds.length?t('Included','ضمن الخطة'):t('Not included','غير مشمول')},{label:t('Plan & follow-up','الخطة والمتابعة'),icon:'check',state:plan?.followUpDate??t('Not scheduled','غير مجدول')}]
 const fields=[['reason','Reason for visit','سبب الزيارة','file'],['diagnosis','Diagnosis','التشخيص','stethoscope'],['symptoms','Symptoms','الأعراض','activity'],['medicalHistory','Medical history','التاريخ المرضي','calendar'],['medications','Current medication','الأدوية الحالية','pill'],['allergies','Allergies','الحساسية','decision'],['findings','Clinical findings','نتائج الفحص','file'],['notes','Doctor note','ملاحظة الطبيب','edit']] as const
 const vitalFields=[['weightKg','Weight (kg)','الوزن (كجم)',20,400,'box'],['heightCm','Height (cm)','الطول (سم)',80,250,'chart'],['systolic','Systolic pressure','الضغط الانقباضي',50,260,'stethoscope'],['diastolic','Diastolic pressure','الضغط الانبساطي',30,160,'activity'],['heartRate','Heart rate','معدل النبض',30,240,'activity']] as const
 return <div className="clinical-assessment" dir={arabic?'rtl':'ltr'} data-no-localize>
 <section className="ca-banner"><div><h1><CareIcon name="stethoscope"/>{t('Clinical assessment & lab results','التقييم الطبي والتحاليل')}</h1><p>{t('Record the visit, symptoms, diagnosis and measurements. Review lab results in the patient file to support programme eligibility.','هنا تسجّل الزيارة والأعراض والتشخيص والقياسات، وتراجع التحاليل في ملف المريض. يستخدم دعم القرار هذه البيانات لفحص معايير البرنامج.')}</p></div><ol>{stages.map((s,i)=><li key={s.label} className={i===0?'current':''}><span><CareIcon name={s.icon}/></span><b>{s.label}</b><small>{s.state}</small></li>)}</ol></section>
 {feedback&&<div className={`ca-feedback ${failed?'error':''}`} role={failed?'alert':'status'}>{feedback}</div>}
 <div className="ca-layout"><div className="ca-main"><section className="ca-card ca-doctor"><h2><CareIcon name="stethoscope"/>{t('Doctor assessment','تقييم الطبيب')}</h2><p>{t('Record symptoms, findings and the assessment plan for this visit.','تسجيل الأعراض والنتائج وخطة التقييم في الزيارة الحالية.')}</p>{!editable&&<p className="ca-readonly">{t('Read-only clinical record for your role.','عرض السجل السريري وفق صلاحيات المراجعة.')}</p>}<form onSubmit={e=>{e.preventDefault();save('Submitted')}}><fieldset disabled={!editable}><div className="ca-fields">{fields.map(([key,en,ar,icon])=><label key={key}>{t(en,ar)}<span><CareIcon name={icon}/>{key==='findings'||key==='notes'?<textarea value={local(assessment[key])} onChange={e=>setAssessment({...assessment,[key]:e.target.value})}/>:<input required={key==='reason'||key==='diagnosis'} value={local(assessment[key])} onChange={e=>setAssessment({...assessment,[key]:e.target.value})}/>}</span></label>)}</div></fieldset>{editable&&<footer><button type="button" onClick={()=>save('Draft')}><CareIcon name="file"/>{t('Save draft','حفظ مسودة')}</button><button className="ca-primary" type="submit"><CareIcon name="check"/>{t('Submit assessment','اعتماد التقييم')}</button></footer>}</form></section>
 <div className="ca-insights"><section className="ca-card ca-completeness"><h2>{t('Data completeness','مدى اكتمال البيانات')}</h2><div><ul>{completeness.map(c=><li key={c.label}><CareIcon name={c.done?'check':'file'}/><span>{c.label}</span></li>)}</ul><div className="ca-ring" style={{background:`conic-gradient(#009e82 ${percent}%,#edf3f4 0)`}}><b>{percent}%</b></div></div><p>{t('Completed fields in this assessment','اكتمال بيانات التقييم الحالي')}</p></section>
 <section className="ca-card ca-support"><h2><CareIcon name="decision"/>{t('Decision support','دعم القرار')}<small>{t('Support only, not a diagnosis','دعم التقييم فقط وليس تشخيصًا مستقلاً')}</small></h2><p>{t('Review the saved evidence alongside the patient’s diagnosis and current care plan.','راجع الأدلة المسجلة مع تشخيص المريض وخطة الرعاية الحالية.')}</p><ul><li>{t('Review laboratory results and their reference ranges.','مراجعة نتائج التحاليل ومقارنتها بالمدى المرجعي.')}</li><li>{t('Follow up on adherence to prescribed medication.','متابعة الالتزام بالأدوية الموصوفة.')}</li>{eligibility.clinical.warnings.map(w=><li key={w}>{local(w)}</li>)}{!eligibility.refill.eligible&&<li>{t('Next regular dispensing date:','موعد الصرف الدوري التالي:')} {eligibility.refill.nextEligibleDate}</li>}</ul><button onClick={()=>setEvidence(v=>!v)} aria-expanded={evidence}><CareIcon name="open"/>{t('View evidence & recommendations','عرض الأدلة والتوصيات')}</button>{evidence&&<div className="ca-evidence">{eligibility.clinical.criteria.map(c=><p key={c.label}>{c.passed?'✓':'—'} {local(c.label)} · {local(c.evidence)}</p>)}<button onClick={()=>onPatient?.(patientId)}>{t('Open patient labs','فتح تحاليل المريض')}</button>{labs.map(l=><p key={l.id}>{local(l.test)} · {l.value} {local(l.unit)} · {l.date}</p>)}</div>}</section></div></div>
 <aside className="ca-side"><section className="ca-card ca-vitals"><h2><CareIcon name="activity"/>{t('Vital signs','القياسات الحيوية')}</h2><p>{t('BMI is calculated from height and weight.','يُحسب مؤشر كتلة الجسم من الطول والوزن.')}</p><form onSubmit={saveVital}><fieldset disabled={!editable}><div className="ca-vital-grid">{vitalFields.map(([key,en,ar,min,max,icon])=><label key={key}>{t(en,ar)}<span><CareIcon name={icon}/><input type="number" step={key==='weightKg'||key==='heightCm'?'0.1':'1'} min={min} max={max} required value={vitals[key]} onChange={e=>setVitals({...vitals,[key]:e.target.value})}/></span></label>)}<div className="ca-bmi"><small>{t('Body mass index','مؤشر كتلة الجسم')}</small><div><CareIcon name="chart"/><strong>{bmi?.toFixed(1)??'—'}</strong></div></div></div></fieldset>{editable&&<button className="ca-primary"><CareIcon name="file"/>{t('Save measurements','حفظ القياسات')}</button>}</form></section>
 <section className="ca-card ca-history"><h2><CareIcon name="chart"/>{t('Previous measurements','السجل السابق للقياسات')}</h2>{(allHistory?history:history.slice(0,2)).map(v=><details key={v.id}><summary><div><b>{v.weightKg} {t('kg','كجم')} · {t('BMI','مؤشر الكتلة')} {v.bmi}</b><small>{t('Pulse','النبض')} {v.heartRate} · {t('Pressure','الضغط')} {v.systolic}/{v.diastolic}</small></div><time>{v.recordedAt.slice(0,10)}</time></summary><p>{t('Height','الطول')}: {v.heightCm} {t('cm','سم')} · {local(v.actor)}</p></details>)}{!history.length&&<p>{t('No measurements recorded yet.','لا توجد قياسات مسجلة بعد.')}</p>}{history.length>2&&<button onClick={()=>setAllHistory(v=>!v)}>{allHistory?t('Show less','عرض أقل'):t('View all measurements','عرض جميع القياسات')}</button>}</section></aside></div></div>
}
