import { useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent } from 'react'
import { assistantScope, assistantLinkAllowed } from './assistantScope'
import { CareIcon } from './CareIcon'
import { PatientAvatar } from './PatientAvatar'
import type { AppData, Role } from './domain'
import type { AdminPage } from './adminAnalytics'
import { answerDataQuestion, type AssistantContext, type RichDataAnswer } from './assistantQuery'
import { readMockWorkspace } from './mockRepository'
import { Skeleton } from './WorkspaceLoading'
import { localizeArabic } from './ArabicText'
import * as catalogue from './ArabicCatalogue'
import robot from './assets/login-ai-assistant.png'
import './DataAssistant.css'

type Message={id:number;question:string;at:string}
type Props={role:Role;data:AppData;arabic:boolean;onNavigate:(page:AdminPage,id?:string)=>void;onCreateRequest?:()=>void}
export function DataAssistant({data:canonicalData,role,arabic,onNavigate,onCreateRequest}:Props){
 const data=useMemo(()=>assistantScope(canonicalData,role),[canonicalData,role])
 const t=(en:string,ar:string)=>arabic?ar:en
 const [draft,setDraft]=useState(''),[messages,setMessages]=useState<Message[]>([]),[pending,setPending]=useState<string|null>(null),[notice,setNotice]=useState(''),[showOptions,setShowOptions]=useState(false),[compact,setCompact]=useState(false)
 const [showExample,setShowExample]=useState(true)
 const controllerRef=useRef<AbortController|null>(null),inputRef=useRef<HTMLTextAreaElement>(null),listRef=useRef<HTMLDivElement>(null),uploadRef=useRef<HTMLInputElement>(null)
 const previewPatient=data.patients.find(p=>data.requests.some(r=>r.patientId===p.id))
 const example:Message={id:0,question:t(`What is the treatment request status for ${previewPatient?.name??''} ${previewPatient?.id??''}?`,`ما هي حالة طلب العلاج للمريض ${previewPatient?.nameAr??previewPatient?.name??''} ${previewPatient?.id??''}؟`),at:''}
 const turns=useMemo(()=>{
  let context:AssistantContext={}
  const source=messages.length?messages:showExample&&previewPatient?[example]:[]
  return source.map(message=>{const answer=answerDataQuestion(canonicalData,message.question,arabic,role,context);context=answer.context;return {message,answer}})
 // The example is derived from current records, never a separate seeded conversation.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[messages,canonicalData,arabic,role,showExample,previewPatient?.id])
 const topics=[{icon:'patients',label:t('Patient overview','تحليل مريض'),question:t(`Patient ${previewPatient?.id??''}`,`ملف المريض ${previewPatient?.id??''}`)},{icon:'file',label:t('Treatment requests','طلبات العلاج'),question:t('All treatment requests under review','جميع الطلبات قيد المراجعة')},{icon:'calendar',label:t('Upcoming visits','المواعيد القادمة'),question:t('Upcoming appointments','المواعيد القادمة')},{icon:'care-plan',label:t('Care plans','خطط الرعاية'),question:t('All care plans in the programme','كل خطط الرعاية في البرنامج')},{icon:role==='Admin'||role==='Pharmacist'?'box':'lab',label:role==='Admin'||role==='Pharmacist'?t('Inventory','المخزون'):t('Lab results','التحاليل'),question:role==='Admin'||role==='Pharmacist'?t('Available stock','المخزون المتاح'):t('Abnormal lab results','نتائج التحاليل غير الطبيعية')},{icon:'bell',label:t('Alerts','التنبيهات'),question:t('Open alerts','التنبيهات المفتوحة')}]
 const counts=[{icon:'patients',label:t('Patients','المرضى'),detail:t('Accessible patient records','سجلات المرضى المتاحة'),value:data.patients.length,question:t('All patients','جميع المرضى'),tone:'green'},{icon:'file',label:t('Treatment requests','طلبات العلاج'),detail:t('Review and care records','سجلات المراجعة والتنفيذ'),value:data.requests.length,question:t('All treatment requests','جميع الطلبات'),tone:'purple'},{icon:'lab',label:t('Lab results','نتائج التحاليل'),detail:t('Recorded laboratory results','نتائج مخبرية مسجلة'),value:data.labs.length,question:t('All lab results','كل التحاليل'),tone:'rose'},{icon:'calendar',label:t('Appointments','المواعيد'),detail:t('Scheduled and previous visits','الزيارات المجدولة والسابقة'),value:data.appointments.length,question:t('All appointments','كل المواعيد'),tone:'blue'},{icon:'care-plan',label:t('Care plans','خطط الرعاية'),detail:t('Linked patient care plans','خطط مرتبطة بملفات المرضى'),value:data.integratedCarePlans?.length??0,question:t('All care plans in the programme','كل خطط الرعاية في البرنامج'),tone:'amber'}]
 const reviewCount=data.requests.filter(r=>r.status==='Under review').length,abnormal=data.labs.filter(l=>l.status==='Abnormal').length,today=new Date().toISOString().slice(0,10),todayCount=data.appointments.filter(a=>a.date===today&&!['Cancelled','No show'].includes(a.status)).length
 useEffect(()=>()=>controllerRef.current?.abort(),[])
 useEffect(()=>{if(messages.length||pending)listRef.current?.scrollTo({top:listRef.current.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})},[messages,pending])
 const ask=async(question:string)=>{
  const value=question.trim();if(!value||pending)return
  setNotice('');setDraft('');setPending(value);setShowExample(false)
  const controller=new AbortController();controllerRef.current=controller
  try{await readMockWorkspace('assistant',controller.signal);if(!controller.signal.aborted)setMessages(current=>[...(current.length?current:showExample&&previewPatient?[example]:[]),{id:Date.now(),question:value,at:new Date().toISOString()}])}
  catch(error){if(!(error instanceof DOMException&&error.name==='AbortError')){setDraft(value);setNotice(t('Could not read the records. Your question is saved; please try again.','تعذر قراءة السجلات. سؤالك محفوظ، حاول مرة أخرى.'))}}
  finally{if(!controller.signal.aborted)setPending(null)}inputRef.current?.focus()
 }
 const reset=()=>{controllerRef.current?.abort();setPending(null);setMessages([]);setShowExample(false);setDraft('');setNotice('');inputRef.current?.focus()}
 const submit=(e:FormEvent)=>{e.preventDefault();void ask(draft)}
 const keyDown=(e:KeyboardEvent<HTMLTextAreaElement>)=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask(draft)}}
 const exportChat=()=>{const text=turns.map(({message,answer})=>`${message.question}\n${answer.title}\n${answer.body}\n${answer.facts.join('\n')}\n${answer.records?.map(r=>`${r.id} ${r.title}\n${r.values.map(v=>`${v.label}: ${v.value}`).join('\n')}`).join('\n')??''}`).join('\n\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='care-assistant-conversation.txt';a.click();URL.revokeObjectURL(url)}
 return <div className="data-assistant" dir={arabic?'rtl':'ltr'}>
  <div className="da-main">
   <header className="da-hero"><div className="da-hero-art" aria-hidden="true"><span className="da-orbit-ring"/><span className="da-orbit-ring second"/><img src={robot} alt=""/>{[{icon:'patients',en:'Patients',ar:'المرضى'},{icon:'calendar',en:'Appointments',ar:'المواعيد'},{icon:'care-plan',en:'Care plans',ar:'خطط الرعاية'},{icon:'file',en:'Treatment requests',ar:'طلبات العلاج'},{icon:'lab',en:'Lab results',ar:'التحاليل'},{icon:'box',en:'Inventory',ar:'المخزون'}].map((item,i)=><span className={`da-orbit-chip chip-${i}`} key={item.icon}><CareIcon name={item.icon}/>{t(item.en,item.ar)}</span>)}</div><h1>{t('Welcome to your intelligent assistant','مرحباً بك في المساعد الذكي')}</h1><p>{t('Explore patient records, treatment requests, appointments and care plans. Connected answers from your healthcare programme.','مساعدك الذكي لتحليل بيانات المرضى وطلبات العلاج والمواعيد وخطط الرعاية، بناءً على بيانات برنامج الرعاية الصحية.')}</p><div className="da-connected"><i/>{t('Connected to programme records','متصل ببيانات البرنامج')}<span/><CareIcon name="reset"/>{t('Updated with your workspace','يتحدث مع مساحة العمل')}</div></header>
   <nav className="da-topics" aria-label={t('Suggested topics','مواضيع مقترحة')}>{topics.map(topic=><button disabled={!!pending} key={topic.icon} onClick={()=>void ask(topic.question)}><CareIcon name={topic.icon}/>{topic.label}</button>)}</nav>
   <section className={`da-chat ${compact?'da-compact':''}`} aria-label={t('Care assistant chat','محادثة مساعد الرعاية')}>
    <div className="da-chat-toolbar"><span><i/>{t('Your conversation','محادثتك')}{turns.at(-1)?.answer.context.patientId&&<b dir="ltr">{turns.at(-1)?.answer.context.patientId}</b>}</span><div><button onClick={reset} title={t('New conversation','محادثة جديدة')} aria-label={t('New conversation','محادثة جديدة')}><CareIcon name="plus"/></button><button onClick={exportChat} disabled={!turns.length} title={t('Download conversation','تنزيل المحادثة')} aria-label={t('Download conversation','تنزيل المحادثة')}><CareIcon name="download"/></button></div></div>
    <div className="da-conversation" ref={listRef} role="log" aria-label={t('Conversation','المحادثة')} aria-live="polite" aria-relevant="additions">
     {!turns.length&&!pending&&<div className="da-empty"><CareIcon name="bot"/><h2>{t('One question. A connected view.','سؤال واحد، ورؤية متكاملة.')}</h2><p>{t('Start with a name, record ID or a topic above. Follow-up questions keep the patient context.','ابدأ باسم أو رقم سجل أو اختر موضوعاً بالأعلى. أسئلة المتابعة تحتفظ بسياق المريض.')}</p></div>}
     {turns.map(({message,answer})=><div className="da-turn" key={message.id}><div className="da-user"><span><CareIcon name="user"/></span><p dir="auto">{message.question}</p></div><AssistantResponse answer={answer} arabic={arabic} role={role} onNavigate={onNavigate} onAsk={ask} pending={!!pending}/></div>)}
     {pending&&<div className="da-pending"><div className="da-user"><span><CareIcon name="user"/></span><p dir="auto">{pending}</p></div><p role="status">{t('Searching connected records…','جارٍ البحث في السجلات المرتبطة…')}</p><Skeleton kind="assistant" arabic={arabic}/><button className="da-text-button" onClick={()=>{controllerRef.current?.abort();setDraft(pending);setPending(null)}}>{t('Stop','إيقاف')}</button></div>}
    </div>
    {showOptions&&<div className="da-options"><label><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/>{t('Compact answers','ردود مختصرة')}</label><span>{t('Search uses the records available to your role.','البحث في السجلات المتاحة لصلاحياتك.')}</span></div>}
    <form className="da-composer" onSubmit={submit}><button className="da-send" type="submit" disabled={!draft.trim()||!!pending} aria-label={t('Send question','إرسال السؤال')}><CareIcon name="send"/></button><label className="sr-only" htmlFor="da-question">{t('Your question','سؤالك')}</label><textarea id="da-question" ref={inputRef} rows={1} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={keyDown} placeholder={t('Ask about a patient, treatment request, visit or lab result…','اكتب سؤالك هنا عن أي مريض أو طلب علاج أو موعد أو تحليل…')} maxLength={2000}/><button type="button" aria-expanded={showOptions} aria-label={t('Answer options','خيارات الرد')} title={t('Answer options','خيارات الرد')} onClick={()=>setShowOptions(!showOptions)}><CareIcon name="filter"/></button><button type="button" aria-label={t('Import question from a text file','استيراد سؤال من ملف نصي')} title={t('Import question (.txt)','استيراد سؤال (.txt)')} onClick={()=>uploadRef.current?.click()}><CareIcon name="upload"/></button><input ref={uploadRef} type="file" hidden accept=".txt,text/plain" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>20000)setNotice(t('Choose a text file smaller than 20 KB.','اختر ملفاً نصياً أصغر من 20 كيلوبايت.'));else{setDraft((await f.text()).slice(0,2000));inputRef.current?.focus()}}e.target.value=''}}/></form>
    <p className="da-footnote">{t('Answers use available programme records. Clinical decisions remain with your care team.','الإجابات من سجلات البرنامج المتاحة. القرار الطبي يبقى لفريق الرعاية.')}</p>{notice&&<p className="da-notice" role="status">{notice}</p>}
   </section>
  </div>
  <aside className="da-side">
   {onCreateRequest&&<button className="da-primary" onClick={onCreateRequest}><CareIcon name="plus"/>{t('New treatment request','طلب علاج جديد')}</button>}
   <section className="da-side-card"><h2>{t('Available programme records','السجلات المتاحة في النظام')}</h2><div className="da-data-list">{counts.map(k=><button key={k.icon} disabled={!!pending} onClick={()=>void ask(k.question)}><span className={`da-icon ${k.tone}`}><CareIcon name={k.icon}/></span><div><span>{k.label}</span><small>{k.detail}</small></div><strong>{k.value}</strong><span className="da-chevron" aria-hidden="true">{arabic?'‹':'›'}</span></button>)}</div></section>
   <section className="da-side-card da-insights"><h2><span className="da-icon green"><CareIcon name="decision"/></span>{t('Smart insights','رؤية ذكية')}</h2>{[{n:reviewCount,text:t('requests awaiting review','طلبات علاج تحتاج مراجعة'),icon:'alert',tone:'amber',q:t('All treatment requests under review','جميع الطلبات قيد المراجعة')},{n:todayCount,text:t('appointments today','مواعيد متابعة اليوم'),icon:'calendar',tone:'blue',q:t('Appointments today','مواعيد اليوم')},{n:abnormal,text:t('abnormal lab results','نتائج تحاليل تحتاج انتباهاً'),icon:'lab',tone:'green',q:t('Abnormal lab results','نتائج التحاليل غير الطبيعية')}].map(i=><button className={`da-insight ${i.tone}`} disabled={!!pending} key={i.icon} onClick={()=>void ask(i.q)}><CareIcon name={i.icon}/><span><strong>{i.n} {i.text}</strong><small>{t('Explore the linked records','استكشف السجلات المرتبطة')}</small></span></button>)}</section>
  </aside>
 </div>
}
function AssistantResponse({answer,arabic,role,onNavigate,onAsk,pending}:{answer:RichDataAnswer;arabic:boolean;role:Role;onNavigate:Props['onNavigate'];onAsk:(q:string)=>void;pending:boolean}){
 const t=(en:string,ar:string)=>arabic?ar:en
 const text=(v:string)=>arabic?localizeArabic(v,catalogue):v
 const [limit,setLimit]=useState(4),[copied,setCopied]=useState(false),[feedback,setFeedback]=useState<boolean|null>(null),[copyError,setCopyError]=useState(false)
 const r=answer.request
 const allowed=(page:AdminPage)=>assistantLinkAllowed(role,page)
 const copy=async()=>{try{await navigator.clipboard.writeText([answer.title,answer.body,...answer.facts,...(answer.records??[]).map(r=>`${r.title} ${r.id}\n${r.values.map(v=>`${v.label}: ${v.value}`).join('\n')}`)].join('\n'));setCopied(true);setCopyError(false)}catch{setCopyError(true)}}
 return <article className={`da-answer ${answer.matched?'':'unmatched'}`}><img className="da-answer-avatar" src={robot} alt=""/><div className="da-answer-inner"><p className="da-answer-intro">{text(answer.body)}</p><div className="da-answer-card">
  {r?<><div className="da-request-summary"><div className="da-request-person"><PatientAvatar patient={answer.patient} arabic={arabic}/><div><b>{arabic?answer.patient?.nameAr??answer.patient?.name:answer.patient?.name}</b><small>{answer.patient?.id} · {answer.patient?.age} {t('years','سنة')}</small></div></div><div><small>{t('Request number','رقم طلب العلاج')}</small><b dir="ltr">{r.id}</b></div><div><small>{t('Medication / dose','الدواء / الجرعة')}</small><b>{text(r.medication??'Mounjaro')} · {text(r.dose)}</b></div><div><small>{t('Submitted','تاريخ الطلب')}</small><b dir="ltr">{(r.createdAt??r.created).slice(0,10)}</b></div><span className={`da-status ${['Rejected','Needs information','Under review'].includes(r.status)?'amber':'green'}`}>{text(r.status)}</span></div><ol className="da-request-steps">{answer.steps?.map(step=><li key={step.label} className={step.state}><span>{step.state==='done'?<CareIcon name="check"/>:<i/>}</span><b>{step.label}</b></li>)}</ol><div className="da-note"><CareIcon name="file"/><div><b>{t('Recorded notes','الملاحظات المسجلة')}</b><p>{text(r.note||r.doctorRationale||r.instructions||t('No notes recorded on this request.','لا توجد ملاحظات مسجلة على هذا الطلب.'))}</p></div></div></>:<><h2>{text(answer.title)}</h2>{answer.records?<><div className="da-result-list">{answer.records.slice(0,limit).map(row=><div className="da-record" key={row.id}><div className="da-record-heading"><div><b>{text(row.title)}</b><small>{text(row.subtitle??row.id)}</small></div>{row.status&&<span className={`da-status ${/Abnormal|Under review|Needs information|Pending|غير طبيعي|قيد المراجعة|معلومات|الانتظار/i.test(row.status)?'amber':/Rejected|Cancelled|مرفوض|ملغي/i.test(row.status)?'rose':'green'}`}>{text(row.status)}</span>}</div><dl>{row.values.map(v=><div key={v.label}><dt>{v.label}</dt><dd dir="auto">{text(v.value)}</dd></div>)}</dl>{row.link&&allowed(row.link.page)&&<button className="da-text-button" onClick={()=>onNavigate(row.link!.page,row.link!.id)}>{row.link.label}<CareIcon name="open"/></button>}</div>)}</div>{!answer.records.length&&<p className="da-no-results">{t('No records match these filters. Try another date or patient.','لا توجد سجلات مطابقة للفلاتر. جرّب تاريخاً أو مريضاً آخر.')}</p>}{answer.records.length>limit&&<button className="da-show-more" onClick={()=>setLimit(limit+8)}>{t(`Show more (${answer.records.length-limit} remaining)`,`عرض المزيد (${answer.records.length-limit} متبقية)`)}</button>}</>:answer.facts.length>0&&<ul className="da-facts">{answer.facts.map((fact,i)=><li key={i}><CareIcon name="file"/><span dir="auto">{text(fact)}</span></li>)}</ul>}</>
  }
  {answer.links.length>0&&<div className="da-sources"><b>{t('Answer sources','مصادر الإجابة')}</b>{answer.links.slice(0,5).map((link,i)=><button key={`${link.id}-${i}`} onClick={()=>onNavigate(link.page,link.id)}><CareIcon name={link.page==='Patients'?'user':'file'}/>{text(link.label)}</button>)}</div>}
 </div><div className="da-response-tools"><button onClick={copy} aria-label={t('Copy answer','نسخ الإجابة')} title={t('Copy answer','نسخ الإجابة')}><CareIcon name={copied?'check':'copy'}/></button><button aria-pressed={feedback===true} onClick={()=>setFeedback(feedback===true?null:true)} title={t('Useful answer','إجابة مفيدة')} aria-label={t('Useful answer','إجابة مفيدة')}><CareIcon name="check"/></button><button aria-pressed={feedback===false} onClick={()=>setFeedback(feedback===false?null:false)} title={t('Needs improvement','تحتاج تحسين')} aria-label={t('Needs improvement','تحتاج تحسين')}><CareIcon name="info"/></button><span role="status">{copyError?t('Copy unavailable in this browser.','النسخ غير متاح في هذا المتصفح.'):feedback!==null?t('Feedback saved for this conversation','تم تسجيل رأيك في المحادثة'):copied?t('Copied','تم النسخ'):''}</span></div><div className="da-followups">{answer.suggestions.map(q=><button key={q} disabled={pending} onClick={()=>onAsk(q)}>{q}<span aria-hidden="true">{arabic?'←':'→'}</span></button>)}</div></div></article>
}
