import { CareIcon } from './CareIcon'
import { PatientAvatar } from './PatientAvatar'
import { useEffect, useRef, useState } from 'react'
import { canReadPatient, saveTreatmentDraft, submitRequest, supportedDoses, treatmentEligibility, type AppData, type RequestPlanInput, type Role } from './domain'

const today = () => new Date().toISOString().slice(0,10)
const after = (date:string,days:number) => new Date(Date.parse(`${date}T12:00:00Z`)+days*86400000).toISOString().slice(0,10)
const clinicalAr:Record<string,string> = {'Mounjaro':'مونجارو','Adult patient (18+)':'العمر 18 سنة فأكثر','BMI at or above 30':'مؤشر كتلة الجسم 30 فأكثر','Relevant diagnosis recorded':'تشخيص مناسب مسجل','HbA1c result available':'نتيجة السكر التراكمي متاحة','Type 2 diabetes':'السكري من النوع الثاني','Weight management':'إدارة الوزن','Active':'نشط','Pending':'قيد الانتظار','Weekly':'أسبوعيًا','Daily':'يوميًا','Every 2 weeks':'كل أسبوعين'}

export function DoctorTreatmentRequest({data,role='Doctor',initialPatientId,arabic,onClose,onComplete}:{data:AppData;role?:Role;initialPatientId:string;arabic:boolean;onClose:()=>void;onComplete:(next:AppData,draft:boolean)=>void}) {
  const patients=data.patients.filter(p=>canReadPatient(data,role,p.id))
  const [patientId,setPatientId]=useState(initialPatientId&&patients.some(p=>p.id===initialPatientId)?initialPatientId:patients[0]?.id??'')
  const [dose,setDose]=useState('5 mg')
  const [details,setDetails]=useState<RequestPlanInput>({frequency:'Weekly',durationDays:84,startDate:today(),endDate:after(today(),83),indication:data.patients.find(p=>p.id===(initialPatientId||patients[0]?.id))?.diagnosis??'',instructions:arabic?'يستخدم وفق تعليمات الطبيب المعالج فقط.':'Use only as prescribed by the treating clinician.',monitoringPlan:arabic?'مراجعة الاستجابة والتحمل والالتزام بالعلاج.':'Review response, tolerance and adherence.',followUpDate:after(today(),28)})
  const [rationale,setRationale]=useState('')
  const [error,setError]=useState('')
  const [saving,setSaving]=useState(false)
  const sheet=useRef<HTMLDivElement>(null)
  const rationaleInput=useRef<HTMLTextAreaElement>(null)
  const errorBox=useRef<HTMLDivElement>(null)
  const t=(en:string,ar:string)=>arabic?ar:en
  const clinical=(value:string)=>arabic?clinicalAr[value]??value:value
  const patient=data.patients.find(p=>p.id===patientId)
  const assessment=treatmentEligibility(data,patientId)
  const previous=assessment.refill.lastDispense
  const medication=data.medications?.[0]
  const plan=data.integratedCarePlans?.find(p=>p.patientId===patientId&&p.status==='Active')
  const update=(patch:Partial<RequestPlanInput>)=>setDetails(current=>({...current,...patch}))
  useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';sheet.current?.focus();return()=>{document.body.style.overflow=old}},[])
  const missingEvidence=[...(!assessment.assessment?[t('Submit a medical assessment in Patient care → Medical assessment.','اعتمد التقييم الطبي من رعاية المريض ← التقييم الطبي.')]:[]),...(!assessment.lab?[t('Record a completed HbA1c result in the patient’s Analysis tab.','سجّل نتيجة مكتملة للسكر التراكمي من تبويب التحاليل في ملف المريض.')]:[])]
  useEffect(()=>{if(error)errorBox.current?.focus()},[error])
  function save(draft:boolean){
    if(!draft){
      if(missingEvidence.length){setError(missingEvidence.join(' '));return}
      if(!assessment.eligible&&rationale.trim().length<8){setError(t('Enter the doctor’s exception rationale (at least 8 characters), then send it to the reviewer.','اكتب مبرر الاستثناء من الطبيب (٨ حروف على الأقل)، ثم أرسل الطلب للمراجع.'));rationaleInput.current?.focus();return}
    }
    setSaving(true);setError('')
    try { onComplete(draft?saveTreatmentDraft(data,role,patientId,dose,details,undefined,{doctorRationale:rationale}):submitRequest(data,role,patientId,dose,details,{doctorRationale:rationale}),draft) }
    catch(err){setError((err as Error).message);setSaving(false)}
  }
  if(!patient)return null
  return <div className="doctor-request-screen" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={sheet} tabIndex={-1} className="doctor-request-sheet" role="dialog" aria-modal="true" aria-label={t('Create treatment request','إنشاء طلب علاج')} dir={arabic?'rtl':'ltr'} lang={arabic?'ar':'en'}>
    <header className="doctor-request-header"><button type="button" className="doctor-back" onClick={onClose} aria-label={t('Close','إغلاق')}><CareIcon name="close"/></button><div><span>{role==='Admin'?t('ADMIN WORKSPACE / MEDICATION REQUEST','بوابة الإدارة / طلب علاج'):t('DOCTOR WORKSPACE / MEDICATION REQUEST','بوابة الطبيب / طلب علاج')}</span><h1>{t('Create treatment request','إنشاء طلب علاج')}</h1><p>{t('Review the patient, prescribe medication, and confirm the system route.','راجع بيانات المريض، وحدد العلاج، ثم تأكد من مسار الطلب.')}</p></div><div className={`request-route-marker ${assessment.eligible?'ready':'review'}`}><span><CareIcon name={assessment.eligible?'check':'alert'}/></span><b>{assessment.eligible?t('Ready for pharmacy','جاهز للصيدلية'):t('Exception review','مراجعة استثنائية')}</b></div></header>
    <div className="doctor-request-select"><label>{t('Patient','المريض')}<select value={patientId} onChange={e=>{setPatientId(e.target.value);setRationale('');setError('');update({indication:data.patients.find(p=>p.id===e.target.value)?.diagnosis??''})}}>{patients.map(p=><option key={p.id} value={p.id}>{arabic?p.nameAr??p.name:p.name} · {p.id}</option>)}</select></label></div>
    <section className="patient-context doctor-request-context"><div><PatientAvatar patient={patient} arabic={arabic}/><span className="context-id">{patient.id}</span><h2>{arabic?patient.nameAr??patient.name:patient.name}</h2><p>{patient.age} {t('years','سنة')} · {patient.residency??t('Patient type missing','فئة المريض غير مسجلة')} · {patient.emirate}</p></div><dl><div><dt>{t('Responsible doctor','الطبيب المسؤول')}</dt><dd>{patient.assignedDoctor??t('Not assigned','غير معين')}</dd></div><div><dt>{t('Current treatment','العلاج الحالي')}</dt><dd>{clinical(patient.treatmentStatus??'')} · {patient.currentDose??t('No medication','لا يوجد دواء')}</dd></div><div><dt>{t('Last dispensing','آخر صرف')}</dt><dd>{previous?.date??t('No dispensing recorded','لا يوجد صرف مسجل')}</dd></div><div><dt>{t('Latest follow-up','آخر متابعة')}</dt><dd>{patient.lastFollowup??t('Not recorded','غير مسجلة')}</dd></div><div><dt>{t('Medical eligibility','الأهلية الطبية')}</dt><dd>{assessment.eligible?t('Criteria and monthly timing met','المعايير وموعد الصرف مستوفيان'):assessment.refill.eligible?t('Evidence needs review','الأدلة تحتاج مراجعة'):`${t('Next regular dispensing','الصرف المعتاد القادم')} ${assessment.refill.nextEligibleDate}`}</dd></div><div><dt>{t('Care stage','مرحلة الرعاية')}</dt><dd>{plan?t('Integrated care active','خطة الرعاية المتكاملة نشطة'):patient.treatmentStatus==='Active'?t('Medication follow-up','متابعة العلاج'):t('Clinical assessment','تقييم سريري')}</dd></div></dl></section>
    <div className="doctor-request-columns"><section className="doctor-prescription"><div className="request-section-heading"><span><CareIcon name="Treatment requests"/></span><div><h2>{t('Medication prescription','وصفة العلاج')}</h2><p>{t('Set the dose and plan for pharmacy verification.','حدد الجرعة والخطة التي ستراجعها الصيدلية.')}</p></div></div><div className="doctor-request-fields"><label>{t('Medication','الدواء')}<input readOnly value={clinical(medication?.name??'')}/></label><label>{t('Dose','الجرعة')}<select value={dose} onChange={e=>setDose(e.target.value)}>{supportedDoses.map(d=><option key={d}>{d}</option>)}</select></label><label>{t('Frequency','التكرار')}<select value={details.frequency} onChange={e=>update({frequency:e.target.value})}>{['Weekly','Daily','Every 2 weeks'].map(v=><option key={v} value={v}>{clinical(v)}</option>)}</select></label><label>{t('Duration (days)','المدة (بالأيام)')}<input type="number" min={28} max={365} value={details.durationDays} onChange={e=>{const duration=Number(e.target.value);update({durationDays:duration,endDate:duration>0?after(details.startDate,duration-1):''})}}/></label><label>{t('Start date','تاريخ البدء')}<input type="date" value={details.startDate} onChange={e=>update({startDate:e.target.value,endDate:after(e.target.value,details.durationDays-1)})}/></label><label>{t('End date','تاريخ الانتهاء')}<input type="date" value={details.endDate} onChange={e=>update({endDate:e.target.value})}/></label><label>{t('Follow-up date','تاريخ المتابعة')}<input type="date" value={details.followUpDate} onChange={e=>update({followUpDate:e.target.value})}/></label><label>{t('Indication','سبب العلاج')}<input value={clinical(details.indication)} onChange={e=>update({indication:e.target.value})}/></label><label className="wide">{t('Instructions','تعليمات الاستخدام')}<textarea rows={3} value={details.instructions} onChange={e=>update({instructions:e.target.value})}/></label><label className="wide">{t('Monitoring plan','خطة المتابعة')}<textarea rows={3} value={details.monitoringPlan} onChange={e=>update({monitoringPlan:e.target.value})}/></label></div></section>
    <aside className="doctor-decision"><div className="request-section-heading"><span><CareIcon name="Decision support"/></span><div><h2>{t('System eligibility','أهلية النظام')}</h2><p>{t('Clinical evidence and monthly dispensing rule.','الأدلة السريرية وقاعدة الصرف الشهري.')}</p></div></div><div className={`doctor-decision-banner ${assessment.eligible?'ready':'review'}`}><b>{assessment.eligible?t('Criteria met — send directly to pharmacy','المعايير مستوفاة — يُرسل للصيدلية'):!assessment.assessment||!assessment.lab?t('Complete clinical evidence first','أكمل الأدلة السريرية أولًا'):t('Exception approval needed','تتطلب الحالة موافقة استثنائية')}</b><p>{assessment.eligible?t('The prescription will enter the pharmacy verification queue.','ستدخل الوصفة قائمة تحقق الصيدلية.'):!assessment.assessment||!assessment.lab?t('A submitted assessment and HbA1c result are required before proceeding.','يجب تسجيل التقييم ونتيجة السكر التراكمي قبل المتابعة.'):t('Record your clinical rationale for independent review before pharmacy release.','سجل مبررك السريري للمراجعة المستقلة قبل إرسال الطلب للصيدلية.')}</p></div><div className="doctor-evidence-grid">{assessment.clinical.criteria.map(item=><div className={item.passed?'pass':'fail'} key={item.label}><span><CareIcon name={item.passed?'check':'alert'}/></span><div><b>{clinical(item.label)}</b><small>{arabic?item.evidence.replace(' years',' سنة').replace('Type 2 diabetes','السكري من النوع الثاني'):item.evidence}</small></div></div>)}<div className={assessment.assessment?'pass':'fail'}><span><CareIcon name={assessment.assessment?'check':'alert'}/></span><div><b>{t('Clinical assessment','التقييم السريري')}</b><small>{assessment.assessment?t('Submitted and available','مسجل ومتاح'):t('Submit the assessment before requesting treatment','سجل التقييم قبل طلب العلاج')}</small></div></div><div className={assessment.refill.eligible?'pass':'fail'}><span><CareIcon name={assessment.refill.eligible?'check':'alert'}/></span><div><b>{t('Monthly refill timing','موعد إعادة الصرف الشهري')}</b><small>{previous?`${t('Last dispensed','آخر صرف')} ${previous.date} · ${t('Next regular date','الموعد المعتاد القادم')} ${assessment.refill.nextEligibleDate}`:t('No previous dispensing recorded','لا يوجد صرف سابق مسجل')}</small></div></div></div>
    {!assessment.eligible&&<label className="doctor-exception-note">{t("Doctor's exception rationale",'مبرر الاستثناء من الطبيب')} <span>{t('Required · at least 8 characters','مطلوب · ٨ حروف على الأقل')}</span><textarea ref={rationaleInput} aria-label={t("Doctor’s exception rationale","مبرر الاستثناء من الطبيب")} aria-describedby="exception-rationale-help" rows={5} value={rationale} onChange={e=>{setRationale(e.target.value);setError('')}} placeholder={t('Explain the clinical reason for treatment despite the system finding','اشرح السبب السريري لطلب العلاج رغم نتيجة النظام')}/><small id="exception-rationale-help">{t('The reviewer receives this rationale with the prescription and clinical evidence.','يستلم المراجع هذا المبرر مع الوصفة والأدلة الطبية.')} ({rationale.trim().length}/8)</small></label>}
    <details className="doctor-history"><summary>{t('Previous dispensing history','سجل الصرف السابق')}</summary>{data.dispenses.filter(d=>d.patientId===patientId).sort((a,b)=>b.date.localeCompare(a.date)).map(d=><p key={d.id}>{d.date} · {d.dose} · {d.centre}</p>)}{!previous&&<p>{t('No medication has been dispensed to this patient.','لم يُصرف دواء لهذا المريض.')}</p>}</details></aside></div>
    {error&&<div ref={errorBox} tabIndex={-1} role="alert" className="doctor-request-error">{error}{!assessment.eligible&&rationale.trim().length<8&&<button type="button" className="text-link" onClick={()=>rationaleInput.current?.focus()}>{t("Write exception rationale","كتابة مبرر الاستثناء")}</button>}</div>}
    <footer className="doctor-request-footer"><section><p>{assessment.eligible?t('System eligibility is met. Pharmacy still verifies identity, prescription, stock and safety.','الأهلية مستوفاة. تتحقق الصيدلية من الهوية والوصفة والمخزون والسلامة.'):t('A reviewer must approve a documented exception before pharmacy can dispense.','يجب أن يوافق المراجع على الاستثناء الموثق قبل الصرف.')}</p>{missingEvidence.length>0?<p className="request-submit-hint">{missingEvidence.join(' ')}</p>:!assessment.eligible&&rationale.trim().length<8?<button className="text-link request-submit-hint" type="button" onClick={()=>rationaleInput.current?.focus()}>{t('Before sending: write an exception rationale (8 characters minimum).','قبل الإرسال: اكتب مبرر الاستثناء (٨ حروف على الأقل).')}</button>:null}</section><div><button type="button" className="button quiet" onClick={onClose}>{t('Cancel','إلغاء')}</button><button type="button" className="button quiet" disabled={saving} onClick={()=>save(true)}>{t('Save draft','حفظ مسودة')}</button><button type="button" className="button primary" disabled={saving} onClick={()=>save(false)}>{saving?t('Saving…','جارٍ الحفظ…'):assessment.eligible?t('Send to pharmacy','إرسال للصيدلية'):t('Request exception review','طلب مراجعة استثنائية')}</button></div></footer>
  </div></div>
}
