import { PatientAvatar } from './PatientAvatar'
import { CareIcon } from './CareIcon'
import { useState } from 'react'
import { calculateEligibility, can, refillEligibility, treatmentEligibility, type AppData, type Role, type TreatmentRequest } from './domain'
import './DoctorRequests.css'

type Props={data:AppData;role:Role;arabic:boolean;requests:TreatmentRequest[];selected:string|null;onSelect:(id:string|null)=>void;onNew:()=>void;reason:string;onReason:(value:string)=>void;onAction:(action:'approve'|'information'|'reject',id:string)=>void;onResubmit:(id:string)=>void}
const statuses=['Under review','Approved','Ready to dispense','Rejected','Needs information'] as const
const arStatus:Record<string,string>={'Draft':'مسودة','Under review':'قيد المراجعة','Approved':'معتمد','Ready to dispense':'جاهز للصرف','Dispensed':'تم الصرف','Completed':'مكتمل','Rejected':'مرفوض','Needs information':'يحتاج معلومات','Abnormal':'مرتفع','Normal':'طبيعي','Pending':'معلّق'}
const arTabs:Record<string,string>={Overview:'مراجعة الطلب',Patient:'بيانات المريض',Eligibility:'الأهلية',Labs:'النتائج المخبرية',Assessment:'التقييم الطبي',Plan:'خطة العلاج والدواء',Audit:'السجل والتدقيق'}
const date=(value?:string)=>value?.slice(0,10)??'—'
const name=(person:AppData['patients'][number]|undefined,arabic:boolean)=>person?(arabic?person.nameAr??person.name:person.name):'—'
const format=(value:string,arabic:boolean)=>arabic?arStatus[value]??value:value
const evidenceText=(value:string,arabic:boolean)=>arabic?value.replace('Weight management','إدارة الوزن').replace('Type 2 diabetes','السكري من النوع الثاني'):value
function Pill({value,arabic}:{value:string;arabic:boolean}){return <span className={`dr-pill ${value.toLowerCase().replaceAll(' ','-')}`}>{format(value,arabic)}</span>}
export function DoctorRequests({data,role,arabic,requests,selected,onSelect,onNew,reason,onReason,onAction,onResubmit}:Props){
 const t=(en:string,ar:string)=>arabic?ar:en
 const [query,setQuery]=useState('')
 const [status,setStatus]=useState('All')
 const [eligibility,setEligibility]=useState('All')
 const [priority,setPriority]=useState('All')
 const [sort,setSort]=useState('Newest')
 const [page,setPage]=useState(1)
 const [perPage,setPerPage]=useState(10)
 const [tab,setTab]=useState('Overview')
 const [checked,setChecked]=useState<string[]>([])
 const [decisionError,setDecisionError]=useState('')
 const [reviewChoice,setReviewChoice]=useState<'approve'|'information'|'reject'>('approve')
 const item=requests.find(request=>request.id===selected)
 const text=(row:TreatmentRequest)=>{const person=data.patients.find(p=>p.id===row.patientId);return `${row.id} ${person?.name??''} ${person?.nameAr??''} ${person?.id??''} ${row.medication??''} ${row.dose}`.toLowerCase()}
 const priorityFor=(row:TreatmentRequest)=>row.status==='Under review'?'High':row.status==='Needs information'?'Medium':'Low'
 const filtered=requests.filter(row=>{const met=treatmentEligibility(data,row.patientId).eligible;return text(row).includes(query.toLowerCase())&&(status==='All'||row.status===status)&&(eligibility==='All'||(eligibility==='Met'?met:!met))&&(priority==='All'||priorityFor(row)===priority)}).sort((a,b)=>sort==='Oldest'?(a.createdAt??'').localeCompare(b.createdAt??''):sort==='Priority'?(['High','Medium','Low'].indexOf(priorityFor(a))-['High','Medium','Low'].indexOf(priorityFor(b)))||(b.createdAt??'').localeCompare(a.createdAt??''):(b.createdAt??'').localeCompare(a.createdAt??''))
 const totalPages=Math.max(1,Math.ceil(filtered.length/perPage))
 const currentPage=Math.min(page,totalPages)
 const shown=filtered.slice((currentPage-1)*perPage,currentPage*perPage)
 const choose=(id:string|null)=>{onSelect(id);setTab('Overview');onReason('');setDecisionError('');setReviewChoice('approve')}
 const person=item?data.patients.find(p=>p.id===item.patientId):undefined
 const plan=item?data.treatmentPlans.find(p=>p.id===item.planId):undefined
 const vitals=person?data.vitals.filter(v=>v.patientId===person.id).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt))[0]:undefined
 const labs=person?data.labs.filter(l=>l.patientId===person.id).sort((a,b)=>b.date.localeCompare(a.date)):[]
 const assessment=person?data.assessments.filter(a=>a.patientId===person.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]:undefined
 const clinical=person?calculateEligibility(person,data.labs):undefined
 const refill=person?refillEligibility(data,person.id):undefined
 const history=item?data.audit.filter(a=>a.entityId===item.id||a.patientId===item.patientId).sort((a,b)=>(b.occurredAt??'').localeCompare(a.occurredAt??'')).slice(0,8):[]
 const stepLabels=[t('Registration','التسجيل'),t('Assessment','التقييم'),t('Lab evidence','الأدلة المخبرية'),t('Clinical review','المراجعة السريرية'),t('Dispensing','صرف الأدوية'),t('Ongoing care','الرعاية المستمرة'),t('Follow-up','المتابعة')]
 const stepDone=[Boolean(person),Boolean(assessment),labs.length>0,Boolean(item&&['Approved','Ready to dispense','Dispensed','Completed'].includes(item.status)),Boolean(item&&data.dispenses.some(d=>d.requestId===item.id)),Boolean(person&&data.integratedCarePlans?.some(p=>p.patientId===person.id&&p.status==='Active')),Boolean(person&&data.appointments.some(a=>a.patientId===person.id&&a.status==='Completed'))]
 const activeStep=stepDone.findIndex(done=>!done)
 return <div className="dr-workspace" dir={arabic?'rtl':'ltr'}>{!item?<>
  <header className="dr-heading"><div><h1>{t('Treatment requests','طلبات العلاج')} <CareIcon name="Treatment requests"/></h1><p>{t('View and track treatment requests for patients in your care.','عرض ومتابعة جميع طلبات العلاج الخاصة بمرضى البرنامج المشترك.')}</p></div>{can(role,'request:create')&&<button className="dr-new" onClick={onNew}><CareIcon name="plus"/> {t('New treatment request','طلب علاج جديد')}</button>}</header>
  <div className="dr-stats"><Stat label={t('Total requests','إجمالي الطلبات')} value={requests.length} icon="Treatment requests" tone="total"/><Stat label={t('Ready to dispense','جاهز للصرف')} value={requests.filter(r=>r.status==='Ready to dispense').length} icon="Ready to dispense" tone="ready"/><Stat label={t('Approved','معتمد')} value={requests.filter(r=>r.status==='Approved').length} icon="Approved" tone="approved"/><Stat label={t('Under review','قيد المراجعة')} value={requests.filter(r=>r.status==='Under review').length} icon="Under review" tone="review"/><Stat label={t('Rejected','مرفوض')} value={requests.filter(r=>r.status==='Rejected').length} icon="Rejected" tone="rejected"/><Stat label={t('Needs information','يحتاج معلومات إضافية')} value={requests.filter(r=>r.status==='Needs information').length} icon="Needs information" tone="information"/></div>
  <div className="dr-toolbar"><label className="dr-search"><span><CareIcon name="search"/></span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={t('Search patient, request or medication...','ابحث عن مريض أو رقم طلب أو دواء...')}/></label><label>{t('Status','الحالة')}<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="All">{t('All','الكل')}</option>{['Draft',...statuses,'Dispensed','Completed'].map(s=><option key={s} value={s}>{format(s,arabic)}</option>)}</select></label><label>{t('Eligibility','الأهلية')}<select value={eligibility} onChange={e=>{setEligibility(e.target.value);setPage(1)}}><option value="All">{t('All','الكل')}</option><option value="Met">{t('Meets criteria','يستوفي المعايير')}</option><option value="Review">{t('Needs review','يتطلب المراجعة')}</option></select></label><label>{t('Priority','الأولوية')}<select value={priority} onChange={e=>{setPriority(e.target.value);setPage(1)}}><option value="All">{t('All','الكل')}</option><option value="High">{t('High','عالية')}</option><option value="Medium">{t('Medium','متوسطة')}</option><option value="Low">{t('Low','منخفضة')}</option></select></label><label>{t('Sort','ترتيب')}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="Newest">{t('Newest','الأحدث')}</option><option value="Oldest">{t('Oldest','الأقدم')}</option><option value="Priority">{t('Priority','الأولوية')}</option></select></label><button className="dr-reset" onClick={()=>{setQuery('');setStatus('All');setEligibility('All');setPriority('All');setSort('Newest');setPage(1)}}>{t('Reset','إعادة تعيين')} <CareIcon name="reset"/></button></div>
  <section className="dr-table-card"><div className="dr-table-scroll"><table><thead><tr><th><input type="checkbox" aria-label={t('Select visible','تحديد الظاهر')} checked={shown.length>0&&shown.every(r=>checked.includes(r.id))} onChange={e=>setChecked(e.target.checked?[...new Set([...checked,...shown.map(r=>r.id)])]:checked.filter(id=>!shown.some(r=>r.id===id)))}/></th><th>{t('Patient','المريض')}</th><th>{t('Request ID','رقم الطلب')}</th><th>{t('Medication / strength','الدواء / التركيز')}</th><th>{t('Submitted','تاريخ الإرسال')}</th><th>{t('Eligibility','الأهلية')}</th><th>{t('Status','الحالة')}</th><th>{t('Priority','الأولوية')}</th><th>{t('Action','الإجراء')}</th></tr></thead><tbody>{shown.map(row=>{const p=data.patients.find(person=>person.id===row.patientId);const met=treatmentEligibility(data,row.patientId).eligible;return <tr key={row.id}><td><input type="checkbox" aria-label={`${t('Select','حدد')} ${row.id}`} checked={checked.includes(row.id)} onChange={e=>setChecked(e.target.checked?[...checked,row.id]:checked.filter(id=>id!==row.id))}/></td><td><span className="dr-person"><PatientAvatar patient={p} arabic={arabic}/><span><b>{name(p,arabic)}</b><small>{p?.id} · {p?.emirate}</small></span></span></td><td className="dr-id">{row.id}</td><td>{row.medication??data.treatmentPlans.find(plan=>plan.id===row.planId)?.medication??'—'} · {row.dose}</td><td>{date(row.createdAt)} <small>{row.createdAt?.slice(11,16)}</small></td><td><span className={`dr-elig ${met?'met':'review'}`}>{met?t('Meets criteria','يستوفي المعايير'):t('Needs review','يتطلب المراجعة')}</span></td><td><Pill value={row.status} arabic={arabic}/></td><td><span className={`dr-priority ${priorityFor(row).toLowerCase()}`}>{priorityFor(row)==='High'?t('High','عالية'):priorityFor(row)==='Medium'?t('Medium','متوسطة'):t('Low','منخفضة')}</span></td><td><button className="dr-review" onClick={()=>choose(row.id)}>{t('Review','مراجعة')}</button></td></tr>})}</tbody></table>{filtered.length===0&&<p className="dr-empty">{t('No requests match these filters.','لا توجد طلبات تطابق هذه الفلاتر.')}</p>}</div><footer><span>{t('Showing','عرض')} {shown.length} {t('of','من')} {filtered.length} {t('requests','طلب')}</span><div><button onClick={()=>setPage(Math.max(1,currentPage-1))} disabled={currentPage===1}>‹</button>{Array.from({length:Math.min(5,totalPages)},(_,i)=><button key={i} className={currentPage===i+1?'active':''} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button onClick={()=>setPage(Math.min(totalPages,currentPage+1))} disabled={currentPage===totalPages}>›</button></div><label>{t('Show','عرض')} <select value={perPage} onChange={e=>{setPerPage(Number(e.target.value));setPage(1)}}><option>5</option><option>10</option><option>20</option></select></label></footer></section>
 </>:<>
  <header className="dr-heading dr-detail-heading"><div><h1>{t('Treatment request','طلب العلاج')} <span>{item.id}</span> <Pill value={item.status} arabic={arabic}/></h1><p>{t('Linked patient, clinical evidence and decision history.','ملف مرتبط ببيانات المريض والأدلة السريرية وسجل القرارات.')}</p></div><button className="dr-back" onClick={()=>choose(null)}>← {t('Back to list','العودة إلى القائمة')}</button></header>
  <div className="dr-detail-layout"><div className="dr-detail-main"><div className="dr-summary"><div><small>{t('Treatment plan','خطة العلاج')}</small><b>{plan?.id??item.planId}</b></div><div><small>{t('Submitted','تاريخ الإرسال')}</small><b>{date(item.createdAt)} · {item.createdAt?.slice(11,16)}</b></div><div><small>{t('Medication','الدواء')}</small><b>{item.medication??plan?.medication??'—'} · {item.dose}</b></div><div className="dr-summary-patient"><PatientAvatar patient={person} arabic={arabic}/><span><b>{name(person,arabic)}</b><small>{person?.age} {t('years','عامًا')} · {person?.emirate} · {person?.id}</small></span></div></div>
   <div className="dr-steps">{stepLabels.map((step,i)=><div key={step} className={stepDone[i]?'done':i===activeStep?'current':''}><i>{stepDone[i]?'✓':i+1}</i><b>{step}</b><small>{stepDone[i]?t('Recorded','مسجل'):i===3?format(item.status,arabic):t('Pending','في الانتظار')}</small></div>)}</div>
   <section className="dr-detail-card"><nav className="dr-tabs">{Object.keys(arTabs).map(key=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{arabic?arTabs[key]:key}</button>)}</nav><div className="dr-tab-content">{tab==='Overview'&&<><div className="dr-evidence"><h3>{t('Eligibility review','مراجعة الأهلية')}</h3><p>{clinical?.eligible?t('Recorded clinical criteria are met.','المعايير السريرية المسجلة مستوفاة.'):t('Some recorded criteria require review.','بعض المعايير المسجلة تتطلب المراجعة.')}</p>{clinical?.criteria.map(c=><div key={c.label}><span><CareIcon name={c.passed?'check':'alert'}/></span><b>{c.label}</b><small data-no-localize>{evidenceText(c.evidence,arabic)}</small></div>)}{refill&&!refill.eligible&&<p className="dr-warning">{t('Next eligible refill','موعد الصرف القادم')}: {refill.nextEligibleDate}</p>}</div><div className="dr-evidence"><h3>{t('Latest vitals','أحدث المؤشرات الحيوية')}</h3><div className="dr-vitals">{[[t('Weight','الوزن'),vitals?.weightKg,'kg'],[t('Height','الطول'),vitals?.heightCm,'cm'],['BMI',vitals?.bmi,''],[t('Blood pressure','ضغط الدم'),vitals?`${vitals.systolic}/${vitals.diastolic}`:undefined,''],[t('Pulse','النبض'),vitals?.heartRate,'bpm']].map(([label,value,unit])=><span key={String(label)}><small>{label}</small><b>{value??'—'} {unit}</b></span>)}</div></div><div className="dr-evidence"><h3>{t('Latest laboratory result','أحدث سجل مخبري')}</h3>{labs[0]?<div><b>{labs[0].test}</b><strong>{labs[0].value} {labs[0].unit}</strong><small>{date(labs[0].date)} · {labs[0].reference}</small><Pill value={labs[0].status} arabic={arabic}/></div>:<p>{t('No lab result recorded.','لا توجد نتائج تحاليل مسجلة.')}</p>}</div></>}
   {tab==='Patient'&&<div className="dr-info-grid">{[[t('Name','الاسم'),name(person,arabic)],[t('Patient ID','رقم المريض'),person?.id],[t('Age','العمر'),person?.age],[t('Residency','الإقامة'),person?.residency],[t('Diagnosis','التشخيص'),person?.diagnosis],[t('Assigned doctor','الطبيب'),person?.assignedDoctor]].map(([label,value])=><div key={String(label)}><small>{label}</small><b>{value??'—'}</b></div>)}</div>}
   {tab==='Eligibility'&&<div className="dr-evidence"><h3>{t('Clinical criteria','المعايير السريرية')}</h3>{clinical?.criteria.map(c=><div key={c.label}><span><CareIcon name={c.passed?'check':'alert'}/></span><b>{c.label}</b><small data-no-localize>{evidenceText(c.evidence,arabic)}</small></div>)}<p>{t('Monthly refill','الصرف الشهري')}: {refill?.eligible?t('Eligible','مستوفٍ'):refill?.nextEligibleDate}</p></div>}
   {tab==='Labs'&&<div className="dr-evidence"><h3>{t('Laboratory history','سجل التحاليل')}</h3>{labs.map(l=><div key={l.id}><b>{l.test}</b><strong>{l.value} {l.unit}</strong><small>{l.reference} · {date(l.date)}</small><Pill value={l.status} arabic={arabic}/></div>)}</div>}
   {tab==='Assessment'&&<div className="dr-info-grid">{[[t('Reason','السبب'),assessment?.reason],[t('Diagnosis','التشخيص'),assessment?.diagnosis],[t('Symptoms','الأعراض'),assessment?.symptoms],[t('Medical history','التاريخ الطبي'),assessment?.medicalHistory],[t('Allergies','الحساسية'),assessment?.allergies],[t('Findings','النتائج'),assessment?.findings],[t('Notes','ملاحظات'),assessment?.notes]].map(([label,value])=><div key={String(label)}><small>{label}</small><b>{value??'—'}</b></div>)}</div>}
   {tab==='Plan'&&<div className="dr-info-grid">{[[t('Medication','الدواء'),plan?.medication??item.medication],[t('Dose','الجرعة'),item.dose],[t('Frequency','التكرار'),plan?.frequency??item.frequency],[t('Start date','تاريخ البدء'),date(plan?.startDate??item.startDate)],[t('End date','تاريخ الانتهاء'),date(plan?.endDate??item.endDate)],[t('Follow-up','المتابعة'),date(plan?.followUpDate??item.followUpDate)],[t('Prescription','الوصفة'),item.prescriptionId]].map(([label,value])=><div key={String(label)}><small>{label}</small><b>{value??'—'}</b></div>)}</div>}
   {tab==='Audit'&&<div className="dr-evidence"><h3>{t('Decision history','سجل القرارات')}</h3>{history.map(a=><div key={a.id}><b>{a.action}</b><small>{date(a.occurredAt)} · {a.actor} · {a.reason??a.detail}</small></div>)}</div>}
   </div></section></div><aside className="dr-decision"><h2>{t('Review decision','قرار المراجعة')}</h2>{item.approvalRoute==='Exception review'&&<div className="dr-exception-rationale"><b>{t("Doctor’s exception rationale","مبرر الاستثناء من الطبيب")}</b><p data-no-localize>{item.doctorRationale??t("No rationale recorded","لم يتم تسجيل مبرر")}</p><small>{t("Approval sends this prescription to pharmacy verification.","الموافقة ترسل هذه الوصفة إلى الصيدلية للتحقق والصرف.")}</small></div>}{can(role,'request:review')&&item.status==='Under review'?<><div className="dr-options">{([['approve',t('Approve','معتمد'),t('Clinical criteria recorded','الموافقة على الطلب')],['information',t('Request information','طلب معلومات إضافية'),t('Return to doctor','إرجاع الطلب للطبيب')],['reject',t('Reject','مرفوض'),t('Add a reason','رفض الطلب مع توضيح السبب')]] as const).map(([value,label,hint])=><button key={value} className={reviewChoice===value?'active':''} onClick={()=>setReviewChoice(value)}><i>{reviewChoice===value?'◉':'○'}</i><span><b>{label}</b><small>{hint}</small></span></button>)}</div><label>{t('Review notes','ملاحظات المراجعة')}<textarea value={reason} onChange={e=>{onReason(e.target.value);setDecisionError('')}} placeholder={t('Add your clinical decision...','أضف ملاحظاتك هنا...')}/></label>{(reviewChoice!=='approve'||item.approvalRoute==='Exception review')&&<p>{t('A decision reason of at least 8 characters is required.','مطلوب توضيح سبب القرار في ٨ حروف على الأقل.')}</p>}{decisionError&&<p role="alert" className="dr-warning">{decisionError}</p>}<button className="dr-confirm" onClick={()=>{if((reviewChoice!=='approve'||item.approvalRoute==='Exception review')&&reason.trim().length<8){setDecisionError(t('Write the reviewer’s decision reason (at least 8 characters) before confirming.','اكتب سبب قرار المراجع (٨ حروف على الأقل) قبل التأكيد.'));return}setDecisionError('');onAction(reviewChoice,item.id)}}>{t('Confirm decision','تأكيد القرار')}</button></>:item.status==='Needs information'&&can(role,'request:submit')?<><p>{t('Add the requested evidence and return this request to review.','أضف المعلومات المطلوبة وأعد الطلب للمراجعة.')}</p><textarea value={reason} onChange={e=>onReason(e.target.value)} placeholder={t('Updated evidence summary','ملخص المعلومات الجديدة')}/><button className="dr-confirm" onClick={()=>onResubmit(item.id)}>{t('Resubmit','إعادة الإرسال')}</button></>:<><Pill value={item.status} arabic={arabic}/><p>{item.doctorRationale??item.note??t('The request is linked to the shared record. Authorized reviewers make approval decisions.','الطلب مرتبط بالسجل المشترك. يتخذ المراجع المخوّل قرار الموافقة.')}</p>{item.reviewer&&<small>{t('Reviewer','المراجع')}: {item.reviewer}</small>}</>}<button className="dr-cancel" onClick={()=>choose(null)}>{t('Back to list','العودة إلى القائمة')}</button></aside></div>
 </>}</div>
}
function Stat({label,value,icon,tone}:{label:string;value:number;icon:string;tone:string}){return <div className={`dr-stat ${tone}`}><span><CareIcon name={icon}/></span><div><small>{label}</small><b>{value}</b></div></div>}
