import { PatientAvatar } from './PatientAvatar'
import { useState } from 'react'
import { canReadPatient, type AppData, type Appointment, type AuditEvent, type Patient, type TreatmentRequest } from './domain'
import type { AdminPage } from './adminAnalytics'
import { CareIcon } from './EcosystemViews'
import './DoctorDashboard.css'

type Props={data:AppData;arabic:boolean;onNavigate:(page:AdminPage,id?:string)=>void;onPatient:(id:string)=>void}
const statusColors:Record<string,string>={'Under review':'#65a9fb',Approved:'#23b374','Ready to dispense':'#ffc35b',Dispensed:'#72c0bc',Rejected:'#f78c91','Needs information':'#8198b2',Draft:'#c7b6e9',Completed:'#1e8977'}
const labelAr:Record<string,string>={'Under review':'قيد المراجعة',Approved:'معتمد','Ready to dispense':'جاهز للصرف',Dispensed:'تم الصرف',Rejected:'مرفوض','Needs information':'يحتاج معلومات',Draft:'مسودة',Completed:'مكتمل',Active:'نشط','Review required':'مراجعة مطلوبة','Meets clinical criteria':'نشط','Not eligible':'قيد التقييم'}
const actionAr:Record<string,string>={'Request submitted':'تم إرسال طلب علاج','Request approved':'تم اعتماد طلب علاج','Information requested':'طلب معلومات إضافية','Integrated care plan confirmed':'تم إنشاء خطة رعاية','Lab result recorded':'تم تسجيل نتيجة تحليل','Medication dispensed':'تم صرف الدواء','Appointment scheduled':'تم جدولة موعد','Clinical assessment submitted':'تم اعتماد تقييم سريري','Patient registered':'تم تسجيل مريض','Care pathway updated':'تم تحديث مسار الرعاية'}
const purposeAr:Record<string,string>={'Clinical follow-up':'متابعة سريرية','Diabetes review':'مراجعة السكري','Review lab results':'مراجعة نتائج التحاليل','Care plan follow-up':'متابعة خطة الرعاية','Initial consultation':'استشارة أولية','Diabetes follow-up':'متابعة السكري','Initial clinical assessment':'تقييم سريري أولي','Treatment review':'مراجعة العلاج'}
const statuses=['Under review','Approved','Ready to dispense','Dispensed','Rejected','Needs information','Draft','Completed'] as const
const dateOnly=(value:string)=>value.slice(0,10)
const isoDay=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const monthKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`
const percent=(now:number,before:number)=>before>0?`${now>=before?'+':''}${Math.round((now-before)/before*100)}%`:''
const status=(value:string,ar:boolean)=>ar?labelAr[value]??value:value

export function DoctorDashboard({data,arabic,onNavigate,onPatient}:Props){
 const t=(en:string,ar:string)=>arabic?ar:en
 const doctor=data.doctors.find(item=>item.id===(data.activeDoctorId??data.doctors[0]?.id))??data.doctors[0]
 const [clinic,setClinic]=useState('all')
 const [selectedDate,setSelectedDate]=useState(()=>new Date().toISOString().slice(0,10))
 const [monthsCount,setMonthsCount]=useState(6)
 const today=new Date(`${selectedDate}T12:00:00`)
 const patients=data.patients.filter(patient=>canReadPatient(data,'Doctor',patient.id)&& (clinic==='all'||patient.treatmentCentre===clinic))
 const patientIds=new Set(patients.map(patient=>patient.id))
 const requests=data.requests.filter(item=>patientIds.has(item.patientId))
 const plans=(data.integratedCarePlans??[]).filter(item=>patientIds.has(item.patientId))
 const appointments=data.appointments.filter(item=>item.doctor===doctor?.name&&patientIds.has(item.patientId))
 const todayAppointments=appointments.filter(item=>item.date===selectedDate&&item.status!=='Cancelled').sort((a,b)=>a.time.localeCompare(b.time))
 const previousDay=isoDay(new Date(today.getTime()-86400000))
 const previousAppointments=appointments.filter(item=>item.date===previousDay&&item.status!=='Cancelled').length
 const activePlans=plans.filter(item=>item.status==='Active')
 const activePatients=patients.filter(item=>item.isActive!==false)
 const monthStart=`${selectedDate.slice(0,7)}-01`
 const previousMonthEnd=isoDay(new Date(today.getFullYear(),today.getMonth(),0))
 const priorPlans=plans.filter(item=>item.createdAt.slice(0,10)<=previousMonthEnd&&item.status==='Active').length
 const priorRequests=requests.filter(item=>dateOnly(item.createdAt??'')<=previousMonthEnd).length
 const priorPatients=activePatients.filter(item=>item.registeredAt&&item.registeredAt<monthStart).length
 const eventList=data.audit.filter(item=>item.patientId?patientIds.has(item.patientId):item.actor==='Doctor').sort((a,b)=>(b.occurredAt??'').localeCompare(a.occurredAt??'')).slice(0,4)
 const monthData=Array.from({length:monthsCount},(_,index)=>{const date=new Date(today.getFullYear(),today.getMonth()-(monthsCount-index),1);const key=monthKey(date);return {key,label:new Intl.DateTimeFormat(arabic?'ar-EG':'en-GB',{month:'short'}).format(date),count:patients.filter(item=>item.registeredAt?.startsWith(key)).length}})
 const maxMonth=Math.max(1,...monthData.map(item=>item.count))
 const statusRows=statuses.map(value=>({value,count:requests.filter(request=>request.status===value).length,color:statusColors[value]})).filter(row=>row.count>0)
 let at=0
 const gradient=statusRows.length?`conic-gradient(${statusRows.map(row=>{const start=at;at+=row.count/requests.length*360;return `${row.color} ${start}deg ${at}deg`}).join(',')})`:'#e9eef2'
 const patientList=[...patients].sort((a,b)=>(b.lastFollowup??'').localeCompare(a.lastFollowup??'')).slice(0,5)
 const taskRequests=requests.filter(item=>['Needs information','Under review','Ready to dispense'].includes(item.status)).sort((a,b)=>(b.createdAt??'').localeCompare(a.createdAt??''))
 const taskLabs=data.labs.filter(lab=>patientIds.has(lab.patientId)&&lab.status==='Abnormal').sort((a,b)=>b.date.localeCompare(a.date)).slice(0,2)
 const tasks=[...taskRequests.map(request=>({id:request.id,patientId:request.patientId,kind:request.status==='Needs information'?'information':request.status==='Ready to dispense'?'dispensing':'request',title:request.status==='Needs information'?t('Add missing information','إضافة معلومات إضافية'):request.status==='Ready to dispense'?t('Check pharmacy handoff','متابعة الصرف'):t('Review treatment request','مراجعة طلب علاج'),date:request.createdAt??'',page:'Treatment requests' as AdminPage})),...taskLabs.map(lab=>({id:lab.id,patientId:lab.patientId,kind:'lab',title:t('Review abnormal lab','مراجعة نتيجة تحليل'),date:lab.date,page:'Patients' as AdminPage}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5)
 const latestRequests=[...requests].sort((a,b)=>(b.createdAt??'').localeCompare(a.createdAt??'')).slice(0,5)
 const clinics=[...new Set(patients.map(item=>item.treatmentCentre).filter((value):value is string=>Boolean(value)))]
 const docName=doctor?.name??t('Doctor','الطبيب')
 const shortDoctor=arabic?docName.replace('Dr. Laila Hassan','د. ليلى حسن').replace('Dr. Omar Khalid','د. عمر خالد'):docName
 return <div className="doctor-dashboard" dir={arabic?'rtl':'ltr'}>
  <header className="dd-welcome"><div><h1>{t(`Good morning, ${docName}`,`صباح الخير، ${shortDoctor}`)} <span aria-hidden="true">👋</span></h1><p>{t('A quick view of your patients, treatment requests and tasks for today.','إليك نظرة عامة على مرضاك وطلبات العلاج والمهام اليوم.')}</p></div><div className="dd-filters"><label><span>{t('Clinic','العيادة')}</span><select value={clinic} onChange={event=>setClinic(event.target.value)}><option value="all">{t('All clinics','جميع العيادات')}</option>{clinics.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label><span>{t('Date','التاريخ')}</span><input type="date" value={selectedDate} onChange={event=>setSelectedDate(event.target.value)}/></label></div></header>
  <div className="dd-kpis"><Kpi label={t('Appointments today','المواعيد اليوم')} value={todayAppointments.length} compare={percent(todayAppointments.length,previousAppointments)} note={t('compared with yesterday','مقارنة بالأمس')} tone="amber" icon="Appointments" onClick={()=>onNavigate('Appointments')}/><Kpi label={t('Active care plans','خطط الرعاية النشطة')} value={activePlans.length} compare={percent(activePlans.length,priorPlans)} note={t('compared with last month','مقارنة بالشهر السابق')} tone="violet" icon="Care plan" onClick={()=>onNavigate('Integrated care plans')}/><Kpi label={t('Treatment requests','طلبات العلاج')} value={requests.length} compare={percent(requests.length,priorRequests)} note={t('compared with last month','مقارنة بالشهر السابق')} tone="blue" icon="Treatment requests" onClick={()=>onNavigate('Treatment requests')}/><Kpi label={t('Active patients','المرضى النشطون')} value={activePatients.length} compare={percent(activePatients.length,priorPatients)} note={t('compared with last month','مقارنة بالشهر السابق')} tone="green" icon="Patients" onClick={()=>onNavigate('Patients')}/></div>
  <div className="dd-three"><section className="dd-card dd-chart"><div className="dd-card-head"><h2>{t('New patients','عدد المرضى الجدد')}</h2><select aria-label={t('Chart range','فترة الرسم')} value={monthsCount} onChange={event=>setMonthsCount(Number(event.target.value))}><option value={6}>{t('Last 6 months','آخر 6 أشهر')}</option><option value={3}>{t('Last 3 months','آخر 3 أشهر')}</option><option value={12}>{t('Last 12 months','آخر 12 شهرًا')}</option></select></div><div className="dd-bars"><div className="dd-axis"><span>{maxMonth}</span><span>{Math.round(maxMonth/2)}</span><span>0</span></div><div className="dd-bar-list">{monthData.map(item=><div className="dd-bar-item" key={item.key}><b>{item.count}</b><div className="dd-bar-track"><span style={{height:`${Math.max(3,item.count/maxMonth*100)}%`}}/></div><small>{item.label}</small></div>)}</div></div></section>
  <section className="dd-card dd-activity"><div className="dd-card-head"><h2>{t('Recent activity','أحدث الأنشطة')}</h2><button onClick={()=>onNavigate('Activity log')}>{t('View all','عرض الكل')}</button></div><div className="dd-list">{eventList.map(event=><EventRow key={event.id} event={event} arabic={arabic} patient={data.patients.find(item=>item.id===event.patientId)} onClick={()=>event.patientId?onPatient(event.patientId):onNavigate('Activity log')}/>)}{!eventList.length&&<Empty arabic={arabic}/>}</div></section>
  <section className="dd-card dd-status"><div className="dd-card-head"><h2>{t('Treatment request status','حالات طلبات العلاج')}</h2></div><div className="dd-status-body"><div className="dd-status-list">{statusRows.map(row=><div key={row.value}><i style={{background:row.color}}/><span>{status(row.value,arabic)}</span><b>{row.count}</b></div>)}</div><div className="dd-donut" style={{background:gradient}}><div><b>{requests.length}</b><span>{t('requests','طلب علاج')}</span></div></div></div></section></div>
  <div className="dd-three dd-lower"><section className="dd-card"><div className="dd-card-head"><h2>{t('Tasks requiring your attention','المهام المطلوبة منك')} <span className="dd-count">{tasks.length}</span></h2><button onClick={()=>onNavigate('Treatment requests')}>{t('View all','عرض الكل')}</button></div><div className="dd-list">{tasks.map(task=>{const person=data.patients.find(item=>item.id===task.patientId);return <button className="dd-task-row" key={task.id} onClick={()=>task.page==='Patients'?onPatient(task.patientId):onNavigate(task.page,task.id)}><span className={`dd-row-icon ${task.kind}`}><CareIcon name={task.kind==='lab'?'Analysis':task.kind==='information'?'Needs information':task.kind==='dispensing'?'Dispensing':'Treatment requests'}/></span><span className="dd-row-copy"><b>{task.title}</b><small>{person?(arabic?person.nameAr??person.name:person.name):task.patientId} · {task.id}</small></span><time>{dateOnly(task.date)||'—'}</time></button>})}{!tasks.length&&<Empty arabic={arabic}/>}</div></section>
  <section className="dd-card"><div className="dd-card-head"><h2>{t('Patients under your care','المرضى تحت رعايتك')}</h2><button onClick={()=>onNavigate('Patients')}>{t('View all','عرض الكل')}</button></div><div className="dd-list">{patientList.map(person=><button className="dd-patient-row" key={person.id} onClick={()=>onPatient(person.id)}><Avatar person={person} arabic={arabic}/><span className="dd-row-copy"><b>{arabic?person.nameAr??person.name:person.name}</b><small>{person.id}</small></span><span className={`dd-pill ${person.eligibility==='Review required'?'warning':'good'}`}>{status(person.eligibility??'Active',arabic)}</span><time>{t('Last visit','آخر زيارة')}: {person.lastFollowup??'—'}</time></button>)}</div></section>
  <section className="dd-card"><div className="dd-card-head"><h2>{t('Upcoming appointments','المواعيد القادمة اليوم')}</h2><button onClick={()=>onNavigate('Appointments')}>{t('View all','عرض الكل')}</button></div><div className="dd-list">{todayAppointments.slice(0,5).map(appointment=><AppointmentRow key={appointment.id} item={appointment} patient={data.patients.find(item=>item.id===appointment.patientId)} arabic={arabic} onClick={()=>onPatient(appointment.patientId)}/>)}{!todayAppointments.length&&<Empty arabic={arabic} text={t('No appointments on this date. Choose another date.','لا توجد مواعيد في هذا اليوم. اختر تاريخًا آخر.')}/>}</div></section></div>
  <section className="dd-card dd-table-card"><div className="dd-card-head"><h2>{t('Latest treatment requests','أحدث طلبات العلاج')}</h2><button onClick={()=>onNavigate('Treatment requests')}>{t('View all','عرض الكل')}</button></div><div className="dd-table-wrap"><table><thead><tr><th>{t('Request ID','رقم الطلب')}</th><th>{t('Patient','المريض')}</th><th>{t('Medication','الدواء')}</th><th>{t('Dose','الجرعة')}</th><th>{t('Submitted','تاريخ الإرسال')}</th><th>{t('Status','الحالة')}</th><th>{t('Action','الإجراء')}</th></tr></thead><tbody>{latestRequests.map(request=><RequestRow key={request.id} request={request} patient={data.patients.find(item=>item.id===request.patientId)} plan={data.treatmentPlans.find(item=>item.id===request.planId)} arabic={arabic} onClick={()=>onNavigate('Treatment requests',request.id)}/>)}</tbody></table>{!latestRequests.length&&<Empty arabic={arabic}/>}</div></section>
 </div>
}
function Kpi({label,value,compare,note,tone,icon,onClick}:{label:string;value:number;compare:string;note:string;tone:string;icon:string;onClick:()=>void}){return <button className={`dd-kpi ${tone}`} onClick={onClick}><span className="dd-kpi-icon"><CareIcon name={icon}/></span><span className="dd-kpi-copy"><b>{label}</b><strong>{value}</strong><small>{compare?<><em>{compare}</em> {note}</>:'—'}</small></span></button>}
function Avatar({person,arabic}:{person:Patient;arabic:boolean}){return <PatientAvatar patient={person} className="dd-avatar" arabic={arabic}/>}
function Empty({arabic,text}:{arabic:boolean;text?:string}){return <p className="dd-empty">{text??(arabic?'لا توجد سجلات في هذا العرض.':'No records in this view.')}</p>}
function EventRow({event,patient,arabic,onClick}:{event:AuditEvent;patient?:Patient;arabic:boolean;onClick:()=>void}){return <button className="dd-event-row" onClick={onClick}><span className="dd-row-icon"><CareIcon name={event.entity}/></span><span className="dd-row-copy"><b>{arabic?actionAr[event.action]??event.action:event.action}</b><small>{patient?(arabic?patient.nameAr??patient.name:patient.name):event.entityId} · {event.entityId}</small></span><time>{event.time}</time></button>}
function AppointmentRow({item,patient,arabic,onClick}:{item:Appointment;patient?:Patient;arabic:boolean;onClick:()=>void}){return <button className="dd-appointment-row" onClick={onClick}>{patient&&<Avatar person={patient} arabic={arabic}/>}<span className="dd-row-copy"><b>{patient?(arabic?patient.nameAr??patient.name:patient.name):item.patientId}</b><small>{arabic?purposeAr[item.purpose]??item.purpose:item.purpose}</small></span><time>{item.time}</time></button>}
function RequestRow({request,patient,plan,arabic,onClick}:{request:TreatmentRequest;patient?:Patient;plan?:AppData['treatmentPlans'][number];arabic:boolean;onClick:()=>void}){return <tr><td>{request.id}</td><td><span className="dd-table-patient">{patient&&<Avatar person={patient} arabic={arabic}/>}<span>{patient?(arabic?patient.nameAr??patient.name:patient.name):request.patientId}<small>{request.patientId}</small></span></span></td><td>{plan?.medication??request.medication??'—'}</td><td>{request.dose}</td><td>{request.createdAt?.slice(0,10)??'—'}</td><td><span className={`dd-request-status ${request.status.toLowerCase().replaceAll(' ','-')}`}>{status(request.status,arabic)}</span></td><td><button onClick={onClick}>{arabic?'عرض':'View'}</button></td></tr>}
