import { useEffect, useState, type ChangeEvent, type FormEvent } from 'react'
import { registerPatientWithIntake, type AppData, type PatientIntake, type PatientType, type Role, type LabResult } from './domain'
import './PatientRegistration.css'

type LabDraft = { test:string; value:string; unit:string; reference:string; status:LabResult['status']; date:string; source:string; interpretation:string }
type Uploaded = { title:string; content:string; fileName:string; mimeType:string; dataUrl:string; sizeBytes:number }
const acceptedTypes = new Set(['application/pdf','image/jpeg','image/png','image/webp','text/plain','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])
const splitList = (value:string) => value.split(/\n|[,،;]/).map(item=>item.trim()).filter(Boolean)
const readFile = (file:File) => new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error(`Could not read ${file.name}.`));reader.readAsDataURL(file)})

export function RegistrationForm({data,role,arabic,onUpdate,onClose,onCreated}:{data:AppData;role:Role;arabic:boolean;onUpdate:(data:AppData)=>void;onClose:()=>void;onCreated:(id:string)=>void}) {
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};document.addEventListener('keydown',escape);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',escape)}},[onClose])
  const t=(en:string,ar:string)=>arabic?ar:en
  const doctors=data.doctors.filter(item=>item.status==='Active'&&(role==='Admin'||item.id==='DOC-001'))
  const centres=data.centres.filter(item=>item.status==='Active')
  const [patient,setPatient]=useState({name:'',nameAr:'',age:'',sex:'Female',residency:'Resident' as PatientType,nationality:'',emiratesId:'',centreId:centres[0]?.id??'',doctorId:doctors[0]?.id??'',diagnosis:'',fastingGlucose:'',previousIllnesses:'',chronicConditions:''})
  const [vitals,setVitals]=useState({weightKg:'',heightCm:'',systolic:'',diastolic:'',heartRate:''})
  const [clinical,setClinical]=useState({reason:'',symptoms:'',medicalHistory:'',medications:'',allergies:'',findings:'',notes:'',status:'Draft' as 'Draft'|'Submitted'})
  const [labs,setLabs]=useState<LabDraft[]>([])
  const [procedures,setProcedures]=useState<{name:string;date:string;note:string}[]>([])
  const [appointment,setAppointment]=useState({date:'',time:'09:00',purpose:'',notes:''})
  const [files,setFiles]=useState<Uploaded[]>([])
  const [error,setError]=useState('')
  const [busy,setBusy]=useState(false)
  const centre=centres.find(item=>item.id===patient.centreId)
  const [today]=useState(()=>new Date().toISOString().slice(0,10))
  const field=(key:keyof typeof patient,label:string,required=false,type='text')=><label>{label}{required&&' *'}<input type={type} required={required} value={patient[key]} onChange={event=>setPatient({...patient,[key]:event.target.value})}/></label>
  const vitalField=(key:keyof typeof vitals,label:string)=><label>{label}<input type="number" min="0" step="any" value={vitals[key]} onChange={event=>setVitals({...vitals,[key]:event.target.value})}/></label>
  async function upload(event:ChangeEvent<HTMLInputElement>){
    const selected=Array.from(event.target.files??[])
    if (!selected.length)return
    setError('')
    const total=files.reduce((sum,file)=>sum+file.sizeBytes,0)+selected.reduce((sum,file)=>sum+file.size,0)
    if (selected.some(file=>!acceptedTypes.has(file.type)||file.size>750_000)||total>1_500_000){setError(t('Use PDF, JPG, PNG, WebP, TXT or DOCX; 750 KB per file and 1.5 MB total.','استخدم PDF أو JPG أو PNG أو WebP أو TXT أو DOCX؛ بحد 750 كيلوبايت للملف و1.5 ميجابايت إجمالاً.'));event.target.value='';return}
    setBusy(true)
    try{const uploaded=await Promise.all(selected.map(async file=>({title:file.name,content:'',fileName:file.name,mimeType:file.type,dataUrl:await readFile(file),sizeBytes:file.size})));setFiles(current=>[...current,...uploaded])}catch(cause){setError((cause as Error).message)}finally{setBusy(false);event.target.value=''}
  }
  function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setError('')
    try{
      const hasVitals=Object.values(vitals).some(Boolean)
      if(hasVitals&&Object.values(vitals).some(value=>!value))throw new Error(t('Complete all vital-sign fields or leave the whole section blank.','أكمل جميع حقول القياسات الحيوية أو اترك القسم كله فارغًا.'))
      const hasClinical=clinical.status==='Submitted'||Object.entries(clinical).some(([key,value])=>key!=='status'&&Boolean(value))
      if(hasClinical&&(!clinical.reason.trim()||!patient.diagnosis.trim()))throw new Error(t('A visit reason and diagnosis are needed to save a clinical assessment.','يلزم سبب الزيارة والتشخيص لحفظ التقييم السريري.'))
      if(appointment.date&&!appointment.purpose.trim())throw new Error(t('Enter the appointment purpose.','أدخل سبب الموعد.'))
      if(appointment.purpose&&!appointment.date)throw new Error(t('Select an appointment date.','اختر تاريخ الموعد.'))
      if(procedures.some(item=>!item.name.trim()||!item.date))throw new Error(t('Complete each procedure name and date.','أكمل اسم وتاريخ كل إجراء طبي.'))
      if(labs.some(item=>!item.test.trim()||!item.unit.trim()||!item.date||!item.value))throw new Error(t('Complete the test, result, unit and date for every lab entry.','أكمل اسم التحليل والنتيجة والوحدة والتاريخ لكل تحليل.'))
      const intake:PatientIntake={patient:{name:patient.name,nameAr:patient.nameAr,age:Number(patient.age),sex:patient.sex,residency:patient.residency,nationality:patient.nationality,emiratesId:patient.emiratesId,centreId:patient.centreId,doctorId:patient.doctorId,diagnosis:patient.diagnosis,fastingGlucose:patient.fastingGlucose,previousIllnesses:splitList(patient.previousIllnesses),chronicConditions:splitList(patient.chronicConditions),procedures:procedures.map(item=>({...item,name:item.name.trim()}))},vitals:hasVitals?{weightKg:Number(vitals.weightKg),heightCm:Number(vitals.heightCm),systolic:Number(vitals.systolic),diastolic:Number(vitals.diastolic),heartRate:Number(vitals.heartRate)}:undefined,labs:labs.map(item=>({...item,value:Number(item.value)})),assessment:hasClinical?{...clinical,diagnosis:patient.diagnosis.trim(),reason:clinical.reason.trim()}:undefined,appointment:appointment.date?appointment:undefined,documents:files}
      const next=registerPatientWithIntake(data,role,intake)
      onUpdate(next)
      onCreated(next.patients.at(-1)!.id)
    }catch(cause){setError((cause as Error).message)}
  }
  return <div className="registration-overlay"><section className="registration-screen" role="dialog" aria-modal="true" aria-label={t('Add patient','إضافة مريض')} dir={arabic?'rtl':'ltr'}>
    <header className="registration-header"><div><span>{t('PATIENT REGISTRY','سجل المرضى')}</span><h2>{t('Add patient','إضافة مريض')}</h2><p>{t('Create a complete shared record. Clinical status is calculated from saved evidence.','أنشئ ملفًا مشتركًا متكاملاً. تُحسب الحالة السريرية من الأدلة المحفوظة.')}</p></div><button type="button" autoFocus onClick={onClose} aria-label={t('Close registration','إغلاق التسجيل')}>×</button></header>
    <form onSubmit={submit} className="registration-form"><div className="registration-intro"><b>{t('New patient intake','بيانات المريض الجديد')}</b><span>{t('Required fields are marked *. Optional sections can be completed now or later in Patient 360.','الحقول المطلوبة مميزة بـ *. يمكن إكمال الأقسام الاختيارية الآن أو لاحقًا في ملف المريض 360.')}</span></div>
      <fieldset><legend><span>01</span>{t('Identity and assignment','الهوية والتعيين')}</legend><div className="registration-grid">{field('name',t('Full name','الاسم الكامل'),true)}{field('nameAr',t('Arabic name','الاسم بالعربية'))}{field('emiratesId',t('Emirates / national ID','رقم الهوية الإماراتية / الوطنية'))}{field('nationality',t('Nationality','الجنسية'))}{field('age',t('Age','العمر'),true,'number')}<label>{t('Sex','النوع')}<select value={patient.sex} onChange={event=>setPatient({...patient,sex:event.target.value})}><option value="Female">{t('Female','أنثى')}</option><option value="Male">{t('Male','ذكر')}</option></select></label><label>{t('Patient type','فئة المريض')}<select value={patient.residency} onChange={event=>setPatient({...patient,residency:event.target.value as PatientType})}><option value="Citizen">{t('Citizen','مواطن')}</option><option value="Resident">{t('Resident','مقيم')}</option><option value="Visitor">{t('Visitor','زائر')}</option></select></label><label>{t('Treatment centre','مركز العلاج')} *<select required value={patient.centreId} onChange={event=>setPatient({...patient,centreId:event.target.value})}>{centres.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{t('Emirate','الإمارة')}<input readOnly value={centre?.emirate??''}/></label><label>{t('Treating doctor','الطبيب المسؤول')} *<select required value={patient.doctorId} onChange={event=>setPatient({...patient,doctorId:event.target.value})}>{doctors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div></fieldset>
      <fieldset><legend><span>02</span>{t('Medical history','التاريخ المرضي')}</legend><div className="registration-grid">{field('diagnosis',t('Diagnosis','التشخيص'))}{field('fastingGlucose',t('Fasting glucose (with unit)','سكر صائم (مع الوحدة)'))}<label className="wide">{t('Previous illnesses — one per line','الأمراض السابقة — مرض في كل سطر')}<textarea value={patient.previousIllnesses} onChange={event=>setPatient({...patient,previousIllnesses:event.target.value})} rows={2}/></label><label className="wide">{t('Chronic conditions — one per line','الأمراض المزمنة — مرض في كل سطر')}<textarea value={patient.chronicConditions} onChange={event=>setPatient({...patient,chronicConditions:event.target.value})} rows={2}/></label></div><div className="registration-subheading"><b>{t('Previous procedures','إجراءات طبية سابقة')}</b><button type="button" onClick={()=>setProcedures([...procedures,{name:'',date:'',note:''}])}>{t('+ Add procedure','+ إضافة إجراء')}</button></div>{procedures.map((item,index)=><div className="registration-repeat" key={index}><label>{t('Procedure','الإجراء')}<input value={item.name} onChange={event=>setProcedures(procedures.map((entry,i)=>i===index?{...entry,name:event.target.value}:entry))}/></label><label>{t('Date','التاريخ')}<input type="date" max={today} value={item.date} onChange={event=>setProcedures(procedures.map((entry,i)=>i===index?{...entry,date:event.target.value}:entry))}/></label><label>{t('Notes','ملاحظات')}<input value={item.note} onChange={event=>setProcedures(procedures.map((entry,i)=>i===index?{...entry,note:event.target.value}:entry))}/></label><button type="button" aria-label={t('Remove procedure','حذف الإجراء')} onClick={()=>setProcedures(procedures.filter((_,i)=>i!==index))}>×</button></div>)}</fieldset>
      <fieldset><legend><span>03</span>{t('Vital signs','القياسات الحيوية')}</legend><p className="registration-hint">{t('Enter all measurements together to calculate BMI and record a dated vital-sign entry.','أدخل القياسات كاملة لحساب مؤشر كتلة الجسم وحفظ قراءة مؤرخة.')}</p><div className="registration-grid">{vitalField('weightKg',t('Weight (kg)','الوزن (كجم)'))}{vitalField('heightCm',t('Height (cm)','الطول (سم)'))}{vitalField('systolic',t('Systolic pressure','الضغط الانقباضي'))}{vitalField('diastolic',t('Diastolic pressure','الضغط الانبساطي'))}{vitalField('heartRate',t('Heart rate','معدل النبض'))}</div>{Number(vitals.weightKg)>0&&Number(vitals.heightCm)>0&&<p className="registration-calculation">BMI: {(Number(vitals.weightKg)/(Number(vitals.heightCm)/100)**2).toFixed(1)}</p>}</fieldset>
      <fieldset><legend><span>04</span>{t('Laboratory evidence','التحاليل الطبية')}</legend><div className="registration-subheading"><p className="registration-hint">{t('Add each real result; eligibility updates from saved evidence.','أضف كل نتيجة فعلية؛ تتحدث الأهلية من الأدلة المحفوظة.')}</p><button type="button" onClick={()=>setLabs([...labs,{test:'HbA1c',value:'',unit:'%',reference:'4.0–5.6',status:'Pending',date:today,source:'',interpretation:''}])}>{t('+ Add lab result','+ إضافة تحليل')}</button></div>{labs.map((item,index)=><div className="registration-lab" key={index}><div className="registration-grid"><label>{t('Test','التحليل')}<input value={item.test} onChange={event=>setLabs(labs.map((entry,i)=>i===index?{...entry,test:event.target.value}:entry))}/></label><label>{t('Result','النتيجة')}<input type="number" min="0" step="any" value={item.value} onChange={event=>setLabs(labs.map((entry,i)=>i===index?{...entry,value:event.target.value}:entry))}/></label><label>{t('Unit','الوحدة')}<input value={item.unit} onChange={event=>setLabs(labs.map((entry,i)=>i===index?{...entry,unit:event.target.value}:entry))}/></label><label>{t('Reference','المرجع')}<input value={item.reference} onChange={event=>setLabs(labs.map((entry,i)=>i===index?{...entry,reference:event.target.value}:entry))}/></label><label>{t('Status','الحالة')}<select value={item.status} onChange={event=>setLabs(labs.map((entry,i)=>i===index?{...entry,status:event.target.value as LabResult['status']}:entry))}><option value="Pending">{t('Pending','قيد الانتظار')}</option><option value="Normal">{t('Normal','طبيعي')}</option><option value="Abnormal">{t('Abnormal','غير طبيعي')}</option></select></label><label>{t('Collection date','تاريخ السحب')}<input type="date" max={today} value={item.date} onChange={event=>setLabs(labs.map((entry,i)=>i===index?{...entry,date:event.target.value}:entry))}/></label><label>{t('Source / lab','المصدر / المختبر')}<input value={item.source} onChange={event=>setLabs(labs.map((entry,i)=>i===index?{...entry,source:event.target.value}:entry))}/></label><label>{t('Interpretation','التفسير')}<input value={item.interpretation} onChange={event=>setLabs(labs.map((entry,i)=>i===index?{...entry,interpretation:event.target.value}:entry))}/></label></div><button type="button" onClick={()=>setLabs(labs.filter((_,i)=>i!==index))}>{t('Remove result','حذف النتيجة')}</button></div>)}</fieldset>
      <fieldset><legend><span>05</span>{t('Clinical assessment','التقييم السريري')}</legend><p className="registration-hint">{t('A submitted assessment needs findings and a care note. Drafts can be completed later by the doctor.','التقييم المعتمد يحتاج نتائج سريرية وملاحظة رعاية. يمكن للطبيب إكمال المسودة لاحقًا.')}</p><div className="registration-grid"><label>{t('Reason for visit','سبب الزيارة')}<input value={clinical.reason} onChange={event=>setClinical({...clinical,reason:event.target.value})}/></label><label>{t('Assessment status','حالة التقييم')}<select value={clinical.status} onChange={event=>setClinical({...clinical,status:event.target.value as 'Draft'|'Submitted'})}><option value="Draft">{t('Draft','مسودة')}</option><option value="Submitted">{t('Submitted','مقدم')}</option></select></label>{(['symptoms','medicalHistory','medications','allergies','findings','notes'] as const).map(key=><label className="wide" key={key}>{({symptoms:t('Symptoms','الأعراض'),medicalHistory:t('Medical history','التاريخ الطبي'),medications:t('Current medications','الأدوية الحالية'),allergies:t('Allergies','الحساسية'),findings:t('Clinical findings','النتائج السريرية'),notes:t('Care note','ملاحظة الرعاية')})[key]}<textarea rows={2} value={clinical[key]} onChange={event=>setClinical({...clinical,[key]:event.target.value})}/></label>)}</div></fieldset>
      <fieldset><legend><span>06</span>{t('First appointment','الموعد الأول')}</legend><div className="registration-grid"><label>{t('Date','التاريخ')}<input type="date" min={today} value={appointment.date} onChange={event=>setAppointment({...appointment,date:event.target.value})}/></label><label>{t('Time','الوقت')}<input type="time" value={appointment.time} onChange={event=>setAppointment({...appointment,time:event.target.value})}/></label><label>{t('Purpose','السبب')}<input value={appointment.purpose} onChange={event=>setAppointment({...appointment,purpose:event.target.value})}/></label><label>{t('Notes','ملاحظات')}<input value={appointment.notes} onChange={event=>setAppointment({...appointment,notes:event.target.value})}/></label></div></fieldset>
      <fieldset><legend><span>07</span>{t('Documents and uploads','المستندات والمرفقات')}</legend><p className="registration-hint">{t('Files stay in this browser’s local demonstration record. Accepted: PDF, JPG, PNG, WebP, TXT, DOCX.','تبقى الملفات داخل السجل التجريبي المحلي لهذا المتصفح. الصيغ: PDF وJPG وPNG وWebP وTXT وDOCX.')}</p><label className="registration-upload"><span>{t('Choose files to upload','اختر ملفات للرفع')}</span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.docx" onChange={upload}/></label>{files.length>0&&<div className="registration-files">{files.map((file,index)=><div key={`${file.fileName}-${index}`}><b>{file.fileName}</b><small>{Math.round(file.sizeBytes/1024)} KB</small><input aria-label={`${t('Document description','وصف المستند')} ${file.fileName}`} placeholder={t('Document description','وصف المستند')} value={file.content} onChange={event=>setFiles(files.map((entry,i)=>i===index?{...entry,content:event.target.value}:entry))}/><button type="button" onClick={()=>setFiles(files.filter((_,i)=>i!==index))}>{t('Remove','حذف')}</button></div>)}</div>}</fieldset>
      {error&&<p role="alert" className="registration-error">{error}</p>}<footer className="registration-footer"><span>{t('Treatment requests and dispensing remain separate clinical workflows.','طلبات العلاج والصرف مساران سريريان منفصلان عن التسجيل.')}</span><div><button type="button" onClick={onClose}>{t('Cancel','إلغاء')}</button><button className="primary" disabled={busy} type="submit">{busy?t('Reading files…','جارٍ قراءة الملفات…'):t('Save patient record','حفظ ملف المريض')}</button></div></footer>
    </form>
  </section></div>
}
