import { CareIcon } from './CareIcon'
import { Fragment, useState } from 'react'
import { type AppData, type InventoryMovement } from './domain'
import './PharmacyInventory.css'

type Props={data:AppData;arabic:boolean}
const day=(value:string)=>value.slice(0,10)
const medication=(data:AppData,dose:string)=>data.medications?.find(item=>item.strengths.includes(dose))?.name??data.medications?.[0]?.name??'Mounjaro'
const movementText=(value:InventoryMovement['type'],ar:boolean)=>ar?({Receiving:'استلام',Dispensing:'صرف',Restock:'إعادة تزويد',Adjustment:'تسوية',Correction:'تصحيح',Expiry:'انتهاء صلاحية'} as Record<string,string>)[value]:value
const centreName=(data:AppData,value:string,ar:boolean)=>{if(!ar)return value;const centre=data.centres.find(item=>item.name===value);return centre?.pharmacy===value?'صيدلية '+centre.emirate:value==='Dubai Central Pharmacy'?'صيدلية دبي المركزية':value==='Sharjah Health Centre'?'مركز الشارقة الصحي':value==='Abu Dhabi Primary Care Centre 2'?'مركز أبوظبي للرعاية الأولية ٢':value}
export function PharmacyInventory({data,arabic}:Props){
 const [view,setView]=useState<'stock'|'movements'>('stock'),[doseFilter,setDoseFilter]=useState('all'),[centreFilter,setCentreFilter]=useState('all'),[typeFilter,setTypeFilter]=useState('all'),[medFilter,setMedFilter]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[expanded,setExpanded]=useState('')
 const [today]=useState(()=>new Date().toISOString().slice(0,10))
 const t=(en:string,ar:string)=>arabic?ar:en
 const cutoff=new Date(`${today}T12:00:00Z`);cutoff.setUTCDate(cutoff.getUTCDate()+60);const soonDate=cutoff.toISOString().slice(0,10)
 const doses=[...new Set(data.batches.map(item=>item.dose))].sort((a,b)=>parseFloat(a)-parseFloat(b))
 const centres=[...new Set(data.batches.map(item=>item.centre))].sort()
 const reservation=data.requests.filter(item=>item.status==='Ready to dispense').sort((a,b)=>(a.createdAt??'').localeCompare(b.createdAt??''))
 const allocated=new Map<string,number>();const slots=new Map(data.batches.map(item=>[item.id,item.expiry>today?item.quantity:0]))
 reservation.forEach(request=>{const batch=data.batches.filter(item=>item.dose===request.dose&&(slots.get(item.id)??0)>0&&item.expiry>today).sort((a,b)=>a.expiry.localeCompare(b.expiry))[0];if(batch){allocated.set(batch.id,(allocated.get(batch.id)??0)+1);slots.set(batch.id,(slots.get(batch.id)??0)-1)}})
 const rows=doses.flatMap(dose=>centres.filter(centre=>data.batches.some(item=>item.dose===dose&&item.centre===centre)).map(centre=>{const batches=data.batches.filter(item=>item.dose===dose&&item.centre===centre);const usable=batches.filter(item=>item.expiry>today);const onHand=usable.reduce((sum,item)=>sum+item.quantity,0);const reserved=usable.reduce((sum,item)=>sum+(allocated.get(item.id)??0),0);const available=Math.max(0,onHand-reserved);const first=usable.filter(item=>item.quantity>0).sort((a,b)=>a.expiry.localeCompare(b.expiry))[0];const expired=batches.some(item=>item.quantity>0&&item.expiry<=today);const status=available===0&&expired?'expired':available<12?'low':first&&first.expiry<=soonDate?'soon':'available';return {key:`${dose}:${centre}`,dose,centre,batches,onHand,reserved,available,expiry:first?.expiry??batches.map(item=>item.expiry).sort()[0]??'',status}}))
 const filteredRows=rows.filter(item=>(doseFilter==='all'||item.dose===doseFilter)&&(centreFilter==='all'||item.centre===centreFilter)&&(medFilter==='all'||medication(data,item.dose)===medFilter))
 const ordered=data.movements.slice().sort((a,b)=>b.at.localeCompare(a.at))
 const currentBalances=new Map(data.batches.map(item=>[item.id,item.quantity]))
 const centreBalances=new Map(rows.map(item=>[item.key,item.batches.reduce((sum,batch)=>sum+batch.quantity,0)]))
 const movementRows=ordered.map(item=>{const key=item.batchId&&currentBalances.has(item.batchId)?item.batchId:`${item.dose}:${item.centre}`;const balances=key===item.batchId?currentBalances:centreBalances;const after=balances.get(key)??0;balances.set(key,after-item.quantity);return {...item,balanceAfter:after}}).filter(item=>(doseFilter==='all'||item.dose===doseFilter)&&(centreFilter==='all'||item.centre===centreFilter)&&(typeFilter==='all'||item.type===typeFilter)&&(medFilter==='all'||medication(data,item.dose)===medFilter)&&(!from||day(item.at)>=from)&&(!to||day(item.at)<=to))
 const records=view==='stock'?filteredRows:movementRows
 const pageCount=Math.max(1,Math.ceil(records.length/pageSize)),currentPage=Math.min(page,pageCount),visible=records.slice((currentPage-1)*pageSize,currentPage*pageSize)
 const changeView=(next:'stock'|'movements')=>{setView(next);setPage(1);setExpanded('')}
 const reset=()=>{setDoseFilter('all');setCentreFilter('all');setTypeFilter('all');setMedFilter('all');setFrom('');setTo('');setPage(1)}
 const setFilter=<T,>(setter:(value:T)=>void)=>(value:T)=>{setter(value);setPage(1)}
 const statusText=(status:string)=>status==='expired'?t('Expired','منتهي الصلاحية'):status==='low'?t('Low stock','مخزون منخفض'):status==='soon'?t('Expiring soon','قريب الانتهاء'):t('Available','متاح')
 const balance=(quantity:number)=>`${quantity>0?'+':''}${quantity}`
 return <div className="pi-workspace" dir={arabic?'rtl':'ltr'}>
  <div className="pi-top"><div><div className="pi-crumb">{t('Programme','البرنامج')} <span>/</span> {view==='stock'?t('Inventory','المخزون'):t('Inventory movements','حركات المخزون')}</div><h1><span aria-hidden="true"><CareIcon name={view==='stock'?'Inventory':'history'}/></span> {view==='stock'?t('Inventory','المخزون'):t('Inventory movements','حركات المخزون')}</h1><p>{view==='stock'?t('Medication quantities by strength and centre.','كميات الأدوية حسب التركيز والمركز.'):t('All receipts, dispensing and adjustments across participating centres.','سجل جميع حركات الاستلام والصرف والتسوية في المراكز المشاركة.')}</p></div><div className="pi-top-tools"><label>{t('Medication','الدواء')}<select value={medFilter} onChange={event=>setFilter(setMedFilter)(event.target.value)}><option value="all">{t('All medications','جميع الأدوية')}</option>{[...new Set(data.medications?.map(item=>item.name)??[])].map(name=><option key={name} value={name}>{name}</option>)}</select></label></div></div>
  <div className="pi-switch" role="tablist" aria-label={t('Inventory views','شاشات المخزون')}><button role="tab" aria-selected={view==='stock'} className={view==='stock'?'active':''} onClick={()=>changeView('stock')}><CareIcon name="pill"/> {t('Stock balances','أرصدة المخزون')}</button><button role="tab" aria-selected={view==='movements'} className={view==='movements'?'active':''} onClick={()=>changeView('movements')}>⇄ {t('Movement log','سجل الحركات')}</button></div>
  {view==='stock'?<><div className="pi-stats"><div className="pi-stat total"><span><CareIcon name="file"/></span><div><small>{t('Available units','إجمالي الوحدات المتاحة')}</small><strong>{rows.reduce((sum,row)=>sum+row.available,0)}</strong></div></div><div className="pi-stat strengths"><span><CareIcon name="pill"/></span><div><small>{t('Strengths','عدد التركيزات')}</small><strong>{doses.length}</strong></div></div><div className="pi-stat low"><span><CareIcon name="alert"/></span><div><small>{t('Low stock rows','وحدات منخفضة المخزون')}</small><strong>{rows.filter(row=>row.status==='low').length}</strong></div></div><div className="pi-stat expiring"><span><CareIcon name="clock"/></span><div><small>{t('Near-expiry batches','دفعات قريبة من الانتهاء')}</small><strong>{data.batches.filter(item=>item.quantity>0&&item.expiry<=soonDate).length}</strong></div></div></div>
   <div className="pi-stock-filters"><label>{t('Centre','المركز')}<select value={centreFilter} onChange={event=>setFilter(setCentreFilter)(event.target.value)}><option value="all">{t('All','الكل')}</option>{centres.map(value=><option key={value} value={value}>{centreName(data,value,arabic)}</option>)}</select></label><label>{t('Strength','التركيز')}<select value={doseFilter} onChange={event=>setFilter(setDoseFilter)(event.target.value)}><option value="all">{t('All','الكل')}</option>{doses.map(value=><option key={value}>{value}</option>)}</select></label><button onClick={reset}><CareIcon name="reset"/> {t('Reset','إعادة ضبط')}</button></div>
   <section className="pi-panel"><h2><CareIcon name="pill"/> {t('Medication inventory by strength and centre','مخزون الدواء حسب التركيز والمركز')}</h2><div className="pi-table-scroll"><table><thead><tr><th>{t('Strength','التركيز')}</th><th>{t('Centre','المركز')}</th><th>{t('Available','المتاح')}</th><th>{t('Reserved','المحجوز')}</th><th>{t('On hand','المخزون')}</th><th>{t('Reorder point','حد إعادة الطلب')}</th><th>{t('Nearest expiry','أقرب انتهاء')}</th><th>{t('Status','الحالة')}</th><th></th></tr></thead><tbody>{(visible as typeof filteredRows).map(row=><Fragment key={row.key}><tr><td dir="ltr"><b>{row.dose}</b></td><td>{centreName(data,row.centre,arabic)}</td><td>{row.available}</td><td>{row.reserved}</td><td>{row.onHand}</td><td>12</td><td dir="ltr">{row.expiry}</td><td><span className={`pi-badge ${row.status}`}>{statusText(row.status)}</span></td><td><button className="pi-expand" aria-expanded={expanded===row.key} onClick={()=>setExpanded(expanded===row.key?'':row.key)}>{expanded===row.key?'⌄':'›'}</button></td></tr>{expanded===row.key&&<tr className="pi-batches" key={`${row.key}-batches`}><td colSpan={9}><strong>{t('Batches','الدفعات')}</strong><div>{row.batches.map(batch=><span key={batch.id}>{batch.batchNumber} · {batch.quantity} {t('units','وحدة')} · {t('expires','تنتهي')} {batch.expiry}</span>)}</div></td></tr>}</Fragment>)}</tbody></table>{records.length===0&&<div className="pi-empty">{t('No matching stock records.','لا توجد سجلات مخزون مطابقة.')}</div>}</div></section></>:<><div className="pi-movement-filters"><label>{t('From date','من تاريخ')}<input type="date" value={from} onChange={event=>setFilter(setFrom)(event.target.value)}/></label><label>{t('To date','إلى تاريخ')}<input type="date" value={to} onChange={event=>setFilter(setTo)(event.target.value)}/></label><label>{t('Strength','التركيز')}<select value={doseFilter} onChange={event=>setFilter(setDoseFilter)(event.target.value)}><option value="all">{t('All','الكل')}</option>{doses.map(value=><option key={value}>{value}</option>)}</select></label><label>{t('Centre','المركز')}<select value={centreFilter} onChange={event=>setFilter(setCentreFilter)(event.target.value)}><option value="all">{t('All','الكل')}</option>{centres.map(value=><option key={value} value={value}>{centreName(data,value,arabic)}</option>)}</select></label><label>{t('Movement type','نوع الحركة')}<select value={typeFilter} onChange={event=>setFilter(setTypeFilter)(event.target.value)}><option value="all">{t('All','الكل')}</option>{[...new Set(data.movements.map(item=>item.type))].map(value=><option key={value} value={value}>{movementText(value,arabic)}</option>)}</select></label><button onClick={reset}><CareIcon name="reset"/> {t('Reset','إعادة ضبط')}</button></div>
   <div className="pi-result-count">{records.length} {t('movements','حركة')}</div><section className="pi-panel pi-movement-panel"><div className="pi-table-scroll"><table><thead><tr><th>{t('Date and time','التاريخ والوقت')}</th><th>{t('User','المستخدم')}</th><th>{t('Centre','المركز')}</th><th>{t('Reference','المرجع')}</th><th>{t('Medication / strength','الدواء / التركيز')}</th><th>{t('Movement','الحركة')}</th><th>{t('Quantity','الكمية')}</th><th>{t('Balance after','الرصيد بعد الحركة')}</th></tr></thead><tbody>{(visible as typeof movementRows).map(item=><tr key={item.id}><td dir="ltr">{item.at.replace('T',' ').slice(0,16)}</td><td>{item.actor==='Pharmacist'?t('Pharmacist','الصيدلي'):item.actor==='Admin'?t('Admin','المسؤول'):item.actor==='Doctor'?t('Doctor','الطبيب'):item.actor}</td><td>{centreName(data,item.centre,arabic)}</td><td dir="ltr">{item.reference}</td><td><b>{medication(data,item.dose)}</b> <span dir="ltr">{item.dose}</span></td><td><span className={`pi-badge movement ${item.quantity<0?'out':'in'}`}>{movementText(item.type,arabic)}</span></td><td className={item.quantity<0?'pi-negative':'pi-positive'} dir="ltr">{balance(item.quantity)}</td><td>{item.balanceAfter}</td></tr>)}</tbody></table>{records.length===0&&<div className="pi-empty">{t('No matching movements.','لا توجد حركات مطابقة.')}</div>}</div></section></>}
  <div className="pi-pagination"><div>{t('Show','عرض')} <select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPage(1)}}><option value={10}>10</option><option value={20}>20</option><option value={50}>50</option></select> {t('per page','لكل صفحة')}</div><span>{t('of','من')} {records.length} {view==='stock'?t('stock rows','صفوف مخزون'):t('movements','حركة')}</span><div className="pi-pages"><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>{arabic?'›':'‹'}</button>{Array.from({length:pageCount},(_,i)=><button key={i} className={currentPage===i+1?'active':''} onClick={()=>setPage(i+1)}>{i+1}</button>).slice(Math.max(0,currentPage-3),Math.min(pageCount,currentPage+2))}<button disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)}>{arabic?'‹':'›'}</button></div></div>
 </div>
}
