import { CareIcon } from './CareIcon'
import { useState } from 'react'
import { inventoryByDose, requestStockSupply, type AppData } from './domain'
import hero from './assets/pharmacy-dashboard-hero.png'
import './PharmacistDashboard.css'

type Props={data:AppData;arabic:boolean;onUpdate:(data:AppData)=>void;onNavigate:(page:'Inventory'|'Dispensing')=>void}
const trStatus:Record<string,string>={'Ready to dispense':'جاهز للصرف','Dispensed':'تم الصرف','Under review':'بانتظار المراجعة','Needs information':'يحتاج معلومات','Approved':'معتمد','Rejected':'مرفوض','Draft':'مسودة'}
const arabicCentre:Record<string,string>={'Dubai Central Pharmacy':'صيدلية دبي المركزية','Sharjah Health Centre':'مركز الشارقة الصحي','Abu Dhabi Primary Care Centre 2':'مركز أبوظبي للرعاية الأولية ٢'}
const moneyDate=(value:string,arabic:boolean)=>new Intl.DateTimeFormat(arabic?'ar-AE':'en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${value}T12:00:00Z`))
export function PharmacistDashboard({data,arabic,onUpdate,onNavigate}:Props){
 const [now]=useState(()=>new Date()),[feedback,setFeedback]=useState('')
 const today=now.toISOString().slice(0,10),soon=new Date(now.getTime()+60*86400000).toISOString().slice(0,10)
 const t=(en:string,ar:string)=>arabic?ar:en
 const pharmacist=data.pharmacists?.[0]
 const name=arabic?pharmacist?.nameAr??pharmacist?.name:pharmacist?.name
 const patients=new Map(data.patients.map(p=>[p.id,p]))
 const ready=data.requests.filter(r=>r.status==='Ready to dispense')
 const todayRequests=data.requests.filter(r=>(r.createdAt??'').slice(0,10)===today)
 const dispensed=data.dispenses.length
 const stock=inventoryByDose(data)
 const stockRows=[...new Set(data.batches.map(b=>`${b.dose}|${b.centre}`))].map(key=>{const [dose,centre]=key.split('|');const batches=data.batches.filter(b=>b.dose===dose&&b.centre===centre);const valid=batches.filter(b=>b.expiry>today);const onHand=valid.reduce((sum,b)=>sum+b.quantity,0);const first=valid.filter(b=>b.quantity>0).sort((a,b)=>a.expiry.localeCompare(b.expiry))[0];const reservations=ready.filter(r=>r.dose===dose).length;return {key,dose,centre,onHand,available:Math.max(0,onHand-reservations),expiry:first?.expiry??batches.map(b=>b.expiry).sort()[0]??'',medication:data.medications?.find(m=>m.strengths.includes(dose))?.name??'Mounjaro'}})
 const low=stockRows.filter(row=>row.available<12).sort((a,b)=>a.available-b.available)
 const near=data.batches.filter(b=>b.quantity>0&&b.expiry<=soon)
 const segment={healthy:0,low:0,soon:0,expired:0}
 data.batches.filter(b=>b.quantity>0).forEach(batch=>{if(batch.expiry<=today)segment.expired+=batch.quantity;else if(batch.expiry<=soon)segment.soon+=batch.quantity;else if((stock[batch.dose]??0)<12)segment.low+=batch.quantity;else segment.healthy+=batch.quantity})
 const total=Object.values(segment).reduce((a,b)=>a+b,0)
 const pct=(n:number)=>total?`${Math.round(n/total*100)}%`:'0%'
 const circle=`conic-gradient(#2db9a0 0 ${pct(segment.healthy)}, #f4c254 ${pct(segment.healthy)} ${pct(segment.healthy+segment.low)}, #fb985b ${pct(segment.healthy+segment.low)} ${pct(segment.healthy+segment.low+segment.soon)}, #f05d64 ${pct(segment.healthy+segment.low+segment.soon)} 100%)`
 const days=Array.from({length:7},(_,i)=>new Date(now.getTime()-(6-i)*86400000).toISOString().slice(0,10))
 const counts=days.map(day=>data.movements.filter(m=>m.type==='Dispensing'&&m.at.slice(0,10)===day).reduce((sum,m)=>sum+Math.abs(m.quantity),0))
 const max=Math.max(1,...counts)
 const latest=data.requests.slice().sort((a,b)=>(b.createdAt??'').localeCompare(a.createdAt??'')).slice(0,5)
 function supply(row:typeof low[number]){try{onUpdate(requestStockSupply(data,'Pharmacist',row.dose,row.centre,Math.max(12-row.available,1)));setFeedback(t('Supply request recorded.','تم تسجيل طلب التوريد.'))}catch(error){setFeedback((error as Error).message)}}
 return <div className="phd-workspace" dir={arabic?'rtl':'ltr'}>
  <header className="phd-hero" style={{backgroundImage:`url(${hero})`}}><div className="phd-hero-text"><small>{t('Hello','مرحبًا بك')}، ☀</small><h1>{t('Pharmacist','الصيدلي')} {name??''}</h1><p>{t('Your pharmacy operations at a glance today.','هنا ملخص عمليات الصيدلية اليوم')}</p></div><time>{new Intl.DateTimeFormat(arabic?'ar-AE':'en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now)}</time></header>
  <div className="phd-kpis"><article className="phd-kpi today"><span className="phd-kpi-icon"><CareIcon name="file"/></span><div><small>{t('Requests today','طلبات الصرف اليوم')}</small><strong>{todayRequests.length}</strong><em>{t('From shared requests','من الطلبات المسجلة')} ↗</em></div></article><article className="phd-kpi dispensed"><span className="phd-kpi-icon"><CareIcon name="check"/></span><div><small>{t('Dispensed','تم صرفها')}</small><strong>{dispensed}</strong><em>{t('Recorded dispensing events','عمليات صرف مسجلة')}</em></div></article><article className="phd-kpi waiting"><span className="phd-kpi-icon"><CareIcon name="clock"/></span><div><small>{t('Awaiting dispensing','بانتظار الصرف')}</small><strong>{ready.length}</strong><em>{t('Ready for pharmacy verification','جاهزة للتحقق الصيدلي')}</em></div></article><article className="phd-kpi low"><span className="phd-kpi-icon"><CareIcon name="pill"/></span><div><small>{t('Low stock rows','أصناف منخفضة المخزون')}</small><strong>{low.length}</strong></div></article><article className="phd-kpi expiry"><span className="phd-kpi-icon"><CareIcon name="alert"/></span><div><small>{t('Batches near expiry','دفعات قريبة من الانتهاء')}</small><strong>{near.length}</strong><button onClick={()=>onNavigate('Inventory')}>{t('View details','عرض التفاصيل')} ←</button></div></article></div>
  <div className="phd-panels"><section className="phd-panel latest"><h2><CareIcon name="file"/> {t('Latest dispensing requests','آخر طلبات الصرف')}</h2><div className="phd-latest-list">{latest.map(r=>{const p=patients.get(r.patientId);return <button key={r.id} onClick={()=>onNavigate('Dispensing')}><div><b>{arabic?p?.nameAr??p?.name:p?.name}</b><small dir="ltr">{r.id}</small></div><time>{(r.createdAt??r.created).slice(11,16)||'—'}</time><span className={`phd-status ${r.status==='Dispensed'?'done':r.status==='Ready to dispense'?'ready':'review'}`}>{t(r.status,trStatus[r.status]??r.status)}</span><i>‹</i></button>})}{latest.length===0&&<p>{t('No requests recorded.','لا توجد طلبات مسجلة.')}</p>}</div></section>
   <section className="phd-panel trend"><h2><CareIcon name="chart"/> {t('Dispensing activity · 7 days','حركة الصرف خلال 7 أيام')}</h2><div className="phd-bars">{days.map((day,i)=><div className="phd-bar" key={day}><b>{counts[i]}</b><span style={{height:`${Math.max(counts[i]?10:2,counts[i]/max*100)}%`}}/><small>{moneyDate(day,arabic)}</small></div>)}</div><button className="phd-panel-link" onClick={()=>onNavigate('Inventory')}>{t('View all movements','عرض كل الحركات')} ←</button></section>
   <section className="phd-panel stock"><h2><CareIcon name="pill"/> {t('Inventory status','حالة المخزون')}</h2><div className="phd-stock-body"><div className="phd-donut" style={{background:circle}}><div><strong>{total}</strong><small>{t('Total units','إجمالي الوحدات')}</small></div></div><div className="phd-legend"><div><span className="healthy"/>{t('Available','متوفر')}<b>{segment.healthy}</b></div><div><span className="low"/>{t('Low stock','منخفض المخزون')}<b>{segment.low}</b></div><div><span className="soon"/>{t('Near expiry','قريب من الانتهاء')}<b>{segment.soon}</b></div><div><span className="expired"/>{t('Expired','منتهي الصلاحية')}<b>{segment.expired}</b></div></div></div><button className="phd-panel-link" onClick={()=>onNavigate('Inventory')}>{t('View inventory','عرض المخزون')} ←</button></section></div>
  <section className="phd-panel phd-low-table"><div className="phd-table-head"><div><h2><CareIcon name="alert"/> {t('Low-stock medications','الأدوية منخفضة المخزون')}</h2><p>{t('Strengths and centres that reached the reorder point or less.','الأصناف التي وصلت إلى حد إعادة الطلب أو أقل.')}</p></div><button onClick={()=>onNavigate('Inventory')}>{t('View all inventory','عرض كل المخزون')} ←</button></div>{feedback&&<p className="phd-feedback" role="status">{feedback}</p>}<div className="phd-table-scroll"><table><thead><tr><th>{t('Medication','الدواء')}</th><th>{t('Strength','التركيز')}</th><th>{t('Balance','إجمالي الرصيد')}</th><th>{t('Minimum','الحد الأدنى')}</th><th>{t('Centre','المركز')}</th><th>{t('Nearest expiry','أقرب انتهاء')}</th><th>{t('Status','الحالة')}</th><th>{t('Action','إجراء')}</th></tr></thead><tbody>{low.map(row=>{const open=(data.supplyRequests??[]).some(item=>item.dose===row.dose&&item.centre===row.centre&&item.status==='Requested');return <tr key={row.key}><td><b>{row.medication}</b></td><td dir="ltr">{row.dose}</td><td>{row.available}</td><td>12</td><td>{arabic?arabicCentre[row.centre]??row.centre:row.centre}</td><td dir="ltr">{row.expiry}</td><td><span className="phd-low-badge">{t('Low stock','منخفض المخزون')}</span></td><td><button disabled={open} onClick={()=>supply(row)}>{open?t('Requested','تم الطلب'):t('Request supply','طلب توريد')}</button></td></tr>})}</tbody></table>{low.length===0&&<div className="phd-empty">{t('No low-stock items.','لا توجد أصناف منخفضة المخزون.')}</div>}</div></section>
 </div>
}
