import { medicationCoverageForRequest, type AppData } from './domain'
export type PharmacyDocumentKind='prescription'|'receipt'
export type PharmacyDocumentModel={title:string;number:string;date:string;arabic:boolean;sections:{title:string;rows:[string,string][]}[];footer:string}
export function pharmacyDocumentModel(data:AppData,requestId:string,kind:PharmacyDocumentKind,arabic:boolean):PharmacyDocumentModel {
 const t=(en:string,ar:string)=>arabic?ar:en
 const request=data.requests.find(r=>r.id===requestId)
 const patient=data.patients.find(p=>p.id===request?.patientId)
 if(!request||!patient)throw new Error('Prescription or patient record is missing.')
 const plan=data.treatmentPlans.find(p=>p.id===request.planId),dispense=data.dispenses.find(d=>d.requestId===requestId),payment=data.payments?.find(p=>p.requestId===requestId)
 if(kind==='receipt'&&!payment)throw new Error('Confirm checkout before issuing a receipt.')
 const doctor=data.doctors.find(d=>d.id===patient.doctorId||d.name===patient.assignedDoctor),pharmacist=data.pharmacists?.find(p=>p.id===dispense?.pharmacistId),batch=data.batches.find(b=>b.id===dispense?.batchId)
 const row=(en:string,ar:string,value:unknown):[string,string]=>[t(en,ar),String(value??'—')]
 const sections:PharmacyDocumentModel['sections']=[{title:t('Patient details','بيانات المريض'),rows:[row('Patient','المريض',arabic?patient.nameAr??patient.name:patient.name),row('Medical record / Emirates ID','رقم الملف / الهوية الإماراتية',`${patient.id} / ${patient.emiratesId??'—'}`),row('Age / Sex / Category','العمر / الجنس / الفئة',`${patient.age} / ${arabic?({Male:'ذكر',Female:'أنثى'}[patient.sex??'']??patient.sex??'—'):patient.sex??'—'} / ${arabic?({Citizen:'مواطن',Resident:'مقيم',Visitor:'زائر'}[patient.residency??'Visitor']??'—'):patient.residency??'—'}`)]}]
 sections.push({title:t('Prescription','الوصفة الطبية'),rows:[row('Request / Prescription','الطلب / الوصفة',`${request.id} / ${request.prescriptionId??request.id}`),row('Medication / Strength','الدواء / التركيز',`${request.medication??plan?.medication??'—'} · ${request.dose}`),row('Frequency / Duration','التكرار / المدة',`${arabic?({Weekly:'أسبوعيًا',Daily:'يوميًا'}[plan?.frequency??request.frequency??'']??plan?.frequency??request.frequency??'—'):plan?.frequency??request.frequency??'—'} / ${plan?.durationDays??request.durationDays??'—'} ${t('days','يومًا')}`),row('Prescriber / Licence','الطبيب / الترخيص',`${(arabic?doctor?.nameAr:doctor?.name)??doctor?.name??patient.assignedDoctor??'—'} / ${doctor?.licenseReference??'—'}`)]})
 if(kind==='prescription')sections.push({title:t('Treatment instructions','تعليمات العلاج'),rows:[row('Indication','دواعي الاستخدام',plan?.indication??request.indication),row('Treatment dates','فترة العلاج',`${plan?.startDate??request.startDate??'—'} → ${plan?.endDate??request.endDate??'—'}`),row('Instructions','تعليمات الاستخدام',plan?.instructions??request.instructions),row('Monitoring plan','خطة المتابعة',plan?.monitoringPlan??request.monitoringPlan),row('Follow-up date','موعد المتابعة',plan?.followUpDate??request.followUpDate),row('Authorization','الاعتماد',request.exceptionApproved?t(`Exception approved · ${request.reviewer??'Recorded reviewer'}`,`استثناء معتمد · ${request.reviewer??'المراجع المسجل'}`):t('System eligibility authorization','اعتماد الأهلية في النظام'))]})
 if(dispense)sections.push({title:t('Dispensing record','بيانات الصرف'),rows:[row('Site / Pharmacist','المركز / الصيدلي',`${dispense.centre} / ${(arabic?pharmacist?.nameAr:pharmacist?.name)??pharmacist?.name??dispense.pharmacistId??'—'}`),row('Quantity / Batch / Expiry','الكمية / الدفعة / الصلاحية',`1 ${t('dispensing unit','وحدة صرف')} / ${batch?.batchNumber??dispense.batchId??'—'} / ${batch?.expiry??'—'}`),row('Dispensed at','تاريخ الصرف',dispense.dispensedAt??dispense.date)]})
 if(payment&&kind==='receipt'){
  const coverage=medicationCoverageForRequest(data,requestId),money=(n:number)=>`${n.toFixed(2)} AED`
  sections.push({title:t('Payment summary','ملخص السداد'),rows:[row('Medication total','إجمالي الدواء',money(coverage.totalAED)),row('State coverage','تغطية الدولة',`${money(coverage.supportAED)} (${coverage.discountPercent}%)`),row('Patient share / Amount paid','حصة المريض / المبلغ المدفوع',money(payment.amountAED)),row('Payment method','طريقة السداد',payment.amountAED===0?t('Fully covered · No payment required','مغطى بالكامل · لا يتطلب دفعًا'):payment.method==='Cash'?t('Cash','نقدًا'):t('Card / Visa','بطاقة / فيزا')),row('Outstanding balance','الرصيد المتبقي',money(0))]})
 }
 return {title:kind==='receipt'?t('Dispensing receipt','إيصال صرف الدواء'):t('Medical prescription','الوصفة الطبية'),number:kind==='receipt'?payment!.receiptNumber:request.prescriptionId??request.id,date:kind==='receipt'?payment!.paidAt:request.createdAt??request.created,arabic,sections,footer:t('Demonstration document • Generated from the recorded care and dispensing data.','مستند تجريبي • صادر من بيانات الرعاية والصرف المسجلة في النظام.')}
}
