import { useState } from 'react'
import { CareIcon } from './CareIcon'
import { completePharmacyCheckout, medicationCoverageForRequest, type AppData } from './domain'
import { PharmacyDocumentPreview } from './PharmacyDocumentViews'
import type { PharmacyDocumentKind } from './pharmacyDocumentModel'
import logo from './assets/healthcare-logo.png'
import './PharmacyCheckout.css'

export function PharmacyCheckout({data,requestId,arabic,identity,blocked,onUpdate}:{data:AppData;requestId:string;arabic:boolean;identity:boolean;blocked:boolean;onUpdate:(next:AppData)=>void}){
 const [method,setMethod]=useState<'Cash'|'Card'>('Cash'),[error,setError]=useState(''),[preview,setPreview]=useState<PharmacyDocumentKind|null>(null),[received,setReceived]=useState(false)
 const t=(en:string,ar:string)=>arabic?ar:en,money=(n:number)=>n.toFixed(2)
 const request=data.requests.find(r=>r.id===requestId)!,payment=data.payments?.find(p=>p.requestId===requestId),dispense=data.dispenses.find(d=>d.requestId===requestId)
 let coverage;let coverageError=''
 try{coverage=medicationCoverageForRequest(data,requestId)}catch(e){coverageError=(e as Error).message}
 const covered=coverage?.patientAED===0,completed=!!payment
 const confirm=()=>{try{onUpdate(completePharmacyCheckout(data,'Pharmacist',requestId,identity,covered?'Covered':method));setError('')}catch(e){setError((e as Error).message)}}
 return <section className={`pharmacy-checkout ${completed?'is-complete':''}`} data-no-localize><div className="checkout-main"><div className="checkout-eyebrow"><span>03</span>{t('DISPENSING & DOCUMENTS','الصرف والمستندات')}</div><h2>{completed?t('Dispensing completed','تم الصرف بنجاح'):covered?t('Ready to confirm dispensing','جاهز لتأكيد الصرف'):t('Payment & dispensing','الدفع وتأكيد الصرف')}</h2><p className="checkout-intro">{completed?t('The prescription and receipt are available in the patient’s file.','الوصفة والإيصال متاحان الآن في ملف المريض داخل النظام.'):covered?t('The medication is fully covered. Confirm collection to issue the receipt.','تكلفة الدواء مغطاة بالكامل. أكّد الاستلام لإصدار إيصال الصرف.'):t('Collect only the patient share shown below, then confirm dispensing.','حصّل حصة المريض الموضحة أدناه، ثم أكّد صرف الدواء.')}</p>
 {!covered&&coverage&&!completed&&<p className="checkout-inline-total">{t('Patient amount due','المطلوب من المريض')} <strong>{money(coverage.patientAED)} AED</strong></p>}
 {covered?<div className="checkout-covered"><span><CareIcon name="decision"/></span><div><strong>{coverage?.discountPercent===100?t('100% covered by the state','تغطية الدولة ١٠٠٪'):t('No patient payment due','لا توجد حصة مستحقة على المريض')}</strong><p>{t('No payment is required from the patient.','لا يوجد أي مبلغ مطلوب من المريض.')}</p></div><b>0.00 <small>AED</small></b></div>:!completed&&coverage&&<><fieldset className="checkout-methods"><legend>{t('Payment method','طريقة الدفع')}</legend>{(['Cash','Card'] as const).map(value=><label key={value} className={method===value?'selected':''}><input type="radio" name="checkout-method" value={value} checked={method===value} onChange={()=>{setMethod(value);setReceived(false)}}/><span className="checkout-method-icon"><CareIcon name={value==='Cash'?'cash':'card'}/></span><strong>{value==='Cash'?t('Cash','نقدًا'):t('Card / Visa','بطاقة / فيزا')}</strong><small>{value==='Cash'?t('At the pharmacy counter','عند شباك الصيدلية'):t('Via the payment terminal','من خلال جهاز الدفع')}</small></label>)}</fieldset><label className="checkout-received"><input type="checkbox" checked={received} onChange={e=>setReceived(e.target.checked)}/>{method==='Cash'?t('I confirm the patient share was received in cash.','أؤكد استلام حصة المريض نقدًا.'):t('I confirm the card transaction was approved on the terminal.','أؤكد نجاح عملية البطاقة على جهاز الدفع.')}</label><p className="checkout-note">{t('Demo recording only. This screen does not charge a bank card.','تسجيل تجريبي فقط؛ هذه الشاشة لا تخصم أموالًا من البطاقة.')}</p></>}
 {completed&&<div className="checkout-success" role="status"><CareIcon name="check"/><div><strong>{payment.receiptNumber}</strong><p>{covered?t('Receipt issued without collecting a payment','صدر الإيصال بدون تحصيل أي مبلغ'):t(`Payment recorded · ${payment.method==='Cash'?'Cash':'Card / Visa'}`,`تم تسجيل السداد · ${payment.method==='Cash'?'نقدًا':'بطاقة / فيزا'}`)}</p></div></div>}
 {(error||coverageError)&&<p className="pd-error" role="alert">{error||coverageError}</p>}
 <div className="checkout-actions"><button className="pd-outline" onClick={()=>setPreview('prescription')}><CareIcon name="file"/>{t('Prescription / Print','الوصفة / طباعة')}</button>{completed?<button className="pd-primary" onClick={()=>setPreview('receipt')}><CareIcon name="receipt"/>{t('Receipt / Print','الإيصال / طباعة')}</button>:<button className="pd-primary" disabled={!!coverageError||(!dispense&&blocked)||(!covered&&!received)} onClick={confirm}><CareIcon name={covered?'check':'receipt'}/>{covered?t('Confirm dispensing & issue receipt','تأكيد الصرف وإصدار الإيصال'):t('Confirm payment & dispensing','تأكيد السداد والصرف')}</button>}</div>
 {!completed&&!dispense&&blocked&&<p className="checkout-note">{t('Complete the identity and prescription checks above to continue.','أكمل التحقق من الهوية والوصفة بالأعلى للمتابعة.')}</p>}
 </div><aside className="checkout-summary"><div className="checkout-paper"><div className="checkout-paper-brand"><img src={logo} alt="Health Care"/><span>HEALTH CARE<small>{t('PHARMACY SERVICES','خدمات الصيدلية')}</small></span><CareIcon name="receipt"/></div><div className="checkout-paper-title"><small>{t('YOUR DISPENSING SUMMARY','ملخص عملية الصرف')}</small><strong>{request.medication??'—'} <span>{request.dose}</span></strong><p>{request.prescriptionId??request.id}</p></div><dl><div><dt>{t('Medication total','إجمالي الدواء')}</dt><dd>{coverage?money(coverage.totalAED):'—'} <small>AED</small></dd></div><div className="coverage"><dt>{t('State coverage','تغطية الدولة')}</dt><dd>{coverage?money(coverage.supportAED):'—'} <small>AED</small></dd></div></dl><div className="checkout-due"><span>{completed?t('Patient amount paid','المبلغ المدفوع من المريض'):t('Patient amount due','المطلوب من المريض')}</span><strong>{coverage?money(payment?.amountAED??coverage.patientAED):'—'} <small>AED</small></strong><p><CareIcon name={covered?'decision':'check'}/>{covered?t('Fully covered','مغطى بالكامل'):completed?t('Payment recorded','تم تسجيل السداد'):t('Medication share only','حصة الدواء فقط')}</p></div><div className="checkout-paper-footer"><CareIcon name="file"/>{t('Receipt + prescription in the patient’s file','الإيصال والوصفة في ملف المريض')}</div></div></aside>
 {preview&&<PharmacyDocumentPreview data={data} requestId={requestId} kind={preview} arabic={arabic} onClose={()=>setPreview(null)}/>}</section>
}
