export const reportTranslations: [string, string][] = [
  ['Comprehensive insights across the UAE Treatment Programme, with current and historical records.', 'مؤشرات شاملة لبرنامج العلاج في الإمارات، تشمل السجلات الحالية والسابقة.'],
  ['Data-driven care', 'رعاية تستند إلى البيانات'], ['for a healthier UAE', 'لإمارات أكثر صحة'], ['Monitor. Analyze. Improve.', 'تابع. حلّل. حسّن.'],
  ['Safety & Compliance', 'السلامة والامتثال'], ['Geographic', 'التوزيع الجغرافي'], ['Custom Reports', 'التقارير المخصصة'],
  ['All Programmes', 'جميع البرامج'], ['Patient category', 'فئة المريض'], ['Apply Filters', 'تطبيق الفلاتر'], ['Reset', 'إعادة ضبط'],
  ['vs previous period', 'مقارنة بالفترة السابقة'], ['Dispensed medications', 'الأدوية المصروفة'], ['Current directory', 'الدليل الحالي'],
  ['Programme cost', 'تكلفة البرنامج'], ['No prior-period baseline', 'لا تتوفر بيانات مرجعية للفترة السابقة'],
  ['Treatment requests trend', 'اتجاه طلبات العلاج'], ['Submission period and current request status', 'فترة الإرسال والحالة الحالية للطلبات'],
  ['Monthly', 'شهريًا'], ['Weekly', 'أسبوعيًا'], ['Requests by programme', 'الطلبات حسب البرنامج'], ['Distribution of treatment requests', 'توزيع طلبات العلاج'],
  ['Top 5 centres by requests', 'أعلى 5 مراكز حسب عدد الطلبات'], ['From linked patient care centres', 'وفق مراكز الرعاية المرتبطة بالمرضى'],
  ['Quick reports', 'تقارير سريعة'], ['Financial summary', 'الملخص المالي'], ['Recent reports', 'أحدث التقارير'],
  ['Saved snapshots and live report templates across all modules', 'تقارير محفوظة وقوالب تعتمد على البيانات الحالية في جميع الأقسام'],
  ['Filters', 'الفلاتر'], ['Generate Report', 'إنشاء تقرير'], ['Generated by', 'أُنشئ بواسطة'],
  ['Ready = live data · Completed = saved snapshot · CSV export', 'جاهز = بيانات حالية · مكتمل = تقرير محفوظ · تصدير ملف بيانات'],
  ['saved preference', 'إعداد محفوظ'], ['Monthly programme report', 'تقرير البرنامج الشهري'], ['Safety Alerts Summary', 'ملخص تنبيهات السلامة'],
  ['Demo schedule preferences. Automatic generation and delivery are not connected.', 'إعدادات جدولة تجريبية. الإنشاء والإرسال التلقائي غير متصلين حاليًا.'],
  ['All figures come from the shared programme repository. Date filters use each record’s event date; active centres reflect the current directory. Programme cost is an estimate.', 'جميع الأرقام من مصدر بيانات البرنامج المشترك. تعتمد فلاتر التاريخ على تاريخ الحدث لكل سجل، وتعكس المراكز النشطة الدليل الحالي. تكلفة البرنامج تقديرية.'],
  ['Close report dialog', 'إغلاق نافذة التقرير'], ['Showing 100 rows. CSV export includes all', 'يُعرض 100 صف. يشمل ملف التصدير جميع'], ['records.', 'السجلات.'],
  ['No records match these filters', 'لا توجد سجلات تطابق الفلاتر'], ['Adjust the date range, location, programme or patient category.', 'عدّل الفترة الزمنية أو الموقع أو البرنامج أو فئة المريض.'],
  ['Treatment requests by submission date and current status', 'طلبات العلاج حسب تاريخ الإرسال والحالة الحالية'],
  ['No requests in this period.', 'لا توجد طلبات خلال هذه الفترة.'], ['Treatment Requests Report', 'تقرير طلبات العلاج'],
  ['The report could not be saved. Check browser storage and try again.', 'تعذر حفظ التقرير. تحقق من مساحة تخزين المتصفح ثم أعد المحاولة.'],
  ['Choose a valid start and end date.', 'اختر تاريخ بداية ونهاية صالحين.'], ['Choose a date range of three years or less.', 'اختر فترة لا تتجاوز ثلاث سنوات.'],
  ['Registered in selected period', 'المسجلون خلال الفترة المحددة'], ['Requests submitted in period', 'الطلبات المرسلة خلال الفترة'],
  ['Includes dispensed / completed', 'تشمل المصروف والمكتمل'], ['Recorded dispensing events', 'عمليات الصرف المسجلة'],
  ['Current directory snapshot', 'صورة الدليل الحالي'], ['Estimated treatment cost', 'تكلفة العلاج التقديرية'],
  ['Report categories', 'فئات التقارير'], ['Report filters', 'فلاتر التقارير'], ['Report from date', 'تاريخ بداية التقرير'], ['Report to date', 'تاريخ نهاية التقرير'],
  ['Dismiss report message', 'إغلاق رسالة التقرير'], ['Report overview metrics', 'مؤشرات ملخص التقارير'], ['Trend interval', 'الفترة الزمنية للاتجاه'],
  ['No requests in the selected scope.', 'لا توجد طلبات ضمن النطاق المحدد.'], ['Geographic request breakdown', 'التوزيع الجغرافي للطلبات'],
  ['Matching treatment requests grouped by centre.', 'طلبات العلاج المطابقة مجمّعة حسب المركز.'], ['Export CSV', 'تصدير ملف بيانات'],
  ['Search reports', 'البحث عن التقارير'], ['Search reports...', 'ابحث عن تقرير...'], ['Report status', 'حالة التقرير'],
  ['Ready reports use the current filters. Completed reports preserve their original snapshot and filters.', 'تستخدم التقارير الجاهزة الفلاتر الحالية. وتحتفظ التقارير المكتملة ببياناتها وفلاترها وقت الحفظ.'],
  ['Download CSV', 'تنزيل ملف البيانات'], ['Preview report', 'معاينة التقرير'], ['Generate a new snapshot', 'إنشاء نسخة محفوظة جديدة'],
  ['No matching reports', 'لا توجد تقارير مطابقة'], ['Change the report category, search or status filter.', 'غيّر فئة التقرير أو البحث أو فلتر الحالة.'],
  ['Table view', 'عرض الجدول'], ['CSV preview', 'معاينة ملف البيانات'], ['Report CSV preview', 'معاينة بيانات التقرير'], ['Report dataset', 'مجموعة بيانات التقرير'],
  ['Creates a saved snapshot of the selected records, available for preview and CSV download.', 'يُنشئ نسخة محفوظة من السجلات المحددة، متاحة للمعاينة وتنزيل البيانات.'],
  ['Centres by treatment requests', 'المراكز حسب طلبات العلاج'], ['Report schedule preferences', 'إعدادات جدولة التقارير'],
  ['Preferences are saved locally. Automatic runs and email delivery are not connected. You can generate a report now using the current filters.', 'تُحفظ الإعدادات محليًا. التشغيل التلقائي والإرسال بالبريد غير متصلين. يمكنك إنشاء تقرير الآن باستخدام الفلاتر الحالية.'],
  ['Enabled preference', 'إعداد مفعّل'], ['Disabled preference', 'إعداد معطّل'], ['Generate now', 'إنشاء الآن'],
  ['Download', 'تنزيل'], ['Preview', 'معاينة'], ['Generate', 'إنشاء'], ['Enable', 'تفعيل'],
]

const reportNames: Record<string, string> = {
  'Integrated care plans': 'خطط الرعاية المتكاملة', 'Rehabilitation progress': 'تقدم التأهيل',
  'Patient overview': 'نظرة عامة على المرضى', 'Treatment requests': 'طلبات العلاج',
  'Review performance': 'أداء المراجعة', 'Treatment approvals': 'موافقات العلاج',
  'Rejections': 'الطلبات المرفوضة', 'Missing information': 'المعلومات الناقصة',
  'Pharmacy dispensing': 'صرف الصيدلية', 'Inventory': 'المخزون', 'Low stock': 'المخزون المنخفض',
  'Expiring medication': 'الأدوية القريبة من انتهاء الصلاحية', 'Adherence': 'الالتزام',
  'Appointments': 'المواعيد', 'Financial / coverage': 'المالية والتغطية', 'Audit': 'التدقيق', 'Operational activity': 'النشاط التشغيلي',
}
for (const [name, arabic] of Object.entries(reportNames)) {
  reportTranslations.push([name, arabic], [`${name} Report`, `تقرير ${arabic}`])
}
reportTranslations.push(
  ['Report name', 'اسم التقرير'], ['Report type', 'نوع التقرير'], ['Date range', 'الفترة الزمنية'],
  ['All Emirates', 'جميع الإمارات'], ['Type 2 diabetes', 'السكري من النوع الثاني'], ['Weight management', 'إدارة الوزن'],
  ['Scheduled reports', 'التقارير المجدولة'], ['Weekly inventory report', 'تقرير المخزون الأسبوعي'],
  ['Programme overview', 'نظرة عامة على البرنامج'], ['Medication dispensing', 'صرف الأدوية'],
  ['Patient adherence', 'التزام المرضى'], ['Safety & audit', 'السلامة والتدقيق'], ['Shared programme records', 'سجلات البرنامج المشتركة'],
  ['Processing hours', 'مدة المعالجة بالساعات'], ['Adherence percent', 'نسبة الالتزام'],
  ['Available for strength', 'المتاح حسب التركيز'], ['Requested evidence', 'الأدلة المطلوبة'],
  ['Emirates', 'الإمارات'], ['Centres', 'المراكز'],
)
/** Only translate built-in report names; preserve anything the user types. */
export function arabicReportName(name: string) {
  return reportTranslations.find(([en]) => en.toLowerCase() === name.toLowerCase())?.[1] ?? name
}
