import { arabicReportName } from './ReportTranslations'
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { type AppData, type ReportFilters, type SavedReport } from './domain'
import { CareIcon } from './CareIcon'
import { downloadCsv, serializeCsv, type CsvRow } from './csvExport'
import { defaultReportFilters, isReportKey, reportChoices, reportGroup, reportOverview, reportRows, type ReportKey } from './reporting'
import logo from './assets/healthcare-logo.png'
import './Reports.css'

const tabs = [{label:'Overview',icon:'dashboard'},{label:'Patients',icon:'patients'},{label:'Treatment',icon:'activity'},{label:'Inventory',icon:'box'},{label:'Safety & Compliance',icon:'decision'},{label:'Financial',icon:'file'},{label:'Geographic',icon:'pin'},{label:'Custom Reports',icon:'clipboard'}]
const chartColors = ['#2788ff','#ff9b24','#12b997','#f95472']
const donutColors = ['#55c6ac','#2d8aff','#ffac33','#8a72ef','#b4a1ff']
const labels = (value:string) => value.replace(/([A-Z])/g,' $1').replace(/^./,letter=>letter.toUpperCase())
const rangeLabel = (filters:ReportFilters) => `${filters.from || 'All dates'} – ${filters.to || 'Today'}`
function ReportDialog({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {
  const ref=useRef<HTMLDialogElement>(null)
  useEffect(()=>{const node=ref.current;node?.showModal();return()=>node?.close()},[])
  return <dialog ref={ref} className="rp-dialog" onCancel={event=>{event.preventDefault();onClose()}} aria-labelledby="rp-dialog-title"><header><div><span>UAE treatment programme</span><h2 id="rp-dialog-title">{title}</h2></div><button className="rp-icon-button" aria-label="Close report dialog" onClick={onClose}><CareIcon name="close"/></button></header>{children}</dialog>
}
function DataTable({rows}:{rows:CsvRow[]}) {
  const columns=[...new Set(rows.flatMap(row=>Object.keys(row)))].filter(key=>rows.some(row=>row[key]!==undefined && row[key]!==''))
  return rows.length ? <><div className="rp-data-scroll"><table><thead><tr>{columns.map(key=><th key={key}>{labels(key)}</th>)}</tr></thead><tbody>{rows.slice(0,100).map((row,index)=><tr key={index}>{columns.map(key=><td key={key}>{String(row[key]??'—')}</td>)}</tr>)}</tbody></table></div>{rows.length>100&&<p className="rp-note">Showing 100 rows. CSV export includes all {rows.length} records.</p>}</> : <div className="rp-empty"><CareIcon name="search"/><b>No records match these filters</b><span>Adjust the date range, location, programme or patient category.</span></div>
}
function Trend({rows}:{rows:ReturnType<typeof reportOverview>['trend']}) {
  const ceiling=Math.max(4,Math.ceil(Math.max(0,...rows.map(row=>row.submitted))/4)*4)
  const x=(i:number)=>40+i*490/Math.max(1,rows.length-1), y=(n:number)=>180-n/ceiling*148
  const series=['submitted','review','approved','rejected'] as const
  return <><svg viewBox="0 0 550 215" className="rp-trend" role="img" aria-label="Treatment requests by submission date and current status"><defs>{series.map((key,index)=><linearGradient key={key} id={`rp-${key}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor={chartColors[index]} stopOpacity=".18"/><stop offset="1" stopColor={chartColors[index]} stopOpacity=".01"/></linearGradient>)}</defs>{[0,1,2,3,4].map(tick=><g key={tick}><line x1="40" x2="530" y1={y(tick*ceiling/4)} y2={y(tick*ceiling/4)} stroke="#e9eff5" strokeDasharray="3 3"/><text x="29" y={y(tick*ceiling/4)+4} textAnchor="end">{tick*ceiling/4}</text></g>)}{series.map((key,index)=>{const path=rows.map((row,i)=>`${i?'L':'M'}${x(i)} ${y(row[key])}`).join(' ');return <g key={key}><path d={`${path} L${x(rows.length-1)} 180 L40 180 Z`} fill={`url(#rp-${key})`}/><path d={path} stroke={chartColors[index]} strokeWidth="2" fill="none"/>{rows.map((row,i)=><circle key={row.key} cx={x(i)} cy={y(row[key])} r="3" fill={chartColors[index]} stroke="white"><title>{row.label}: {row[key]} {key}</title></circle>)}</g>})}{rows.map((row,i)=>(rows.length<=12||i%Math.ceil(rows.length/10)===0||i===rows.length-1)&&<text key={row.key} x={x(i)} y="202" textAnchor="middle">{row.label}</text>)}</svg><div className="rp-chart-legend">{['Submitted','Under review','Approved','Rejected'].map((name,index)=><span key={name}><i style={{background:chartColors[index]}}/>{name}</span>)}</div></>
}
function MiniTrend({values,tone}:{values:number[];tone:string}) {
  const max=Math.max(1,...values)
  return <svg className={`rp-mini-trend ${tone}`} viewBox="0 0 48 22" aria-hidden="true"><polyline points={values.map((value,index)=>`${2+index*44/Math.max(1,values.length-1)},${20-value/max*17}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>
}
function Donut({groups,total}:{groups:{name:string;count:number}[];total:number}) {
  let cursor=0
  const stops=groups.map((group,index)=>{const from=cursor;cursor+=group.count/Math.max(1,total)*100;return `${donutColors[index%donutColors.length]} ${from}% ${cursor}%`})
  return <div className="rp-distribution"><div className="rp-donut" style={{background:total?`conic-gradient(${stops.join(',')})`:'#eaf0f5'}}><div><b>{total.toLocaleString()}</b><small>Total requests</small></div></div><div className="rp-donut-legend">{groups.map((group,index)=><div key={group.name}><i style={{background:donutColors[index%donutColors.length]}}/><span>{group.name}</span><b>{Math.round(group.count/Math.max(1,total)*100)}%</b><small>{group.count}</small></div>)}{!groups.length&&<p>No requests in this period.</p>}</div></div>
}

export function Reports({data,now,onUpdate,arabic=false}:{data:AppData;now:Date;arabic?:boolean;onUpdate:(data:AppData)=>void}) {
  const defaults=useMemo(()=>defaultReportFilters(now),[now])
  const [draft,setDraft]=useState<ReportFilters>(defaults),[filters,setFilters]=useState<ReportFilters>(defaults)
  const [tab,setTab]=useState('Overview'),[interval,setInterval]=useState<'Monthly'|'Weekly'>('Monthly')
  const [query,setQuery]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('')
  const [preview,setPreview]=useState<{name:string;rows:CsvRow[];range:string}|null>(null),[showCsv,setShowCsv]=useState(false)
  const [generate,setGenerate]=useState(false),[reportKey,setReportKey]=useState<ReportKey>('requests'),[reportName,setReportName]=useState('Treatment Requests Report')
  const [schedulesOpen,setSchedulesOpen]=useState(false),[centresOpen,setCentresOpen]=useState(false),[advanced,setAdvanced]=useState(false),[reportStatus,setReportStatus]=useState('All')
  const overview=useMemo(()=>reportOverview(data,filters,now,interval),[data,filters,now,interval])
  const updateDraft=(key:keyof ReportFilters,value:string)=>setDraft(current=>({...current,[key]:value}))
  const titleFor=(key:ReportKey)=>reportChoices.find(item=>item.id===key)!.label
  const rowsFor=(key:ReportKey)=>reportRows(data,key,filters,now.getTime())
  const showReport=(key:ReportKey)=>{setShowCsv(false);setPreview({name:titleFor(key),rows:rowsFor(key),range:rangeLabel(filters)})}
  const generateReport=(key:ReportKey,name:string)=>{
    const saved:SavedReport={id:crypto.randomUUID(),name:name.trim()||`${titleFor(key)} Report`,type:key,generatedAt:new Date().toISOString(),generatedBy:'Admin',filters:{...filters},rows:structuredClone(rowsFor(key))}
    try { onUpdate({...data,savedReports:[saved,...(data.savedReports??[])]}) } catch { setError('The report could not be saved. Check browser storage and try again.');return }
    setError('');setGenerate(false);setMessage(`${saved.name} generated with ${saved.rows.length} records.`)
  }
  const apply=()=>{if(!draft.from||!draft.to||draft.from>draft.to){setError('Choose a valid start and end date.');return}if(Date.parse(draft.to)-Date.parse(draft.from)>3*366*86400000){setError('Choose a date range of three years or less.');return}setError('');setFilters({...draft});setTab('Overview')}
  const chooseTab=(next:string)=>{setTab(next);setQuery('');setReportStatus('All');setAdvanced(false)}
  const recentKeys:ReportKey[]=['requests','inventory','adherence','audit','financial']
  const templates=(tab==='Overview'?reportChoices.filter(item=>recentKeys.includes(item.id)):reportChoices.filter(item=>tab==='Custom Reports'||tab==='Geographic'||reportGroup(item.id)===tab)).map(item=>({id:`live-${item.id}`,name:`${item.label} Report`,type:item.id,generatedBy:'Shared programme records',range:rangeLabel(filters),rows:rowsFor(item.id),status:'Ready',saved:false}))
  const saved=(data.savedReports??[]).filter(item=>(!filters.from||item.filters.to>=filters.from)&&(!filters.to||item.filters.from<=filters.to)&&(filters.scope==='All'||item.filters.scope===filters.scope)&&(filters.programme==='All'||item.filters.programme===filters.programme)&&(filters.category==='All'||item.filters.category===filters.category)).map(item=>({id:item.id,name:item.name,type:item.type,generatedBy:item.generatedBy,range:rangeLabel(item.filters),rows:item.rows,status:'Completed',saved:true}))
  const listed=[...saved,...templates].filter(item=>(tab==='Overview'||tab==='Geographic'||tab==='Custom Reports'||reportGroup(item.type)===tab)&&(filters.type==='All'||reportGroup(item.type)===filters.type)&&(reportStatus==='All'||item.status===reportStatus)&&`${item.name} ${reportGroup(item.type)}`.toLowerCase().includes(query.toLowerCase()))
  const metrics=[{label:'Total patients',icon:'patients',tone:'blue',note:'Registered in selected period'},{label:'Treatment requests',icon:'file',tone:'blue',note:'Requests submitted in period'},{label:'Approved requests',icon:'check',tone:'teal',note:'Includes dispensed / completed'},{label:'Dispensed medications',icon:'box',tone:'amber',note:'Recorded dispensing events'},{label:'Active centres',icon:'building',tone:'violet',note:'Current directory snapshot'},{label:'Programme cost',icon:'file',tone:'rose',note:'Estimated treatment cost'}]
  const currentGroups=overview.programmes.length>5?[...overview.programmes.slice(0,4),{name:'Other',count:overview.programmes.slice(4).reduce((sum,item)=>sum+item.count,0)}]:overview.programmes
  const quick: {label:string;key:ReportKey;icon:string}[]=[{label:'Programme overview',key:'patients',icon:'patients'},{label:'Treatment requests',key:'requests',icon:'file'},{label:'Medication dispensing',key:'dispensing',icon:'box'},{label:'Inventory status',key:'inventory',icon:'clipboard'},{label:'Patient adherence',key:'adherence',icon:'activity'},{label:'Safety & audit',key:'audit',icon:'alert'},{label:'Financial summary',key:'financial',icon:'file'}]
  return <div className="reports-workspace"><section className="rp-hero"><div><div className="rp-breadcrumb">Programme <span>/</span> Reports</div><h1>Reports</h1><p>Comprehensive insights across the UAE Treatment Programme, with current and historical records.</p></div><div className="rp-hero-note"><img src={logo} alt=""/><span><b>Data-driven care<br/>for a healthier UAE</b><small>Monitor. Analyze. Improve.</small></span></div></section>
    <div className="rp-body"><nav className="rp-tabs" aria-label="Report categories">{tabs.map(item=><button key={item.label} aria-pressed={tab===item.label} onClick={()=>chooseTab(item.label)}><CareIcon name={item.icon}/>{item.label}</button>)}</nav>
    <section className="rp-filter-panel" aria-label="Report filters"><div className="rp-filters"><fieldset className="rp-date-range"><legend>Date range</legend><div><CareIcon name="calendar"/><input type="date" aria-label="Report from date" value={draft.from} max={draft.to} onChange={event=>updateDraft('from',event.target.value)}/><span>–</span><input type="date" aria-label="Report to date" value={draft.to} min={draft.from} onChange={event=>updateDraft('to',event.target.value)}/></div></fieldset><label>Emirate / centre<select value={draft.scope} onChange={event=>updateDraft('scope',event.target.value)}><option value="All">All Emirates</option><optgroup label="Emirates">{[...new Set(data.centres.map(item=>item.emirate))].sort().map(item=><option key={item}>{item}</option>)}</optgroup><optgroup label="Centres">{data.centres.map(item=><option key={item.id}>{item.name}</option>)}</optgroup></select></label><label>Programme<select value={draft.programme} onChange={event=>updateDraft('programme',event.target.value)}><option value="All">All Programmes</option>{[...new Set(data.patients.map(item=>item.diagnosis))].sort().map(item=><option key={item}>{item}</option>)}</select></label><label>Patient category<select value={draft.category} onChange={event=>updateDraft('category',event.target.value)}><option value="All">All</option>{[...new Set(data.patients.map(item=>item.residency).filter(Boolean))].map(item=><option key={item}>{item}</option>)}</select></label><label>Report type<select value={draft.type} onChange={event=>updateDraft('type',event.target.value)}><option>All</option>{tabs.slice(1,6).map(item=><option key={item.label}>{item.label}</option>)}</select></label><div className="rp-filter-actions"><button className="rp-primary" onClick={apply}><CareIcon name="filter"/>Apply Filters</button><button className="rp-secondary" onClick={()=>{setDraft(defaults);setFilters(defaults);setTab('Overview');setQuery('');setError('');setReportStatus('All')}}><CareIcon name="reset"/>Reset</button></div></div>{error&&<p className="rp-error" role="alert">{error}</p>}</section>
    {message&&<div className="rp-message" role="status"><CareIcon name="check"/>{message}<button aria-label="Dismiss report message" onClick={()=>setMessage('')}><CareIcon name="close"/></button></div>}
    <section className="rp-kpis" aria-label="Report overview metrics">{metrics.map((item,index)=>{const value=overview.totals[index],previous=overview.prior[index];const change=previous?Math.round((value-previous)/previous*100):null;return <article key={item.label}><span className={`rp-icon ${item.tone}`}><CareIcon name={item.icon}/></span><div><span>{item.label}</span><div className="rp-kpi-value"><strong>{index===5?`${new Intl.NumberFormat('en',{notation:value>=1000000?'compact':'standard',maximumFractionDigits:1}).format(value)} AED`:value.toLocaleString()}</strong>{index!==4&&change!==null&&<small className={change>=0?'rp-positive':'rp-negative'}>{change>=0?'↑':'↓'} {Math.abs(change)}%</small>}</div><small title={item.note}>{index===4?'Current directory':previous?'vs previous period':'No prior-period baseline'}</small></div>{index!==4&&<MiniTrend values={overview.sparkSeries[index]} tone={item.tone}/>}</article>})}</section>
    <div className="rp-analysis-grid"><section className="rp-card rp-trend-card"><div className="rp-card-heading"><div><h2>Treatment requests trend</h2><p>Submission period and current request status</p></div><select aria-label="Trend interval" value={interval} onChange={event=>setInterval(event.target.value as typeof interval)}><option>Monthly</option><option>Weekly</option></select></div><Trend rows={overview.trend}/></section><section className="rp-card rp-programme-card"><div className="rp-card-heading"><div><h2>Requests by programme</h2><p>Distribution of treatment requests</p></div></div><Donut groups={currentGroups} total={overview.requests.length}/></section><section className="rp-card rp-centres-card"><div className="rp-card-heading"><div><h2>Top 5 centres by requests</h2><p>From linked patient care centres</p></div></div><button className="rp-link rp-centres-all" onClick={()=>setCentresOpen(true)}>View all</button><div className="rp-centre-bars">{overview.centres.slice(0,5).map(item=><div key={item.name}><div><span>{item.name}</span><b>{item.count}</b></div><div className="rp-bar"><i style={{width:`${item.count/Math.max(1,overview.centres[0]?.count??0)*100}%`}}/></div></div>)}{!overview.centres.length&&<p className="rp-note">No requests in the selected scope.</p>}</div></section><section className="rp-card rp-quick"><h2>Quick reports</h2>{quick.map(item=><button key={item.key} onClick={()=>showReport(item.key)}><span className="rp-mini-icon"><CareIcon name={item.icon}/></span><span>{item.label}</span><span aria-hidden="true">›</span></button>)}</section></div>
    {tab==='Geographic'&&<section className="rp-card rp-geography"><div className="rp-card-heading"><div><h2>Geographic request breakdown</h2><p>Matching treatment requests grouped by centre.</p></div><button className="rp-secondary" onClick={()=>downloadCsv('geographic-request-report.csv',overview.centres)}>Export CSV</button></div><DataTable rows={overview.centres}/></section>}
    <div className="rp-bottom-grid"><section className="rp-card rp-recent"><div className="rp-card-heading"><div><h2>{tab==='Custom Reports'?'Custom reports':'Recent reports'}</h2><p>Saved snapshots and live report templates across all modules</p></div><div className="rp-table-actions"><label className="rp-search"><CareIcon name="search"/><input aria-label="Search reports" placeholder="Search reports..." value={query} onChange={event=>setQuery(event.target.value)}/></label><button className="rp-secondary" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}><CareIcon name="filter"/>Filters</button><button className="rp-primary" onClick={()=>{setGenerate(true);setReportKey('requests');setReportName('Treatment Requests Report')}}><CareIcon name="plus"/>Generate Report</button></div></div>{advanced&&<div className="rp-table-filter"><label>Report status<select value={reportStatus} onChange={event=>setReportStatus(event.target.value)}><option>All</option><option>Ready</option><option>Completed</option></select></label><span>Ready reports use the current filters. Completed reports preserve their original snapshot and filters.</span></div>}
    <div className="rp-table-scroll"><table className="rp-recent-table"><thead><tr>{['Report name','Type','Date range','Generated by','Status','Records','Actions'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{listed.map(item=><tr key={item.id}><td><span className={`rp-file-icon ${reportGroup(item.type)==='Inventory'?'teal':'rose'}`}><CareIcon name="file"/></span><b>{item.name}</b></td><td>{reportGroup(item.type)}</td><td>{item.range}</td><td>{item.generatedBy}</td><td><span className={`rp-status ${item.saved?'completed':'ready'}`}>{item.status}</span></td><td>{item.rows.length.toLocaleString()}</td><td><div className="rp-row-actions"><button className="rp-icon-button" title="Download CSV" aria-label={`Download ${item.name}`} disabled={!item.rows.length} onClick={()=>downloadCsv(`${item.name.replaceAll(' ','-')}.csv`,item.rows)}><CareIcon name="download"/></button><button className="rp-icon-button" title="Preview report" aria-label={`Preview ${item.name}`} onClick={()=>{setShowCsv(false);setPreview({name:item.name,rows:item.rows,range:item.range})}}><CareIcon name="eye"/></button><button className="rp-icon-button" title="Generate a new snapshot" aria-label={`Generate ${item.name}`} onClick={()=>{setReportKey(isReportKey(item.type)?item.type:'requests');setReportName(item.name);setGenerate(true)}}><CareIcon name="plus"/></button></div></td></tr>)}</tbody></table>{!listed.length&&<div className="rp-empty"><b>No matching reports</b><span>Change the report category, search or status filter.</span></div>}</div><div className="rp-table-footer"><span>{listed.length} reports</span><span>Ready = live data · Completed = saved snapshot · CSV export</span></div></section>
    <aside className="rp-card rp-schedules"><div className="rp-card-heading"><h2>Scheduled reports</h2><button className="rp-link" onClick={()=>setSchedulesOpen(true)}>View all</button></div>{(data.reportSchedules??[]).map(item=><div className="rp-schedule" key={item.id}><span className="rp-mini-icon"><CareIcon name="calendar"/></span><div><b>{item.name}</b><small>{item.frequency} · saved preference</small></div><button className="rp-switch" role="switch" aria-label={`Enable ${item.name}`} aria-checked={item.enabled} onClick={()=>onUpdate({...data,reportSchedules:data.reportSchedules?.map(row=>row.id===item.id?{...row,enabled:!row.enabled}:row)})}><span/></button></div>)}<p className="rp-schedule-note">Demo schedule preferences. Automatic generation and delivery are not connected.</p></aside></div>
    <p className="rp-source-note"><i/> All figures come from the shared programme repository. Date filters use each record’s event date; active centres reflect the current directory. Programme cost is an estimate.</p></div>
    {preview&&<ReportDialog title={preview.name} onClose={()=>setPreview(null)}><div className="rp-preview-heading"><span>{preview.range} · {preview.rows.length} records</span><div><button className="rp-secondary" onClick={()=>setShowCsv(!showCsv)}>{showCsv?'Table view':'CSV preview'}</button><button className="rp-primary" disabled={!preview.rows.length} onClick={()=>downloadCsv(`${preview.name.replaceAll(' ','-')}.csv`,preview.rows)}><CareIcon name="download"/>Download CSV</button></div></div>{showCsv?<textarea className="rp-csv-preview" aria-label="Report CSV preview" readOnly value={serializeCsv(preview.rows)}/>:<DataTable rows={preview.rows}/>}</ReportDialog>}
    {generate&&<ReportDialog title="Generate report" onClose={()=>setGenerate(false)}><form className="rp-generate-form" onSubmit={event=>{event.preventDefault();generateReport(reportKey,reportName)}}>{error&&<p className="rp-error" role="alert">{error}</p>}<label>Report name<input required maxLength={120} value={arabic ? arabicReportName(reportName) : reportName} onChange={event=>setReportName(event.target.value)}/></label><label>Report dataset<select value={reportKey} onChange={event=>{setReportKey(event.target.value as ReportKey);setReportName(`${titleFor(event.target.value as ReportKey)} Report`)}}>{reportChoices.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><div className="rp-generation-summary"><b>{rowsFor(reportKey).length} matching records</b><span>{rangeLabel(filters)}</span><span>{filters.scope} · {filters.programme} · {filters.category}</span><p>Creates a saved snapshot of the selected records, available for preview and CSV download.</p></div><div className="rp-dialog-actions"><button type="button" className="rp-secondary" onClick={()=>setGenerate(false)}>Cancel</button><button className="rp-primary" type="submit">Generate report</button></div></form></ReportDialog>}
    {centresOpen&&<ReportDialog title="Centres by treatment requests" onClose={()=>setCentresOpen(false)}><DataTable rows={overview.centres}/></ReportDialog>}
    {schedulesOpen&&<ReportDialog title="Report schedule preferences" onClose={()=>setSchedulesOpen(false)}><p className="rp-note">Preferences are saved locally. Automatic runs and email delivery are not connected. You can generate a report now using the current filters.</p>{(data.reportSchedules??[]).map(item=><div className="rp-schedule-detail" key={item.id}><div><b>{item.name}</b><span>{item.frequency} · {item.enabled?'Enabled preference':'Disabled preference'}</span></div><button className="rp-primary" onClick={()=>{generateReport(isReportKey(item.report)?item.report:'requests',item.name);setSchedulesOpen(false)}}>Generate now</button></div>)}</ReportDialog>}
  </div>
}
