import { useState, type FormEvent } from 'react'
import { CareIcon } from './CareIcon'
import { useDialogFocus } from './useDialogFocus'
import { createOperationalAlert, dismissAlert, markAlertRead, can, type AppData, type ManualAlert, type Role } from './domain'
import { alertsWorkspaceData, alertTypeIcon, type WorkspaceAlert } from './alertsWorkspaceData'
import type { AdminPage } from './adminAnalytics'
import { localizeArabic } from './ArabicText'
import * as catalogue from './ArabicCatalogue'
import './SafetyAlerts.css'

type Props={data:AppData;role:Role;arabic:boolean;onUpdate:(data:AppData)=>void;onNavigate:(page:AdminPage,id?:string)=>void}
const arLabels:Record<string,string>={Inventory:'المخزون',Treatment:'العلاج',Safety:'السلامة',Clinical:'الالتزام',Appointments:'المواعيد',Critical:'عالية',Warning:'متوسطة',Info:'منخفضة',High:'عالية',Medium:'متوسطة',Low:'منخفضة',Unread:'غير مقروء',Read:'مقروء',Information:'معلومات إضافية',Handled:'تم التعامل معه'}
const initialDraft:Omit<ManualAlert,'id'|'timestamp'>={title:'',detail:'',category:'Safety',severity:'Warning',priority:'Medium',centre:'',medicationId:''}
export function SafetyAlerts({data,role,arabic,onUpdate,onNavigate}:Props){
 const t=(en:string,ar:string)=>arabic?ar:en
 const label=(v:string)=>arabic?arLabels[v]??v:v
 const local=(v:string)=>arabic?localizeArabic(v,catalogue):v
 const [clock]=useState(()=>Date.now())
 const rows=alertsWorkspaceData(data,role,clock)
 const [query,setQuery]=useState(''),[severity,setSeverity]=useState('All'),[category,setCategory]=useState('All'),[state,setState]=useState('All'),[priority,setPriority]=useState('All'),[period,setPeriod]=useState('All'),[sort,setSort]=useState('Newest')
 const [page,setPage]=useState(1),[size,setSize]=useState(10),[selection,setSelection]=useState<string[]>([])
 const [detailId,setDetailId]=useState<string|null>(null),[creating,setCreating]=useState(false),[draft,setDraft]=useState(initialDraft),[error,setError]=useState('')
 const selected=rows.find(a=>a.id===detailId)
 const close=()=>{setCreating(false);setDetailId(null);setError('')}
 const dialogRef=useDialogFocus(creating||!!selected,close)
 const editable=can(role,'alerts:manage')
 const time=(a:WorkspaceAlert)=>Number.isFinite(Date.parse(a.timestamp))?Date.parse(a.timestamp):0
 const filtered=rows.filter(a=>(!query||local(`${a.title} ${a.detail} ${a.medication??''} ${a.dose??''} ${a.centre??''} ${a.patientName??''} ${a.patientNameAr??''} ${a.entityId??''}`).toLowerCase().includes(query.trim().toLowerCase()))&&(severity==='All'||a.severity===severity)&&(category==='All'||a.category===category)&&(state==='All'||a.state===state)&&(priority==='All'||a.priority===priority)&&(period==='All'||time(a)>=clock-Number(period)*86400000)).sort((a,b)=>sort==='Priority'?({High:0,Medium:1,Low:2}[a.priority]-{High:0,Medium:1,Low:2}[b.priority])||time(b)-time(a):sort==='Oldest'?time(a)-time(b):time(b)-time(a))
 const pages=Math.max(1,Math.ceil(filtered.length/size)),current=Math.min(page,pages),shown=filtered.slice((current-1)*size,current*size)
 const reset=()=>{setQuery('');setSeverity('All');setCategory('All');setState('All');setPriority('All');setPeriod('All');setSort('Newest');setPage(1);setSelection([])}
 const bulk=(action:'read'|'handle',ids=selection)=>{if(!ids.length)return;onUpdate(ids.reduce((next,id)=>action==='read'?markAlertRead(next,role,id):dismissAlert(next,role,id),data));setSelection([])}
 const open=(a:WorkspaceAlert)=>{setDetailId(a.id);if(editable&&!data.readAlerts?.includes(a.id))onUpdate(markAlertRead(data,role,a.id))}
 const save=(event:FormEvent)=>{event.preventDefault();try{onUpdate(createOperationalAlert(data,role,draft));close();reset()}catch(e){setError(local(e instanceof Error?e.message:String(e)))}}
 const filter=(name:string,value:string,update:(v:string)=>void,values:string[],all:string,icon:string)=><label className="sa-filter"><CareIcon name={icon}/><span className="sr-only">{name}</span><select aria-label={name} value={value} onChange={e=>{update(e.target.value);setPage(1)}}><option value="All">{all}</option>{values.map(v=><option value={v} key={v}>{label(v)}</option>)}</select></label>
 const stats=[{title:t('Handled','تم التعامل معها'),value:rows.filter(a=>a.state==='Handled').length,tone:'green',icon:'check'},{title:t('Information needed','معلومات إضافية'),value:rows.filter(a=>a.state==='Information').length,tone:'blue',icon:'info'},{title:t('Requires action','تتطلب إجراء'),value:rows.filter(a=>a.state!=='Handled'&&a.severity!=='Info').length,tone:'amber',icon:'clock'},{title:t('Unread','غير مقروء'),value:rows.filter(a=>a.state!=='Handled'&&!data.readAlerts?.includes(a.id)).length,tone:'red',icon:'alert'}]
 return <div className="safety-alerts" dir={arabic?'rtl':'ltr'}>
 <section className="sa-hero"><div className="sa-hero-copy"><small>{t('Your safety & supply workspace','مساحة متابعة السلامة والإمداد')}</small><h1><CareIcon name="decision"/>{t('Safety & supply alerts','تنبيهات السلامة والإمداد')}</h1><p>{t('Proactive monitoring for patient safety and medication continuity across the UAE.','مراقبة استباقية لضمان سلامة المرضى واستمرارية توفر الأدوية في جميع أنحاء الإمارات.')}</p></div><div className="sa-stats">{stats.map(s=><div className={`sa-stat ${s.tone}`} key={s.tone}><div><span><CareIcon name={s.icon}/></span><strong>{s.value}</strong></div><small>{s.title}</small></div>)}</div></section>
 <section className="sa-panel"><div className="sa-toolbar"><label className="sa-search"><CareIcon name="search"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} aria-label={t('Search alerts','بحث في التنبيهات')} placeholder={t('Search alerts, medication, patient, stock or centre…','ابحث في التنبيهات (الدواء، المريض، المخزون، المركز...)')}/></label><div className="sa-toolbar-actions">{editable&&<><details className="sa-menu"><summary aria-label={t('Bulk actions','إجراءات جماعية')}><CareIcon name="more"/></summary><div><button disabled={!selection.length} onClick={()=>bulk('read')}>{t('Mark selected as read','تحديد المختار كمقروء')}</button><button disabled={!selection.length} onClick={()=>bulk('handle')}>{t('Mark selected as handled','تحديد المختار كتم التعامل معه')}</button></div></details><button className="sa-primary" onClick={()=>{setDraft(initialDraft);setCreating(true);setError('')}}><CareIcon name="plus"/>{t('New alert','تنبيه جديد')}</button></>}</div></div>
 <div className="sa-filters"><label className="sa-filter"><CareIcon name="calendar"/><span className="sr-only">{t('Time period','الفترة الزمنية')}</span><select aria-label={t('Time period','الفترة الزمنية')} value={period} onChange={e=>{setPeriod(e.target.value);setPage(1)}}><option value="All">{t('All time','الفترة الزمنية: الكل')}</option><option value="1">{t('Last 24 hours','آخر ٢٤ ساعة')}</option><option value="7">{t('Last 7 days','آخر ٧ أيام')}</option><option value="30">{t('Last 30 days','آخر ٣٠ يومًا')}</option></select></label>{filter(t('Severity','الخطورة'),severity,setSeverity,['Critical','Warning','Info'],t('All severities','جميع مستويات الخطورة'),'decision')}{filter(t('Read state','حالة القراءة'),state,setState,['Unread','Read','Information','Handled'],t('All read states','جميع حالات القراءة'),'file')}{filter(t('Type','النوع'),category,setCategory,[...new Set(rows.map(a=>a.category))],t('All types','جميع الأنواع'),'box')}{filter(t('Priority','الأولوية'),priority,setPriority,['High','Medium','Low'],t('All priorities','جميع الأولويات'),'filter')}<button className="sa-reset" onClick={reset}><CareIcon name="reset"/>{t('Reset','إعادة الضبط')}</button></div>
 <div className="sa-results"><span>{t(`${filtered.length} alerts found`,`تم العثور على ${filtered.length} تنبيه`)}{selection.length>0&&` · ${selection.length} ${t('selected','محدد')}`}</span><label><CareIcon name="filter"/><select aria-label={t('Sort alerts','ترتيب التنبيهات')} value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="Newest">{t('Sort: newest first','ترتيب: الأحدث أولًا')}</option><option value="Oldest">{t('Oldest first','الأقدم أولًا')}</option><option value="Priority">{t('Highest priority','الأولوية الأعلى')}</option></select></label></div>
 <div className="sa-table-scroll"><table><thead><tr><th><input type="checkbox" aria-label={t('Select visible alerts','تحديد التنبيهات الظاهرة')} checked={shown.length>0&&shown.every(a=>selection.includes(a.id))} onChange={e=>setSelection(e.target.checked?[...new Set([...selection,...shown.map(a=>a.id)])]:selection.filter(id=>!shown.some(a=>a.id===id)))}/></th>{[['Alert','التنبيه'],['Type','النوع'],['Severity','الخطورة'],['Medication / product','الدواء / المنتج'],['Location / centre','الموقع / المركز'],['Date and time','التاريخ والوقت'],['Status','الحالة'],['Actions','إجراءات']].map(([en,ar])=><th key={en}>{t(en,ar)}</th>)}</tr></thead><tbody>{shown.map(a=><tr key={a.id} className={selection.includes(a.id)?'selected':''}><td><input type="checkbox" aria-label={`${t('Select','تحديد')} ${local(a.title)}`} checked={selection.includes(a.id)} onChange={e=>setSelection(e.target.checked?[...selection,a.id]:selection.filter(id=>id!==a.id))}/></td><td className="sa-title"><b>{local(a.title)}</b><small>{local(a.detail)}</small></td><td><span className="sa-type"><CareIcon name={alertTypeIcon(a.category)}/>{label(a.category)}</span></td><td><span className={`sa-badge ${a.severity.toLowerCase()}`}><CareIcon name={a.severity==='Critical'?'alert':a.severity==='Warning'?'info':'clock'}/>{label(a.severity)}</span></td><td>{a.medication?local(`${a.medication}${a.dose?' '+a.dose:''}`):'—'}</td><td>{a.centre?local(a.centre):t('Programme-wide','على مستوى البرنامج')}</td><td className="sa-date">{time(a)?<><span>{a.timestamp.includes('T')?new Date(time(a)).toLocaleTimeString(arabic?'ar-AE':'en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Dubai'}):'—'}</span><span>{new Date(time(a)).toLocaleDateString('en-GB',{timeZone:'Asia/Dubai'}).replaceAll('/','-')}</span></>:'—'}</td><td><span className={`sa-badge state-${a.state.toLowerCase()}`}><i/>{label(a.state)}</span></td><td><div className="sa-row-actions"><button onClick={()=>open(a)}>{t('Open','فتح')}</button>{editable&&<details className="sa-menu"><summary aria-label={`${t('Actions','إجراءات')} ${a.id}`}><CareIcon name="more"/></summary><div><button onClick={()=>bulk('read',[a.id])}>{t('Mark read','تحديد كمقروء')}</button><button disabled={a.state==='Handled'} onClick={()=>bulk('handle',[a.id])}>{t('Mark handled','تم التعامل معه')}</button></div></details>}</div></td></tr>)}</tbody></table></div>
 {!filtered.length&&<div className="sa-empty"><CareIcon name="bell"/><h2>{t('No matching alerts','لا توجد تنبيهات مطابقة')}</h2><p>{t('Try a different search or reset the filters.','جرّب بحثًا آخر أو أعد ضبط الفلاتر.')}</p><button onClick={reset}>{t('Reset filters','إعادة ضبط الفلاتر')}</button></div>}
 <footer className="sa-pagination"><div><button aria-label={t('Previous page','الصفحة السابقة')} disabled={current===1} onClick={()=>setPage(current-1)}>‹</button>{Array.from({length:Math.min(pages,5)},(_,i)=>{const n=Math.max(1,Math.min(current-2,pages-4))+i;return <button key={n} aria-current={n===current?'page':undefined} className={n===current?'active':''} onClick={()=>setPage(n)}>{n}</button>})}<button aria-label={t('Next page','الصفحة التالية')} disabled={current===pages} onClick={()=>setPage(current+1)}>›</button></div><span>{filtered.length?(current-1)*size+1:0} – {Math.min(current*size,filtered.length)} {t('of','من')} {filtered.length} {t('alerts','تنبيه')}</span><label>{t('Show','عرض')}<select aria-label={t('Rows per page','عدد الصفوف في الصفحة')} value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[10,20,50].map(n=><option key={n}>{n}</option>)}</select>{t('per page','لكل صفحة')}</label></footer></section>
 {(creating||selected)&&<div className="sa-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section ref={dialogRef} className="sa-dialog" role="dialog" aria-modal="true" aria-label={creating?t('New alert','تنبيه جديد'):t('Alert details','تفاصيل التنبيه')}><header><h2>{creating?t('New alert','تنبيه جديد'):local(selected!.title)}</h2><button aria-label={t('Close','إغلاق')} onClick={close}><CareIcon name="close"/></button></header>{creating?<form onSubmit={save}><label>{t('Title','عنوان التنبيه')}<input required maxLength={150} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>{t('Details','التفاصيل')}<textarea required rows={3} maxLength={1000} value={draft.detail} onChange={e=>setDraft({...draft,detail:e.target.value})}/></label><div className="sa-form-grid">{(['category','severity','priority'] as const).map(key=><label key={key}>{t(key==='category'?'Type':key==='severity'?'Severity':'Priority',key==='category'?'النوع':key==='severity'?'الخطورة':'الأولوية')}<select value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}>{(key==='category'?['Inventory','Treatment','Safety','Clinical','Appointments']:key==='severity'?['Critical','Warning','Info']:['High','Medium','Low']).map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>)}<label>{t('Centre','المركز')}<select value={draft.centre} onChange={e=>setDraft({...draft,centre:e.target.value})}><option value="">{t('Programme-wide','على مستوى البرنامج')}</option>{data.centres.map(c=><option key={c.id} value={c.name}>{local(c.name)}</option>)}</select></label><label>{t('Medication','الدواء')}<select value={draft.medicationId} onChange={e=>setDraft({...draft,medicationId:e.target.value})}><option value="">{t('Not specified','غير محدد')}</option>{data.medications?.map(m=><option key={m.id} value={m.id}>{local(m.name)}</option>)}</select></label></div>{error&&<p role="alert">{error}</p>}<footer><button type="button" onClick={close}>{t('Cancel','إلغاء')}</button><button className="sa-primary" type="submit">{t('Create alert','إنشاء التنبيه')}</button></footer></form>:selected&&<><p>{local(selected.detail)}</p><dl><dt>{t('Type','النوع')}</dt><dd>{label(selected.category)}</dd><dt>{t('Priority','الأولوية')}</dt><dd>{label(selected.priority)}</dd><dt>{t('Status','الحالة')}</dt><dd>{label(selected.state)}</dd><dt>{t('Related record','السجل المرتبط')}</dt><dd dir="ltr">{selected.entityId??'—'}</dd></dl><footer>{selected.page!=='Alerts'&&<button onClick={()=>onNavigate(selected.page,selected.entityId)}>{t('Open related record','فتح السجل المرتبط')}</button>}{editable&&selected.state!=='Handled'&&<button className="sa-primary" onClick={()=>{bulk('handle',[selected.id]);close()}}>{t('Mark handled','تم التعامل معه')}</button>}</footer></>}</section></div>}
 </div>
}
