import {CareIcon} from './CareIcon'
import {can,treatmentEligibility,type AppData,type Role} from './domain'
import {localizeArabic} from './ArabicText'
import * as catalogue from './ArabicCatalogue'
import './TreatmentEligibility.css'
export function TreatmentEligibility({data,role,patientId,planId,arabic,onRequest,onInventory,onPlan,onBack,onCreateRequest}:{data:AppData;role:Role;patientId:string;planId?:string|null;arabic:boolean;onRequest:(id?:string)=>void;onInventory:()=>void;onPlan:()=>void;onBack:()=>void;onCreateRequest:()=>void}){
 const t=(en:string,ar:string)=>arabic?ar:en,local=(v:string)=>arabic?localizeArabic(v.replace('Next medication dispensing date:','موعد صرف الدواء التالي:').replace('Submitted clinical assessment missing','لم يُسجّل تقييم سريري معتمد').replace('HbA1c result missing','نتيجة السكر التراكمي غير مسجلة').replace('kg/m²','كجم/م²'),catalogue):v
 const patient=data.patients.find(p=>p.id===patientId)!
 const eligibility=treatmentEligibility(data,patientId)
 const plan=data.integratedCarePlans?.find(p=>p.patientId===patientId&&p.id===planId)??data.integratedCarePlans?.filter(p=>p.patientId===patientId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]
 const request=data.requests.find(r=>r.id===plan?.treatmentRequestId)??data.requests.filter(r=>r.patientId===patientId).sort((a,b)=>(b.createdAt??b.created).localeCompare(a.createdAt??a.created))[0]
 const vital=data.vitals.filter(v=>v.patientId===patientId).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt))[0]
 const labs=data.labs.filter(l=>l.patientId===patientId&&l.status!=='Pending').sort((a,b)=>b.date.localeCompare(a.date))
 const a1c=labs.find(l=>l.test.toLowerCase()==='hba1c'),glucose=labs.find(l=>/glucose|fasting blood sugar/i.test(l.test))
 const criteria=eligibility.clinical.criteria.filter(c=>c.passed)
 const attention=[...eligibility.reasons.map(local),...eligibility.clinical.warnings.map(local)]
 const steps=[{label:t('Medical assessment','التقييم الطبي'),state:eligibility.assessment?t('Completed','مكتمل'):t('Required','مطلوب'),done:eligibility.assessment},{label:t('Treatment eligibility','أهلية العلاج'),state:eligibility.eligible?t('Criteria met','مستوفٍ للمعايير'):t('Review required','تتطلب مراجعة'),done:eligibility.eligible},{label:t('Medication','العلاج الدوائي'),state:request?local(request.status):t('Not prescribed','غير موصوف'),done:!!request},{label:t('Physiotherapy','العلاج الطبيعي'),state:plan?.rehabilitation?local(plan.rehabilitation.status):t('Not included','غير مشمول'),done:false},{label:t('Home exercises','التمارين المنزلية'),state:plan?.homeExerciseIds.length?t('Included in plan','ضمن الخطة'):t('Not included','غير مشمول'),done:false},{label:t('Follow-up & monitoring','المتابعة والمراقبة'),state:plan?.followUpDate??t('Not scheduled','غير مجدول'),done:false}]
 const icons=['user','chart','stethoscope','lab']
 return <div className="treatment-eligibility" data-no-localize>
  <section className="te-journey"><div><h2><CareIcon name="care-plan"/>{t('Treatment eligibility steps','خطوات أهلية العلاج')}</h2><p>{t('Current eligibility and care stages from the patient record.','مراحل مراجعة أهلية العلاج وحالة الرعاية وفق بيانات المريض المسجلة.')}</p><ol>{steps.map((s,i)=><li key={s.label} className={s.done?'done':''}><span>{i===0&&s.done?<CareIcon name="check"/>:i+1}</span><b>{s.label}</b><small>{s.state}</small></li>)}</ol></div></section>
  <div className="te-columns">
   <section className="te-card te-patient"><h2><CareIcon name="user"/>{t('Patient information','معلومات المريض الأساسية')}</h2>{[[t('Record number','رقم الملف'),patient.id,'file'],[t('Age','العمر'),`${patient.age} ${t('years','سنة')}`,'calendar'],[t('Sex','النوع'),local(patient.sex??'—'),'user'],[t('Primary diagnosis','التشخيص الرئيسي'),local(patient.diagnosis),'file']].map(([label,value,icon])=><div className="te-info-row" key={label}><CareIcon name={icon}/><small>{label}</small><b>{value}</b></div>)}</section>
   <section className="te-card te-criteria"><h2><CareIcon name="check"/>{t('Criteria met','المعايير المستوفاة')}</h2>{criteria.map((c,i)=><div className="te-criterion" key={c.label}><CareIcon name={icons[i]}/><div><b>{local(c.label)}</b><small>{local(c.evidence)}</small></div><CareIcon name="check"/></div>)}{!criteria.length&&<p>{t('No criteria met in the recorded evidence.','لم تُستوفَ معايير وفق الأدلة المسجلة.')}</p>}</section>
   <section className="te-card te-attention"><h2><CareIcon name="bell"/>{t('What needs attention?','ما الذي يحتاج انتباهًا؟')}</h2>{attention.length?attention.map((text,i)=><div className="te-notice warning" key={`${i}-${text}`}><CareIcon name="alert"/><span>{text}</span></div>):<div className="te-notice success"><CareIcon name="check"/>{t('All eligibility requirements are met in the current record.','جميع متطلبات الأهلية مستوفاة وفق البيانات المسجلة.')}</div>}{a1c?.status==='Abnormal'&&<div className="te-notice"><CareIcon name="info"/>{t('Review the abnormal HbA1c result with the treating clinician.','يُوصى بمراجعة نتيجة السكر التراكمي غير الطبيعية مع الطبيب المعالج.')}</div>}{request&&<div className="te-notice"><CareIcon name="info"/>{t('Follow up on adherence to the prescribed medication.','متابعة التزام المريض بالأدوية الموصوفة.')}</div>}<footer><button onClick={()=>onRequest(request?.id)}><CareIcon name="file"/>{t('Review treatment requests','مراجعة طلبات العلاج')}</button>{can(role,'inventory:read')&&<button onClick={onInventory}><CareIcon name="box"/>{t('Check inventory','فحص المخزون')}</button>}</footer></section>
  </div>
  <section className="te-results"><h2><CareIcon name="chart"/>{t('Latest recorded results','آخر النتائج المسجلة')}</h2><div>{[{label:t('Blood glucose','سكر الدم'),value:glucose?String(glucose.value):'—',unit:glucose?local(glucose.unit):t('Not recorded','غير مسجل'),date:glucose?.date,icon:'lab',tone:'green'},{label:'HbA1c',value:a1c?`${a1c.value} ${a1c.unit}`:'—',unit:a1c?'':t('Not recorded','غير مسجل'),date:a1c?.date,icon:'lab',tone:'purple'},{label:t('Body mass index','مؤشر كتلة الجسم'),value:String(vital?.bmi??patient.bmi),unit:t('kg/m²','كجم/م²'),date:vital?.recordedAt.slice(0,10),icon:'chart',tone:'amber'},{label:t('Blood pressure','ضغط الدم'),value:vital?`${vital.systolic}/${vital.diastolic}`:'—',unit:vital?t('mmHg','مم زئبق'):t('Not recorded','غير مسجل'),date:vital?.recordedAt.slice(0,10),icon:'activity',tone:'rose'}].map(r=><article key={r.label}><i className={r.tone}><CareIcon name={r.icon}/></i><div><small>{r.label}</small><b dir="ltr">{r.value}</b><small>{r.unit}</small>{r.date&&<small>{r.date}</small>}</div></article>)}</div></section>
  <footer className="te-footer"><div>{plan&&<button className="te-primary" onClick={onPlan}><CareIcon name="care-plan"/>{t('View plan & follow-up','عرض الخطة والمتابعة')}</button>}{can(role,'request:create')&&<button onClick={onCreateRequest}><CareIcon name="file"/>{t('Create treatment request','إنشاء طلب علاج')}</button>}</div><button onClick={onBack}><CareIcon name="open"/>{t('Back to patient care list','العودة إلى قائمة رعاية المريض')}</button></footer>
 </div>
}
